### ISSUE TITLE
Removing a documented function causes warning on first devtools::document()

### ISSUE THREAD

**Issue by jeanimal** [hadley/devtools#1006]
If I delete or rename a previously documented function, the first time I run devtools::document() I get a "Objects listed as exports, but not present in namespace" warning.  Running devtools::document() again no longer has a warning, although I do not see any changes in files.  So there is a workaround of just running devtools::document() twice to be sure everything was done right the first time.

The warning was worrying the first time I saw it, but I would call this a low prioirty bug.

An example is below from when I renamed a function from predictP2 --> predictRowPair.

> devtools::document()
Updating heuristica documentation
Loading heuristica
Writing NAMESPACE
Writing predictRowPair.Rd
Deleting predictP2.Rd
Warning message:
In setup_ns_exports(pkg, export_all) :
  Objects listed as exports, but not present in namespace: predictP2
> devtools::document()
Updating heuristica documentation
Loading heuristica

**Comment by jeanimal** [comment]
I am using version devtools_1.9.1

**Comment by hadley** [comment]
It's not a bug - it's just a warning that comes from load_all.
