### ISSUE TITLE
`dev_help` fails to find type="html" help, even when type="text" exists...

### ISSUE THREAD

**Issue by stevenpollack** [hadley/devtools#1008]
A reproducible example is available at this gist: https://gist.github.com/stevenpollack/141b14437c6c4b071fff#file-bestpracticeswalkthrough-r

Which I've been testing, _with_ `devtools`:

```
devtools::source_gist('https://gist.github.com/stevenpollack/141b14437c6c4b071fff')
```

It outputs a warning message:

> The file /var/folders/xv/zh9pr4x130x4grh_y77k11y00000gn/T//RtmpY7ToMU/Rtxt375e4af8cd54.html does not exist.

I suspect this has to do with the double `//` in the URI. 

If you comment out [line 109](https://gist.github.com/stevenpollack/141b14437c6c4b071fff#file-bestpracticeswalkthrough-r-L109) and remove the comment on line 110, the help get's pulled up without any issues...

**Comment by hadley** [comment]
That's a really massive reprex. Could you try making something smaller please?

**Comment by stevenpollack** [comment]
I can try, but the gist (pun unintended) of the example is:

1. make, add, and `dev_help` a roxygenated function.
2. make and add _another_ roxygenated function.
3. try and `dev_help` the function in step 2 with the style being html

...

**Comment by hadley** [comment]
Fixed in pkgload
