### ISSUE TITLE
FR: Elicit restart message when installing a pre-loaded package

### ISSUE THREAD

**Issue by MichaelChirico** [hadley/devtools#1010]
When using `install.packages` (in RStudio, at least), a friendly warning message is produced whenever you try to install a package which is already loaded in the namespace, which offers as well to restart the R session and head off any issues this might cause.

It would be nice if `install_github` (and other `install*` functions from the package, though I've personally not used any) would produce its own warning message paralleling this functionality.

**Comment by hadley** [comment]
It would be nice - it's most important for binary packages on windows. Are you interested in putting together a PR for review?

**Comment by MichaelChirico** [comment]
@hadley I've got no expertise so it would take quite some time/elbow grease to get it going -- better suited to someone that knows the workings of the package and all.

I'll put it somewhere in the middle of my priority list.
