### ISSUE TITLE
install_version sometimes uses wrong URL

### ISSUE THREAD

**Issue by wch** [hadley/devtools#1026]
Note that this bug might not be replicable in the future -- I think it will only happen on packages that were released in the last couple of days.

Shiny 0.13.0 has just been released on CRAN, and I'm trying to install 0.12.2 on Linux with `install_version`. When I do that, it fails to download the file because it's using the wrong URL:

```
> install_version('shiny', '0.12.2', type='source')
Installing package into ‘/home/winston/R/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/shiny_0.12.2.tar.gz'
Content type 'text/html; charset=iso-8859-1' length 312 bytes
==================================================
downloaded 312 bytes

Error in untar2(tarfile, files, list, exdir, restore_times) : 
  incomplete block on file
```

It's using the path for up-to-date packages (https://cran.rstudio.com/src/contrib), but that path currently contains 0.13.0. However, if I use an older version, it installs fine, because it's using the correct path (https://cran.rstudio.com/src/contrib/Archive/shiny/).

```
> install_version('shiny', '0.12.1', type='source')
Downloading package from url: https://cran.rstudio.com/src/contrib/Archive/shiny/shiny_0.12.1.tar.gz
Installing shiny
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  CMD INSTALL '/tmp/Rtmp88oc6Y/devtools56ac107d4a75/shiny'  \
  --library='/home/winston/R/3.2' --install-tests 

* installing *source* package ‘shiny’ ...
** package ‘shiny’ successfully unpacked and MD5 sums checked
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (shiny)
```

So it seems that there's probably a bug in how devtools decides what the latest available version is.

**Comment by jimhester** [comment]
I think this is very transient, it now works fine for '0.12.2' as well.

```r
> install_version('shiny', '0.12.2', type='source')
Downloading package from url: https://cran.rstudio.com/src/contrib/Archive/shiny/shiny_0.12.2.tar.gz
Installing shiny
'/usr/local/Cellar/r/3.2.3/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/dt/r5s12t392tb5sk181j3gs4zw0000gn/T/RtmpbT31m1/devtools3ac848fec49c/shiny' --library='/usr/local/lib/R/3.2/site-library' --with-keep.source  \
  --install-tests

* installing *source* package ‘shiny’ ...
** package ‘shiny’ successfully unpacked and MD5 sums checked
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (shiny)
```

**Comment by gaborcsardi** [comment]
@wch One possible explanation is that your R session has been running for a day or so and you had an old version of the `aviailable.packages()` table cached.

I'll fix this in mangothecat/remotes, with a simple alternative approach: we just try both urls, the current first, and the one in Archive if the current fails.

**Comment by wch** [comment]
Yes, @gaborcsardi, I think you're right -- my R session has been open for over a day and I think it had an old cached version of `available.packages()`.

**Comment by jimhester** [comment]
It might make sense to have the memoised cache timeout after a day. https://github.com/hadley/memoise/issues/11 has a proposal to that effect, or could use the non-arguments cache in the same way https://github.com/hadley/memoise/pull/16 if that is merged.

**Comment by wch** [comment]
Agreed. Maybe even a shorter time would make sense, like 4-8 hours?

**Comment by gaborcsardi** [comment]
AFAIR `available.packages()` itself uses a cache now, so maybe we could scrap the caching entirely.

**Comment by gaborcsardi** [comment]
Btw. I think simply trying both URLs is still a better solution, gets rid of the expired cache, an (admittedly improbable) race condition, and also omits downloading the large `available.packages()` table.

**Comment by jimhester** [comment]
Trying both makes sense to me.

FWIW `available.packages()` still much slower than the memoised version

``` r
microbenchmark(times = 10L,
  available_packages(repos = "https://cran.rstudio.com", type = "both"),
  available.packages(contrib.url(repos = "https://cran.rstudio.com", type = "both"), type = "both")
)
#> Unit: microseconds
#>                                                                                                    expr
#>                                   available_packages(repos = "https://cran.rstudio.com", type = "both")
#>  available.packages(contrib.url(repos = "https://cran.rstudio.com",      type = "both"), type = "both")
#>         min         lq        mean     median         uq        max neval
#>      64.977     69.516    116.5874    139.475    149.765    158.225    10
#>  291890.933 300657.495 307988.7893 304793.931 313268.456 338722.133    10
```
