### ISSUE TITLE
Get tarballs for a tree of packages

### ISSUE THREAD

**Issue by Ironholds** [hadley/devtools#1039]
Mostly writing this down so I don't forget the idea and can come back and implement it after this plane journey (and to offer Hadley a chance to say "that doesn't fit here really and/or is a bad idea"):

A common problem with firewalled machines is having to individually courier .tar.gz files of R packages across via SFTP or similar, and having to manually work out the tree of dependencies and thus _which_ .tar.gzs you need. It's manual and time-consuming and manky.

Write a function, <code>get_package_source</code>, which accepts a package name and directory:

1. Hits up metacran to work out the tree of dependencies that package has;
2. Grabs the latest tarball for each package in that tree;
3. Stores them all in the directory.

Hey presto, much easier!

(For even easier work you could write out a little file to the directory containing the order in which packages should be installed and pair this with an <code>install_tree</code> function you'd run on the firewalled machine that installs the tarballs in order).

**Comment by bearloga** [comment]
Even though we discussed this on twitter, I should note here that this functionality is exactly implemented by `makeRepo()` in Revolution Analytics' [miniCRAN package](https://github.com/RevolutionAnalytics/miniCRAN).

**Comment by Ironholds** [comment]
Yep, so this is extraneous and we're good :)
