### ISSUE TITLE
Inconsistency in R version dependency

### ISSUE THREAD

**Issue by carloscinelli** [hadley/devtools#1047]
Hi Hadley and Jim,

There is an inconsistency in the R version dependency:
* `devtools` requires  R (>= 3.0.2).
* However, `devtools` imports `withr` and `withr` requires R (>= 3.2.0).

So when one tries to install `devtools` in r-oldrel, it currently fails. 

See the CRAN tests: https://cran.r-project.org/web/checks/check_results_devtools.html

Also, this configuration causes problem with Gabor's r-builder in Travis, when testing in r-oldrel. See this example (https://travis-ci.org/renkun-ken/formattable/jobs/103427303).

I think the way to go here would be to relax `withr` dependency, at least to r-oldrel. But if `withr` dependency can't be relaxed, maybe `devtools` dependency should be set to R (>= 3.2.0).

**Comment by gturri** [comment]
I believe I experience the same issue: installing devtools now fails with error `ERROR: dependency ‘withr’ is not available for package ‘devtools’`.

**Comment by jimhester** [comment]
I can relax the withr dependency to 3.0.2 but I am not sure when I will do another withr release...
