### ISSUE TITLE
Description Remotes can not have spaces after the second line

### ISSUE THREAD

**Issue by lucacerone** [hadley/devtools#1055]
I am not sure whether this is actually an R (v3.2.3) issue or a devtools ( v 1.10.0.9000) issue,
so I apologize now if it is not relevant.

If in my `DESCRIPTION` file I have something like:
```
Depends:
 R (>= 3.2.3)
Imports:
 devtools (>= 1.10.0)
Remotes:
 hadley/ggplot2
```
then everything works fine.

However if I change `DESCRIPTION` to be (note: I have now two github remotes)

```
Depends:
 R (>= 3.2.3)
Imports:
 devtools (>= 1.10.0)
Remotes: 
  hadley/ggplot2
  hadley/memoise
```

then `install()` fails with error:

```
Downloading GitHub repo hadley/ggplot2
hadley@master
from URL https://api.github.com/repos/hadley/ggplot2
hadley/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  URL using bad/illegal format or missing URL
```

I have experienced similar issues using git:: url:: and so on, although now I am not able to reproduce the issue with them.

**Comment by jimhester** [comment]
`Remotes: ` works the same as `Imports: ` etc, you need commas in between each entry.

```diff
@@ -3,5 +3,5 @@
 Imports:
  devtools (>= 1.10.0)
 Remotes:
-  hadley/ggplot2
+  hadley/ggplot2,
   hadley/memoise
```

**Comment by lucacerone** [comment]
thanks (embarassed)
