### ISSUE TITLE
Retrieving result of check for automated processing

### ISSUE THREAD

**Issue by torbjorn** [hadley/devtools#1057]
I'm working with automating a local repository setup, and as part of that I'd like to check the packages before adding them to the repo.

As far as I can tell I can't easily fetch the result of the check() , in terms of NOTEs, WARNINGs and ERRORs.

What I am doing to work around this, is:

    d <- tempdir()

    devtools::check(
        package.path,
        quiet=TRUE,
        check_dir = d
        )

    pkgname <- package_name( package.path )

    check.dir <- file.path(
        d,
        paste0( pkgname, ".Rcheck" )
        )

    if( file.exists( check.dir ) )
        result <- devtools::check_failures(check.dir)

This gives me text results meant for human eyes which most likely can be parsed by looking for ` \\.\\.\\. (NOTE|WARNING|ERROR)` , which is not ideal.

Is there another way?

**Comment by hadley** [comment]
You can now :) `check()` now returns an object with errors, warnings, and notes.
