### ISSUE TITLE
difficulty getting Github info

### ISSUE THREAD

**Issue by bbolker** [hadley/devtools#1058]
I'd love to replace my clunky, organically grown reverse dependency checking machinery with devtools's version ...  however, when I try to run `revdep_check()` on a local copy of the `lme4` package I get "Unknown Github repo format" when it tries to run
```
devtools:::remote_metadata(as.package("lme4"))
```
to retrieve the dependency information.

I traced this as far as `github_remote parse`, where `x` is equal to `ssh://git@github.com/lme4/lme4` -- 
the function is looking for `https://` or `git://` URLs, and if it can't find them it fails ... maybe `ssh://` is an old format ... ?

**Comment by bbolker** [comment]
OK, I fixed this via `git remote set-url origin git@github.com:lme4/lme4.git` . Might be worth adding the older format to the list of possible cases, if it isn't just something wonky that happens to work for me?

Feel free to close this (I'll leave it open for now)

**Comment by hadley** [comment]
Yeah, I think ssh is an older format.

**Comment by jsta** [comment]
For people arriving here trying to track down this error message - I fixed by switching the repo's `git remote origin` from **http** to **https**:
```
$ git remote set-url origin https://github.com/jsta/foo.git
```
