### ISSUE TITLE
http:// vs https:// in hardcoded repositories

### ISSUE THREAD

**Issue by bbolker** [hadley/devtools#1059]
There are a few places where the RStudio CRAN mirror (`cran.studio.com`) is hard-coded, for convenience (e.g. functions that will get used non-interactively, where user may not have set repo in their .Rprofile).  Right now these are hard-coded as `http://...`, which causes various difficulties when using R-devel (which insists on `https://` in many important contexts) - specifically, dependencies may fail to be found when installing packages.   In particular, changing `http://` to `https://` in line 56 of `deps.R` fixes a lot of problems ...

**Comment by hadley** [comment]
Want to do a PR?

**Comment by bbolker** [comment]
OK, although does it need to be/should it be conditional on R >= 3.3.0? (I thought there were other uses of hard-coded http://, but I think I was wrong)
