### ISSUE TITLE
document (control+shift+d) on custom library

### ISSUE THREAD

**Issue by carlmcqueen** [hadley/devtools#1061]
Attended the Advanced R - Developer conference this weekend and used command+shift+D repeatedly and returned to work where R has a custom library due to shared folder write permissions and the function doesn't work.  

Temporary Solution: Had to move the packages devtools needed to the vanilla library of R as a work around, hoping there is fix for this coming in the future where custom libraries will be supported due to this limitation.

(R is unable to write to my C: drive on this computer)

R Version: 3.2.3
Devtools: Current CRAN release
R Studio: Preview Release.

**Comment by hadley** [comment]
Custom libraries already should be supported. Could you please paste the exact error message you get?

**Comment by carlmcqueen** [comment]
New Updated fixed it for me, not sure what was going on.

**Comment by carlmcqueen** [comment]
Hadley:  I removed devtools from my workaround of putting it in the library in the R install folder and I removed devtools from my main directory.  I then reinstalled it to the custom library location I use.  Having it installed in two places is never a good idea.  Now I'm getting issues again.

when I hit control+shift+d I get:
devtools::document(roclets=c('rd', 'collate', 'namespace'))
Error in loadNamespace(name) : there is no package called 'devtools'
Calls: suppressPackageStartupMessages ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

Exited with status 1.

when I hit build source from the build tab:
==> devtools::document(roclets=c('rd', 'collate', 'namespace'))

Error in loadNamespace(name) : there is no package called 'devtools'
Calls: suppressPackageStartupMessages ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

Exited with status 1.

Do you think it's devtools or do you think it's Rstudio?

**Comment by jimhester** [comment]
This is an RStudio. See https://support.rstudio.com/hc/en-us/community/posts/200652506-RStudio-Desktop-is-not-resecting-my-R-LIBS-USER. You are probably setting your R user directory in a way RStudio is not picking up (like your shell startup files).

**Comment by carlmcqueen** [comment]
@jimhester I do use a custom Rprofile.site that defines the library.  The site you linked doesn't seem to mention a solution as I understand the .Renviron is the same as a windows .site for windows.  

I have the libpath defined there and when I type .libpaths() it lists the path that I use.

Is there a better way to have RStudio recognize a custom library instead of the default location?

**Comment by morrowcj** [comment]
I am also having this problem. I switched to a custom library to avoid reinstalling all the packages with each new R update. Since doing so, I haven't been able to get the package build functionality of Rstudio to work. I set the custom library in my Rprofile.site file with the line: 
`.libPaths("~/custom_dir")`
Is there a way to get Rstudio to recognize this directory when using the build tools (ctrl+shift+D)? Typing `.libPaths()` returns the correct directory but Rstudio still gives this error:
```
==> devtools::document(roclets=c('rd', 'collate', 'namespace', 'vignette'))

Error in check_dep_version(pkg, version, compare) : 
  Dependency package roxygen2 not available.
Calls: suppressPackageStartupMessages ... <Anonymous> -> check_suggested -> check_dep_version
Execution halted

Exited with status 1.
```
Here's my setup info:
```
#version info
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray     
```
