### ISSUE TITLE
create function to infer dependencies? [feature request]

### ISSUE THREAD

**Issue by stevenpollack** [hadley/devtools#1065]
I'm wondering if there is room in the `devtools` philosophy for a function, "`update_dependencies`" (say), that could search all the bodies of all function's loaded from `load_all` for `::` (or `:::`) to (partially) infer package dependencies?

It could then add the appropriate `importFrom()`'s to your package's `NAMESPACE`, and either suggest how to invoke `use_package` or just invoke it for you with `type = 'Imports'`. 

I am happy to implement this function, I'm just not sure if this should be done here, or potentially somewhere else (maybe in `roxygen2`)?

**Comment by hadley** [comment]
I don't think that's the right approach, because there's no way to infer if a package should be suggested or imported.

**Comment by stevenpollack** [comment]
So, you'd rather users manually handle `@import`, `@importFrom`, and then `use_package`, as opposed to having at least some computer assistance?

**Comment by hadley** [comment]
Yes - I believe that those are important decisions that can not be automated.  (Especially since you should never use `@import` and only rarely use `@importFrom`)

**Comment by stevenpollack** [comment]
I'm not sure I'm following. In the chance when I am importing, say, `stringr::str_replace_all()`, shouldn't I include `@importFrom stringr str_replace_all` inside my roxygen block?

**Comment by hadley** [comment]
No - you either do `stringr::str_replace_all()` _or_ `@importFrom stringr str_replace_all` + `str_replace_all()`

**Comment by stevenpollack** [comment]
Right on. Well, then I was ***sorely*** mistaken:

I always figured we should be using `::` (or `:::`) _and_ also annotating our roxygen. 😅

So, given a person is following your form above: there's absolutely _no reason_ for my proposed function to exist. Awesome. YOU ARE THE MAN!
