### ISSUE TITLE
Add a CONTRIBUTING.md file to devtools

### ISSUE THREAD

**Issue by jimhester** [hadley/devtools#1075]
Github automatically links to contributing files when users open a new PR (https://github.com/blog/1184-contributing-guidelines).

It might be useful to have one which states common things for contributing to devtools.

- Running devtools::document() to update the documentation before submitting
- Adding a note to NEWS.md
- Link to http://adv-r.had.co.nz/Style.html
- Link to http://r-pkgs.had.co.nz/git.html#pr-make

Might also be handy to make a template to add a contributing.md to other projects, add it to `.Rbuildignore` etc.

**Comment by hadley** [comment]
#1011 ;)  But we do need a specific one for devtools too.

**Comment by hadley** [comment]
I'm also not sure sure how to handle the fact that the advice will basically be identical across all my repos

**Comment by jimhester** [comment]
Have `use_github()` automatically add it for us :smile:.

**Comment by jimhester** [comment]
I guess you have most of this already at https://github.com/hadley/ggplot2/blob/master/CONTRIBUTING.md, so we can adapt that as the template
