### ISSUE TITLE
Doctor functions vs custom release checks

### ISSUE THREAD

**Issue by jennybc** [hadley/devtools#1078]
Is it clear when something should be a custom release check vs a doctor function?

I was looking at [this proposal to develop a repo health check](https://github.com/onyb/repodoctor/) and was about to point out that `devtools` has a large suite of doctor functions for R packages. But then realized there are, in fact, only 2 (`dr_devtools()` and `dr_github()`).

Regardless, that link contains a few things that might be nice to check or doctor for (README? tests? travis or similar?).

**Comment by hadley** [comment]
I imagine the doctor functions are something you run at the beginning of class to make sure that eveyone is set up ok.  It also seems useful to run them before release to make sure you're still good to go.  

Does that make sense?
