### ISSUE TITLE
Getting error messages when installing RStudio addins - Error in curl::curl_fetch_memory(url, handle = handle) : Problem with the SSL CA cert (path? access rights?)

### ISSUE THREAD

**Issue by darny** [hadley/devtools#1079]
Hi. Darny here - an RStudio newbie.

It was [recommended ](http://blog.rstudio.org/2016/02/09/new-release-of-rstudio-v0-99-878/)that I post my question here.

My current versions are: RStudio 0.99.878 & R 3.2.3 installed in a Windows 7 Professional – 64 bit laptop.

I have the latest versions of htmltools, shiny, and miniUI.

I followed the installation instructions from [https://github.com/rstudio/addinexamples](https://github.com/rstudio/addinexamples) and [http://rstudio.github.io/rstudioaddins/](http://rstudio.github.io/rstudioaddins/).

I tried using the Install button from the Packages Pane in RStudio, to no avail. (I used the keyword **addin**)

I entered this in the console and gave me error messages:

```
> if (!requireNamespace(“devtools”, quietly = TRUE))
+ install.packages(“devtools”)
```

```
> devtools::install_github(“rstudio/htmltools”)
Downloading GitHub repo rstudio/htmltools@master
from URL https://api.github.com/rep…/rstudio/htmltools/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) :
Problem with the SSL CA cert (path? access rights?)
```

```
> devtools::install_github(“rstudio/shiny”)
Downloading GitHub repo rstudio/shiny@master
from URL https://api.github.com/repos/rstudio/shiny/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) :
Problem with the SSL CA cert (path? access rights?)
```

```
> devtools::install_github(“rstudio/miniUI”)
Downloading GitHub repo rstudio/miniUI@master
from URL https://api.github.com/repos/rstudio/miniUI/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) :
Problem with the SSL CA cert (path? access rights?)
```

```
> devtools::install_github(“rstudio/addinexamples”)
Downloading GitHub repo rstudio/addinexamples@master
from URL https://api.github.com/…/rstud…/addinexamples/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) :
Problem with the SSL CA cert (path? access rights?)
```
How can I install the addins package successfully?

Thanks in advance.

**Comment by hadley** [comment]
Please restart R then `install.packages(c("curl", "httr"))` then try again.

**Comment by darny** [comment]
It worked ! Very much appreciated, @hadley ! 

![addins](https://cloud.githubusercontent.com/assets/3765207/12949763/98fc56ae-d044-11e5-9cff-6036672209c4.png)

**Comment by bent3well** [comment]
I was having the same problem using install_from_swirl(...) in the swirl package that's used in the Coursera Data Science Specialization. Thanks for your help and inspiration, Dr. Wickham!

**Comment by smallmonster23** [comment]
I have the same question，but the according the way above .the problem is exist.

**Comment by prakash-aditya44** [comment]
Hi,

R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

when running these commands:


install.packages(c("curl", "httr"))
sc <- spark_connect(master = "my_cloud_url", method = "livy")

Following error comes:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't connect to server

**Comment by nick-youngblut** [comment]
I'm still getting the "SSL CA cert (path? access rights?)" after updating "curl" and "httr". 

~~~
> devtools::install_github("hadley/r4ds")
Installation failed: Problem with the SSL CA cert (path? access rights?)
~~~

~~~
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] httr_1.2.1      devtools_1.13.2

loaded via a namespace (and not attached):
[1] R6_2.2.0      tools_3.3.1   withr_1.0.2   curl_2.7      memoise_1.0.0
[6] git2r_0.18.0  digest_0.6.12
~~~

Any ideas on what's going wrong?

**Comment by haseebmahmud** [comment]
Same problem. @hadley 's solution is not working. 

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.10

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rfacebook_0.6.15 httpuv_1.3.5     rjson_0.2.15     httr_1.3.1       curl_3.1        
[6] devtools_1.13.4 

loaded via a namespace (and not attached):
 [1] compiler_3.4.3 R6_2.2.2       tools_3.4.3    withr_2.1.1    rstudioapi_0.7
 [6] yaml_2.1.16    Rcpp_0.12.14   memoise_1.1.0  git2r_0.20.0   digest_0.6.13
