### ISSUE TITLE
Better workflow for large revdep checks

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#1080]
Currently `revdep_check()` fails with `nthreads > 1` on the mac. I think this some bug deep in the `mclapply()` because it only happens with large numbers of packages, only on the mac, and not with `parLapply()` and a PSOCK cluster. The bug surfaces itself by writing tens of Gb to disk, seemingly (from what I can tell in activity monitor) written by kernel_task. I think this might be a consequence of trying to "join" back together a large number of forked processes (but I might be completely off base).

I need a better workflow doing large numbers of dependency tests, either by fixing this problem on the mac, or making it easier for me to spin up a large digital ocean client and run the tests there.

**Comment by jimhester** [comment]
I wonder if this is an issue when the package being tested also uses `mclapply()`. It might be worth seeing if it is caused by a specific package(s).

**Comment by hadley** [comment]
Oh good thought - I'll try `mc.allow.recursive = FALSE`

**Comment by hadley** [comment]
Tried it and still had same failure - it does always seem to happen once the last package is checked.

**Comment by hadley** [comment]
Reinstalling my revdep library seems to have made this problem go way
