### ISSUE TITLE
devtools::check does not check for valid URLs

### ISSUE THREAD

**Issue by sjPlot** [hadley/devtools#1084]
The "normal" package check (as CRAN) w/o using devtools indicates invalid URLs in the documentation (.rd-files), using devtools, however, does not.

**Comment by hadley** [comment]
The check in `release()` does - I think the `check_version = TRUE` also turns on url checking.

**Comment by hadley** [comment]
It's disabled by default because it's super slow and gives spurious warnings about CRAN versions.
