### ISSUE TITLE
check() doesn't use --no-manual anymore by default

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1087]
It also breaks if pdflatex isn't installed. I think this is caused by 3188bbfdea, but I'm not sure how to handle it:

- [ ] Add a new arg "manual = FALSE" to check()?
- [ ] Redo the pdflatex check in check_built()?
- [ ] ?

**Comment by hadley** [comment]
I made this change because I assumed (possibly) incorrectly that you'd want to suppress building the manual, and if there was no manual in the package, you wouldn't need to check it.

**Comment by krlmlr** [comment]
I think R CMD check still looks for a manual or tries to build one. This is what I see when `pdflatex` is not installed and I run check():

```
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without hyperrefs or index ... ERROR
Re-running with no redirection of stdout/stderr.
Hmm ... looks like a package
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  pdflatex is not available
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  pdflatex is not available
Error in running tools::texi2pdf()
You may want to clean up by 'rm -rf /tmp/RtmpFYGkVI/Rd2pdfe41141f346'
```

**Comment by hadley** [comment]
So I guess we need to check during both building and checking? Or should the check move back to `check()`?

**Comment by krlmlr** [comment]
I think we need to do the check in both places, yes. Optionally we may want to add a new arg "manual = FALSE" to check().

**Comment by hadley** [comment]
I think an additional argument passed down to both `build()` and `check_built()` would be best
