### ISSUE TITLE
Recognize RStudio addins when using load_all

### ISSUE THREAD

**Issue by daattali** [hadley/devtools#1089]
This is not high priority at all, but I love that `load_all` mimics a real install so well in so many respects.  It'd be nice if it could also recognize new addins in the `/inst/rstudio/addins.dcf` and somehow could add them to the RStudio menus.

**Comment by hadley** [comment]
@jjallaire @kevinushey is this feasible?

**Comment by jjallaire** [comment]
Yes, I think this would be quite straightforward. I'll log an issue for the
next release.

**Comment by hadley** [comment]
@jjallaire just to confirm, this is an RStudio issue, not a devtools issue?

**Comment by jjallaire** [comment]
Yup, and we fixed a couple of weeks ago!

J.J.

**Comment by hadley** [comment]
Great
