### ISSUE TITLE
`yesno` is a bit misleading

### ISSUE THREAD

**Issue by johnbaums** [hadley/devtools#1093]
When running `build_win()`, a prompt is shown with two randomly generated synonyms (kind of) for "no", and one for "yes". It's kind of reminiscent of dialogue from [Guybrush Threepwood](http://2.bp.blogspot.com/-VrC65SgwUrk/U1-ADto9vtI/AAAAAAAALOs/RweQyX5pDTc/s1600/scummvm01390.png).

The prompt isn't a question, so it was unclear to me what I was responding to. In the example below, I assumed that the prompt was referring to whether or not I'd received the email (particularly because of the "not yet"). Maybe it's just an idiot test, and I failed... but maybe it's worth clearing things up.

```
> devtools::build_win()
Building windows version of mypackage for R-release, R-devel with win-builder.r-project.org.

E-mail will be delivered to me@email.com.
1: No
2: Definitely
3: Not yet
```

**Comment by hadley** [comment]
I think making the statement a question makes it easier to see what's happening.
