### ISSUE TITLE
install_github forces remotes to branch tip

### ISSUE THREAD

**Issue by aronatkins** [hadley/devtools#1099]
I am trying to create a reproducible environment for document rendering. My intention was to lock `rmarkdown` and `bookdown`, for example, to specific commit SHAs.

```
R -e "devtools::install_github('rstudio/rmarkdown', ref = '70b9f1ec4ce71628d5d74f9a6287933a415fef9b')"
R -e "devtools::install_github('rstudio/bookdown', ref ='9f7dc0897c96c22f20f6cb69b757538fb7a0cf46')"
```

The `bookdown` package contains a `Remotes` specification:

```
Remotes: rstudio/rmarkdown, rstudio/htmltools, ramnathv/htmlwidgets
```

When `install_github` installs `bookdown`, the `rmarkdown` package is re-installed from the tip of its master branch (partial log from `bookdown` installation):

```
Downloading GitHub repo rstudio/rmarkdown@master
from URL https://api.github.com/repos/rstudio/rmarkdown/zipball/master
Installing rmarkdown
```

Is there a way to inform `install_github` that the `rmarkdown` remote is satisfied by the previously installed version? Is there more metadata that `bookdown` could include to specify the minimum version it needs from a particular remote?

I'm looking for recommendations for an installation technique that can let me and my teammates locally obtain the same package versions and thus the same rendering environment.

I am ignoring for the moment the fact that we are not locking all the dependencies; especially those that arrive from CRAN. I am focused right now on the dependencies that are rapidly changing. Locking versions for these GitHub dependencies means that we will all see the same behavior -- consistency of result is more important than some of us having the absolute latest code.

**Comment by jimhester** [comment]
Right now the remotes do not respect the `upgrade_dependencies` argument of `install()`. This is an oversight I am currently working on correcting.

In the meantime I would suggest you create a personal fork of bookdown and modify the `Remotes:` to pin to the versions you want to use.

```yaml
Remotes: rstudio/rmarkdown@70b9f1ec4ce71628d, rstudio/htmltools@abc123, ramnathv/htmlwidgets@xyz242526
```
If you want to lock down the CRAN dependencies as well add them to your `Remotes:` from the GitHub mirrors at https://github.com/cran. e.g.
```yaml
Remotes: cran/knitr@1.12.3
```

**Comment by aronatkins** [comment]
Thanks for the suggestions, @jimhester. I'm going to let `rmarkdown` float for now, but will use this `Remotes` trick if we decide we want to start pinning. Our need to pin may change when `bookdown` goes to CRAN.
