### ISSUE TITLE
add host argument to use_github()?

### ISSUE THREAD

**Issue by ijlyttle** [hadley/devtools#1101]
Hi,

The use-case for this is for people who use enterprise GitHub.

I have looked at the code, and I think this can be done, but it would involve (I think) also adding a host argument to:

- `github_GET()`
- `github_POST()`
- `use_github_links()`

The change to `use_github_links()` could be a bit hairy as it might have to map `api.github.com` to `https://github.com` and `github.foo.com/api/v3` to `https://github.foo.com`. 

I am happy to do a PR on this, if you think it is worthwhile to go forward. If so, a couple quick questions:

1. Are there other functions I would need to touch?

2. I also see a problem in testing the code, as it would require a public enterprise version of github to test against. Would it be enough to do private, informal testing, and also (of course) ensure that any changes do not break the existing behavior?

**Comment by hadley** [comment]
I'd be happy to review a PR of this. I don't think you need to worry too much about testing - as long as it works for public github, and the url is pluggable, it should work for any internal github.

**Comment by ijlyttle** [comment]
Will do - thanks!

**Comment by ijlyttle** [comment]
done in #1215
