### ISSUE TITLE
Use BatchJobs instead of parallel::mclapply()

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1106]
Big advantages:
- Restartability: The job definitions are part of the cache, and set up during its creation. BatchJobs records which jobs haven't completed yet and can rerun only the failed ones in a revdep_check_resume() run
- Scalability: Works interactively, multicore, in a local network of machines via SSH, or on a HPC cluster; devtools doesn't need to care about configuration
- Ease of use: BatchJobs::batchMap() is a drop-in replacement of parallel::mclapply()

**Comment by gaborcsardi** [comment]
I like BatchJobs a lot, but that brings in a lot of dependencies, and `devtools` already has some biggish ones.

**Comment by jimhester** [comment]
It would only be used conditionally so could just be in Suggests, so it
wouldn't be too bad...

**Comment by hadley** [comment]
Is there a backend for windows? `makeClusterFunctionsMulticore()` uses multicore, so wouldn't help on windows.

**Comment by gaborcsardi** [comment]
@hadley Looks like not. :( I suppose SSH would work on windows, but needs an SSH server.....

**Comment by hadley** [comment]
Which brings us back to `parLapply()` :/

**Comment by gaborcsardi** [comment]
Personally I hate the `parallel` API, zero feedback to the user..... anyway.....

**Comment by krlmlr** [comment]
@hadley: makeClusterFunctionsMulticore() is a misnomer, it [spawns new R processes](http://www.rdocumentation.org/packages/BatchJobs/functions/makeClusterFunctionsMulticore). The documentation mentions Linux, but I don't see a reason why it shouldn't work on Windows.

**Comment by hadley** [comment]
@klmr ah thanks. But it looks like it uses this bash script: https://github.com/tudo-r/BatchJobs/blob/master/inst/bin/linux-helper. That's not going to work on windows.

**Comment by krlmlr** [comment]
It might be possible to implement a connector to the snow package, which should work on Windows, too (https://github.com/tudo-r/BatchJobs/issues/114).

**Comment by mllg** [comment]
> Scalability: Works interactively, multicore, in a local network of machines via SSH, or on a HPC cluster; devtools doesn't need to care about configuration

> Ease of use: BatchJobs::batchMap() is a drop-in replacement of parallel::mclapply()

If you guys care about these two points, I would like to point you to <https://github.com/berndbischl/parallelMap>. Instead of calling `mclapply`, you call `parallelMap`. The user can configure the backend (sequential, multicore, socket, mpi, SSH, HPC) from outside the package, e.g. in his Rprofile. You can also allow users to specifically which parts to parallelize by labeling the calls to `parallelMap`.

**Comment by hadley** [comment]
@mllg is there someway for children to send information back to the parents for display? That's a deal breaker for me.

**Comment by mllg** [comment]
> @mllg is there someway for children to send information back to the parents for display? That's a deal breaker for me.

I'm not sure I completely understand what you are asking for. Do you mean the output which is send to `stdout()` on the nodes or the the results?

**Comment by hadley** [comment]
Much improved parallelism now in revdechecp
