### ISSUE TITLE
Windows 100% portable R and RTools environment, please do not try to detect RTools

### ISSUE THREAD

**Issue by AndreMikulec** [hadley/devtools#1108]
I am working in a 100% Windows portable R and RTools environment.

So, RTools  is not in my Windows registry.
I have many versions of Rtools on my Windows machine (for many versions of R and for many isolated projects).  I use environment variables ( just like UNIX users ).

This is a feature request.  Perhaps 

```r
devtools::install_github 
```
can have an extra parameter for some (UNIX like) Windows users to "not perform a check for RTools" and just trust that the user has the RTools (and its many sub-directories )  in the %PATH%.

Perhaps, this

```r
> args(devtools::install_github)
function (repo, username = NULL, ref = "master", subdir = NULL,
    auth_token = github_pat(), host = "api.github.com", ...)
```
Can have an extra parameter " windows_devtools_check = TRUE"  ( for Windows users )

```r
> args(devtools::install_github)
function (repo, username = NULL, ref = "master", subdir = NULL,
   auth_token = github_pat(), host = "api.github.com", 
   windows_devtools_check = TRUE, ...) # ** Here **
```

So, I can call devtools::install_github like this(below) without an error.  . . . 

```r
>  devtools::install_github("rstudio/addinexamples", type = "source", 
   windows_devtools_check = FALSE) # ** Here **
```

Note: I did look at "R/rtools.r" code.   The addition of a new parameter  

```r
windows_devtools_check = TRUE 
```
seems like an easy parameter to add.

Thanks,
Andre Mikulec
Andre_Mikulec@Hotmail.com

**Comment by kenahoo** [comment]
Even simpler, maybe it could only perform the check if it detects that an installation attempt failed?

**Comment by hadley** [comment]
As long as `ls` and `gcc` are on the path, devtools won't mess with it. So I'd recommend you set up your path variables appropriately.

**Comment by AndreMikulec** [comment]
Yes, error on my part.  Dummy me. I noticed that mistake today.  In my .bat file I forgot  to append ";%PATH%".
