### ISSUE TITLE
Cannot Download rsconnect from githib

### ISSUE THREAD

**Issue by DavidKamm** [hadley/devtools#1111]
I'm following the directions from rstudio to get rsconnect from github using devtools and get the following:

> devtools::install_github('rstudio/rsconnect')
Downloading GitHub repo rstudio/rsconnect@master
from URL https://api.github.com/repos/rstudio/rsconnect/zipball/master
Error in utils::unzip(src, exdir = target) : 
  cannot open file 'C:/Users/DAVIDK~1/AppData/Local/Temp/RtmpI5kqFD/devtools9283bf611fa/rstudio-rsconnect-202c93b/R/accounts.R': No such file or directory

Any idea what I am doing wrong?

**Comment by kippandrew** [comment]
I suspect something strange is going on with your environment which is breaking `devtools`.

The good news is `rsconnect` is now on CRAN, so you can install it with;

```
install.packages('rsconnect')
```
