### ISSUE TITLE
Export dcf functions

### ISSUE THREAD

**Issue by lionel-** [hadley/devtools#1112]
Would you be open to export `write_dcf()` and `read_dcf()`? I'd like to use them in vdiffr to update dependency notes à la Roxygen.

Compared to the base versions, they are nicer to work with and they format the DESCRIPTION file consistently with devtools, thus reducing commit noise.

**Comment by hadley** [comment]
I think @gaborcsardi has a separate package for this?

**Comment by gaborcsardi** [comment]
Yes, https://github.com/metacran/description

It'll go on CRAN soon, I am considering adding a non-OO API to it, and then it is good to go.

**Comment by lionel-** [comment]
thanks that looks nice!
