### ISSUE TITLE
support installing bioconductor dependencies with install_github

### ISSUE THREAD

**Issue by vivekbhr** [hadley/devtools#1113]
Hi @hadley 

I and some others faced this problem while working on a package which depends on some bioconductor packages, that when you try to install them using `devtools::install_github()`, they fail due to these dependencies which need `biocLite()` to be installed.

A way to install R packages that depends on bioconductor packages is using `biocLite()` with `siteRepos` argument, but this doesn't work for github, [as discussed here](https://www.biostars.org/p/178056/#181355) with an example.

So it would be great if devtools can provide some channel to biocLite when using install_github, so that bioconductor dependencies are also automatically installed.

Thanks
Vivek

**Comment by jimhester** [comment]
This is already supported by both `install_github()` and `biocLite()`.

```r
devtools::install_github("Bioconductor-mirror/Gviz")
```
And 
```r
BiocInstaller::biocLite("Bioconductor-mirror/Gviz")
```
both do what you want to do. If you are developing a new package make sure it has `BiocViews` populated in your DESCRIPTION, which is what devtools uses to detect a package is a Bioconductor package (https://github.com/hadley/devtools/blob/dfec75fe9d457d6b0bb04f99252e3dcf0940f0e4/R/utils.r#L149-L151).

**Comment by vivekbhr** [comment]
Thanks a lot @jimhester .. I finally got my package to work after populating the biocViews.
