### ISSUE TITLE
Installation does not work with a folder name with ' in the path.

### ISSUE THREAD

**Issue by VermillionAzure** [hadley/devtools#1114]
devtools::install_github('trestletech/shinyAce')

This does not work on Windows 7 if my user folder name has an apostrophe, as the path name is cut off where it appears in the path string.

The error is:

    Error: unexpected symbol in "tools:::.test_load_package('shinyAce', 'C:/Users/Person's"

**Comment by kevinushey** [comment]
This is an error in the `tools` package itself, so you might want to raise this with R core maintainers.
