### ISSUE TITLE
Cryptic error message for malformed @param

### ISSUE THREAD

**Issue by JohnReid** [hadley/devtools#1115]
The following code gives a crypic error message:

> Error in FUN(X[[i]], ...) : subscript out of bounds

```
#' Doc
#' 
#' @param 
#'
#' @export
#'
f <- function() {
}
```

**Comment by jimhester** [comment]
This should be submitted to https://github.com/klutometis/roxygen/issues instead.

**Comment by tbates** [comment]
Should be closed: this doesn't replicate under roxygen 5.0.1

    #' f
    #' @param 
    #' @export
    #'
    f <- function() {
    }

Build error:
    @param [test.r#3]: requires a value 

    packageVersion("roxygen2")
    [1] ‘5.0.1’
