### ISSUE TITLE
`devtools::test()` command not able to use package examples for testing

### ISSUE THREAD

**Issue by LiNk-NY** [hadley/devtools#1116]
When running a package check, the `example("exampleTopic")` line within my test-exampleTopic.R runs fine using the `testthat` framework. When solely running `devtools::test()` I get a warning and subsequent error message saying: 
```
Example tests : Warning messages:
1: In example("exampleTopic") :
  no help found for ‘exampleTopic’
...
Exited with status 1
```
Might this have to do with creating a new testing environment? Why won't package examples work?

**Comment by hadley** [comment]
That's nothing something I would advice since examples are run automatically by R CMD check anyway, and should generally serve a different purpose to tests.
