### ISSUE TITLE
publish a news file (visible at CRAN/web/packages/devtools/NEWS

### ISSUE THREAD

**Issue by tbates** [hadley/devtools#1120]
There's currently no NEWS entry for devtools at 
 https://cran.rstudio.com/web/packages/devtools/NEWS

(where there is for instance, for [Hmisc](https://cran.rstudio.com/web/packages/Hmisc/NEWS) )

**Comment by jimhester** [comment]
Devtools uses NEWS.md, which is now rendered by CRAN as HTML.

See https://cran.rstudio.com/web/packages/devtools/news.html

**Comment by tbates** [comment]
Ahh.. So this is perhaps a bug report for RStudio (which in it's package update dialog links to news and too a blank page for devtools

**Comment by jimhester** [comment]
Yep looks to be hardcoded to NEWS (https://github.com/rstudio/rstudio/blob/d5ab5dfa53c057a289179826a94622b715146e79/src/cpp/session/modules/SessionPackages.R#L429-L432)

@kevinushey What do you think the best way to handle this situation is? I don't think there is any way to tell the type of NEWS file a given package is using other than to try both of them.

**Comment by kevinushey** [comment]
I think there are a couple options:

1) Determine the appropriate NEWS link based on the contents of the `https://cran.rstudio.com/web/packages/devtools/` landing page,

2) Try both, and use the first one that works, 

One potential option (which isn't great, but avoids a web request) is to infer the appropriate NEWS URL based on the locally installed package -- e.g. look for an installed version of `devtools`, and see if there is a `NEWS.md` versus `NEWS` file present.

**Comment by jimhester** [comment]
There are 22 packages on CRAN with both NEWS and NEWS.md (https://gist.github.com/jimhester/9e5251c07ffba9e2cfd5 for query code, https://github.com/cran/granovaGG/ for an example package).

Looking at the first one https://cran.r-project.org/web/packages/granovaGG/index.html CRAN links to the rendered NEWS.html file produced from NEWS.md and does not link to the NEWS file.

I would probably do 2) as both of the options require two requests and then you don't have to worry about the layout breaking your parse.

**Comment by hadley** [comment]
Closing since this seems more like an RStudio issue
