### ISSUE TITLE
Function to check that head is up to date from remote

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#1128]
From @jimhester, should be able to do with `fetch_heads(repo)`. Replace existing function that checks remote is up to date with master.

**Comment by jennybc** [comment]
For a github remote specifically, this is now a simple API call: https://developer.github.com/changes/2016-02-24-commit-reference-sha-api/.

**Comment by krlmlr** [comment]
To me, this looks like git_sync_status() with the fetch() call re-enabled. Am I missing anything? What's the advantage of asking fetch_heads()?

**Comment by hadley** [comment]
@krlmlr the goal is to add a warning to `release()` if there are commits on the master remote that you don't have locally. What's the best way to figure that out?

**Comment by krlmlr** [comment]
I think git_sync_status() is a good template. ahead_behind() does the checking, local branch is in sync if ahead = behind = 0, if behind > 0 the remote has new commits, if ahead > 0 local has new commits. The fetch() call synchronizes with the remote.

For the release() check, you'd probably:

1. try to fetch(), if this fails (offline?) a warning is issued
2. if fetch() succeeds, check ahead_behind()
3. if ahead *or* behind, warn

**Comment by hadley** [comment]
Ah the problem seems to be that git2r doesn't support the git protocol for updating: "Error in 'git2r_remote_fetch': Unsupported URL protocol".  That makes it not very useful for me.

**Comment by krlmlr** [comment]
git: works for me on Linux, but not https: . If errors in fetch() raised a warning only, this would still be useful.

**Comment by krlmlr** [comment]
Is there a reason why the [Git-specific checks](https://github.com/hadley/devtools/blob/5eb095b314238f002118b24aafc1d0b42c378bb5/R/release.r#L57-L67) are not part of the devtools checks in release_checks()? Anyway perhaps it's better to refactor to a new `git_checks()`.

**Comment by hadley** [comment]
Because they're checks that your git state is good, not for problems with the package

**Comment by krlmlr** [comment]
I'll work on git_checks() then.

**Comment by krlmlr** [comment]
Right: The git@github.com remote protocol (for r/w access) seems unsupported, too.

**Comment by krlmlr** [comment]
@hadley: I got `git@github.com` remotes working with git2r by installing ssh2 libraries on my system. Could you check the full output of

```
install.packages("git2r")
```

to see if git2r is configured with SSH support?

**Comment by krlmlr** [comment]
@hadley: https://github.com/ropensci/git2r/issues/131 might be of interest: SSH remotes should basically work with binary builds on OS X and Windows. Can you confirm? On OS X you'd need to install from source to see if SSH support is enabled.
