### ISSUE TITLE
wrong tagname throws abstruse error

### ISSUE THREAD

**Issue by ckluss** [hadley/devtools#1130]
Hi

thx for the wunderful package. When I use @example instead of @examples I get an abstruse error

> devtools::document()
Updating x documentation
Loading x
Writing NAMESPACE
Error in file(con, "r") : cannot open the connection

If there is a simple way it would be good to get a helpfuler message ;)

Greetings
Christof

**Comment by hadley** [comment]
This is a roxygen2 bug - can you please file an issue there? (if it doesn't already exist)
