### ISSUE TITLE
DESCRIPTION: space at the end of fields that start with \n

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/devtools#1132]
This came up here: https://github.com/metacran/description/issues/14

It seems that in theory R requires a space after the colon for each key in DESCRIPTION, even if the value start with a newline. (The space is not part of the value, a newline immediately after the colon, is.)

Currently `devtools` does not add a space there, in fact if there was a space there originally, it removes it (this is only true for the most recent version AFAIR).

Handling this is somewhat tricky, because the space is not part of the value, so after we read in the file, we have no idea if there was a space there or not. Unless we store this as meta-information.

I am not sure what to do with this, and I don't think it is very important (`read.dcf` reads the file without the space), but it would be nice to handle it the same way. 

`description` currently adds a space there, even if it wasn't there originally, simply because it does not store meta-information, only the keys and the values.

**Comment by lionel-** [comment]
> I am not sure what to do with this, and I don't think it is very important (read.dcf reads the file without the space), but it would be nice to handle it the same way.

I think it's very important. Think of all the back and forth commit noise if the development tools don't format DESCRIPTION the same way :/

**Comment by hadley** [comment]
Is this now resolved? (I think it is)

**Comment by gaborcsardi** [comment]
Kinda. Currently
1. `desc` keeps the space if it is there, keeps its absence if it is absent, and adds it to new fields it creates.
2. `devtools` does not add spaces AFAIK.
3. RStudio removes the space AFAIK.

It would be great to change 3. imo, but that's a separate issue.
