### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle)

### ISSUE THREAD

**Issue by rellan** [hadley/devtools#1134]
I am getting this problem with several packages. 

```
devtools::install_github("rstudio/bookdown")
Downloading GitHub repo rstudio/bookdown@master
from URL https://api.github.com/repos/rstudio/bookdown/zipball/master
Installing bookdown
Downloading GitHub repo rstudio/rmarkdown@master
from URL https://api.github.com/repos/rstudio/rmarkdown/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
Timeout was reached`
```

None of the solutions already proposed in other issues works for me.

**Comment by rellan** [comment]
When I tried at work I didn´t have any problem. It might be some weird internet configuration at home that I am not aware of.

Solved.

**Comment by tanwira08** [comment]
I am getting this problem with "rmarkdown" . . .

devtools::install_github("rstudio/rmarkdown")
Downloading GitHub repo rstudio/rmarkdown@master
from URL https://api.github.com/repos/rstudio/rmarkdown/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL connect error
