### ISSUE TITLE
Error in release function

### ISSUE THREAD

**Issue by rz1988** [hadley/devtools#1143]
Hi, 

When I try to publish my package to CRAN by calling the release function, I got this error. My package has passed the R CMD CHECK with no notes or warnings. I ran it on Windows 10 with R 3.2.4.

Uploading package & comments
Confirming submission
Error in if (new_url$query$submit == "1") { : argument is of length zero

Thanks,
Ryan

**Comment by hadley** [comment]
Did you check all the check boxes?

**Comment by rz1988** [comment]
Hi Hadley, 

Yes I did check all the boxes. Actually, I have successfully uploaded the package to CRAN thru the website. 

Thanks,
Ryan

**Comment by antaldaniel** [comment]
I had the same issue, and after visiting the CRAN website, I realized the reason:

> CRAN vacation from Sep 1 to Sep 9, 2018.
> --
> During this time, the submission of packages is not possible.
> Sorry for any inconvenience

**Comment by vijaybarve** [comment]
@hadley Need to trap this error and change message?
