### ISSUE TITLE
Discrepancy between build_vignettes and document(roclets="vignettes")

### ISSUE THREAD

**Issue by josherrickson** [hadley/devtools#1145]
If I call `build_vignettes()`, the built vignette files get placed into inst/doc/.

If I call `document(roclets="vignette")`, the built vignette files stay in vignettes/.

There is a discrepancy here. It arises most because in current versions of Rstudio, the only way I can find to build vignettes from the interface (without running a full check or build) is to run Document, with the option for vignette selected (which adds `vignette` to the list of `roclets` in `document`).

Additionally, `clean_vignettes` only removes the files in inst/man/, not the built files in vignettes/.

Shouldn't `build_vignettes()` and `document(roclets="vignette")` function identically?

**Comment by hadley** [comment]
Could you please file this on the roxygen repo? (since it's a roxygen2 bug)
