### ISSUE TITLE
install_version doesn't work

### ISSUE THREAD

**Issue by wch** [hadley/devtools#1150]
For example:

```
> devtools::install_version("shiny", version = "0.12.0", type='source') 
Error in devtools::install_version("shiny", version = "0.12.0", type = "source") : 
  version '0.12.0' is invalid for package 'shiny'
```

This version of Shiny is present on CRAN.

I believe the problem is that `package_find_repo` no longer returns a data frame with row names, so this line fails to find a match: https://github.com/hadley/devtools/blob/d721219/R/install-version.r#L38

**Comment by jimhester** [comment]
Should be fixed with https://github.com/hadley/devtools/commit/3b066eefbadbe54bba69e725762c2a665270bd89, thanks Winston.

**Comment by wch** [comment]
Thanks!
