### ISSUE TITLE
devtools tests broken on R-oldrel (3.1.3)

### ISSUE THREAD

**Issue by jimhester** [hadley/devtools#1152]
See https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/devtools-00check.html

https://travis-ci.org/hadley/devtools/jobs/123372567#L5249-L5715

**Comment by hadley** [comment]
@wch looks like this was you - would you mind taking a look?

**Comment by hadley** [comment]
Actually seems ok now
