### ISSUE TITLE
check() should use rcmdcheck()

### ISSUE THREAD

**Issue by imanuelcostigan** [hadley/devtools#1153]
The latter has much better log formatting than the default R log.

rcmdcheck repo [here](https://github.com/MangoTheCat/rcmdcheck)

**Comment by hadley** [comment]
Not on CRAN yet

**Comment by jimhester** [comment]
Looks like it is actually https://cran.r-project.org/package=rcmdcheck

**Comment by hadley** [comment]
Ooops, I was looking for "rmdcheck"

**Comment by hadley** [comment]
Looking at a bit more, I don't think we can switch now because we have so much custom logic about envvars etc. Switching engines would be a lot of work

**Comment by jimhester** [comment]
Probably true, I guess this can stay on the backlog until we can get to it.

**Comment by imanuelcostigan** [comment]
is it bad form to :+1: ones own issue? Too late...
