### ISSUE TITLE
load_all unloads dll before calling .onUnload

### ISSUE THREAD

**Issue by hhoeflin** [hadley/devtools#1160]
When running load_all after the package was already loaded before with load_all, unload_dll is called before the .onUnload hook is executed. Due to this behavior, library functions that are needed to properly unload the package are not available.

**Comment by jimhester** [comment]
Do you have an example package where this is occurring?

**Comment by hhoeflin** [comment]
None that I can publish at the moment, sorry.

**Comment by hadley** [comment]
If your unloading code uses C, why not register it at the C level?
