### ISSUE TITLE
installing from git(hub) with submodules

### ISSUE THREAD

**Issue by jonkeane** [hadley/devtools#1163]
Currently git(hub) repositories with submodules can't be installed. There is a warning when using `install_github()`, but after the switch to `git2r` it looks like `args="--recursive"` are no longer supported in `install_git()`.

I've looked through git2r and I don't see any support for submodules there, but I might be missing it somewhere.

Would it be possible (and more importantly advisable) to add an option to check for a `.gitmodules` file when the repository is downloaded and then also download the submodules specified there before installing the package? I would be happy to take a stab at adding this and sending a pull request, but I want to make sure this isn't a terrible idea first.

This is an off shoot from Issue #751

**Comment by hadley** [comment]
Yeah, I think that's a reasonable thing to add

**Comment by vspinu** [comment]
@jonkeane, have you dug on this further? It's quite a headache I must say.

**Comment by jonkeane** [comment]
I haven't looked at this since I sent the PR. If you check out the code at that point it should work, but let me know if there are any problems and I'll see what I can do to fix them.

**Comment by jimhester** [comment]
Also a workaround with CRAN devtools is to use something like the following https://github.com/hadley/devtools/pull/751#issuecomment-215540807

**Comment by rtobar** [comment]
I'm also eager to see these changes included in devtools. Thus, I rebased @jonkeane's patch on top of the current master, and added a small improvement on top of it. I commented on the original pull request about this to know whether I should create a new one or if we can reuse it to include my changes as well.

**Comment by ronammar** [comment]
Has this feature been incorporated into `devtools` master?
Would the syntax appear as follows?:

```r
devtools::install_git(myRepoURL, args="--recursive")
```
