### ISSUE TITLE
Error using development devtools with travis-tool and installing covr

### ISSUE THREAD

**Issue by jimhester** [hadley/devtools#1165]
This is from new code merged with https://github.com/hadley/devtools/pull/1067
```r
Error in switch(x$RemoteType, github = remote("github", host = x$RemoteHost,  : 
  EXPR must be a length 1 vector
```
https://travis-ci.org/trinker/termco#L3830-L3834

I have not yet been able to reproduce it locally.

Also possibly related is `missing: TRUE` errors at https://travis-ci.org/hadley/devtools/jobs/125581841#L674

**Comment by krlmlr** [comment]
I've seen this too, it's handled in dd36872a1786 (part of #1183).
