### ISSUE TITLE
Honour _R_CHECK_FORCE_SUGGESTS_ in install_deps

### ISSUE THREAD

**Issue by jackwasey** [hadley/devtools#1171]
I see mention of `_R_CHECK_FORCE_SUGGESTS_` in #625 and #181 but I think this is a new use case: I want `install_deps` to (perhaps optionally, but by default) honour this environment variable. Right now, in Travis builds, `_R_CHECK_FORCE_SUGGESTS_` is ignored, and Travis builds fails because unavailable suggested packages are attempted to be installed, and there is not a check for whether _all_ the dependencies were installed successfully.

This is probably an Travis R script bug, too, but I wonder what you think about `devtools` respecting arcane R environment variables.

**Comment by jimhester** [comment]
Devtools does not fail if packages are not installed so there is nothing to change.
