### ISSUE TITLE
install() also upgrade dependencies with fixed versions

### ISSUE THREAD

**Issue by Tutuchan** [hadley/devtools#1179]
Let's say the `Imports` field my `DESCRIPTION` file looks like this:
```yaml
Imports:
    DBI (== 0.3.1),
    dplyr (>= 0.4.3),
    DT (>= 0.1),
    jsonlite (>= 0.9.17)
```

When running `install()`, it tries to upgrade all dependencies, even the ones that have a specific version (like `DBI` in this example). Is this expected behavior ?

**Comment by hadley** [comment]
Yes - because using fixed dependencies in R is not good practice (because each library can only have one version of a package, using fixed dependencies makes mutually incompatible versions easy)
