### ISSUE TITLE
The package dependency installation for private package repositories

### ISSUE THREAD

**Issue by dykim22** [hadley/devtools#1186]
From devtools version 1.9, unofficial packages can be installed by adding the remote location to `Remotes` in the `DESCRIPTION` file. But it is only available for public package repositories. What about extending the current form to include `auth_token`?

```
Remotes: [type::]<Repository><auth_token(optional)>
```

**Comment by hadley** [comment]
I think that's a bad idea because you shouldn't be recording password like things in your DESCRIPTION.  I think using the github PAT env var should work?
