### ISSUE TITLE
Add git tagging to devtools::release()

### ISSUE THREAD

**Issue by adamobeng** [hadley/devtools#1198]
Many R packages, including those in [rOpenSci](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news) use git tags/github releases to identify their CRAN releases, and include updates from the NEWS file in the GitHub release info.

Could this be automated as part of devtools::release()?

(cc @scottkosty, @njtierney, @kbenoit)

**Comment by wch** [comment]
One problem is that, right after you run release(), you can't be sure that the submitted package will actually be accepted onto CRAN without any revisions.

**Comment by kbenoit** [comment]
Or that Brian Ripley won't give you two weeks to upload a revision, after it's been published, to fix a single non-ASCII character in an .Rd file!

**Comment by wch** [comment]
Just another thought about this: One thing that `release()` could do is to write a file named "released_to_cran" to package directory, with some content like: "This package was sent to CRAN with devtools::release(). If it was accepted, you should remove this file and tag the commit that was released (a3728b). If it was rejected, just remove this file."

Seeing the file there would serve as a reminder to tag the commit before committing more code.

**Comment by hadley** [comment]
Oh I like that idea!
