### ISSUE TITLE
install_github(): trouble installing github dependencies

### ISSUE THREAD

**Issue by jennybc** [hadley/devtools#1207]
I'm having trouble with `install_github()` in the case where it will also need to install dependencies from github remotes. It seems the host URL is missing `https://`. 

``` r
withr::with_libpaths(tmp_lib, devtools::install_github(ghspec, force = TRUE), "prefix")
#> Using GitHub PAT from envvar GITHUB_PAT
#> Downloading GitHub repo jennybc/googlesheets@v0.2.0
#> from URL https://api.github.com/repos/jennybc/googlesheets/tarball/v0.2.0
#> Installing googlesheets
#> Downloading GitHub repo hadley/dplyr@master
#> from URL api.github.com/repos/hadley/dplyr/tarball/master
#> Error in curl::curl_fetch_memory(url, handle = handle) : 
#>  Couldn't connect to server
```

I suppose it is [this change](https://github.com/hadley/devtools/commit/463023920a73955874586ea2724231f3bef232fa#diff-9cd731e712d3f7ad63f2895c7b3813a2), but I'm not sure what the preferred fix would be.

**Comment by jimhester** [comment]
The issue is packages installed before https://github.com/hadley/devtools/commit/463023920a73955874586ea2724231f3bef232fa are not going to have the protocol in their RemoteUrl. I just opened #1208 to fix this.
