### ISSUE TITLE
devtools no longer writes git commit hash (sha1) to DESCRIPTION

### ISSUE THREAD

**Issue by kevinushey** [hadley/devtools#1217]
E.g.

```
devtools::install_github("hadley/lazyeval")
cat(readLines(system.file("DESCRIPTION", package = "lazyeval")), sep = "\n")
```

```
Package: lazyeval
Version: 0.1.10.9000
Title: Lazy (Non-Standard) Evaluation
Description: An alternative approach to non-standard evaluation using
    formulas. Provides a full implementation of LISP style 'quasiquotation',
    making it easier to generate code with other code.
Authors@R: c(
    person("Hadley", "Wickham", ,"hadley@rstudio.com", c("aut", "cre")),
    person("RStudio", role = "cph")
    )
License: GPL-3
LazyData: true
Depends: R (>= 3.1.0)
Suggests: knitr, rmarkdown (>= 0.2.65), testthat, covr
VignetteBuilder: knitr
RoxygenNote: 5.0.1
Author: Hadley Wickham [aut, cre],
  RStudio [cph]
Maintainer: Hadley Wickham <hadley@rstudio.com>
Built: R 3.2.4; x86_64-apple-darwin13.4.0; 2016-06-09 20:54:06 UTC; unix
RemoteType: github
RemoteHost: https://api.github.com
RemoteRepo: lazyeval
RemoteUsername: hadley
RemoteRef: master
GithubRepo: lazyeval
GithubUsername: hadley
GithubRef: master
```

Note that the `GithubSHA1` field is no longer written. This is quite problematic as it breaks `packrat`s ability to `restore()` projects with latest devtools -- hopefully the fix is simple! (cc: @jimhester)

**Comment by jimhester** [comment]
Ah you have yourself to blame for this one I think [`devtools::git_extract_sha1()`](https://github.com/hadley/devtools/blob/master/R/git.R#L153-L175) is not working because it assumes a .zip file format rather than .tar.gz. (due to #1196).

We will have to see if there is a corresponding comment on the tarball.

**Comment by jimhester** [comment]
From https://www.kernel.org/pub/software/scm/git/docs/git-archive.html

>  Additionally the commit ID is stored in a global extended pax header if the tar format is used; it can be extracted using git get-tar-commit-id

Don't know if git2r has a similar command (I am guessing not).

**Comment by kevinushey** [comment]
Ah, shoot -- thanks for digging in. I'll see if we can use similar tricks to extract the header from the tarball.

**Comment by kevinushey** [comment]
It seems like the git commit id is not actually embedded in the tarballs distributed through the GitHub API, so we might have to revert that commit and go back to using `zip`. 😞 

(`git get-tar-commit-id` is failing to discover the commit id, in my case)

**Comment by kevinushey** [comment]
Oops, sorry, they are -- but you have to un-`gzip` the file first (to get the plain `tar` archive), and then attempt to read from that.

Overall, I think we might want to just revert to downloading zipballs. (Sorry for the noise!)
