### ISSUE TITLE
Problems with git checking?

### ISSUE THREAD

**Issue by rpruim** [hadley/devtools#1227]
I'm getting this

``` r
devtools::release()
## Uncommited changes in git. Proceed anyway?
```

but I've just committed and pushed.  Is this picking up that there are untracked files?  Is it just a bug?  I chose to "proceed anyway", but I'd like to know what caused the warning.

**Comment by jimhester** [comment]
Yes anything that shows up when you run `git status` will trigger this (including untracked files).

Either run `git clean` to remove them, add them to your `.gitignore` to ignore them or ignore this warning (as you did).

This behavior is needed if you forget to commit a new file for instance, so this is definitely working as intended.

**Comment by rpruim** [comment]
Perhaps the message could change.  I did not have "uncommited changes".  Perhaps "uncomitted changes or untracked files" would be better.  Even better would be to have it detect which problem exists and report accordingly.

While I do use .gitignore, I often have a handful of files that are not required for building the package, but I haven't decided about regarding being on github.  These are things like notes to myself in data-raw/.  I leave them untracked to keep them on my radar.

**Comment by hadley** [comment]
Yeah, I'm not entirely sure what the message should be here. I find it a helpful reminder because often I forget to check stuff in and then what's on github is subtly out-of-sync with what's on CRAN.

**Comment by rpruim** [comment]
I like the reminder as well, so I'm not complaining about that.  And being reminded about untracked files is good too, because I sometimes forget to add in derived files (like .Rd files).  But the message makes it sound like there are modified, tracked files in need of committing.

**Comment by hadley** [comment]
Re-opening just as a reminder to improve the text
