### ISSUE TITLE
should submit_cran() emit a warning or ask for confirmation?

### ISSUE THREAD

**Issue by rpruim** [hadley/devtools#1228]
It is easy to spot this (say by auto-completion) and think it is what `release()` is.  (Someone I know may have done this ;-)  Perhaps an argument could be added to avoid this when called from within other functions (like `release()`) but alert interactive users to the existence of `release()`, since that is likely what they want.

**Comment by hadley** [comment]
It doesn't feel too dangerous to me as you still have to confirm submission with the email link.

**Comment by hadley** [comment]
`submit_cran()` should probably work the same way as `build_win()`, i.e. move the confirmation & email check out of `release()`.
