### ISSUE TITLE
Proposal of new function: build_manual()

### ISSUE THREAD

**Issue by twolodzko** [hadley/devtools#1238]
As far as I know, devtools do not offer possibility to easily and directly build pdf manual. Maybe something like the function below could be added?

```
#' Create package manual
#' 
#' @param pkg package description, can be path or package name.  See
#'   \code{\link{as.package}} for more information
#' @param path path in which to produce package.  If \code{NULL}, defaults to
#'   the parent directory of the package.
#' 
#' @seealso \code{\link{RdUtils}} 
#' @export

build_manual <- function(pkg = ".", path = NULL) {
  pkg <- as.package(pkg)
  if (is.null(path)) {
    path <- dirname(pkg$path)
  }
  name <- paste0(pkg$package, "_", pkg$version, ".pdf", collapse = " ")
  system(paste0("R CMD Rd2pdf --force --output=", path, "/", name, " ", shQuote(pkg$path), collapse = " "))
}
```

**Comment by AndreasChristianHill** [comment]
After installing the latest devtools release, I also just ran into the issue that running "check" or "build" does no longer produce a pdf-manual. It says --no-manual and I don't know how to change this. Is this a new issue of devtools or did i might have changed some settings?

**Comment by twolodzko** [comment]
@AndreasChristianHill that is actually one of the reasons I started using this function... AFAIK this default behavior cannot be changed.

**Comment by AndreasChristianHill** [comment]
@twolodzko Spending a bit more time reading the devtools-manual, I figured out that all options (including producing a pdf-manual) can actually be set if you call the respective functions "check" and "build" in the command line. E.g. checking with producing a manual goes like `check(pkg = ".", document = TRUE, build_args = NULL, ...,
  manual = TRUE, cran = TRUE, check_version = FALSE,
  force_suggests = FALSE, run_dont_test = FALSE, args = NULL,
  env_vars = NULL, quiet = FALSE, check_dir = tempdir(), cleanup = TRUE)`.
However, it seems to me that these options cannot be changed using the "configure build tools" in RStudio anymore. That would be worth a request @Hadley in my opinion.

**Comment by twolodzko** [comment]
@AndreasChristianHill sorry, this is what I meant - Rstudio. Running `check(manual=TRUE)` works fine, but needs you to wait until compilation, while `R CMD Rd2pdf` works instantly. As about Rstudio, I did not found any way to revert the default behavior to produce pdf's.

**Comment by hadley** [comment]
This seems like a good idea, but unfortunately it's not high enough on my priority list that I will implement it myself. However, I'd be happy to review a PR.

**Comment by twolodzko** [comment]
@hadley what about the code I proposed in my initial message? I may pull it (it works for me on Windows and Linux), but I can't see point of PR if for some reason you find it insufficient. Also my knowledge of what can go wrong in producing the pdf manuals is limited to practical issues, so I don't know what could potentially go wrong with the code (if it can).

**Comment by hadley** [comment]
Yeah, that seems a fine place to start for a PR.
