### ISSUE TITLE
install_svn doesn't work with R-forge

### ISSUE THREAD

**Issue by dmurdoch** [hadley/devtools#1239]
As mentioned in https://github.com/hadley/devtools/issues/684 last year, `install_svn` assumes all paths in Subversion repositories contain either "trunk" or "branches".  Those are just conventional names, they aren't requirements, and the repositories created on R-forge.r-project.org don't use those names.

I don't like the suggested fix from https://github.com/hadley/devtools/issues/684.  The proper fix is to drop the assumption that every repository must have a particular structure.  Allow users to specify something like `svn://svn.r-forge.r-project.org/svnroot/rgl/pkg/rgl` entirely in the `url` part of the name, or split up between the `url` and `subdir` parts.

Edited to add:  The same problem occurs in `remotes`, which got the code from here (or vice versa).  I've created a patch and sent the following pull request there:  https://github.com/MangoTheCat/remotes/pull/33.

**Comment by jimhester** [comment]
I agree this is a major limitation with the current implementation of `install_svn()` and that dropping this assumption is the right idea. 

Non-standard SVN layouts was part of the motivation for writing `install_bioc()`, although Bioconductor repositories also have additional requirements that would require a custom function even with this change.

**Comment by hadley** [comment]
Devtools will be switching to use remotes in the future, so I'm going to close this issue. Thanks for the PR!

**Comment by gaborcsardi** [comment]
I think this is fixed in `remotes`, actually.
