### ISSUE TITLE
class (Rcpp module) accessible via load_all but requires <package>::: reference following build, install and attachment.  Why?  

### ISSUE THREAD

**Issue by flummoxed** [hadley/devtools#1241]
I have been presuming that classes exposed via an Rcpp Module using loadModule(<moduleName>,TRUE) would be accessible WITHOUT the namespace qualifier (after attachment).   Any clarification/redirection is appreciated:

```
 > library(devtools)
 > library(roxygen2)
 > devtools::document()
 Updating <package> documentation
 Loading <package>
 Loading required package: haven
 Loading required package: dplyr
 Loading required package: ggplot2
 Loading required package: Rcpp
 .onInit called from within zzz.R (loadModule, TRUE)

 > Individual
C++ class 'Individual' <0x7faa2361e300>
```

after building (devtools::build) and installing package (type="source"):

   library(package)
   Loading required package: haven
   Loading required package: dplyr
   Attaching package: ‘dplyr’
   Loading required package: ggplot2
   Loading required package: Rcpp
  .onInit called from within zzz.R (loadModule, TRUE)

> Individual
>    Error: object 'Individual' not found
> <package>:::Individual
>    C++ class 'Individual' <0x7f96b0c9c6f0>

**Comment by dmurdoch** [comment]
It would only be accessible if it is exported in your NAMESPACE file.  If you're using roxygen2 to produce that file, are you telling it to export the symbol?  If you're writing it yourself, are you explicitly doing the export?  In any case, this doesn't look like a `devtools` issue.

**Comment by flummoxed** [comment]
After trial and error -- located this prior thread with a solution which
worked:

https://github.com/klutometis/roxygen/issues/374

Thank you
