### ISSUE TITLE
Remove `Remotes` field when doing release()

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/devtools#1242]
Maybe.

**Comment by jimhester** [comment]
We should just have a check in `release()` that fails if you have `Remotes:`. Keeping it in is going to generate a NOTE from R CMD check which CRAN will complain about.

**Comment by gaborcsardi** [comment]
Well, the check is already there, you get a NOTE when `release()` runs the check. So in this case there is nothing to do.

I was thinking about removing it from the built tarball (with a warning or message).

**Comment by hadley** [comment]
devtools release check flags it too I think
