### ISSUE TITLE
devtools::install and install_github do not pass on Additional_repositories on when installing deps?

### ISSUE THREAD

**Issue by cboettig** [hadley/devtools#1243]
If I have package A that depends on package B, which depends on package C; and B & C are in the listed `Additional_repositories` drat repository, it seems `devtools::install()` fails to find package C when trying to install B (and thus fails to install A & B).  A simple `install.packages("A", repo="my.drat.repo")` works fine.

For a concrete example:

``` r
install.packages("RNeXML", dep=TRUE, repos=c("https://cran.rstudio.com", "http://packages.ropensci.org"))
```

Works just fine.  But 

``` r
devtools::install_github("ropensci/RNeXML", deps=TRUE)
```

fails by failing to install the suggested dependency `rrdf` because `rrdflibs` is "not available", even though both are on the drat repo.

**Comment by eddelbuettel** [comment]
Also, the discussion [in the remotes vignette](https://github.com/hadley/devtools/blob/master/vignettes/dependencies.Rmd) fails to mention `drat` use.  Given that CRAN supports it, and other packages use it, you may want to mention this (as a non-devtools alternative).

**Comment by jimhester** [comment]
@cboettig I just opened a PR that should address your issue (as long as you specify your repos appropriately)

@eddelbuettel That vignette was written to explain the remotes feature of devtools, not as a general review of available CRAN alternatives. However if you would like `drat` to be mentioned in it I am sure we would be happy to merge a pull request with the change.

**Comment by cboettig** [comment]
Thanks @jimhester , very nice!

**Comment by eddelbuettel** [comment]
@jimhester could do if you think it fits -- I was mostly coming from the 'well remotes is not the only way to do this' angle of actually mentioning the fact that CRAN now formally supports Additional_repositories.  The remotes documentation, focused as it is, seems to imply it was the only game in town.
