### ISSUE TITLE
install_bitbucket fails when dependencies are private

### ISSUE THREAD

**Issue by moosilauke18** [hadley/devtools#1245]
So, I have a repo in bitbucket which is private the depends on another private repo. As of the latest devtools version (1.12.0), it fails with a 401 unauthorized. I'm using `dependencies=TRUE` and sending auth_user and password in `install_bitbucket`. 

Also, the dependency I can install no problem first, so it's an issue when the dependency is private.

**Comment by thercast** [comment]
Just wanted to mention that I'm experiencing the same issue with private GitHub repositories that depend on packages in other GitHub private repositories.  I installed the dependency package from the other private repo first and the install went through without a hitch.  But during the installation of the main package from the private GitHub repo it still tries to install the dependency package even though it is already available.  FWIW I am using packrat with this project.

**Comment by filipsch** [comment]
I'm also seeing this issue. Exact same situation that @moosilauke18 mentions, but for private packages on GitHub.
