### ISSUE TITLE
check modifies RcppExports

### ISSUE THREAD

**Issue by rdiaz02** [hadley/devtools#1248]
Running `devtools::check("somedir", document = FALSE)` can modify (without any notification) files `/R/RcppExports.R` and `/src/RcppExports.cpp`. I think this is a bug, since I cannot find it documented that modification of those files is a possible side effect of running `check`.

In the most inocuous cases, these leads to adding/removing spaces/newlines, which is annoying (as under version control things have changed, but trivially).

In more serious cases this might mean that a package that passes `R CMD check` fails `devtools::check`.

Even if these possible modifications were made explicit in the help, I do not think modifying these files would be a good idea. I'd suggest running the check **without** modifications, and adding the suggested modifications to the output).

**How can the behavior that leads to errors be triggered?**

Having commented arguments in the function calls.

a) Definitely if you have them in your C++ code, like

```
// [[Rcpp::export]]
void f(double x,
       //double y,
       double z) {
blablabla
```

The `y` leads to the spurious introduction of a `y` in RcppExports{R/cpp}.

b) I think also in some R code Suppose you have  `packagename.R` with a function
like

```
f <- function(x) {
  g(
  #y = oldy,
  x = x)
}
```

And in RcppExports you'll have

```
g < function(x) {
  .Call('packagename_g', PACKAGE = 'packagename', x)
}
```

And in RcppExporst.cpp

```
SEXP packagename_g(SEXP xSEXP);
blablabla
```

**How can this behavior that leads to removing newlines/whitspace be  triggered?**

Add newlines between entries for each function in `RcppExports.cpp`, add
extra whitespace between arguments in `RcppExports.cpp`, etc.

**Comment by hadley** [comment]
It automatically calls `Rcpp::compileAttributes()` for you, which I think is important.

**Comment by rdiaz02** [comment]
You are the boss, of course, but that behavior can break perfectly functional packages. In particular, the examples I give above show that comments, which should be innocuous, can lead to breakage. Moreover, this precludes a package author from tuning the output of `Rcpp::compileAttributes()` outside of `devtools`.

I think that calling `Rcpp::compileAttributes()` should be optional and, ideally, its output should not overwrite the existing files (but be provided as a suggestion).

**Comment by hadley** [comment]
I think if you are hand-tuning the output from `Rcpp::compileAttributes()` you are going to be in a world of pain anyway.

**Comment by rdiaz02** [comment]
Not if I decide to add another argument to a function, for instance, or comment one out sometime after I got the output from `compileAttributes`. Modifying the files is simple. 

Regardless, one might want to use `devtools` on packages that have long had the `compileAttributes` dance taken care of but, as I showed above, that might fail.
