### ISSUE TITLE
biocInstaller necessary if biocViews in DESCRIPTION but not a bioc Package

### ISSUE THREAD

**Issue by muschellij2** [hadley/devtools#1254]
This issue arose in the `matrixStats` package (https://github.com/HenrikBengtsson/matrixStats), with associated issue opened there @HenrikBengtsson:
https://github.com/HenrikBengtsson/matrixStats/issues/88

Overall, the "issue" is that in utils https://github.com/hadley/devtools/blob/master/R/utils.r#L155:
```r
is_bioconductor <- function(x) {
  x$package != "BiocInstaller" && !is.null(x$biocviews)
}
```
Implies that if biocViews exists and the package is not `BiocInstaller`, then the package is assumed bioconductor package.  This is probably a good assumption or one of the only ways to distinguish the CRAN/bioC package distinction.  Thus, though not an `Imports` or `Suggests`, `BiocInstaller` seems to be a hidden/implicit dependency when installing using `devtools`.  This affects Travis builds.  

This may not be an "issue" exactly, and I may just add an install of `BiocInstaller` to the Travis to make it work, but figured I'd bring up the point here.

**Comment by jimhester** [comment]
Yes this is true, however on travis there is no need to install `BiocInstaller` manually. You can set

```yaml
use_bioc: true
```
To automatically install `BiocInstaller`, or set

```yaml
r:
  - bioc-devel
  - bioc-release
```

To testing using the current Bioconductor devel and release branch (automatically implies use_bioc).

**Comment by muschellij2** [comment]
Adding `bioc_packages: BiocInstaller` worked:
https://travis-ci.org/muschellij2/testmatrixstats/builds/142568390
as well as `use_bioc: true`:
https://travis-ci.org/muschellij2/testmatrixstats/builds/142569006

As I just want to check against CRAN (as these are **all** CRAN-based packages), I think just using `use_bioc: true` maybe the most appropriate.  I just have never run into `biocViews` causing a problem with installation because it has an inherent dependency of sorts on `BiocInstaller` though no packages in the installation actually depend on that package or any bioC packages

This should patch the issue discussed with @HenrikBengtsson for `matrixStats`, but I'd like to hear your thoughts about needing to add to the non-default `.travis.yml` (from `use_travis()`) for packages that do not depend on bioC, but have bioViews in DESCRIPTION.

**Comment by muschellij2** [comment]
Although this should be solved in future versions of matrixStats, this method did not seem to work for the following package based on the error:
https://travis-ci.org/emsweene/oasis/builds/142846730#L1043

**Comment by jimhester** [comment]
The argument is `bioc_required: true`, I was going off of memory (which is faulty, sorry).

**Comment by muschellij2** [comment]
Thanks - I'll look into and close again.

**Comment by benjjneb** [comment]
I just ran into this same issue after making an innocuous change to my Bioconductor package (https://github.com/benjjneb/dada2).

Adding both `use_bioc: true` and `bioc_required: true` to  `.travis.yml` finally fixed the problem, but why did this suddenly crop up?
