### ISSUE TITLE
Regression testing for revdep check

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1255]
1. Install dev version of package
2. Perform revdep check
3. Save
4. Install current CRAN version
5. Perform revdep check
6. Save
7. Compare

This allows isolating packages that are failing already with the currently released version of a package. Test times double, but processing power is cheap.

To keep things simple, the `check.R` file generated by `use_revdep()` could be adapted to create two calls to `revdep_check()`. A luxury version would extend this by comparing the check results and writing only the regressions to a separate file.

**Comment by jimhester** [comment]
I agree this is the best strategy. To save time you only really only need to check the packages which fail in some way in the first check, which should speed things up for the second round of checks.

**Comment by krlmlr** [comment]
FWIW, I'm getting good results with a simple shell script: https://github.com/rstats-db/RSQLite/blob/750624bc6f4c568c3a164caa1629b60b89764ca2/revdep/diff.sh.

**Comment by hadley** [comment]
This is the strategy implemented in revdepcheck, and boy is it better
