### ISSUE TITLE
idea: use_pipe()?

### ISSUE THREAD

**Issue by ijlyttle** [hadley/devtools#1258]
Given the emergence of the idea of Tidy API's, which encourages use of the pipe, could it be useful to provide a function `use_pipe()` that would create a pipe.R file like [this](https://github.com/rstudio/ggvis/blob/master/R/pipe.R)? h/t @ramnathv [here](http://stackoverflow.com/questions/27947344/r-use-magrittr-pipe-operator-in-self-written-package#comment56720179_27979637).

I see the plus side as making it easier to use "your" package functions not having to load magrittr explicitly.

I see a drawback (potentially) if _every_ package exports the pipe, could that be messy/problematic? (Honestly, I don't know.)

Thoughts?

**Comment by hadley** [comment]
I like it. As far as I know, there are no problems with everyone re-exporting the pipe.

**Comment by hadley** [comment]
Also it might be worthwhile to let this simmer for a bit, with the aim of eventually becoming `use_tidyverse()` or similar.

**Comment by ijlyttle** [comment]
Happy to let this simmer - if/when I can be of help, please let me know.
