### ISSUE TITLE
Error resolving package name for private github repo

### ISSUE THREAD

**Issue by eriknil** [hadley/devtools#1262]
I'm running into some problems when installing and resolving dependencies for packages that imports/depends on packages in a private github repo.

``` r
> deps <- devtools::dev_package_deps(dependencies = TRUE)
Using GitHub PAT from envvar GITHUB_PAT
Using GitHub PAT from envvar GITHUB_PAT
Error in data.frame(package = package, installed = installed, available = available,  : 
  row names contain missing values
> 
```

The issue seems to be that we are not authenticating to Github when trying to resolve the package name. We then end up getting an error message when trying to construct a `data.frame` of named vectors with `NA` names.

I'm submitting a pull request for a solution where we:
1. Use the oath_token to authenticate before downloading the DESCRIPTION file.
2. Download the description from https://raw.githubusercontent.com/user/repo/... instead of https://github.com/user/repo/RAW/.... For some reason the latter approach doesn't seem to work.

**Comment by eriknil** [comment]
We get the same error when specifying a remote package in the DESCRIPTION that doesn't exist.

I've uploaded a package on eriknil/depError that will fail to install because of this. Reproducible example below:

```r
> devtools::install_github("eriknil/depError")
Downloading GitHub repo eriknil/depError@master
from URL https://api.github.com/repos/eriknil/depError/zipball/master
Installing depError
Error in data.frame(package = package, installed = installed, available = available,  : 
  row names contain missing values
> 
```

I updated the PR to fix this.

**Comment by DavidSichau** [comment]
We have currently the same problem, is there any chance that this pull request can be accepted?

**Comment by eriknil** [comment]
I ended up using the old [r-travis](https://github.com/craigcitro/r-travis) instead. Had to change a few things but this allowed me to install my own fork of devtools. Just a temporary solution though.

Would be glad to update the PR if there's anything else needed.

**Comment by jimhester** [comment]
It will likely be merged eventually next time we are doing devtools maintenance.

In the meantime you can add `r_github_packages: hadley/devtools#1263` to your `.travis.yml` and it would use the code from that pull request to install dependencies.

**Comment by dy-kim** [comment]
@jimhester Is it `r_github_packages: hadley/devtools#1263`, not `r_github_packages: hadley/devtools#1262`?

**Comment by jucor** [comment]
Hi @jimhester , @hadley : any chance you'd share no-commitment guesstimate when is the "devtools maintenance"? Promise, we won't hold you to it :)

**Comment by jimhester** [comment]
The plan is to do major package development work in the next month or so

**Comment by jucor** [comment]
Great, thanks a lot for the quick answer and the heads up @jimhester!  (and it is pre-emptively understood that "plan" and "reality" do not always match)

**Comment by kirillseva** [comment]
@jimhester ;)

**Comment by deanchen** [comment]
Would be great if we can get this supported within devtools. We've been maintaining a forked version of devtools for this reason.

**Comment by cmdcolin** [comment]
This is just a random note but I ran into this same error message when I had a "Remotes:" line in my description file that separated the two things by spaces instead of comma, and then installed the app via install_github. If devtools was able to catch that error it would be great ;) but otherwise just thought I'd add that note for posterity
