### ISSUE TITLE
Error when calling getMyConnections

### ISSUE THREAD

**Issue by PanosJee** [hadley/devtools#1267]
When I try to call getMyConnections(in.auth) I get the following error:

> Error in UseMethod("xpathApply") : 
>   no applicable method for 'xpathApply' applied to an object of class "c('xml_document', 'xml_node')"

LinkedIn doesn't allow me to add the r_network scope to my app anymore & perhaps connection data are not available anymore. I guess this should be the reason for the problem.

**Comment by hadley** [comment]
I don't think this is a devtools issue
