### ISSUE TITLE
`check(check_version = FALSE)` should use `_R_CHECK_CRAN_INCOMING_REMOTE_`

### ISSUE THREAD

**Issue by dmurdoch** [hadley/devtools#1271]
Currently the `check_version` option of `devtools::check()` defaults to `FALSE`.  When `FALSE`, it sets  `_R_CHECK_CRAN_INCOMING_` to false, which does a lot more than just turning off the version checks:  it also turns off a bunch of style checks which can cause a package to be rejected by CRAN.  Those style checks are quick, unlike the version number check, which can be quite slow.

I've just added a new environment variable to R-devel (as of revision r70944) called  `_R_CHECK_CRAN_INCOMING_REMOTE_` which is a more appropriate variable to set false by default.  It keeps the quick local checks, but turns off the remote ones, including the version check.  (The style checks will still only be run if `_R_CHECK_CRAN_INCOMING_` is true, e.g. if `--as-cran` is given as a check option.)

It's not clear yet whether this will make it into R-patched, so for now it should only be used if

```
getRversion() >= "3.4.0" && as.numeric(R.version[["svn rev"]]) >= 70944
```

**Comment by hadley** [comment]
@dmurdoch I'm finally getting around to implementing this. Did it make it into R-patched?

**Comment by dmurdoch** [comment]
No, it's still only in R-devel.  It probably should go into R-patched, I just haven't had time.  If you're planning a devtools update soon I'll try to push it forward, but otherwise I'd like to wait until things calm down here in December.

**Comment by hadley** [comment]
I'm working on devtools at the moment, but we're planning for a big release (splitting devtools up into many smaller pieces), so it's unlikely to be ready this year.
