### ISSUE TITLE
load_all() error: shared object not found?

### ISSUE THREAD

**Issue by skyebend** [hadley/devtools#1272]
I'm trying to test reverse dependencies of the sna package before release. revdep_check fails with "Error (1)" message.  After looking at another issue here, I'm trying `load_all()`, which reports that it isn't locating the shared library, even though I've just run R CMD INSTALL to install it.  Any suggestions on how to debug?  I'm running R in the bash terminal on debian. 

```
load_all('sna', quiet=FALSE)
Loading sna
Loading required package: statnet.common
Loading required package: network
network: Classes for Relational Data
Version 1.13.0 created on 2015-08-31.
copyright (c) 2005, Carter T. Butts, University of California-Irvine
                    Mark S. Handcock, University of California -- Los Angeles
                    David R. Hunter, Penn State University
                    Martina Morris, University of Washington
                    Skye Bender-deMoll, University of Washington
 For citation information, type citation("network").
 Type help("network-package") to get started.

Error in library.dynam("sna", package = pkgname, lib.loc = libname) : 
  shared object ‘sna.so’ not found
```

Looks like someone else had similar issue: https://groups.google.com/forum/#!topic/rdevtools/57Px4zBuhcY

**Comment by stla** [comment]
Similar problem with `devtools:release()`.

**Comment by hadley** [comment]
Could you please provide a minimal reprex? You need to at least provide a link to sna, but ideally you'd do work on a copy of the sna package progressively removing code until you figure out exactly what's triggering the problem.

**Comment by skyebend** [comment]
sna is on CRAN.  But I'm no longer seeing the original issue, so perhaps it was local config problem.

```
install.packages('sna')
library(devtools)
load_all('sna',quiet=FALSE)
Error: Can't find 'sna'.
```
However, if I peek in .libPaths() and give it the full path to the package, it works fine and does not generate the shared object error.  I'm guessing that before I only gave the path to the local source dir, not the installed system path. 
```
load_all('/home/skyebend/R/i686-pc-linux-gnu-library/3.2/sna',quiet=FALSE)
Loading sna
Loading required package: statnet.common
Loading required package: network
network: Classes for Relational Data
Version 1.14 created on 2016-05-07.
copyright (c) 2005, Carter T. Butts, University of California-Irvine
                    Mark S. Handcock, University of California -- Los Angeles
                    David R. Hunter, Penn State University
                    Martina Morris, University of Washington
                    Skye Bender-deMoll, University of Washington
 For citation information, type citation("network").
 Type help("network-package") to get started.
```

**Comment by hadley** [comment]
I think you misunderstand `load_all()` - it's meant to be called on a local development package, not an installed package.
