### ISSUE TITLE
Check() fails while Travis-CI and winbuilder pass.

### ISSUE THREAD

**Issue by privefl** [hadley/devtools#1274]
My package in developement: 
https://github.com/privefl/bigsnpr

**Explanation of the issue:**
I need package "snpStats" from Bioconductor for comparative tests, so I put it in my DESCRIPTION file.
After some researchs on the Internet, I chose to add 
```
SuggestsNote: BioC (>= 3.0)
Additional_repositories: http://bioconductor.org/packages/release/bioc/
```
in my DESCRIPTION file in order to enable the view of "snpStats" during the installation of packages in the check.

When doing that, Travis-CI and winbuilder builds pass without any error but `devtools::check()` or
`devtools::check(force_suggests = TRUE)` don't, saying that "snpStats" is not available.

I am doing something wrong ? Is it an issue with devtools ?

**Comment by ck37** [comment]
If you add `biocViews:` to your DESCRIPTION file I think you don't need the extra suggestsNote or Additional_repositories.

**Comment by privefl** [comment]
```
#SuggestsNote: BioC (>= 3.0)
#Additional_repositories: http://bioconductor.org/packages/release/bioc/
biocViews:
```
won't work anymore (tested on Travis).

**Comment by privefl** [comment]
See fix at https://github.com/privefl/bigsnpr/pull/1.

Thanks jimhester.
