### ISSUE TITLE
error in devtools::install_github('IRkernel/IRkernel') / win10 x64 

### ISSUE THREAD

**Issue by Luxios** [hadley/devtools#1275]
I have met something wrong like this,

devtools::install_github('IRkernel/IRkernel')
Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
Downloading GitHub repo IRKernel/IRdisplay@master
from URL https://api.github.com/repos/IRKernel/IRdisplay/zipball/master
Installing IRdisplay
"D:/Program Files/R/R-3.2.5/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Luxio/AppData/Local/Temp/RtmpiSGMTK/devtoolsb105cbc7cbf/IRkernel-IRdisplay-8e24901"  \
  --library="D:/Program Files/R/R-3.2.5/library" --install-tests 

'D:\Program' neither inside or outside order，nor exe or bat.
Error: Command failed (1)

How can I deal with it?

**Comment by cosli** [comment]
@Luxios 
Just try to reinstall R in a dirctory where the `path` doesn't include `space` , like `D:/R` .

**Comment by burgerga** [comment]
@cosli that is not always possible, and seen the numerous threads/issues opened everywhere, it would definitely by easier if devtools would properly escape paths.

**Comment by cosli** [comment]
@burgerga Yes, that would be the best way by making ` devtools` package to handle this error properly.

**Comment by burgerga** [comment]
@cosli I was having another look at it, but can't reproduce the issue with the newest R, 3.3.1, can you?

**Comment by Luxios** [comment]
@burgerga  No,I can't. I tried to use another tool.Has the problem be solved?
