### ISSUE TITLE
FR: Get rid of C code

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1282]
This would allow building/upgrading devtools on Windows without Rtools and perhaps without `build_github_devtools()`.

It's only the `nsreg()` function which is called by `ns_registry()`; to me it looks like it does the same as `.Internal(getNamespaceRegistry())`. Getting the latter past the CRAN checks is possible with some eval-bquote trickery. This is a CRAN-able version of `.Internal()`:

```r
internal <- function(code) {
  Internal <- as.name(".Internal")
  code_sub <- substitute(code)

  eval(bquote(
    .(Internal)(.(code_sub))))
}
```

Putting `ns_registry()` into a separate package is also an option.

**Comment by drknexus** [comment]
... even if that passed the letter of the CRAN rules regarding calling Internal functions it would seem to very much violate the spirit of the dictum.  That being said, the aim you express certainly is laudable.  One wonders if `base` would/could expose that functionality directly.

**Comment by krlmlr** [comment]
To me, exposing an internal object via C code falls in the same league as hiding a call to `.Internal()` from the CRAN checks.

Direct access to the namespace registry seems necessary so that `devtools` can emulate package loading, without actually installing the package. Under normal circumstances, this is solely the responsibility of `base`, and there are good reasons why direct access to the namespace registry is not allowed. On the other hand, `devtools` tests its package loading mechanism very carefully. To me, this means that exporting the functionality from `base` is not desired, but it's okay to bend the rules somewhat for `devtools`.

**Comment by jimhester** [comment]
```r
(get(".Internal", envir = baseenv(), mode = "function"))(getNamespaceRegistry())
# with a call to
utils::globalVariables("getNamespaceRegistry")
```
Also seems to avoid a NOTE without resorting to bquote/eval.

I think this is a good suggestion, it would be very nice to be able to install devtools without needing RTools installed.
