### ISSUE TITLE
 Error in system(cmd, intern = !verbose) : 'C:/Program' not found

### ISSUE THREAD

**Issue by reuning** [hadley/devtools#1288]
I am trying to run an RStan model but am getting an error from devtools I think. The relevant part of the error is:

```
Error in system(cmd, intern = !verbose) : 'C:/Program' not found
In addition: Warning message:
In find_rtools() :
  WARNING: Rtools 3.4 found on the path at c:/Rtools is not compatible with R 3.3.1.

Please download and install Rtools 3.3 from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH, then run find_rtools().
```

I tried running find_rtools():

```
> find_rtools()
Error: running command '"C:/Program Files/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 2
```

rtools is installed, and the path is right, I think:

```
> shell("PATH")
PATH=C:\Program Files\R\R-3.3.1\bin\x64;c:\Rtools\bin;c:\Rtools\mingw_32\bin;C:\Program Files (x86)\ActiveState Komodo Edit 10\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\SysWow64;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\Skype\Phone\;C:\Anaconda2;C:\Anaconda2\Scripts;C:\Anaconda2\Library\bin;C:\Anaconda3;C:\Anaconda3\Scripts;C:\Anaconda3\Library\bin
```

I am afraid this might be a problem with how Rtools was installed, but this is a university computer and so before trying to figure out how to get IT to fix it I wanted to make sure there wasn't something simple that I was missing. Thanks for any help.

**Comment by reuning** [comment]
I think it has to do with a path issue caused by my lack of ability to edit the path. Fixed it now by reinstalling R into a happier place.

**Comment by rubenarslan** [comment]
Can this somehow be fixed in devtools by somehow escaping the path/using short DOSpaths with ~? It's really hard to debug for non-technical users and not a very googleable error message when it happens. It can even happen for packages that don't need compilation.
