### ISSUE TITLE
install_github ignores lib argument

### ISSUE THREAD

**Issue by lshep** [hadley/devtools#1293]
Hello, 
I was trying to install a package to a specific location through the lib argument and it appears to ignore and use .libPaths()[1] .  

As an example, the following ignores the lib and installs at .libPaths()[1]
`install_github("hadley/devtools", lib="/tmp/")`

The following works as desired 
`install.packages("devtools", lib="/tmp/")`

**Comment by jimhester** [comment]
from `?install` it mentions

>     To install a package in a non-default library, use ‘with_libpaths’.

So `withr::with_libpaths("/tmp", install_github("hadley/devtools"))` should do the trick.

**Comment by lshep** [comment]
Thank you. My mistake.
