### ISSUE TITLE
document() removes "@" in example section

### ISSUE THREAD

**Issue by boxuancui** [hadley/devtools#1294]
I am writing a package, and in my example section, I have the following line of code:

    #' ...
    #' @examples
    #' ## returns version of SQL server
    #' dbGetQuery(con, "select @@version")

After running `document()`, the .Rd file removes one `@` character and it became this:

    ## returns version of SQL server
    dbGetQuery(con, "select @version")

**Comment by jimhester** [comment]
This is really a [roxygen issue](https://github.com/klutometis/roxygen/issue), but `@` symbols in roxygen need to be escaped by doubling them. So you need to use

```r
#' dbGetQuery(con, "select @@@@version")
```

**Comment by boxuancui** [comment]
I see. I will close it. Thanks for your help!
