### ISSUE TITLE
install_github fails on clean R

### ISSUE THREAD

**Issue by zji90** [hadley/devtools#1297]
When testing install_github() function on a clean R (no additional package was installed except those coming with R itself), I encountered the following problem:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘htmltools’

The command I used was as follows:

source("https://bioconductor.org/biocLite.R")
biocLite("GenomicAlignments")
if (!require("devtools"))
  install.packages("devtools")
devtools::install_github("SCRAT","zji90")

The problem seems to occur because my package SCRAT depends on shiny and shiny depends on htmltools. However for some reason this dependency is ignored (probably because this is a two-level dependency?). If I run install.packages("shiny",dependencies = T) before devtools::install_github("SCRAT","zji90") the problem does not occur any more.

The problem happens on multiple Windows computers under multiple R versions (3.3.x and 3.2.x) so I am not copying sessionInfo() here.

**Comment by jimhester** [comment]
This is a known issue (#1246, #1265) and is fixed in the development version of devtools. Please install it with `devtools::install_github("hadley/devtools")`.
