### ISSUE TITLE
use_git() should set local user name and e-mail configuration

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1299]
at least if there is no such global setting, perhaps from `getOption("devtools.desc.author")`.

**Comment by hadley** [comment]
That seems a little aggressive to me - don't we want to encourage people to set globally?  Maybe just a message if not set?

**Comment by krlmlr** [comment]
I'm using a per-repository user/email config, it would be useful to me. This would only kick in if the Git options aren't set globally *and* option `devtools.desc.author` is set, and we could give a message that describes what we do.
