### ISSUE TITLE
FR: load_all() should check imports

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1311]
Can `load_all()` check if a `NAMESPACE` import is also declared in `DESCRIPTION`?

https://github.com/klutometis/roxygen/issues/429#issuecomment-243230990

**Comment by hadley** [comment]
This would require quite a bit of NAMESPACE parsing, so I'm not sure it's worth the effort.

**Comment by krlmlr** [comment]
I've seen at least one case where a package loaded with load_all() that didn't declare an import in DESCRIPTION couldn't use that import. That also helps, but is not very nice.

The following code is a first approximation (use `ns_env()` inside `devtools`):

```r
asNamespace("devtools") %>%
  parent.env() %>%
  as.list %>%
  lapply(environment) %>%
  purrr::compact() %>%
  vapply(getPackageName, character(1)) %>%
  unique
```

**Comment by hadley** [comment]
Moved to pkgload
