### ISSUE TITLE
install_deps() doesn't check version requirements

### ISSUE THREAD

**Issue by kenahoo** [hadley/devtools#1314]
It appears that if I have a version requirement like `Imports: PackageX (>= 0.10)` in my `DESCRIPTION` file, and then I call `install_deps()` on my package when a lesser version of `PackageX` is installed, `install_deps()` won't notice that it's outdated and needs to be upgraded.

Is my understanding correct?  I didn't dig very deep in the code to confirm it yet.

One avenue to fixing it would be to use the new stuff in my PR #1259 to ensure that the correct versions of dependencies get installed.

**Comment by jonkeane** [comment]
I'm running into this issue as well, although it's in the context of of trying to install an older package from cran. 

I can get the appropriate version with devtools' `install_version()`, but it looks like `install_deps()` is calling `install.packages()` directly. It shouldn't be too difficult to swap in `install_version()` at [https://github.com/hadley/devtools/blob/12574cc356fbd8362899890f7203f61578b5e258/R/deps.R#L330-L332](lines 30-32 in `deps.R`) 

Or am I'm missing a better way to ensure/force the installation of a specific version of a dependency?

**Comment by hadley** [comment]
Yes, that is my understanding.

**Comment by kenahoo** [comment]
Wait - did you mean to close this?  It seems like it would be good to fix it.

**Comment by hadley** [comment]
It's pretty low-priority right now - if it happens it's likely to happen in another package.

**Comment by kenahoo** [comment]
I'd love to help if possible - we have a continuous build server for R packages that we sometimes have to go manually install/update stuff on when we hit this issue, and it would be nice to get it working more smoothly.  If I prepared a PR could you look at it, or is there already another package (materializing?) on this topic?

**Comment by kenahoo** [comment]
We're still struggling with this, could you comment on the "another package" you mentioned?

**Comment by hadley** [comment]
We'll probably split up in to pkgdeps for determining the complete set of dependencies of a given package and comparing against what you currently have installed; and pkginstall for installing individual packages from different sources.

**Comment by kenahoo** [comment]
That sounds like a good plan.  Thanks for the update.

I might create a forkbranch to see what could be done directly in devtools in the short term too.
