### ISSUE TITLE
Consult Urban Dictionary in setup() and release()

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1315]
for the package name. Per [Hadley's PSA](https://twitter.com/hadleywickham/status/770744837104541696).

Can use the udapi package. With Ironholds/udapi#1, we get:

``` r
print(get_term("PSA")[1:3,])
```
- (+1196/-143) Publice Service Announcement.  Rarely used as an acronym.
  
  > This following snow warning is a public service announcement.
- (+228/-196) A protein made specifically by the prostate gland -- Prostate Specific Antigen. It is
  measured by a blood test, and is used for screening for prostate cancer and checking for the
  results of treating that disease.
  
  > James saw his doctor today, since he was upset that his PSA was over ten thousand (normal is
  >     up to four). Then he went to make final arrrangements.
- (+158/-143) Pacific Southwest Airlines headquartered in San Diego, California. Featured
  Smileliners (Airplanes with smiles painted on the nose). Purchased by USAir in 1987
  
  > "PSA, Catch our smile!"

**Comment by hadley** [comment]
It seems a bit aggressive to run this every time. Just a helper function would be handy though.

**Comment by krlmlr** [comment]
Do you want to wrap udapi::get_term()? How about calling for setup() only, and add a release question?
