### ISSUE TITLE
Install from github failing on Windows

### ISSUE THREAD

**Issue by cdeterman** [hadley/devtools#1316]
I am trying to troubleshoot an install of my gpuR package on a Windows machine.  The build progresses normally but when it tries to load the package it fails with the following final output:

``` r
ERROR: loading failed
* removing 'C:/Users/User/Documents/R/win-library/3.3/gpuR'
* restoring previous 'C:/Users/User/Documents/R/win-library/3.3/gpuR'
Error: Command failed (1)
```

Running a `traceback()` results in the following but nothing stands out as particularly informative to me here.  Perhaps you can lend some insight?

``` r
> traceback()
8: stop("Command failed (", status, ")", call. = FALSE)
7: fun(r, args = args, env_vars = env_vars, path = path, ...)
6: R(paste("CMD INSTALL ", shQuote(built_path), " ", opts, sep = ""), 
       quiet = quiet)
5: install(source, ..., quiet = quiet, metadata = metadata)
4: FUN(X[[i]], ...)
3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
2: install_remotes(remotes, quiet = quiet, ...)
1: devtools::install_github("cdeterman/gpuR", ref = "develop")
```

You can see the existing issue [here](https://github.com/cdeterman/gpuR/issues/9).

**Comment by victorvicpal** [comment]
I have the same issue installing my MGSR package on a Jupyter notebook.
