### ISSUE TITLE
improper devtools::document() with file names leading with "_"

### ISSUE THREAD

**Issue by alexWhitworth** [hadley/devtools#1317]
Related to [issue no 989](https://github.com/hadley/devtools/issues/989).

I also get error `Error: Missing name at **_data-model_data.R**`. This is solved via removing the leading "_" from the file name. If this is not a bug, file name guidelines should at least be provided in the documentation or vignettes.

```
R> devtools::document("callProjection")
... 
Error: Missing name at _data-model_data.R:19
```

 (Or perhaps this is a standard naming convention problem with all *.R files that I am unaware of? I can't find documentation of this anywhere if that is the case.)

**Comment by jimhester** [comment]
From
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-subdirectories
R source files must start with support our lower case ASCII letter or digit.

**Comment by wch** [comment]
It might be a good idea to have `load_all()` give a warning if filenames are invalid.

**Comment by alexWhitworth** [comment]
@jimhester -- Thanks!! I clearly missed that

**Comment by hadley** [comment]
Moved to pkgload - we'd love a PR, but unfortunately it's not pressing enough to work on automatically.
