### ISSUE TITLE
FR: New use_src_deps()

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1323]
for tracking dependencies between source and header files (in packages with compiled code). This makes sure that building/loading the package works properly even when switching between branches. (This usually works anyway, but if it doesn't, R crashes.)

See https://github.com/rstats-db/RSQLite/commit/1d2912cc3b232705f6dd1a67bdf2af1222b123cf for the necessary changes, also https://github.com/rstats-db/RSQLite/pull/138.

**Comment by gaborcsardi** [comment]
Can't these packages just use make? I don't know the details, just
asking....

**Comment by krlmlr** [comment]
R CMD build uses make, of course. This is about automatically inferring dependencies between source and header files.

The R build system (at least on my system) offers access to predefined rules that build `.d` files from source files by invoking the compiler with a special switch. These files encode the dependencies in a format readable by make. You're welcome to try it out in bleeding-edge RSQLite.

**Comment by hadley** [comment]
What's `use_src_deps()`?

**Comment by krlmlr** [comment]
Never mind, devtools::compile_dll() + ccache + gold should work for most users. Does devtools::install() call needs_clean(), like compile_dll() does?
