### ISSUE TITLE
No manual pdf created when devtools is used during RStudio package check

### ISSUE THREAD

**Issue by marchtaylor** [hadley/devtools#1325]
The following answer correctly points out that when devtools functions are allowed to be used during a package check in Rstudio, manual creation is over-ridden despite global settings:
http://stackoverflow.com/a/39274711/1199289

**Comment by twolodzko** [comment]
There is also a related feature request to add function to build the pdf manually: https://github.com/hadley/devtools/issues/1238

**Comment by hadley** [comment]
Why do you want the manual?

**Comment by twolodzko** [comment]
@hadley manual is a part of documentation, it also needs to be checked. If you include TeX formulas (`\eqn{}{}` and `\deqn{}{}`) than from time to time there are issues with producing pdf's, so this needs running `check(manual=TRUE)` each time to check if the issue is solved.

**Comment by hadley** [comment]
I think we'll implement the `build_manual()` function, but I think very few people use the pdf manuals these days.
