### ISSUE TITLE
idea: github pages - using /docs folder in master branch

### ISSUE THREAD

**Issue by ijlyttle** [hadley/devtools#1328]
GitHub made some changes recently to how they deal with GitHub pages - one of the new options is that pages can be served from a `/docs` folder in the master branch. I'm sure you saw the news - [here's the link](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/).

As you know, `/docs` is a non-standard top-level directory for an R package - it generates a note during `devtools::check()`.

On the other hand, it keeps public documentation closer to the source.

I guess my questions are:

1. Is there a reason you should not use `/docs` as a place to keep gh-pages for a package? In other words, is this a bad idea to begin with?

1. Assuming that you use `/docs` for gh-pages and that you want to avoid the note from being generated, could it be possible/advisable to modify `devtools::release()` to avoid including that directory from being sent to CRAN?

**Comment by jimhester** [comment]
You should be able to add `^docs/` to your `.Rbuildignore file, and it won't be included in the built package.

**Comment by ijlyttle** [comment]
Thanks! (feeling shame)

Reading some more, I realized that there is this function called `devtools::use_build_ignore()`. 

Closing the issue (should not have been opened, apologies). Interested to hear opinions on the advisability (or lack of) of using `/docs` in this manner.

**Comment by jimhester** [comment]
I think it is just as valid to store the website in `docs/` as in a gh-pages branch.

**Comment by ijlyttle** [comment]
Thanks!

**Comment by jennybc** [comment]
I've always found the gh-pages branch approach awkward, as it seems optimized to make it hard to see everything you need to see at once when troubleshooting. I prefer the location based approach in `docs/`.

**Comment by ijlyttle** [comment]
I prefer the idea of using `docs` as well for exactly those reasons, and am starting to dip my toes in. I'm probably paranoid, but I'm interested to find out if this approach isn't "too good to be true".

So far, so good - if I am reading correctly.
