### ISSUE TITLE
Package installation for revdep_check is not parallelized

### ISSUE THREAD

**Issue by wch** [hadley/devtools#1331]
I think it used to be the case that when `revdep_check()` was called with a value for `Ncpus`, it would install packages in parallel because it passed `Ncpus` to `install.packages()`. Now the packages seem to be installed one at a time, which is much slower -- I'm installing over 600 packages for a revdep check, so the cost is not trivial. I believe this happens because it ends up calling `install_remotes`, which looks like it installs packages one at a time.

**Comment by krlmlr** [comment]
I've been through this with RSQLite. It's a one-time cost, which you can alleviate by setting `MAKEFLAGS=-j $(nproc)` .

See https://github.com/MangoTheCat/remotes/issues/34 for a related discussion; looks like devtools might eventually forward to the "remotes" package (#1310).

**Comment by hadley** [comment]
This will be/is resolved in the new revdepcheck package
