### ISSUE TITLE
issue installing devtools from RStudio

### ISSUE THREAD

**Issue by prodipta** [hadley/devtools#1332]
Hi, I tried installing devtools from github from within R Studio, first installing the CRAN version (devtools  \* 1.12.0   2016-06-24 CRAN (R 3.2.5)), and then calling install_github("hadley/devtools").  Unfortunately, the first time I did, I did not have Rtools installed, so it aborted and prompted me to install RTools (3.3). Subsequently it failed consistently, with the following error message: 

```
Downloading GitHub repo hadley/devtools@master
from URL https://api.github.com/repos/hadley/devtools/zipball/master
Installing devtools
"C:/PROGRA~1/R/R-32~1.4RE/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Prodipta/AppData/Local/Temp/Rtmpeo6pOp/devtools467810a4569c/hadley-devtools-26c507b"  \
  --library="C:/Program Files/R/R-3.2.4revised/library" --install-tests 
- installing _source_ package 'devtools' ...
  *\* R
  *\* inst
  *\* tests
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* installing vignettes
  *\* testing if installed package can be loaded
  **\* arch - i386
  Error : package 'devtools' is not installed for 'arch = i386'
  Error: loading failed
  Execution halted
  **\* arch - x64
  ERROR: loading failed for 'i386'
- removing 'C:/Program Files/R/R-3.2.4revised/library/devtools'
- restoring previous 'C:/Program Files/R/R-3.2.4revised/library/devtools'
  Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Program Files\R\R-3.2.4revised\library\00LOCK-hadley-devtools-26c507b\devtools\libs\x64\devtools.dll to C:\Program Files\R\R-3.2.4revised\library\devtools\libs\x64\devtools.dll: Permission denied
  Error: Command failed (1)
```

**Comment by mpettis** [comment]
Following these instructions helped me (found after having similar issue, finding this issue): https://github.com/hadley/devtools/issues/426

**Comment by woodhaha** [comment]
I have tried many times intalling the pkg "devtools" from GitHub on my windows10(x+64),and finally successed.
Fllowing the steps
1.upgrade the java devlopment enviroment on my win10 ( http://www.oracle.com/technetwork/java/javase/downloads/index.html)
install "Java SE 8u131"(Java Platform, Standard Edition)
and then configuring the developing enviroment on java control panel,setting the java runtime for related Apps 

2.install "Rtools34" in （Path C:\Rtools）,then select components(R toolset,Cygwin DLLs, R3.3.x+64 bit toolchain,Extras to build 64bit R）

3.install“cygwin setup-x86_64”comfiguring the linux devlopment enviroment 
4.install "basic-miktex-2.9.6236-x64"
5.restart your windows system, then in RStudio configuring Rtools 
developing enviroment by using the function 
normalizePath("C:/Rtools/bin"),and lastly using devtools::build_github_devtools() to install the Github devtools pkg"devtools_1.12.0.9000.zip"
