### ISSUE TITLE
install_github could choose to not download .Rbuildignore files/folders

### ISSUE THREAD

**Issue by dfalbel** [hadley/devtools#1341]
I have a package with a large `data-raw` folder. While I would like to keep it inside the github repo, I think it shouldn't be downloaded when installing the package from Github. Is it possible?

**Comment by gaborcsardi** [comment]
Create releases, and the built source R package to them. These will not contain the `data-raw` folder. Then you can install them with the `@` notation: `install_github("user/repo@release")` AFAIR.

**Comment by dfalbel** [comment]
@gaborcsardi  Thanks! I'll test this as soon as possible
