### ISSUE TITLE
install_deps() doesn't pass parameter repos on to update.packages

### ISSUE THREAD

**Issue by jirkalewandowski** [hadley/devtools#1343]
This leads to the direct dependencies being installed from the repository given in the parameter repos, while dependencies of dependencies are installed from getOption("repos").

**Comment by jimhester** [comment]
I saw the same issue and fix it in #1339 as well.

**Comment by jirkalewandowski** [comment]
(duplicate of #1243, thanks @jimhester )

**Comment by hashar** [comment]
That one is still affecting me with devtools 1.13.2 when doing:
```
> getOption("repos")
    CRAN 
"@CRAN@" 

> install.packages("devtools", repos="http://cran.us.r-project.org")
...
> devtools::install_deps("src", repos="http://cran.us.r-project.org", dependencies = TRUE )
Installing testthat
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/tmp/RtmpXB6s5u/devtools10dd7bf8ed3e/testthat'  \
  --library='/home/hashar/Rpackages' --install-tests 

ERROR: dependencies ‘crayon’, ‘praise’, ‘magrittr’ are not available for package ‘testthat’
* removing ‘/home/hashar/Rpackages/testthat’
Installation failed: Command failed (1)
```

https://github.com/ManifestoProject/manifestoR/commit/7f76cf1466dc989e0e6a91b2377baf78d9efbb47 is a working workaround. Or namely set the repos with `options`:

```
> options(repos="http://cran.us.r-project.org")
> install.packages("devtools", dependencies = TRUE )
// works
```

**Comment by bearloga** [comment]
@jimhester has the fix for this made it into the version that's on CRAN?
