### ISSUE TITLE
install_bioc hanging at prompt

### ISSUE THREAD

**Issue by shapenaji** [hadley/devtools#1344]
```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin14.5.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1     packrat_0.4.7-1

```

Was attempting to pull the GenomicRanges lib from bioconductor, but ran into the following:

> devtools::install_bioc('GenomicRanges')
> Error validating server certificate for 'https://hedgehog.fhcrc.org:443':
> - The certificate is not issued by a trusted authority. Use the
>   fingerprint to validate the certificate manually!
>   Certificate information:
> - Hostname: *.fhcrc.org
> - Valid: from Sat, 18 Oct 2014 16:52:00 GMT until Fri, 23 Nov 2018 15:15:23 GMT
> - Issuer: http://certs.godaddy.com/repository/, GoDaddy.com, Inc., Scottsdale, Arizona, US
> - Fingerprint: *********************************\* (Redacted: A bunch of hex)
>   (R)eject, accept (t)emporarily or accept (p)ermanently? 

At this point, regardless of what I choose, the function just hangs, (I had to force-quit my R session to get out of it).

EDIT: the bioclite.R approach works fine though, where I source it from bioconductor directly.

**Comment by hadley** [comment]
@shapenaji unfortunately this is unlikely to be devtools fault, but we'll take a look.

@jimhester any idea where the cert validation dialog is coming from?

**Comment by shapenaji** [comment]
Yeah, I suspected the certificate error was an SEP. But the hanging on failure seemed like a potential issue for devtools in future.

**Comment by hadley** [comment]
That's probably not devtools fault either - I suspect you're using RStudio?

**Comment by shapenaji** [comment]
Yes, I haven't tried it again in some time (and I believe I updated RStudio in the meantime, since now I get this, with no hang)

`> devtools::install_bioc('GenomicRanges')
svn: E170013: Unable to connect to a repository at URL 'https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/GenomicRanges'
svn: E230001: Server SSL certificate verification failed: issuer is not trusted
Error: There was a problem retrieving the current SVN revision
In addition: Warning message:
running command ''/usr/bin/svn' info --xml --username readonly --password readonly https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/GenomicRanges' had status 1 `

**Comment by jimhester** [comment]
FWIW this is the same as https://github.com/hadley/devtools/issues/1401 which also talks about why it occurs and how to fix the issue.
