### ISSUE TITLE
Installation problem with RPostgres

### ISSUE THREAD

**Issue by jenast** [hadley/devtools#1347]
Install_github("rstats-db/RPostgres") fails on two Windows 7 machines, running R 3.3.1 and devtools 1.12.0.

Error message:
"> install_github("rstats-db/RPostgres")
Downloading GitHub repo rstats-db/RPostgres@master
from URL https://api.github.com/repos/rstats-db/RPostgres/zipball/master
Error: running command '"C:/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 2"

After downgrading to devtools 2.10, the installation works fine. I'm not sure whether the problem lies with devtools or RPostgres so I will open an issue at both repositories.

Thanks for the efforts!

Jens

**Comment by hadley** [comment]
WFM.

Can you install other packages with compiled code? e.g. `devtools::install_github("tidyverse/readr")`

**Comment by jenast** [comment]
Same result when using devtools 1.12, but works with version 1.10.

But it worked on an old R 3.2.3 installation, and works for me also after updating to R 3.3.2. So the issue is resolved, whatever the problem was. 

Thanks again and sorry for the trouble.

**Comment by pfizer1234** [comment]
I have this problem with R 3.3.2

> install_github("hadley/testthat")
Downloading GitHub repo hadley/testthat@master
from URL https://api.github.com/repos/hadley/testthat/zipball/master
Error: running command '"C:/R/R-3.3.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 2


> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 10586)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.12.0

loaded via a namespace (and not attached):
[1] httr_1.2.1    R6_2.2.0      withr_1.0.2   curl_2.3      memoise_1.0.0 git2r_0.18.0  digest_0.6.11
