### ISSUE TITLE
build vignette time stamp flagged by CRAN

### ISSUE THREAD

**Issue by brry** [hadley/devtools#1348]
On CRAN checks, I get the WARNING: Files in the 'vignettes' directory  newer than all files in 'inst/doc'.
`Windows cmd > R CMD build berryFunctions` creates a tar.gz with the same time stamp for both files.
`Rstudio > devtools::build()`  creates a tar.gz where vignettes/berryFunctions.Rmd is consistently exactly one second newer than inst/doc/berryFunctions.Rmd

Rstudio, devtools and all packages are up to date.
The vignette is fairly long and has also been rebuild with `devtools::build_vignette()` just yesterday, just in case that matters somehow.
The package is at github.com/brry/berryFunctions.

```
> devtools::session_info()
Session info ------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.903)          
 language (EN)                        
 collate  German_Germany.1252         
 tz       Europe/Berlin               
 date     2016-09-21                  

Packages ----------------------------
 package    * version date       source        
 devtools     1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest       0.6.10  2016-08-02 CRAN (R 3.3.1)
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.1)
 rstudioapi   0.6     2016-06-27 CRAN (R 3.3.1)
 withr        1.0.2   2016-06-20 CRAN (R 3.3.1)


```

**Comment by gergness** [comment]
Sorry if this is unrelated, but I had a similar issue, but running R CMD from the command line didn't help. To fix, I had to delete the files in inst/doc and then recreate them with build_vignette().

**Comment by schloerke** [comment]
[hafen/packagedocs](http://github.com/hafen/packagedocs) found that deleting the whole `inst/doc` folder before calling `devtools::build()` worked around the issue.

**Comment by hadley** [comment]
Yeah, you generally shouldn't be including `inst/docs` in your submission. I'll look into this whole workflow and figure out what's going wrong.

**Comment by stefvanbuuren** [comment]
This is my approach to circumvent the time stamp problem:
```
devtools::build_vignettes()
devtools::build(vignettes = FALSE)
```

**Comment by brry** [comment]
I do not have the problem anymore. Change date for vignettes/bF.Rmd is 2016-10-13 21:55, while in inst/doc/bF.Rmd its 2017-01-16 12:38. 
In other words: since october, `build_vignettes()` has sucessfully changed inst/doc/*.Rmd files (several times, even) without touching the time stamp of vignettes/*.Rmd.

**Comment by stefvanbuuren** [comment]
Yes, `build_vignettes()` is fine, but `build()` appears to touch files.

**Comment by gaborcsardi** [comment]
I guess build copies everything over to a temporary directory, and then the file modification dates are updated. It should be possible to copy over the files without changing the modification dates.

**Comment by hadley** [comment]
I have never seen this problem so I'm not sure what's different with your workflows. Do you have files in `inst/doc` before submitting?
