### ISSUE TITLE
install_version doesn't leverage config values when fetching Meta/archive.rds

### ISSUE THREAD

**Issue by dmarkwat** [hadley/devtools#1356]
First off: love this tool.  Unfortunately, when we are behind a CRAN mirror with self-signed certs (e.g. self-hosted mirror) and basic auth, obtaining the "Meta/archive.rds" files isn't done with any of the config values set in the install_version function call.

Example that fails
`install_version('slam', version='0.1-37', repos="https://self-hosted.repo", config = config( ssl_verifypeer = FALSE, userpwd='user:pass'))`

But, the following call to install_url works (which appears would be called if install_version got past the package_find_repo call)
`install_url("https://self-signed.repo/src/contrib/Archive/slam/slam_0.1-37.tar.gz", config = config(ssl_verifypeer = FALSE, userpwd='user:pass')))`

The line that appears to be failing is [this line in read_archive](https://github.com/hadley/devtools/blob/master/R/install-version.r#L50).

It looks like `curl()` could be used in place of `url()`, passing in a handle using the same config values passed in to install_version (if config is passed in, anyway)?  This is probably a huge edge case, but it would be a huge help.

**Comment by hadley** [comment]
Why are you using https with self-signed certs?

**Comment by dmarkwat** [comment]
The software I am working with (Sonatype's Nexus 3) uses https and the company I am working with typically doesn't like handing out signed certs for internal usage, especially non-production.  So this is mostly for testing unless I simply can't get a signed cert at all.  All the same, it worked for install_url (with the config) and not install_version which seemed a little inconsistent so I tried to track down the root cause.

**Comment by hadley** [comment]
Ok, makes sense. This isn't super high priority, but we're planning some work on the install side and we'll try to get this in.

**Comment by dmarkwat** [comment]
That would be great; hope to see it soon!
