### ISSUE TITLE
export yesno?

### ISSUE THREAD

**Issue by joethorley** [hadley/devtools#1359]
I find the yesno function incredibly useful in my packages.

If I was to submit a pull request that exports it and changes the response to be TRUE if the user answers yes (I would of course add a ! to all yesno calls in the devtools package) would you be interested in accepting it?

**Comment by hadley** [comment]
I'd rather think about generalising it slightly (what other devtools functions work in a similar way?) and pull out to a separate package.

**Comment by joethorley** [comment]
What do you mean by similar? If you mean question based, with the exception of three calls to 
`menu(c("Yes", "No")) == 1`, yesno is the only code to use the menu function?

FWIW I created a package for my own use <https://github.com/poissonconsulting/yesno>. It could form the basis for development although there is very little to it.

**Comment by hadley** [comment]
Ok, then lets close for now.

**Comment by joethorley** [comment]
Do you mind if I push it to CRAN? I can add you as an co-author.

**Comment by hadley** [comment]
Could you eliminate the dependency on datacheckr?

**Comment by joethorley** [comment]
Yes

Sent from my iPhone

On Nov 3, 2016, at 17:43, Hadley Wickham <notifications@github.com> wrote:

Could you eliminate the dependency on datacheckr?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hadley/devtools/issues/1359#issuecomment-258315996>,
or mute
the thread

**Comment by joethorley** [comment]
I've removed the dependency on datacheckr and added substantially more documentation.

I've also replaced the string argument with ... which is then paste0(..., collapse = "") (as you have it in the original devtools function).

I think its CRAN ready. I would like to add you as a co-author. I'm happy to remain as maintainer if thats what you prefer but have no attachment either way. I'm also happy to move the package to your profile on GitHub. Let me know what you are thinking.

I've invited you to repo in case you want to make any changes directly.

**Comment by joethorley** [comment]
Can I push to CRAN with you as a co-author? Or would you prefer to have your name removed?

**Comment by hadley** [comment]
I don't have time to think through this through at the moment, but you need to acknowledge that the code was extracted from devtools and I am the primary author.

**Comment by joethorley** [comment]
I have set you as the primary author and myself as the compiler and maintainer. 
I have also explicitly acknowledged the source of the code as devtools.
I am planning on submitting to CRAN in early 2017 unless you indicate otherwise.
The package is at <https://github.com/poissonconsulting/yesno>.

**Comment by joethorley** [comment]
@hadley I would like to submit yesno (https://github.com/poissonconsulting/yesno) to CRAN with you as primary author and myself as compiler and maintainer. I'm also happy to entirely remove my name and have you take it over. I would just like to be able to use in my current and future CRAN packages. Thanks

**Comment by joethorley** [comment]
Since other packages I want to push to CRAN require this functionality I am going to push yesno to CRAN on Feb 15th with @hadley as the primary author (as requested on Nov 28). If I get other direction I will follow it.

**Comment by hadley** [comment]
Fine

**Comment by joethorley** [comment]
FWIW yesno is now on CRAN

<https://cran.r-project.org/web/packages/yesno/index.html>

thanks for your flexibility :)
