### ISSUE TITLE
check_suggested fails for BiocInstaller

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#1360]
Since it's not on CRAN

**Comment by hadley** [comment]
This causes pain in `revdep_check_install` if there are any CRAN packages with a BiocViews setting because the library is in the wrong place, since `biocLite` is undocumented, getting it to install in the right library is a pain.

cc @jimhester

**Comment by hadley** [comment]
This is now resolved, right?

**Comment by jimhester** [comment]
Yeah with https://github.com/hadley/devtools/commit/f0d1c7ed3d7f30d559b62eb0060135589824c687
