### ISSUE TITLE
Persistant 'Warning' for R dependencies. 

### ISSUE THREAD

**Issue by aarti7** [hadley/devtools#1363]
I am building a package and I keep getting this  warning when I check the package:
"**_\* checking data for ASCII and uncompressed saves ... WARNING
  Warning: package needs dependence on R (>= 2.10)_**"

The (obvious) solution was to add a depends field in the description file. 
Like this =>
 **_Depends: R (>= 2.1.0)_**

So, I did that. But the warning doesn't wanna go away at all. 
What can be done here? Any suggestions?

**Comment by jimhester** [comment]
The warning is saying it needs a dependency on R 2.__10__, not 2.__1__.

Also devtools is really not the proper place for this issue (or your previous one #1357).

Problems generated from R CMD check should probabably go to the [R-package-devel mailing list](https://stat.ethz.ch/mailman/listinfo/r-package-devel).

**Comment by aarti7** [comment]
So silly of me. Pretty embarrassed right now! Gonna head for stronger coffee! 
Thank you so much for solving it. 

And I will stop posting queries here. I didn't know of the  forum you posted the link for. It definitely is extremely helpful. Thanks a ton!
