### ISSUE TITLE
Moving of vignettes fails depending on access rights to folders

### ISSUE THREAD

**Issue by lmr2391** [hadley/devtools#1364]
I experienced a problem when building the vignettes. The error message when running 

``` r
devtools::build_vignettes()
```

was 
_Error in file.copy(out_mv, doc_dir, overwrite = TRUE) : 
  more 'from' files than 'to' files_

However, since the _vignettes_ folder contained the build vignettes, I didn't care about it until I wanted to release the package and noticed that the zipped file doesn't contain them.

Tracing down the cause of these issues, I narrowed it down to line 23-25 of vignette-r.r

``` r
if (!file.exists(doc_dir)) {
    dir.create(doc_dir, recursive = TRUE, showWarnings = FALSE)
  }
```

In my case, the subfolder _doc_ in _inst/doc_ didn't exist yet. So the code tried to create it but did not succeed because I don't have writing access to some of the previous folders (e.g. if the package root is in p:/folder1/folder2/package I don't have writing access to p:/folder1). Setting `r recursive = FALSE` will solve the issue for me but certainly create new ones for people who don't have the _inst_ folder yet. 

I don't know why you set `r showWarnings = FALSE`, but if it was `TRUE`, I would have solved the access rights issue much faster. Actually I'm surprised that `dir.create` only creates a warning and not an error if it didn't succeed. Maybe adding something like

``` r
if (!file.exists(doc_dir)) {
    dir.create(doc_dir, recursive = TRUE, showWarnings = FALSE)
    if (!file.exists(doc_dir)) stop(paste("Couldn't create folder ", doc_dir))
  }
```

would be a good idea

**Comment by hadley** [comment]
This feels out of scope for devtools to me. We will fix eventually when we turn out sights on a better package for performing file and directory operations
