### ISSUE TITLE
Is it possible to unload package "car"

### ISSUE THREAD

**Issue by likanzhan** [hadley/devtools#1369]
Dear _devtools_ developers,
As you probably know, there exist two packages for generalized additive models: _gam_ and _mgcv_ which are incompatible with each other. Here,  I want to use the package _gam_ for my statistical analysis.  At first, the script works fine:

``` r echo=T, eval=T
library(gam)
SLIDf<-read.table("http://socserv.mcmaster.ca/jfox/Books/Applied-Regression-3E/datasets/SLID-women.txt", header=T)

SLIDf[,"region"] <- factor(SLIDf[,"region"], levels=
               c("Atlantic", "Quebec", "Ontario", "Prairies", "BC"))

(gam189<-gam(working ~  1 + region + kids0004 + kids0509  + 
            lo(education, span=0.7) + lo(familyIncome, span=0.7), 
              family=binomial, data=SLIDf))

par(mfrow=c(1,2))
plot(gam189, se=T, terms="lo(familyIncome, span = 0.7)", 
     ylim=c(-2.5,3), font.lab=2, xlab="Family Income",
     ylab="Fitted Logit of Labor–Force Participation"
     )
mtext("(a)", side=3, adj=3/6, padj=-.1)
plot(gam189, se=T, terms="lo(education, span = 0.7)", 
     ylim=c(-3.5,2), font.lab=2, xlab="Education",
     ylab="Fitted Logit of Labor–Force Participation"
     )  
mtext("(b)", side=3, adj=3/6, padj=-.1)
```

But my script also uses the package _car_, which causes the problem, probably because _car_ also automatically imports package _mgcv_. However, even if I detaches the package _car_ with _unloadNamespace("car")_, _detach("package:car", unload=TRUE)_, or _unload("car")_ from the package _devtools_, the problem persists. It is really annoying. So my question is: is it possible to cleanly unload the package _car_, or is there a way to start a new clean r session without restarting the R itself?  thank you very much.

``` r echo=T, eval=T
library(gam)
library(car)
SLIDf<-read.table("http://socserv.mcmaster.ca/jfox/Books/Applied-Regression-3E/datasets/SLID-women.txt", header=T)

SLIDf[,"region"] <- factor(SLIDf[,"region"], levels=
               c("Atlantic", "Quebec", "Ontario", "Prairies", "BC"))

(gam189<-gam(working ~  1 + region + kids0004 + kids0509  + 
            lo(education, span=0.7) + lo(familyIncome, span=0.7), 
              family=binomial, data=SLIDf))

par(mfrow=c(1,2))
plot(gam189, se=T, terms="lo(familyIncome, span = 0.7)", 
     ylim=c(-2.5,3), font.lab=2, xlab="Family Income",
     ylab="Fitted Logit of Labor–Force Participation"
     )
mtext("(a)", side=3, adj=3/6, padj=-.1)
plot(gam189, se=T, terms="lo(education, span = 0.7)", 
     ylim=c(-3.5,2), font.lab=2, xlab="Education",
     ylab="Fitted Logit of Labor–Force Participation"
     )  
mtext("(b)", side=3, adj=3/6, padj=-.1)
```

**Comment by jimhester** [comment]
This is IMHO a bug in R, from `?detach` it states

> registered S3 methods from the  namespace will not be removed.

So the S3 methods remain even if a given namespace is removed. Therefore there is not much you can do in this case but to not attach gam and car in the same session.
