### ISSUE TITLE
SetClassUnion errors in run_examples

### ISSUE THREAD

**Issue by flying-sheep** [hadley/devtools#1372]
Seems like #168 resurfaced when running `run_examples` twice or having the package in question loaded

**Comment by hadley** [comment]
Could you please provide a minimal reprex?

**Comment by flying-sheep** [comment]
no, sorry. my elbow is bust and typing left-handed is hard.

it occurs with [this package](http://bioconductor.org/packages/release/bioc/html/destiny.html)

**Comment by hadley** [comment]
Moved to pkgload — but we can't reproduce locally.
