### ISSUE TITLE
Wrapping C++ code in R

### ISSUE THREAD

**Issue by KhagayN** [hadley/devtools#1377]
Hello!

I am following Wickham's R Packages book on wrapping C++ functions in R (Chapter 10) but, I am having problems understanding what it means when Wickham states to include the royxgen tags that I need to add to my package 

#' @useDynLib your-package-name
#' @importFrom Rcpp source-cpp

These are roxygen tags so they should be included in R code but, at the moment I don't have any R code. All I have is a C++ file and the output from running devtools::document(). The reason I am asking this question is because after running devtools::document(), there are no exported functions in the NAMESPACE file. 

Thanks for the help!

**Comment by jimhester** [comment]
`devtools::use_rcpp()` will set things up for you and tell you exactly what to include.

You just need to make a new `.R` file in the `R/` directory with only the following.

```r
#' @useDynLib pkgName
#' @importFrom Rcpp sourceCpp
NULL
```

**Comment by KhagayN** [comment]
I ran that code and it has updated the NAMESPACE file but, after running load_all() and call package_name::function_name() 

I get a 

Error in .Call("rSeqLibPackage_timesTwo", PACKAGE = "rSeqLibPackage",  : 
  "rSeqLibPackage_timesTwo" not available for .Call() for package "rSeqLibPackage"

What is happening?
