### ISSUE TITLE
README.rmd should start with setup chunk

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#1379]
i.e. `{r setup, include = FALSE}`

**Comment by hadley** [comment]
It should also include `library(xyz)` in that chunk

**Comment by jennybc** [comment]
This chunk might also be nice in a new vignette, but that is currently initialized via `rmarkdown::draft()`, so easier said than done. Maybe it could be added to the `html_vignette` template over there?

**Comment by hadley** [comment]
Moved to usethis issues.
