### ISSUE TITLE
load_all should install all missing dependency packages, at list optionally

### ISSUE THREAD

**Issue by RudyPastel** [hadley/devtools#1380]
Bonjour,

it would be very convenient when sharing packages under development that load_all installs all missing dependency packages, at least optionally, when called just as the function install.packages does.

Thank you

**Comment by jimhester** [comment]
I don't think this is going to happen, installing dependencies and `load_all()` are really different fundamentally. However if you want this you can write a function to do this yourself!

```r
my_load_all <- function(pkg = ".", ...) {
  devtools::install_deps(pkg)
  load_all(...)
}
```
