### ISSUE TITLE
Improve `github_response` to be able to handle various type of `GitHub's Media Type`

### ISSUE THREAD

**Issue by dy-kim** [hadley/devtools#1384]
- `GitHub` has its [`custom media types`](https://developer.github.com/v3/media/#commits-commit-comparison-and-pull-requests)
- Present `github_response` accepts only `JSON` typed responses

  ```R
  github_response <- function(req) {
    text <- httr::content(req, as = "text")
    parsed <- jsonlite::fromJSON(text, simplifyVector = FALSE)
    ...
  }
  ```

**Comment by hadley** [comment]
That seems out of scope for devtools - the github support is just the minimal needed for installing from github. I'd rather put more advanced stuff in a separate package (like gh).

**Comment by dy-kim** [comment]
@hadley I agree minimizing scope for `devtools` in supporting GitHub. But still, I think getting `SHA` from GitHub could be included in the minimal requirements for installing from GitHub. 

So I'd like to suggest building `github_response` at least to be able to handle a response for a `SHA` request(or making use of the functionality from `gh`).

**Comment by dy-kim** [comment]
Can we get an advice from @jimhester ?
