### ISSUE TITLE
Convenience function to make canonical CRAN link

### ISSUE THREAD

**Issue by jennybc** [hadley/devtools#1385]
This is pretty trivial but would be handy: a convenience function to produce the canonical CRAN link (but ... if you actually visit it ... immediately redirects to a URL that earns you a wrist slap):

https://CRAN.R-project.org/package=devtools

I know these are now available at the bottom of CRAN pages, but might be nice to get easily within devtools.

**Comment by clesiemo3** [comment]
Would this be something as simple as this with the ability to cat() the output for easy copy/paste?

```
CRAN.link <- function(pkg, root="https://CRAN.R-project.org/package=", return.value = TRUE){
  urls <- paste0(root,pkg)
  if(!return.value){
    for(u in urls){
      cat(paste0(u,"\n"))
    }
    return(invisible())
  } else {
    return(urls)
  }
}
```

```
> CRAN.link(devtools::package_deps("devtools")[,1])
 [1] "https://CRAN.R-project.org/package=curl"       "https://CRAN.R-project.org/package=devtools"  
 [3] "https://CRAN.R-project.org/package=digest"     "https://CRAN.R-project.org/package=git2r"     
 [5] "https://CRAN.R-project.org/package=httr"       "https://CRAN.R-project.org/package=jsonlite"  
 [7] "https://CRAN.R-project.org/package=memoise"    "https://CRAN.R-project.org/package=mime"      
 [9] "https://CRAN.R-project.org/package=openssl"    "https://CRAN.R-project.org/package=R6"        
[11] "https://CRAN.R-project.org/package=rstudioapi" "https://CRAN.R-project.org/package=whisker"   
[13] "https://CRAN.R-project.org/package=withr"     
> CRAN.link(devtools::package_deps("devtools")[,1], return.value = FALSE)
https://CRAN.R-project.org/package=curl
https://CRAN.R-project.org/package=devtools
https://CRAN.R-project.org/package=digest
https://CRAN.R-project.org/package=git2r
https://CRAN.R-project.org/package=httr
https://CRAN.R-project.org/package=jsonlite
https://CRAN.R-project.org/package=memoise
https://CRAN.R-project.org/package=mime
https://CRAN.R-project.org/package=openssl
https://CRAN.R-project.org/package=R6
https://CRAN.R-project.org/package=rstudioapi
https://CRAN.R-project.org/package=whisker
https://CRAN.R-project.org/package=withr
> CRAN.link("devtools")
[1] "https://CRAN.R-project.org/package=devtools"
> CRAN.link("devtools", return.value = FALSE)
https://CRAN.R-project.org/package=devtools
```

**Comment by jennybc** [comment]
Pretty much! But it would follow devtools naming conventions ... maybe `use_cran_canonical()`? And possibly just use `message()` to print something to screen, the way many other infrastructure helpers advise you on what to do next. Alternatively, it would be nice to put the canonical URL on the clipboard but I don't think that Rubicon has been crossed yet in devtools.

**Comment by clesiemo3** [comment]
I'd be willing to tidy up the code above, use message() and put in a pull request if the appropriate parties are on board.

Clipboard is a tricky one in R if you want to support multiple operating systems. Might be better to just pipe the output of this function into another that handles the clipboard world

**Comment by hadley** [comment]
@jennybc where do you see people using this?

**Comment by jennybc** [comment]
Somehow I missed the above question. Typical scenario: you are working on package A and want to mention + link to package B and as a matter of policy you've decided to use canonical CRAN links everywhere.

It is truly a very minor thing, so drop it if you like. If it survives, it would be nice if available in a workflow package that one is willing to load in all interactive sessions via .Rprofile.

**Comment by hadley** [comment]
Moved to usethis issues.
