### ISSUE TITLE
[install_github] Error: running command ... had status 2

### ISSUE THREAD

**Issue by HughParsonage** [hadley/devtools#1386]
I cannot install any github repository using `install_github`:

```r
devtools::install_github("hadley/ggplot2")
```

> Downloading GitHub repo hadley/ggplot2@master
> from URL https://api.github.com/repos/hadley/ggplot2/zipball/master
> Installing ggplot2
> Downloading GitHub repo hadley/scales@master
> from URL https://api.github.com/repos/hadley/scales/zipball/master
> Error: running command '"C:/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 2

I have tried reinstalling R and using the stable and dev versions of `devtools`. Attempts to build a package locally (by cloning the repository) are, on the other hand, successful. 

`devtools::session_info()` (for stable version)

```
Session info --------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.903)          
 language (EN)                        
 collate  English_Australia.1252      
 tz       Australia/Sydney            
 date     2016-11-01                  

Packages ------------------------------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 curl        2.2     2016-10-21 CRAN (R 3.3.1)
 devtools    1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest      0.6.10  2016-08-02 CRAN (R 3.3.1)
 git2r       0.15.0  2016-05-11 CRAN (R 3.3.0)
 httr        1.2.1   2016-07-03 CRAN (R 3.3.1)
 memoise     1.0.0   2016-01-29 CRAN (R 3.3.1)
 R6          2.2.0   2016-10-05 CRAN (R 3.3.1)
 rsconnect   0.5     2016-10-17 CRAN (R 3.3.1)
 withr       1.0.2   2016-06-20 CRAN (R 3.3.1)
```

and for `dev` version (had to fork, clone, and build locally):

```

Session info -------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.903)          
 language (EN)                        
 collate  English_Australia.1252      
 tz       Australia/Sydney            
 date     2016-11-01                  

Packages -----------------------------------------------------------------------------------------------------------------------------------------------------
 package   * version     date       source        
 curl        2.2         2016-10-21 CRAN (R 3.3.1)
 devtools  * 1.12.0.9000 2016-11-01 local         
 digest      0.6.10      2016-08-02 CRAN (R 3.3.1)
 git2r       0.15.0      2016-05-11 CRAN (R 3.3.0)
 httr        1.2.1       2016-07-03 CRAN (R 3.3.1)
 memoise     1.0.0       2016-01-29 CRAN (R 3.3.1)
 R6          2.2.0       2016-10-05 CRAN (R 3.3.1)
 rsconnect   0.5         2016-10-17 CRAN (R 3.3.1)
 withr       1.0.2       2016-06-20 CRAN (R 3.3.1)

```

and `base::sessionInfo()`:

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.12.0.9000

loaded via a namespace (and not attached):
 [1] httr_1.2.1     R6_2.2.0       rsconnect_0.5  tools_3.3.1    withr_1.0.2    rstudioapi_0.6 curl_2.2       memoise_1.0.0  git2r_0.15.0   digest_0.6.10 
```

**Comment by clesiemo3** [comment]
scales needs some C compiled (https://github.com/hadley/scales/blob/master/src/colors.cpp) and it looks like you're having trouble with setting the config for the C Compiler (https://svn.r-project.org/R/trunk/src/scripts/config R CMD config CC)

Not the best answer I know but I'd wager to say that it's not a devtools issue but rather an issue around whatever C/C++ compiler you have on your machine and it interacting with R. You might be able to mess around with the config on your machine (such as http://stackoverflow.com/questions/10921153/c-compilation-flags-from-r) but that's a bit beyond my knowledge. Perhaps someone else can take this further.

**Comment by HughParsonage** [comment]
Thanks for the response. I'm somewhat sceptical of your diagnosis, however, because I can build the package locally. (That is if I fork the `ggplot2` repo, clone it on my computer, then build the package locally, I do not get any error.) Does your diagnosis explain this behaviour?

**Comment by clesiemo3** [comment]
When you build locally it's probably not pulling scales and building it as a dependency. It is just building the ggplot2 code which doesn't appear to have C code to compile.

Try this: `devtools::install_github("hadley/ggplot2", dependencies = FALSE)` and see if it is successful and just relies on an already installed scales package.

**Comment by HughParsonage** [comment]
You're right: running that will build correctly! My mistake.

**Comment by clesiemo3** [comment]
Nice! Glad to hear it. Definitely an odd problem :)

The bandaid solution is to install binary packages to avoid compiling but someday you'll probably need to compile SOMETHING. Still no idea on that unfortunately =\

I guess you can survive if you find a friend with a windows machine to build all your packages for you ;)
