### ISSUE TITLE
`skip_on_cran()` ignored when `check(cran=TRUE)`

### ISSUE THREAD

**Issue by thibautjombart** [hadley/devtools#1387]
Hi there, 

When trying to replicate CRAN's settings for testing, `skip_on_cran()` seems to be ignored even when  `check(cran=TRUE)`. It seems to be linked to the fact that `Sys.setenv("NOT_CRAN" = "true")` by default, so that one needs:
```
Sys.setenv("NOT_CRAN" = "false")
devtools::check(cran = TRUE) # (for emphasis, I know it's the default)
```
Seems that the first line shouldn't be necessary?

**Comment by hadley** [comment]
Yeah, that's not the point of `cran = TRUE` - it's more about enabling slightly more tests in `R CMD check`
