### ISSUE TITLE
Testing on Solaris

### ISSUE THREAD

**Issue by elbamos** [hadley/devtools#1393]
Is there an equivalent to travis or devtools::build_win() for Solaris?

I'm trying to submit to CRAN an update to my package, which uses a lot of Rcpp C++ code.  CRAN is asking me on the submission whether I've fixed issues on the "check results" page, which shows that installation is failing on Solaris and on an older version of Windows.  https://cran.r-project.org/web/checks/check_results_largeVis.html

The Windows failure I can live with -- the log shows that its trying to use a C++00 compiler, and I list C++11 in my SystemRequirements in the Description file. 

But I'm not sure how to approach the Solaris errors because I don't have access to a Solaris machine for testing? 

I had to resubmit a few times when I first submitted the package, so I'm trying to make sure I get everything right the first time and don't draw the ire of the CRAN maintainers. Any advice you have would be appreciated.  Thanks!

**Comment by jimhester** [comment]
The short answer is there is not a builder for Solaris. You can try to use a VM ala https://gist.github.com/jeroenooms/4c61c821172ad640545d, but it is not trivial to reproduce CRANs build environment.
