### ISSUE TITLE
Do not clean up the *.Rcheck directories if they contain errors/warnings

### ISSUE THREAD

**Issue by yihui** [hadley/devtools#1395]
Currently the `revdev/checks/` directory is completely wiped out after `revdep_check()` is finished. I feel it is useful to see the full check log when there are errors or warnings. In particular, when the installation failed, I have no idea why it failed. The summary only contains the log like this:

```
checking whether package ‘ANLP’ can be installed ... ERROR
Installation failed.
See ‘..../revdep/checks/ANLP.Rcheck/00install.out’ for details.
```

And `ANLP.Rcheck` has been removed.

**Comment by hadley** [comment]
We'll be deprecating `revdep_check()` and friends in the very near future in favour of the vastly superior [revdepcheck](https://github.com/r-lib/revdepcheck)
