### ISSUE TITLE
install_github hangs without output [version 1.12.0, R version 3.3.2 (2016-10-31)]

### ISSUE THREAD

**Issue by mruessler** [hadley/devtools#1396]
I am using `devtools` 1.12.0. with R 3.3.2 on a linux machine.
When trying to install a package from Github the process hangs without output.

    sink("install.log", split = TRUE)
    devtools::install_github("hadley/devtools")

The file `install.log` is 0 bytes.
Increasing R verbosity does not yield more information, either.
I downloaded the package and installed from local. Loading the github version gave errors:

    library("devtools", lib.loc="~/.R/library")
    Error in get(method, envir = home) : 
      lazy-load database '/home/martin/.R/library/devtools/R/devtools.rdb' is corrupt
    In addition: Warning message:
    In get(method, envir = home) : internal error -3 in R_decompress1
    Error: package or namespace load failed for ‘devtools’

In addition but maybe unrelated, the process `ssh-agent` consumes 25% CPU.

**Comment by hadley** [comment]
Can you please give `sessionInfo()`?

**Comment by mruessler** [comment]
> sessionInfo()
    R version 3.3.2 (2016-10-31)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Arch Linux
    
    locale:
     [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8   
     [6] LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] devtools_1.12.0
    
    loaded via a namespace (and not attached):
    [1] withr_1.0.2   memoise_1.0.0 digest_0.6.9

**Comment by hadley** [comment]
What happens if you Ctrl + C during the install? Can you get a `traceback()`?

**Comment by mruessler** [comment]
I cannot interrupt with Ctrl + C. Only process termination works. The ssh-agent process returns back to normal CPU values after R is killed. So no `traceback()`

**Comment by hadley** [comment]
The error you saw with the local version usually implies you need to restart R.  Can you try that?

**Comment by jimhester** [comment]
I think what is going on is the `ssh-agent` is prompting for a password, but there is no tty to receive one. Try cloning or fetching from a github repository on the command line, input your password when prompted and it should then be cached.

**Comment by mruessler** [comment]
@jimhester Good call! When I cloned the `devtools` repository and added a key via `ssh-add` I was suddenly able to install with `devtools::install_github("hadley/devtools")`. As far as I can remember this was not standard behaviour a few months ago. I wonder what has changed…
There is probably nothing that can be done from within R in this case, right?

**Comment by hadley** [comment]
I don't think there's much we can do here, although it's not clear to me why ssh-agent is involved at all.
