### ISSUE TITLE
message "installing vignettes" when `build_vignettes=FALSE`

### ISSUE THREAD

**Issue by stla** [hadley/devtools#1399]
Hello,
I've just installed `pkgdown` following the instruction given on [hadley.github.io/pkgdown/](http://hadley.github.io/pkgdown/), that is:
`devtools::install_github("hadley/pkgdown")`
I got this message during the installation:
`** installing vignettes`
Therefore I was surprised that there was no vignette in the package after it was installed...

I finally reinstalled the package with the vignettes by doing:
`devtools::install_github("hadley/pkgdown", build_vignettes=TRUE)`

This is just to say that the message `** installing vignettes` is puzzling.

**Comment by hadley** [comment]
Unfortunately that message is generated by R, not devtools, so there's no easy way to suppress it.
