### ISSUE TITLE
FR: collect all relevant logs of reverse dependency check

### ISSUE THREAD

**Issue by helix123** [hadley/devtools#1410]
http://r-pkgs.had.co.nz/release.html#release-submission mentions a nice example with an example directory containing all relevant log files: 

> Important reverse dependency check notes (full details at 
> https://github.com/wch/checkresults/tree/master/dplyr/r-release)

Unfortunately, I have not found a function in devtools to generate such a directory automatically. I think this would be very handy (compared to collecting the files from each package by hand).

**Comment by jimhester** [comment]
See `?devtools::revdep_check`, `?devtools::revdep_check_save_summary` etc.

**Comment by helix123** [comment]
Sorry to chip in again. I cannot find an option to get the full checking logs of each checked package... moreover, the files in `check_dir` get removed after revdep_check()

From ?revdep_check:
> check_dir	
> A temporary directory to hold the results of the package checks. This should not exist as after the revdep checks complete successfully this directory is blown away.
