### ISSUE TITLE
specify alternative subdirectory instead of 'hostname/repos/'

### ISSUE THREAD

**Issue by lengning** [hadley/devtools#1412]
Hi,
I tried to run devtools::install_github("pkgdir",username="xx",host="https://github.company.com") to install package from our enterprise github. The function broke because it tried to search for
https://github.company.com/repos/pkgdir/zipball/master
However, seems the zipped file of the pkg is at:
https://github.company.com/pkgdir/zipball/master

I wonder whether there is an option to specify the subdirectory instead of "repos"?

I tried to fork the code and replace the hard coded 'repos/' with blank, and seems it worked. But I wonder whether there will be a more appropriate way to do so.

Thank you!
Ning

**Comment by hadley** [comment]
Is this still failing for you? What version of GitHub enterprise are you using?

**Comment by hadley** [comment]
Moved to a meta issue, but it would still be useful if you could answer the above questions here.
