### ISSUE TITLE
devtools 1.12.0 CRAN check failures on R-patched

### ISSUE THREAD

**Issue by jimhester** [hadley/devtools#1415]
https://cran.r-project.org/web/checks/check_results_devtools.html, https://www.r-project.org/nosvn/R.check/r-patched-linux-x86_64/devtools-00check.html

I can't reproduce the R-patched failures locally on MacOS with [`R 3.3.2 RC (2016-10-26 r71594)`](http://r.research.att.com/mavericks/R-3.3-branch/R-3.3-branch-mavericks.pkg) or on [R-hub `R version 3.3.2 RC (2016-10-28 r71606)`](https://builder.r-hub.io/status/devtools_1.12.0.tar.gz-054ded186f464134b06c16d07fbf954c).

**Comment by hadley** [comment]
I'm assuming this is fixed now
