### ISSUE TITLE
Error: Could not find build tools necessary to build grpreg

### ISSUE THREAD

**Issue by RBaudier** [hadley/devtools#1420]
When trying to install an R package from here:
devtools::install_github("pbreheny/grpreg")

I get this:

Downloading GitHub repo pbreheny/grpreg@master
from URL https://api.github.com/repos/pbreheny/grpreg/zipball/master
Error: Could not find build tools necessary to build grpreg

Any ideas on what I'm missing? The package I'm trying to install (https://github.com/pbreheny/grpreg) says it only requires devtools.

**Comment by hadley** [comment]
If you're on windows, you'll also need to install [Rtools](https://cran.r-project.org/bin/windows/Rtools/)
