### ISSUE TITLE
Devtools encoding

### ISSUE THREAD

**Issue by danielsjf** [hadley/devtools#1421]
On my computer, Rstudio opens all file in UTF-8 by default. However, when I use devtools::load_all("."), it seems that the code is loaded using the system locale.

I've created a new package project in Rstudio and I only have one file: test.R. In this file I've put the following code:

    test_print <- function(){
        print("€")
    }

If I then save the file, use devtools::load_all(".") and execute the function, I see the following output:

    > test_print()
    â¬

However, I've explicitly used the save with encoding option in RStudio (in UTF-8). The mistake in encoding can be seen when I set a debug pointer on the print line. Suddenly I see the following code:

    test_print <- function(){
        print("â¬")
    }

But if I source the function straight from RStudio, then it works as expected and prints the euro sign: €.

The same behaviour is achieved when I build the package (using build and reload in Rstudio). Using mypackage:::test_print() also yields the desired normal euro sign.

I don't know if it can be specified anywhere, but it would be nice to source the files with load_all() using the UTF-8 encoding.

**Comment by danielsjf** [comment]
The same problem happens when devtools::test() is used on a file that is UTF-8 encoded while the machine encoding is different.

**Comment by gaborcsardi** [comment]
AFAIK R code files must ASCII. You need to encode non-ascii characters using `\uxxxx` escape sequences.

**Comment by danielsjf** [comment]
@gaborcsardi Rstudio by default saves files as UTF-8. Also, everything works when I source the code from Rstudio or if I compile the package using the build as source from Rstudio. It seems that devtools has a different behavior.

**Comment by gaborcsardi** [comment]
Again, R code files should be ASCII. UTF-8 R files might work on your system, but they might fail on another system. (Or on the same system with a different setting, like it happens to you.) This is regardless of what encoding `devtools` uses. It is very poor practice to write code that only works if the user's platform has a specific encoding.

Please see https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Encoding-issues 

In particular:
> There is a portable way to have arbitrary text in character strings (only) in your R code, which is to supply them in Unicode as \uxxxx escapes.

**Comment by danielsjf** [comment]
@gaborcsardi it was not possible to supply my characters in ASCII since they were not part of ASCII. However, your suggestion to put them in unicode worked.

I did declare the UTF-8 encoding in my description though (in fact Rstudio does this automatically when you create a new package). I perfectly understand that not every system works in UTF-8, but that doesn't mean that you can't parse UTF-8 on a given system. As long as there is a way to be aware of the UTF-8 encoding, UTF-8 usually avoids a lot of issues.

**Comment by nicholaelaw** [comment]
I apologize for the grave-digging, but `devtools::document()` is giving me similar troubles.

I understand that in the past source code should be ASCII only. But I'm using the `data.table` package in my package, and the data I'm dealing with had column names in Chinese. `data.table` allows using unquoted column names in its syntax. For example, I can just type `dt[15L, 编号]` and retrieve the item from row 15, column 编号.

However code written this way could not be processed by `devtools::document()` on Windows. If environment encoding is left untouched, it throws an 'invalid multibyte character at line XX' error. If I set `options(encoding = 'UTF-8')`, the error becomes "unexpected '<' at line XX:YY".

I am aware of the escaping method mentioned above. In fact `dt[15L, eval(parse(text = '编号'))]` works too. Chinese in quotes does not bother `devtools::document()` at all. But for operations involving dozens of columns code like that becomes very hard to read and tiresome. 

Therefore I request that Unicode variable name support be added to `devtools::document()`. Currently it fails on Windows, but works fine on macOS. I'd have test to confirm the situation on Linux, but I believe it works there too.

**Comment by gaborcsardi** [comment]
https://github.com/r-lib/devtools/issues/1421#issuecomment-287082810  still holds  I think.

**Comment by nicholaelaw** [comment]
The situation, I think, is that code works. It works across platforms. I've run code like this across Windows, macOS and Linux (CentOS). As R sources are now required to be UTF-8, I think it will work on any system that supports UTF-8 and has a recent version of R.

What's not working though, is `devtools::document`. I can skip it by manually editing `NAMESPACE` and the package builds fine, albeit without documentation. So I think it could be said that it was `devtools` not working for a specific platform...

I hope

**Comment by gaborcsardi** [comment]
>  As R sources are now required to be UTF-8

Why do you think so? This is from "Writing R Extensions":

>  Only ASCII characters (and the control characters tab, formfeed, LF and CR) should be used in code files. Other characters are accepted in comments14, but then the comments may not be readable in e.g. a UTF-8 locale. Non-ASCII characters in object names will normally15 fail when the package is installed. Any byte will be allowed in a quoted character string but \uxxxx escapes should be used for non-ASCII characters. However, non-ASCII character strings may not be usable in some locales and may display incorrectly in others.

**Comment by gaborcsardi** [comment]
I think the problem is not the guide, but that R reads the source files in the default system locale. If  that is not UTF-8 (AFAIK it never is on Windows), then the installation of your UTF-8 package will fail.

**Comment by nicholaelaw** [comment]
Yet it works. It works on Windows. My comments on how the package works across platforms are mysteriously ignored. What must I do to convince you that it works?

I'm using my package right now on Windows 10, in RStudio, with locale

```r
> Sys.getlocale()
[1] "LC_COLLATE=Chinese (Simplified)_China.936;LC_CTYPE=Chinese (Simplified)_China.936;LC_MONETARY=Chinese (Simplified)_China.936;LC_NUMERIC=C;LC_TIME=Chinese (Simplified)_China.936"
```

**Comment by gaborcsardi** [comment]
Yes, it does work on Windows  _if_  your files are also in the local encoding (i.e. Chinese (Simplified)_China.936).  But if you package this up on this Windows and try to install it on a system with a different locale, that will probably fail.)

I.e. the problem is using the _same_ code files on all platforms.

**Comment by nicholaelaw** [comment]
AFAIK, RStudio defaults to UTF-8 encoding for all sources on all platforms. I'm staring at my sources encoded in UTF-8, lines ending with LF (Posix), written on Windows. The package builds fine, installs fine and runs fine.

![image](https://user-images.githubusercontent.com/10719482/44231167-c4642600-a1cf-11e8-9bf8-d0a2f9115577.png)

**Comment by nicholaelaw** [comment]
This exact source, was pulled from my GitHub repository, originally pushed from my MacBook, after it's been built and tested to work. In other words, this exact package works on both macOS (UTF-8 locale) and Windows (rubbish locale), without any modification.
