### ISSUE TITLE
The build ignore list is ignored when building a binary on Windows

### ISSUE THREAD

**Issue by danielsjf** [hadley/devtools#1425]
I've put a test file in mypackage/inst/extdata/test.zip.

Next I've added the following line in .Rbuildignore.

    ^inst/extdata/test\.zip$

When I run devtools::build(), I can inspect mypackage_version.tar.gz and the ignored file is indeed not present.

However, when I run devtools::build(binary=T), I can see test.zip in the extdata folder in the mypackage_version.zip file.

**Comment by hadley** [comment]
Confusingly, the way to build a binary package is to call `R CMD install`. That means you need to make sure your file is also listed in `.Rinstignore`.
