### ISSUE TITLE
install_version with repo=file:~/xxx

### ISSUE THREAD

**Issue by stla** [hadley/devtools#1426]
Hello, 
On Windows, `install_version` fails when the repo is given as `file:~/xxx`. 
I know I can use an absolute path, but `file:~/xxx` is useful for collaborating (especially with a packrat project).

The problem is that `devtools:::read_archive` fails. It works with `file://~/xxx`, but `available.packages` fails. Also `devtools:::url_remote` only works with `file:///`. 

It would be nice if `devtools::install_version` converts relative paths to absolute paths at the beginning. Like:
```
f <- function(repo){
  if(substr(repo, 1, 5) == "file:"){
    repo <- paste0("file:///", path.expand(sub("^file:?/*", "", repo)))
 }
  return(repo)
}
repos <- sapply(repos, f)
```
But I don't know whether this is cross-platform...

**Comment by hadley** [comment]
`file:~/xxx` is not a valid URI, so I'm not sure why you expect it to work?

**Comment by stla** [comment]
Because `available.packages()` works with `file:~/xxx`, if I well remember (not sure, I have abandoned to use packrat since, but I remember that something works).
