### ISSUE TITLE
check() does not scold me about unused Import

### ISSUE THREAD

**Issue by jennybc** [hadley/devtools#1427]
I have knitr listed in Imports, even though there are no actual calls of the form `knitr::foo()`. (There is a good reason for that. Also not my point.)

When I run `devtools::check()`, it does NOT complain about this.

```
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
```

But `R CMD check` does issue a NOTE.

```
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘knitr’
  All declared Imports should be used.
* checking S3 generic/method consistency ... OK
```

Neither `devtools::release()` nor `devtools::check_built()` issues the NOTE. Am I missing some additional argument to make the devtools check functions more CRAN-like?

**Comment by hadley** [comment]
I've seen this too and I don't understand why 😢

**Comment by jimhester** [comment]
`R CMD check` has roughly [1 Billion](https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L4528-L4829) options.

```r
cyclocomp::cyclocomp(tools:::.check_packages)
#> [1] 1207
```
Some options take a long time to run, which we turn off, but some which only work on certain platforms.

I think rcmdcheck does a better job of mimicking CRAN settings, so this should improve soon!
