### ISSUE TITLE
check_built, revdep_check require full path names

### ISSUE THREAD

**Issue by bbolker** [hadley/devtools#1431]
I don't know whether it's a structural issue or an oversight that full path names are needed for `check_built()` and (by extension) for `revdep_check()`, but it had me stumped for a while.  If it's not structural it would seem better to me to allow `check_built("./foo.tar.gz")` to work as well as `check_build("~/stuff/foo.tar.gz")` and similarly (`revdep_check(...,check_dir="local_path")`), but if you'd prefer either in the short or long term to leave the behaviour the way it is, I would be happy to provide a documentation patch as a PR.

**Comment by hadley** [comment]
All the devtools revdep checking functions will be deprecated shortly in favour of the vastly better [revdepcheck](https://github.com/r-lib/revdepcheck)

**Comment by bbolker** [comment]
are you interested in beta testers? (I would try it out but the repo says DO NOT USE IT)
