### ISSUE TITLE
install_github extraction sometimes fails when .Rbuildignore is present

### ISSUE THREAD

**Issue by Vin985** [hadley/devtools#1433]
Hi,

I have this weird problem at work when if try to install a package via install github and a .Rbuildignore file is present, then the package extraction fails. I get the following error:

> install_github("hadley/devtools")
Downloading GitHub repo hadley/devtools@master
from URL https://api.github.com/repos/hadley/devtools/zipball/master
Error in utils::unzip(src, exdir = target) : 
  cannot open file 'C:/Users/CHRIST~1/AppData/Local/Temp/RtmpOUEcJp/devtools1344435d3aae/hadley-devtools-1ce84b0/R/R.r': No such file or directory

I did some tests, if I remove the .Rbuildignore file, everything works fine.
If I manually download the package, extract it and use devtools::install() on it, no problems either.
This has happened at least for me and another colleague but others don't seem tohaveany problem with it. I don't know if it can be a permission problem since I'm not an administrator on my computer.

The content of the .Rbuildignore doesn't seem to matter, if the file is empty, the install fails as well.

The tests were made with devtools 1.12.0 and R 3.3.1 32bits (fails also with 64bit)

Any idea on this?

Thanks

Sylvain

**Comment by Kenkleinman** [comment]
I have this problem also.  Major PIA.

**Comment by hadley** [comment]
Could you please both provide `session_info()`? (Just the OS part, not the packages)

**Comment by Kenkleinman** [comment]
I have not been able to install_github() on my work computer since I got it, but today, it works.  Is that a smiley face or a frowney face?

**Comment by hadley** [comment]
It seems to be the same problem as #1464, so lets move all discussion there. It looks like it's going to be painful to track down the issue since it's seemingly random on which computers it works.
