### ISSUE TITLE
devtools::build_win() suddenly gives error "Error in curl::curl_fetch_memory"

### ISSUE THREAD

**Issue by friendly** [hadley/devtools#1435]
On two computers, both running R 3.2.5 and with devtools 1.12.0, I'm getting now this error when I try to
send a package to Win Builder:

    > devtools::build_win()
    Building windows version of HistData for R-devel with win-builder.r-project.org.
    ...
    Error in curl::curl_fetch_memory(url, handle = h) : 
      Upload failed (at start/before it took off)

This error was discussed in #1079 in a different context and @hadley  suggested re-installing `curl` and `httr`. I've done that, as well as updating nearly all other packages, but it still gives the same error.

Here is my sessionInfo:

    > sessionInfo()
    R version 3.2.5 (2016-04-14)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 7 x64 (build 7601) Service Pack 1

    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    loaded via a namespace (and not attached):
    [1] tools_3.2.5     withr_1.0.2     curl_2.3        memoise_1.0.0   digest_0.6.11  
    [6] devtools_1.12.0

**Comment by hadley** [comment]
I think this was just a temporary win-builder problem.

**Comment by friendly** [comment]
Confirmed.  It now seems to work.  I only filed an issue because it didn't work for two days

**Comment by dankelley** [comment]
I'm finding this problem, today 2017-03-30 and yesterday, with `R-devel`, although `R-release` works okay ("oce" package).

**Comment by dankelley** [comment]
Also, I tried with the web interface and got as follows, so I don't think this is a `devtools::build_win()` problem.
```
R-devel
For uploading R source packages to be built and checked with R-devel, please use this second form:
ERROR: Access to the path 'C:\Inetpub\ftproot\R-devel\oce_0.9-21.tar.gz' is denied.
```

**Comment by camrinbraun** [comment]
Same for me today but only with `R-devel`, both using `devtools::build_win()` and the web interface. `R-release` works fine via both methods. Any idea why this is happening?
