### ISSUE TITLE
DESCRIPTION LazyData unnecessary

### ISSUE THREAD

**Issue by jakubkuzilek** [hadley/devtools#1436]
According to [CRAN Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file) LazyData option is ignored since R version 2.14.0. It is reasonable to remove it from DESCRIPTION file.

**Comment by hoelk** [comment]
I think you misread. From your link:

> The ‘LazyData’ logical field controls whether the R datasets use lazy-loading. A ‘LazyLoad’ field was used in versions prior to 2.14.0, but now is ignored.

**Comment by jakubkuzilek** [comment]
Ahh, you are right, I should stop reading at night :)
