### ISSUE TITLE
Use _R_CHECK_SUGGESTS_ONLY_=true in revdep checks

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1438]
because this is what CRAN uses for their incoming checks. Perhaps other switches are also useful (in R-ints just above https://cran.r-project.org/doc/manuals/r-release/R-ints.html#R-coding-standards).

This was a problem with tibble 1.3.0 release.

**Comment by hadley** [comment]
Can you please move to revdepcheck?
