### ISSUE TITLE
package startup message not shown when build and reload

### ISSUE THREAD

**Issue by dracodoc** [hadley/devtools#1442]
# Steps to reproduce
1. create a package
2. edit zzz.R in /R folder with
```
.onAttach <- function(libname, pkgname) {
  packageStartupMessage("test")
}
```
3. build and reload. There is a message of "test" when package was loaded.
4. build and reload again, no more messages no matter how many times build and reload, or load package manually again.
5. manually restart R session with ctrl-shift-F10, then build and reload, message appear again.

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] message_0.1.0

loaded via a namespace (and not attached):
[1] tools_3.3.2
```

devtools version: `1.12.0.900`

**Comment by hadley** [comment]
Build and reload is an RStudio function that installs the package, restarts R, and then calls `library()`. I'm surprised that something is going wrong here, but I see the issue too.

@kevinushey @jjallaire could you please take a look?

**Comment by kevinushey** [comment]
I'll try and see if I can figure out what's going on.

**Comment by dracodoc** [comment]
The fact that manual restart R session works make me wonder if the `build and reload` function called `.rs.restartR()`, but that function didn't do these two things according to [this](https://stackoverflow.com/questions/6313079/quit-and-restart-a-clean-r-session-from-within-r#comment61693127_25934774) 
- Data from current session is removed
- Packages from current session are unloaded

It's probably not this simple, since I don't think packages are not unloaded, which is part of the whole purpose.

I didn't find the code of the `build and reload` function so I can only guess this much.

**Comment by kevinushey** [comment]
I see the same issue all the way back to RStudio v0.98.1091 (didn't test anything older, though) so this appears to be a long-standing issue.

**Comment by hadley** [comment]
I'm going to close this, and leave in the hands of the IDE team
