### ISSUE TITLE
Example for Git Remotes Confusing

### ISSUE THREAD

**Issue by PerFuchs** [hadley/devtools#1445]
Your example how to use `Remotes` for a git type dependency does not work. It shows a http git url, but in your implementation you use `git archive` which seems to be unsupported by the git http implementation.

Your example in `vignettes/dependencies.html`
```
Remotes: git::https://github.com/hadley/ggplot2.git
```
Devtool error if I'm actually use a git http url in `Remotes`:
```
Error in vapply(remote, remote_package_name, character(1)) : 
  values must be type 'character',
 but FUN(X[[1]]) result is type 'logical'
```

Caused by this error of the official git client:
```
git archive --remote http://server-name/git/gittest HEAD
fatal: Operation not supported by protocol.
Unexpected end of command stream
```

I think you should change the example to use ssh and no GitHub repository because GitHub does not support `git archive` at all:
```
Remotes: git::git@private-git-server.com:tidyverse/ggplot2.git
```

**Comment by jimhester** [comment]
This seems correct, perhaps `git@bitbucket.org:dannavarro/lsr-package.git` would be a good example.

**Comment by PerFuchs** [comment]
Yep, I agree. Works on my machine as well.
