### ISSUE TITLE
Feature request: Check that URLs in DESCRIPTION::Description are enclosed in <...>

### ISSUE THREAD

**Issue by ijlyttle** [hadley/devtools#1446]
I just had to make a CRAN resubmission because a URL in DESCRIPTION::Description was not enclosed in <...>.

This seems like it should be straightforward to check.

I'm happy to make a PR.

**Comment by hadley** [comment]
Since this is caught by R CMD check (with the appropriate version of R) it's outside the scope of devtools. You should generally be using `build_win()` or `rhub::check_for_cran()` to make sure you've checked with the latest version of R.
