### ISSUE TITLE
Feature request: add -I"./inst/include" to devtools::test() ccflags

### ISSUE THREAD

**Issue by thk686** [hadley/devtools#1447]
Currently if your testthat code needs to use sourceCpp, it will fail to find headers in the "inst/include" directory. Adding a symlink from "inst/include" to "include" fixes the problem, but it would be cleaner to just add -I"inst/include" to the complier include path when calling devtools::test(). Note that the symlink does not fix problems with calling devtools::check(args = c('--as-cran')) as this probably calls testthat in a different environment.

**Comment by hadley** [comment]
Shouldn't you do this yourself by providing a `Makevars`?
