### ISSUE TITLE
`run_examples` shouldn't pass `show` to `pkgload::run_example`

### ISSUE THREAD

**Issue by amcdavid** [hadley/devtools#1449]
`pkgload::run_example` lacks a `show` parameter (not sure if this is intentional or an oversight), but `devtools::run_examples` tries to pass this parameter via `lapply` nonetheless. This makes `run_examples` fail with the following:
> 
> Running 76 example files in devtools ------------------------------------------
> Loading devtools
> Error in FUN(X[[i]], ...) : unused argument (show = TRUE)
> Loading devtools

## Repex ##
`$ git clone git@github.com:hadley/devtools.git`
> Cloning into 'devtools'...
```
$ cd devtools/
$ R
> run_examples()
```
> Updating devtools documentation
> Loading devtools
> Updating roxygen version in  /Users/amcdavid/Downloads/devtools/DESCRIPTION 
> Writing package_deps.Rd
> Writing use_build_ignore.Rd
> Writing use_readme_rmd.Rd
> Writing install_svn.Rd
> Writing install_version.Rd
> Writing path.Rd
> Writing reexports.Rd
> Writing revdep_check.Rd
> Writing devtools-deprecated.Rd
> Running 76 example files in devtools ------------------------------------------
> Loading devtools
> Error in FUN(X[[i]], ...) : unused argument (show = TRUE)
> Loading devtools

`> sessionInfo()`
> R version 3.3.2 (2016-10-31)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: macOS Sierra 10.12.2
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] devtools_1.12.0.9000 knitr_1.15.1        
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.9         roxygen2_5.0.1      crayon_1.3.2       
>  [4] digest_0.6.12       withr_1.0.2         rprojroot_1.2      
>  [7] R6_2.2.0            jsonlite_1.2        backports_1.0.5    
> [10] git2r_0.18.0        magrittr_1.5        httr_1.2.1         
> [13] stringi_1.1.2       rstudioapi_0.6      testthat_1.0.2     
> [16] whisker_0.3-2       callr_1.0.0.9000    tools_3.3.2        
> [19] stringr_1.1.0       pkgload_0.0.0.9000  pkgbuild_0.0.0.9000
> [22] memoise_1.0.0

**Comment by amcdavid** [comment]
Additionally, in the `pkgload` refactor, `dev_help` was moved and is currently not re-exported by `devtools`.  Is this the intended API?  If so, a deprecation message to users about this change seems appropriate, since it was a public function in devtools previously.

**Comment by lbusett** [comment]
HI. I have the same issue: `run_example` fails with 

    Error in FUN(X[[i]], ...) : unused argument (show = TRUE)

> sessionInfo()

> R version 3.4.1 (2017-06-30)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
> [3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
> [5] LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] devtools_1.13.2.9000
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.4.1      tools_3.4.1         withr_1.0.2         memoise_1.1.0       pkgload_0.0.0.9000 
> [6] digest_0.6.12       pkgbuild_0.0.0.9000 rlang_0.1.1

**Comment by briancohn** [comment]
I am also getting this error
