### ISSUE TITLE
devtools::check building entire package, including data-raw

### ISSUE THREAD

**Issue by robertamezquita** [hadley/devtools#1453]
It seems that check() is ignoring `.Rbuildignore` when checking the package. In my case, I have links to raw data in my data-raw folder that are in the GB, and when check() goes to run the error is similar to below:

```
devtools::check()
 Updating datpkg documentation
 Loading datpkg
 Setting env vars -----------------------------------------------------------------------------------------------------------------
 CFLAGS  : -Wall -pedantic
 CXXFLAGS: -Wall -pedantic
 Building datpkg ------------------------------------------------------------------------------------------------------------------
 '/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD build '/mnt/sdb1/ra364/repos/datpkg'  \
   --no-resave-data --no-manual

 * checking for file ‘/mnt/sdb1/ra364/repos/ctldat/DESCRIPTION’ ... OK
 cp: error writing '/tmp/Rtmpn5iy5b/Rbuild4bd03bc1056d/datpkg/README.md': No space left on device
...
cp: error writing '/tmp/Rtmpn5iy5b/Rbuild4bd03bc1056d/datpkg/data-raw/DAT.R': No space left on device
 cp: error writing '/tmp/Rtmpn5iy5b/Rbuild4bd03bc1056d/datpkg/.git/refs/heads/master': No space left on device
...
```

The current solution is to move my `data-raw` folder out of the package directory, delete the relevant `/tmp/Rtmp*/Rbuild*/datpkg` directories, and then trying the check again.

**Comment by jimhester** [comment]
Did you try running

```shell
R CMD build .
R CMD check datpkg*tar.gz
```

I think you will observe the same behavior

**Comment by robertamezquita** [comment]
Yes, you're right, same result occurs when doing `R CMD build .` ..so this isn't a devtools problem then, sorry about that...but if you happen to have any suggest workarounds for this, I would very much appreciate the help! Thanks ~

**Comment by jimhester** [comment]
Unfortunately the way `R CMD build` works is it [copies the full package directory, then deletes excluded files](https://github.com/wch/r-source/blob/903ecd26b8e0f9fbdd8a6e6e2bcb1d52bc6bfc4d/src/library/tools/R/build.R#L929-L1007), so I don't think there is any way to avoid doing what you are currently doing.

You could probably put those steps in a Makefile (or write an R function) to make them less painful to do, but I think that is all I can offer 😦 .

**Comment by robertamezquita** [comment]
The Makefile workaround is a great idea, thank you so much!
