### ISSUE TITLE
install_github() exits with error when multiple packages are present in repository

### ISSUE THREAD

**Issue by lukasz-bednarz-reddeersystems** [hadley/devtools#1457]
When using _install_github()_ to install packages from a repo that has multiple subfolders with packages in it:

```r
install_github("user/MyRepoName", ref = "release",  auth_token = Sys.getenv("GITHUB_PAT"), subdir = "Library/MyPackage1/", dependencies = TRUE)
```

will work only if _MyPackage1_ doesn't have dependencies within packages present in _"user/MyRepoName/Library"_

```r
install_github("user/MyRepoName", ref = "release",  auth_token = Sys.getenv("GITHUB_PAT"), subdir = "Library/MyPackage2/", dependencies = TRUE)
```

will fail if _MyPackage2_ depends on _MyPackage1_ until "dependencies = FALSE" is set:

```r
install_github("user/MyRepoName", ref = "release",  auth_token = Sys.getenv("GITHUB_PAT"), subdir = "Library/MyPackage2/", dependencies = FALSE)
```
However, this is not optimal for package deployment as it will also skip installing external CRAN dependencies.

The error returned is like this:

_Downloading GitHub user/MyRepoName@release
from URL https://api.github.com/repos/user/MyRepoName@release/zipball/release
Installing MyPackage2
Downloading GitHub repo user/MyRepoName@release
from URL https://api.github.com/repos/user/MyRepoName@release/zipball/release_
**Error in stop(github_error(request)) : Not Found (404)**

I have walked through the code and the error is happening when trying to pull the dependency package MyPackage1 from the same GitHub repo . The original remote$auth_token is not copied to subsequent calls to install_remote() for dependent packages. I have checked in debug mode and if I copy the remote$auth_token field from first call when downloading _MyPackage2_ to second install_remote() call for dependent package _MyPackage1_ it is working.

Also, there is a scope for optimization as these packages (MyPackage1, MyPackage2, MyPackage3,...) got downloaded in first zipball anyway as they reside in the same Library folder

**Comment by hadley** [comment]
The expectation of one package per repo is deeply baked into devtools, and you will be sailing upstream if you try to fight it.
