### ISSUE TITLE
Avoid reloading packages 

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/devtools#1458]
More specifically, it would be great if a package request **not** to be unloaded/reloaded, or at least not its shared lib. 

This is because some packages cannot be reloaded properly. This includes all packages that depend on libglib on Linux. libgtk also depends on libglib, so libgtk dependent packages cannot be reloaded, either. If these packages are unloaded, they typically leave some extra threads behind. If they are then reloaded, then they probably crash R.

I am not sure what the best way would be to indicate this in the package.

**Comment by jimhester** [comment]
What devtools function in particular are you talking about? `install()` has a `reload` argument which can be set to `FALSE` to avoid attempting to reload the package.

**Comment by gaborcsardi** [comment]
E.g. `test()`. But also `install()`, because if you just do `install_github()`, then you will probably not add `reload = FALSE`.

This is sg I can work around for myself, but people that install my package from GH will not be aware of it, and they'll just see the crashes. Hence the suggestion to trigger a message from the package.

Btw. I can add a `stop()` into `.onUnload()`, and while this will not stop the unloading, because it is converted to a warning, at least it gives a message. Looks like `devtools::unload()` does not call `.onUnload()`, at least I don't see the message.
