### ISSUE TITLE
native routine registration (feature request)

### ISSUE THREAD

**Issue by spedygiorgio** [hadley/devtools#1461]
The upcoming version of R makes compulsory native routine registration (see [R Mailing List](https://stat.ethz.ch/pipermail/r-devel/2017-February/073755.html)) Is it possible to build a function to make this easier? Especially for those using Rcpp with devtools :-)

**Comment by jimhester** [comment]
See https://github.com/RcppCore/Rcpp/issues/636, eventually Rcpp will generate this automatically for you, without any changes to devtools.
