### ISSUE TITLE
document() failing after upgrade from 1.7.0 to 1.12.0 due to NAMESPACE file

### ISSUE THREAD

**Issue by RalphJO** [hadley/devtools#1466]
Note: Also upgrading roxygen2 from 4.1.1 to 6.0.1

Hi, 

I have a package for which document() was working with devtools 1.7.0 and roxygen2 4.1.1.

After upgrading to devtools 1.12.0 and roxygen2 6.0.1 it fails as follows: 

If the NAMESPACE file exists prior to calling _document_ I get 

> Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.

 with the result that build fails as my imports and exports are not set up (previously the NAMESPACE file was over-written).

However, if I delete the existing NAMESPACE file (which should be fully created by roxygen2 anyway) I get

> Updating MyPackage documentation
 Loading MyPackage
 Re-compiling MyPackage
 "c:/R-3.3.2/bin/x64/R" --no-site-file --no-environ --no-save  \
   --no-restore --quiet CMD INSTALL  \
   "C:\MyPackage"  \
   --library="C:\Users\Ralph\AppData\Local\Temp\Rtmp4QMFIi\devtools_install_14a44c08602b"  \
   --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec  \
   --no-multiarch --no-test-load --preclean

>  * installing *source* package 'MyPackage' ...
 ERROR: a 'NAMESPACE' file is required

This error occurs in the call to _install_min_
   from _compile_dll_
   from _load_all_
   from _document_

**Comment by BarkleyBG** [comment]
I've had a similar issue with devtools 1.12 and roxygen 6.0.1. However, I was able to get this to work with devtools 1.12 and roxygen 4.0.1. If you rolled back to your roxygen 4.1.1, are you able to get this to work?

**Comment by hadley** [comment]
Just delete the contents of NAMESPACE, without deleting the complete file.

**Comment by privefl** [comment]
I have the same issue. 
Deleting the contents of NAMESPACE didn't change the warning: `Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.`.
Command used: `devtools::document(roclets=c('rd', 'collate', 'namespace'))`.

**Comment by jimhester** [comment]
Just keep the `# Generated by roxygen2: do not edit by hand` line at the top then.

**Comment by RalphJO** [comment]
Thank you for all the suggestions. Adding # Generated by roxygen2: do not edit by hand to the namespace file is the workaround that worked for me. It does feel like a workaround not a fix though: I'm not sure a function designed to create the documentation should fail with an error if a piece of documentation doesn't exist.
----Original message----
From : notifications@github.com
Date : 09/03/2017 - 13:06 (GMT)
To : devtools@noreply.github.com
Cc : ralpholsson@btinternet.com, author@noreply.github.com
Subject : Re: [hadley/devtools] document() failing after upgrade from 1.7.0 to 1.12.0 due to NAMESPACE file (#1466)
Just keep the # Generated by roxygen2: do not edit by hand line at the top then.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hadley/devtools","title":"hadley/devtools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hadley/devtools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jimhester in #1466: Just keep the `# Generated by roxygen2: do not edit by hand` line at the top then."}],"action":{"name":"View Issue","url":"https://github.com/hadley/devtools/issues/1466#issuecomment-285346175"}}}
