### ISSUE TITLE
bug install_cran with local repo containing white spaces

### ISSUE THREAD

**Issue by stla** [hadley/devtools#1467]
Hello, 

```
> repo <- c(SL="file:////RIXDSNTP001/CMCSTAT/7. STAT ANALYSES and IA/71- IA/LocalApps/CRANlike-SL")
> devtools::install_cran("SLutils", repos=repo, type="source")
Installing 1 package: SLutils
Warning: package incorrect '//RIXDSNTP001/CMCSTAT/7.'
Warning: package incorrect 'STAT'
Warning: package incorrect 'ANALYSES'
Warning: package incorrect 'and'
Warning: package incorrect 'IA/71-'
Warning: package incorrect 'IA/LocalApps/CRANlike-SL/src/contrib/SLutils_1.4.12.tar.gz'
Erreur : ERREUR : aucun package spécifié
```

There is exactly the same issue with the base function `install.packages`. But there's no such issue with `devtools::install_version`.

NB: this occurs only for `type="source"`.

**Comment by stla** [comment]
Hmm.. however there's this solution:

`repo <- c(SL="file:////Rixdsntp001/cmcstat/7~1.STA/71-IA~1/LOCALA~1/CRANLI~1")
`

To get such an “encoding”, use the function `shortPathName`.

**Comment by hadley** [comment]
Since the error is likely coming from `install.packages()` not devtools we won't fix here. But we'll definitely be thinking more about this problem in the general context of robust package installation.
