### ISSUE TITLE
testthat.R is not used

### ISSUE THREAD

**Issue by fangly** [hadley/devtools#1468]
Hi,

I use "testthat" for unit testing and therefore have a "tests/testthat.R" file, which looks like this:
```R
library(testthat)
library(pkg2)      # this package
library(pkg1)      # a dependency with expectation functions for use by testthat
source("utils.R")  # contains convenience functions useful for my test suite
test_check("pkg2", reporter="summary")
```

Notice the two lines that make use "pkg1" and "utils.R" that are customizations I made this file.

If I run `devtools::check()`, all is good, and I can see that my  "tests/testthat.R" file is used:
```
* checking tests ...
  Running 'testthat.R' [49s]
```

But when I run `devtools::test()`, my  "tests/testthat.R" file is *not* used and I have to manually load "pkg1" and "tests/utils.R". I would expect `devtools::test()` to detect that I have a  "tests/testthat.R" file and use it, just like `devtools::test()` does.

Cheers,
Florent

PS/ This is with devtools 1.12.0, and `devtools::uses_testthat()` returns `TRUE`.

**Comment by jimhester** [comment]
You should be use [helper scripts](https://github.com/hadley/testthat/blob/37cc0d04fc497edcf62fe44729c73e3c77559b2e/R/test-files.R#L16-L18) to do this, which are sourced by `devtools::test()`. Simply rename your `utils.R` file to `helper-utils.R` and place it in `testthat/` and this will work as you intend.

**Comment by fangly** [comment]
Great suggestion regarding the **helper utils**, Jim, thanks! Back when I investigated this issue, the corresponding [StackOverflow question](https://stackoverflow.com/questions/35941729/r-testthat-unit-test-data-and-helper-function-conventions/41777777#41777777) did not have this answer.

But there is still the issue of **other code** that may be present in the "tests/testthat.R" file. In my case, I have a `library(pkg1)` statement, that loads a module containing testthat expectations. Or I may append extra lines of code to the file in the future to postprocess the `test_check()` results. Do you have a better alternative for these use cases, other than having `devtools::test()` use the "tests/testthat.R" just like `devtools::check()`?

**Comment by ClaytonJY** [comment]
@jimhester Could this issue be reopened? I'm having a very similar issue; package loaded in `testthat.R` is loaded as expected with `devtools::check()`, but not with `devtools::test()`. In this case I'm loading `checkmate` to extend the `testthat` assertions, so the failure when `test()`-ing is that it can't find the `checkmate` function I use first.

I would think the idea is for testing to be done exactly the same way in both testing and checking, but that appears to not be the case in version `1.13.5.9000` (current github).

Does this issue belong in one of the new diaspora packages? Not clear which one handles testing functionality.

**Comment by jimhester** [comment]
This is the way that this has always worked, it is very unlikely to change. If you want custom logic to be run both during R CMD check and interactively with `devtools::test()` you need to put it in a helper script.

**Comment by ClaytonJY** [comment]
@jimhester thanks for the quick response; does that mean when using `devtools`,  the `testthat.R` file should never contain anything but the following?

```r
library(testthat)

test_check("mypackage")
```

e.g. anything beyond that is custom logic that needs to go in a `helper*` file?

**Comment by jimhester** [comment]
Yes that is right

**Comment by ClaytonJY** [comment]
gotcha, thanks @jimhester

**Comment by jennybc** [comment]
@jimhester helped me work through a lot of related misunderstandings recently here, in case it's a helpful read:

https://github.com/r-lib/pkgload/issues/56
