### ISSUE TITLE
How to install latest release without knowing release tag version

### ISSUE THREAD

**Issue by kush99993s** [hadley/devtools#1469]
Hello everyone,

How I can use install_github to install latest release without knowing release tag or release title  or commit id?

If we know tag version, we can install as follows
`devtools::install_github("OHDSI/OhdsiRTools@v1.0.1")`

During my search I have notice following code from (http://stackoverflow.com/questions/40179493/r-how-can-i-install-a-specific-release-by-install-github)

`devtools::install_github("OHDSI/OhdsiRTools@*release")`

and however, these don't work. and it edited saying it is out of date as well. 

I can see devtools has option to do. However, it is very old release 
 
https://github.com/hadley/devtools/pull/475, and it is not working
Do you guys have any suggestion ??

**Comment by jennybc** [comment]
If you want the latest release, why install it from github vs from CRAN via `install.packages()`?

**Comment by dy-kim** [comment]
I've referred the following [GitHub API method](https://developer.github.com/changes/2015-02-18-new-releases-api-methods/).

Please give attention that this codes are using unexported function `github_GET()` from `devtools`.
```
end_point <- "repos/OHDSI/OhdsiRTools/releases/latest"
response <- devtools:::github_GET(end_point)
latest_tag_name <- response$tag_name
devtools::install_github("OHDSI/OhdsiRTools", ref = latest_tag_name)
```

**Comment by jimhester** [comment]
This could actually be useful functionality. Some packages may never go on CRAN but still have GitHub releases. The situation is rare enough I don't think it is worth including in `install_github()` unless more people are looking for it. If you do think this is worthwhile, you would need to open an issue in remotes.
