### ISSUE TITLE
devtools::load_all() does not install packages (Bioconductor)

### ISSUE THREAD

**Issue by matdoering** [hadley/devtools#1470]
Dear all,
I am wondering if it is the intended behavior that devtools::load_all() does not check whether package dependencies are fulfilled? The description says:

> load_all loads a package. It roughly simulates what happens when a package is installed and
loaded with library.

But if I don't have a dependency installed (in this case Biostrings), the following happens when running load_all():

> devtools::load_all()
Loading testPkg
Error in (function (dep_name, dep_ver = NA, dep_compare = NA)  : 
  Dependency package Biostrings not available.

If, however, I run the 'proper'
install command, Biostrings is installed successfully:

> devtools::install()
  Installing testPkg
  trying URL
  'https://bioconductor.org/packages/3.3/bioc/src/contrib/Biostrings_2.40.2.tar.gz

It would be nice if load_all() would install required packages directly rather than having to call devtools::install() beforehand, particularly if you do not want to actually install your development package (which is why you are using devtools). 

Additionally, if BiocInstaller is not available, the following happens for install():

> devtools::install()
Installing testPkg
‘BiocInstaller’ must be installed for this functionality.
Fehler in loadNamespace(name) : there is no package called ‘BiocInstaller’
package ‘BiocInstaller’ is not available (for R version 3.3.2) 

In this case, you have to manually load biocLite() to make it work.

Please find attached a minimal working example in terms of a test package.

Thanks and best regards
 Matthias

[testPkg.zip](https://github.com/hadley/devtools/files/816653/testPkg.zip)

**Comment by jimhester** [comment]
`load_all()` never installs package dependencies regardless of source, you need to use `devtools::install_deps()` to install dependencies for development packages.

**Comment by matdoering** [comment]
Ok, thank you for clarifying. In this case, would it be possible to update the function documentation to reflect this?

Apart from this, what about the problem of installing BiocInstaller using install() as described above? It seems that devtools doesn't load biocLite correctly?

**Comment by jimhester** [comment]
The error message says the issue
> ‘BiocInstaller’ must be installed for this functionality.

you need to run the install directions at https://bioconductor.org/install/ _once_ to install the `BiocInstaller` package. Once it is installed devtools will use it for all further installations.

**Comment by matdoering** [comment]
Well, of course the issue is clearly communicated. But when you are distributing a package in development to a person that is not a developer you have to tell them how it's done rather than having it done automatically by devtools. Just a suggestion :-)
