### ISSUE TITLE
Files in the 'vignettes' directory newer than all files in 'inst/doc' checked for by devtools::release()?

### ISSUE THREAD

**Issue by joshuarosenberg** [hadley/devtools#1473]
For a recent submission of a package I am developing to CRAN, I received a note to address this warning:

`Files in the 'vignettes' directory newer than all files in 'inst/doc' [name of file]`

This was because I changed something in the vignette but did not use `devtools::run_examples()`, which addressed this when I re-submitted the package.

**My question**: Does `devtools::check()` or the checks run by `devtools::release()` check for this warning? I (don't think) I saw this when I ran these before submitting.

**Comment by cvitolo** [comment]
I had a similar issue with an Rmd vignette. I fixed it by changing the YAML header of the vignette to something like this:

```
---
author: "Name Surname"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Title of your vignette}
  %\usepackage[UTF-8]{inputenc}
---
```

**Comment by hadley** [comment]
It's likely because the check occurs in a newer version of R than you had installed. In general, it's a good idea to run `build_win()` before submitting to CRAN because then you know that you're running the same checks that CRAN will.
