### ISSUE TITLE
Incorrect results filename printed by revdep_check()

### ISSUE THREAD

**Issue by ezwelty** [hadley/devtools#1474]
[This line](https://github.com/hadley/devtools/blob/5824bce2e26c7d754fb17f872cb99e49da4d3d37/R/revdep.R#L277) should read:

```
rule("Saving check results to `revdep/checks.rds`")
```

(check => checks)

**Comment by hadley** [comment]
`revdep_check()` will be deprecated shortly, in favour of the vastly superior [revdepcheck](http://github.com/r-lib/revdepcheck) package
