### ISSUE TITLE
document() looks for Rtools in `c:/Rtools/`

### ISSUE THREAD

**Issue by Neil-Schneider** [hadley/devtools#1478]
When running `document()` prior to building the source files, it attempts to locate Rtools in `C:/Rtools/`. Rtools is in my environmental path, but under a different path. It will throw the following error: `c:/Rtools/mingw_64/bin/g++: not found`. If I run `install("packagename")` prior to `document()`, the documentation will generate successfully. This is because `install()` is finding Rtools/gcc in my path. 

I attempted to tracking the root of where it is adding `C:/Rtools/` to the path, or explicitly looking calling `C:/Rtools/`, but didn't have much luck.

**Comment by stla** [comment]
Try to run `devtools::find_rtools()` before, then run `document()`.
