### ISSUE TITLE
Problem loading devtools

### ISSUE THREAD

**Issue by wiaidp** [hadley/devtools#1479]
I'm using devtools for setting-up my packages on gitHub. When following the instructions (getting started) on http://r-pkgs.had.co.nz/intro.html I encountered the following issue (I checked for similar issues but did not found relevant answers yet):

```
* installing *source* package 'devtools' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Error : package 'devtools' is not installed for 'arch = i386'
Fehler: Laden fehlgeschlagen
Ausführung angehalten
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/Marc/Documents/R/win-library/3.3/devtools'
* restoring previous 'C:/Users/Marc/Documents/R/win-library/3.3/devtools'
Warnung in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE)
  Problem C:\Users\Marc\Documents\R\win-library\3.3\00LOCK-hadley-devtools-d8ab190\devtools\libs\x64\devtools.dll nach C:\Users\Marc\Documents\R\win-library\3.3\devtools\libs\x64\devtools.dll zu kopieren: Permission denied
Error: Command failed (1)
```

I tried with different versions of R (32 bit, 64 bit, older and latest release). Rtools as well as all necessary libraries are installed.

**Comment by wiaidp** [comment]
A similar issue was discussed at https://github.com/hadley/devtools/issues/1332 but the link provided there (https://github.com/hadley/devtools/issues/426) did not address that problem, at least as far as I can see.

**Comment by hadley** [comment]
The error message suggests that you have devtools loaded already. I'd recommend trying again in a fresh R session.
