### ISSUE TITLE
print version of package in console output while testing with revdep_check

### ISSUE THREAD

**Issue by helix123** [hadley/devtools#1480]
Can we have the version number in the console output of `revdep_check()` as well? It is in the results (e.g. README.md, problems.md).

I mean this output (example):
```
Checking packages ---------------------------------------------
Checked AER         : 0 errors | 0 warnings | 1 note 
Checked bdynsys     : 0 errors | 0 warnings | 1 note
[....]
```

**Comment by hadley** [comment]
`revdep_check()` will be deprecated shortly, in favour of the vastly superior [revdepcheck](http://github.com/r-lib/revdepcheck) package
