### ISSUE TITLE
our package has a generated DESCRIPTION

### ISSUE THREAD

**Issue by jpritikin** [hadley/devtools#1483]
In OpenMx, `DESCRIPTION` is generated by the build process from `DESCRIPTION.in`. How do you recommend we use devtools in this situation? For example, install_github fails,

```
> install_github("OpenMx/OpenMx", ref="stable", dependencies=FALSE)
Downloading GitHub repo OpenMx/OpenMx@stable
from URL https://api.github.com/repos/OpenMx/OpenMx/zipball/stable
Error: Does not appear to be an R package (no DESCRIPTION)
```

**Comment by jimhester** [comment]
Devtools expects a valid DESCRIPTION file, I think you will have to generate it at least once outside the build process in order to use devtools.

**Comment by jpritikin** [comment]
Can't we ask devtools to look at DESCRIPTION.in? The only differences are:

```
Date: @DATE@
Version: @VERSION@
```

It doesn't need the date and version, does it?
