### ISSUE TITLE
Feature Request: Find Minimum Version of Required Packages

### ISSUE THREAD

**Issue by billdenney** [hadley/devtools#1484]
I've recently experienced an issue with my PKNCA package where I didn't know that a new feature I added had a minimum required version of a package in the Imports list.  I'd like to propose a new feature of devtools that will take a list of packages and install them to look for the version number of dependencies where tests fail.  It would then indicate that the next version is the required version.

A potential interface could be:
```r
find_required_dep_version(pkg=".", which_set=c("Depends", "Imports", "Suggests"), which_library, repo=getOption("repos"), ...)
```

It would then search on CRAN (or potentially other repository types) installing dependency packages one-by-one back in time until tests fail.

If this would be of interest, I can generate a pull request.

**Comment by hadley** [comment]
This is useful but out of scope for devtools, especially as we are moving to a bunch of smaller packages (i.e. devtools will become more like the tidyverse package - it will aggregate together tools from a bunch of other packages).
