### ISSUE TITLE
Wish: build() should exclude git-ignored files

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1487]
Perhaps this is easiest to achieve with a fresh clone to a temporary directory:

```sh
git clone . $tempdir
R CMD build $tempdir
```

Rationale: By now I often have a considerable number of files and directories in `.git/inst/exclude`, such as IDE files, a package-local library (à la packrat), etc.. It's difficult to add these files to `.Rbuildignore` without committing them to the repository. On the other hand, I usually `build()` only for a CRAN release, and then I want a build from a clean state, just like on Travis.

**Comment by jimhester** [comment]
I would find this useful as well, but I don't think we can assume users are using git when they run build, or that all changes have been committed to the repo. I think this is best done as a wrapper function `build_clean()`? that does a shallow clone into a temporary directory and then calls `build()` as normal.

**Comment by gaborcsardi** [comment]
IMO, we should not do this, there is already an easy solution: `.Rbuildignore`.

**Comment by krlmlr** [comment]
Yeah, a new `git2r::with_clean_clone()` would achieve roughly the same. We might consider a facility that warns about vcs-ignored files that are not .Rbuildignore-d, because that is usually a mistake (but not always).
