### ISSUE TITLE
install_packages_unless_installed appropriate here?

### ISSUE THREAD

**Issue by earino** [hadley/devtools#1488]
I constantly find myself wanting to "install this package unless it's already installed." Would this be the right package to submit a PR for with something like the following function:

```
install_packages_unless_installed <- function(pkgs, ...) {
  installed_packages <- rownames(installed.packages())
  packages_to_install <- pkgs[! pkgs %in% installed_packages]

  install.packages(packages_to_install, ...)
}
```

**Comment by jimhester** [comment]
You can get this behavior by calling `devtools::install_cran()`, which will only install packages from CRAN if they are a newer version than the currently installed version.

**Comment by earino** [comment]
@jimhester perfect! Thank you!
