### ISSUE TITLE
install_github fails

### ISSUE THREAD

**Issue by blosloos** [hadley/devtools#1499]
Dear devtools developer(s)

Using the install_github("...") with recently released R v3.4.0 leads to the following error (or similar, translated):

```
"Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : 
  Missing value, where TRUE/FALSE is expected"
```

Am runing on Win10, 64bit, Rtools 3.4. Any ideas? (In addition, I have repeatedly faced problems for the dependency packages (to be taken from CRAN) when using the command - as a side-note). Thank you!

**Comment by jimhester** [comment]
This is an regression in R actually and was fixed in R-patched available at (https://stat.ethz.ch/R/daily/), see also the [R-patched release notes](https://cloud.r-project.org/doc/manuals/r-devel/NEWS.html).

> file.mtime() no longer returns NA on Windows when the file or directory is being used by another process.

**Comment by blosloos** [comment]
Ok! Wow, thanks for your speedy reply on labour's day!
