### ISSUE TITLE
install_version() not working (perhaps only on Windows?)

### ISSUE THREAD

**Issue by daattali** [hadley/devtools#1504]
On Windows 7, I can't seem to install any package with `install_version()`. For example:

```
devtools::install_version(package = "ggplot2", version = "2.1.0")
```

Results in

```
Trying https://cran.rstudio.com/
Trying http://www.stats.ox.ac.uk/pub/RWin
Downloading package from url: https://cran.rstudio.com//src/contrib/Archive/ggplot2/ggplot2_2.1.0.tar.gz
/usr/bin/tar: Cannot connect to C: resolve failed
Installation failed: Does not appear to be an R package (no DESCRIPTION)
Warning messages:
1: running command 'tar.exe -xf "C:\Users\Dean\AppData\Local\Temp\RtmpOyB7ak\file9e4c71cb646b.tar.gz" -C "C:/Users/Dean/AppData/Local/Temp/RtmpOyB7ak/devtools9e4c62ab2155"' had status 128 
2: In utils::untar(src, exdir = target, compressed = "gzip") :
  ‘tar.exe -xf "C:\Users\Dean\AppData\Local\Temp\RtmpOyB7ak\file9e4c71cb646b.tar.gz" -C "C:/Users/Dean/AppData/Local/Temp/RtmpOyB7ak/devtools9e4c62ab2155"’ returned error code 128
3: running command 'tar.exe -tf "C:\Users\Dean\AppData\Local\Temp\RtmpOyB7ak\file9e4c71cb646b.tar.gz"' had status 128
```

The same happens when I specifically set the repo, or when I try other packages and other versions.

I get this error with both devtools 1.12 and 1.13

I notice it's trying to call `/usr/bin/tar` so perhaps that's the problem?

I can install fine using github branch/release.

**Comment by jimhester** [comment]
Not sure, I would check your `%PATH%`, it looks like there is more than one version of tar on it?

**Comment by daattali** [comment]
You're right, I have a tar under C:\Program Files\Git\usr\bin as well as
under Rtools/bin

I placed Rtools above git in my PATH and that fixed this error (didn't know
that order mattered)

Although now when I try to install 2.2.1 I get

trying URL 'https://cran.rstudio.com/src/contrib/ggplot2_2.2.1.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/src/contrib/ggplot2_2.2.1.zip'

So it looks like it's not going to the correct URL when using the current
version. Don't want to open another issue in case it's again a problem on
my end

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by gaborcsardi** [comment]
Actually, is there any reason not to use the internal `tar` implementation? Is it slow?

**Comment by jennybc** [comment]
> I placed Rtools above git in my PATH and that fixed this error (didn't know that order mattered)

I'm surprised you don't have PTSD from this re: STAT 545!

**Comment by daattali** [comment]
I guess my way of dealing is by "blocking" :)  I don't think this specific issue of the order within your PATH was ever encountered at UBC? If it was, it really is a repressed memory...

**Comment by hadley** [comment]
@gaborcsardi I have a vague memory of buggyness, but maybe that's fixed now.

This should move to remotes, right?

**Comment by gaborcsardi** [comment]
Yes, remotes. We'll need to look/ask around about problems with the internal implementation. It would be great if we could just use that.
