### ISSUE TITLE
devtools version 1.13.1

### ISSUE THREAD

**Issue by mdavy86** [hadley/devtools#1507]
Usually I would bootstrap install the Github version of devtools, but I have just noticed that the master branch version is currently [1.12.0.9000](https://github.com/hadley/devtools/blame/master/DESCRIPTION#L3), and a release branch [1.13.0](https://github.com/hadley/devtools/releases/tag/v1.13.0) 
is now available.

However on CRAN the latest version is currently [1.13.1](http://cran.stat.auckland.ac.nz/web/packages/devtools/index.html)

This might create some confusion as people can currently only see the release version 
[1.13.0](https://github.com/hadley/devtools/releases/tag/v1.13.0) in Github.

**Comment by jimhester** [comment]
I just added a GitHub release https://github.com/hadley/devtools/releases/tag/v1.13.1 and bumped the master version to 1.13.1.9000

**Comment by mdavy86** [comment]
thanks for that.
