### ISSUE TITLE
SHA1 check false positives with multiple libraries

### ISSUE THREAD

**Issue by jeroen** [hadley/devtools#1509]
When `install_github` checks the SHA1 to see if a package actually needs to be updated, it should only check in the library where the package is about to be installed.

Currently it gives a false positive when you try to install a package in a given library, but the package is already available from another library. For example:

```r
devtools::install_github('rwebapps/gitstats')
# Installing gitstats
# ...
# * DONE (gitstats)

my_private_lib <- tempdir()
withr::with_libpaths(my_private_lib, devtools::install_github('rwebapps/gitstats'))
# Skipping install of 'gitstats' from a github remote, the SHA1 (fc578831) has not changed since last install.
#  Use `force = TRUE` to force installation

library("gitstats", lib.loc = my_private_lib)
# Error in library("gitstats", lib.loc = my_private_lib) : 
#  there is no package called ‘gitstats’
```

Not sure if this intended but it is dangerous. When working with many libraries (such as packrat) you want to assume that installing a package in a given library will indeed install or update the package in that library to the latest version. The fact that the package was also available from another lib during installation shouldn't matter.

**Comment by jimhester** [comment]
Yes that makes sense. 

A simple fix could be

```diff
diff --git a/R/install-remote.R b/R/install-remote.R
index c55981a..42ede9c 100644
--- a/R/install-remote.R
+++ b/R/install-remote.R
@@ -149,7 +149,7 @@ remote_sha <- function(remote, ...) UseMethod("remote_sha")

 package2remote <- function(name, repos = getOption("repos"), type = getOption("pkgType")) {

-  x <- tryCatch(packageDescription(name, lib.loc = .libPaths()), error = function(e) NA, warning = function(e) NA)
+  x <- tryCatch(packageDescription(name, lib.loc = .libPaths()[[1]]), error = function(e) NA, warning = function(e) NA)

   # will be NA if not installed
   if (identical(x, NA)) {
```

My only question is if there is any case R will not install to the first directory in `.libPaths()`. I believe not, `install.packages()` fails if the library is not writable...

**Comment by jeroen** [comment]
@jimhester I think this solution will suffice. You could pass down the `lib` arg to `install.packages()` but maybe that's not needed.

lgtm, let's merge :D (this one has really been bugging me :)

**Comment by jimhester** [comment]
I have actually changed my mind about this, I don't think only looking at the first library is appropriate in many cases. If you want this behavior I would wrap your installation command in something like this instead to temporarily set libPaths as desired.

```r
withr::with_libpaths(.libPaths()[[1]], {
  install_xyz()
})
```
