### ISSUE TITLE
Code coverage does not run on appveyor

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/devtools#1510]
See https://github.com/hadley/devtools/blob/ad6f28ef9de6a02e1ea300af45d34deccc40bd2f/appveyor.yml#L29

Here 
```
on_success:
  - Rscript -e 'covr::codecov()'
```
should be double quoted or not quoted at all, because the quotes are passed to Rscript as well, and it just prints `'covr::codecov()'` as a string:
https://ci.appveyor.com/project/hadley/devtools/build/1.0.855#L391
See line 391:
```
Rscript -e 'covr::codecov()'
[1] "covr::codecov()"
```

I don't remember if you need a token to upload the results, or codecov an appveyor are integrated.

**Comment by jimhester** [comment]
They should be integrated, but if it doesn't work I will add the token manually

**Comment by gaborcsardi** [comment]
The codecov website claims that they are integrated, but it still does not work me.....

**Comment by schifferl** [comment]
@jimhester thank you for the excellent work that you have done with Travis CI, AppVeyor, and Codecov

I can confirm that both of the points brought up by @gaborcsardi are still issues.

See my YAML files here https://github.com/schifferl/devtoo

See the single quotes issue at line 324 https://ci.appveyor.com/project/schifferl/devtoo/build/1.0.3#L324

Then see the missing integration at line 259 https://ci.appveyor.com/project/schifferl/devtoo/build/1.0.4#L259

I will just fix with the token but wanted to confirm the behavior

**Comment by schifferl** [comment]
I suppose it is somewhat of a moot point because Codecov will just merge matrix builds into a single report. https://codecov.io/pricing

> How does Codecov combine matrix builds and multiple CI providers?

> Effortlessly. Codecov merges builds into a single report while maintaining the original source of the coverage data. Send as many uploads from different CI providers and languages to Codecov. Plug-and-Play! See a fine example here pyca/cryptography .
