### ISSUE TITLE
release() should call document()

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1516]
before checking that all files are committed to Git. (Sorry if this has been suggested before.)

**Comment by jimhester** [comment]
It already implicitly calls document when it runs the package check, because the default is `document = TRUE`. It is true this is after the Git checks.

**Comment by hadley** [comment]
I think we'll probably totally rethink the `release()` function in the near future. I don't use it any more since it just seems to cause me more hassle than it saves.

**Comment by krlmlr** [comment]
I don't even remember how to manually upload a package to CRAN ;-) Would be interested to understand the hassle it's causing to you.

**Comment by hadley** [comment]
I don't know exactly - it's just some additional friction so I've basically switch to just using `submit_cran()`. I think it's probably just because my workflow has drifted a bit and so the questions aren't quite right.
