### ISSUE TITLE
Wrong width calculation in the pre-release spell check

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1517]
From tibble:

```
df           as_tibble.Rd:51, tibble-package.Rd:8, description:1
Kirill       tibble-package.Rd:65
Müller      tibble-package.Rd:65
RStudio      tibble-package.Rd:75
```

**Comment by hadley** [comment]
@jeroen can you please take a look? I think this is your code

**Comment by jeroen** [comment]
This is a bug in `sprintf()` word lit seems?

```r
cat(sprintf("| %-10s|", c("df", "Kirill", "Müller", "RStudio")), sep = "\n")
```
```
| df        |
| Kirill    |
| Müller   |
| RStudio   |
```

**Comment by hadley** [comment]
Yeah, looks like it. Anyone want to push to R-devel / bugzilla?

**Comment by jeroen** [comment]
I think they will just say that it's working as intended. C level sprintf simply looks at the number of bytes in the string. It doesn't take into account multibyte characters. Maybe stringi has something smarter.
