### ISSUE TITLE
Don't include badges in README when preparing tarball for CRAN submission

### ISSUE THREAD

**Issue by fmichonneau** [hadley/devtools#1518]
It seems that the README.md that gets uploaded on CRAN shouldn't include the badges that show code coverage, build status, etc.

These badges are obviously very useful when seen on GitHub, but they don't make sense when viewed on CRAN (or locally). Arguably, a lot less people read the README from CRAN than GitHub.

For instance, the repository might move (e.g., the links included in the README for dplyr 0.5.0 point to https://travis-ci.org/hadley/dplyr and https://codecov.io/github/hadley/dplyr?branch=master which are broken as the corresponding github repo has moved to tidyverse/dplyr) or the badges show the coverage/build status of the development version and not the version currently hosted on CRAN.

I am not sure what would be a reasonable technical solution to this, but it seems that devtools would be a natural place to handle it.

**Comment by MarkEdmondson1234** [comment]
Relevant, I just had a package fail CRAN submission as the codecover badge was incorrect. https://github.com/hadley/devtools/issues/1528

**Comment by hadley** [comment]
I think this out of scope for devtools - I think it's good to include the badges, although we may need to think about how to make clear they're apply to the dev version.
