### ISSUE TITLE
BUG: parse_check_results() fails to pick statuses when R CMD check reports on timings

### ISSUE THREAD

**Issue by HenrikBengtsson** [hadley/devtools#1519]
When forcing `R CMD check` to report on process times ("timings") for all tests;
```sh
export _R_CHECK_TIMINGS_=0
```
`devtools::revdep_check()` fails to detect ERRORs, WARNINGs, and NOTEs.

For example, I observe:

```
Checked doFuture            : 0 errors | 0 warnings | 0 notes
Checked fiery               : 0 errors | 0 warnings | 0 notes
Checked future.BatchJobs    : 0 errors | 0 warnings | 0 notes
```

although fiery's `00check.log` file contains:

```r
* checking tests ... [1s/11s] ERROR
  Running ‘testthat.R’ [1s/11s]
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  5: lazy(expr = {
         message("test")
         10
     })
  6: .Defunct(msg = "Future strategy 'lazy' is deprecated. Instead, use f <- futur
e(..., lazy = TRUE) or v %<-% { ... } %lazy% TRUE.")
  7: stop(paste(msg, collapse = ""), call. = FALSE, domain = NA)
  
  testthat results ===============================================================
=
  OK: 152 SKIPPED: 0 FAILED: 3
  1. Error: futures can be added and called (@test-Fire.R#214) 
  2. Error: DelayStack works (@test-FutureStack.R#7) 
  3. Error: TimeStack works (@test-FutureStack.R#34) 
  
  Error: testthat unit tests failed
  Execution halted
* DONE
Status: 1 ERROR
```

# Troubleshooting

The reason for this is that [devtools:::parse_check_results()](https://github.com/hadley/devtools/blob/master/R/check-results.R#L12-L14) (master branch, but also in 1.13.1) assumes that `R CMD check` does not report on timings because it looks for fixed string patterns:
```r
      errors =   pieces[grepl("... ERROR", pieces, fixed = TRUE)],
      warnings = pieces[grepl("... WARN", pieces, fixed = TRUE)],
      notes =    pieces[grepl("... NOTE", pieces, fixed = TRUE)]
```
but those won't pick up `... [1s/11s] ERROR`.

When one don't do `export _R_CHECK_TIMINGS_=0`, then it works;
```r
Checked doFuture            : 0 errors | 0 warnings | 0 notes
Checked fiery               : 1 error  | 0 warnings | 0 notes
Checked future.BatchJobs    : 1 error  | 0 warnings | 0 notes
```

# Solution
Need to use a regular expression instead.

H/T @jimhester

**Comment by hadley** [comment]
[revdepcheck](http://github.com/r-lib/revdepcheck/issues) is vastly superior to `devtools::revdep_check()`. I highly suggest you switch - we'll be deprecating `revdep_check()` v. soon.

**Comment by HenrikBengtsson** [comment]
Just for my clarification, that was a 'wontfix' correct?

**Comment by hadley** [comment]
We won't fix it in devtools. If it's still a problem we might consider fixing in revdepcheck.
