### ISSUE TITLE
Placing "Remotes" somewhere other than DESCRIPTION?

### ISSUE THREAD

**Issue by talgalili** [hadley/devtools#1521]
Based on this:
https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html
I added a Remotes field to a DESCRIPTION file of a package, which then got rejected by CRAN due to:
"
Unknown, possibly mis-spelled, fields in DESCRIPTION:
  'Remotes'
"

Is there another location where this can be placed, so it would still be accepted by CRAN, but would work when installing it through install_github?

**Comment by gaborcsardi** [comment]
You need to remove it before cran submission. 

It is not supposed to be there in a CRAN package.

**Comment by talgalili** [comment]
Thanks @gaborcsardi (I found that out today :) )

1. Maybe it should be made clearer in the vignette.
2. I do think it might be helpful to have a place to put it so that it could be also pushed to CRAN without extra hassle.

**Comment by jimhester** [comment]
This is actually a feature, if your package is using Remotes it is depending on development packages which aren't going to be available on CRAN. `devtools::release()` warns about this as well as R CMD check, both of which should be used before submitting to CRAN. See http://r-pkgs.had.co.nz/release.html#release-check for some suggestions on the process you should use to catch this type of error before it is submitted to CRAN

**Comment by talgalili** [comment]
Hi Jim, thanks for the explanation.
Would it be helpful if I would try to a PR with some of the text written here into the vignette? I believe there would be value in clarifying it a bit more for people who would read it in the future.

**Comment by jennybc** [comment]
This is in the CRAN submission section at the end of the vignette.

> When you submit your package to CRAN, all of its dependencies must also be available on CRAN. For this reason, release() will warn you if you try to release a package with a Remotes field.

**Comment by talgalili** [comment]
Yes, I read that - but it wasn't clear to me enough.
For example, if I include ggplot2, that package is already on CRAN - so by that logic it should have been fine. I think an alternative way to write this would be:

"
CRAN does not support the "Remotes" field. When submitting your package to CRAN, the "Remotes" field should first be removed from the DESCRIPTION file. This is because all of the package dependencies must also be available on CRAN. For this reason, release() will warn you if you try to release a package with a Remotes field.
"

What do you think?
