### ISSUE TITLE
Package S4 methods are sometimes not dispatched when using `load_all`

### ISSUE THREAD

**Issue by jonkeane** [hadley/devtools#1522]
I'm working on development of a few packages and we are using a number of S4 classes and methods. When using devtools' `load_all()` I've noticed that sometimes custom methods aren't being dispatched.

Here is a minimal example (I'm trying to write a new method for `write.csv`, and have that method pass all of it's arguments to another function, hence my use here.)
A package with the following in `./R/[anyfile].R`:
```
new_class <- setClass("new_class", slots = c(text = 'character'))
setGeneric("write.csv")
setMethod("write.csv", "new_class", function (...)  print("using new_class method") )
```
When loaded with `load_all()` and trying to run the following:
```
new_obj <- new_class(text = 'foo')
write.csv(new_obj, file = 'bar')
```
Errors with (presumably because the standard `write.csv` method is being used):
```
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class "structure("new_class", package = "test")" to a data.frame
```

Whereas, if I (install and) load the package with `install()` and run the same lines, I get what I expect:
```
new_obj <- new_class(text = 'foo')
write.csv(new_obj, file = 'bar')
[1] "using new_class method"
```

If I _only_ provide `new_obj` and no other arguments my custom method is dispatched with both `load_all()` and `install()`, but I would like to be able to pass on arbitrary arguments with my custom method.
```
write.csv(new_obj)
[1] "using new_class method"
```

Because devtools' `test()` uses `load_all()`, I'm also seeing this behavior when I run tests through devtools as well. Running tests as part of `R CMD check` use the custom method just like if the package were installed / loaded with `install()`.

**Comment by hadley** [comment]
Can you please create a minimal package that illustrates this package and then create a reprex using the reprex package?
