### ISSUE TITLE
Download datadet during installation procedure

### ISSUE THREAD

**Issue by Jadamso** [hadley/devtools#1525]
Hello, 

I would like to host my R package on github. But I have designed the package to include one file that is large (4GB) and this prevents me from hosting on github. However, if there is a way for me to execute a script during install, then this would be an adequate workaround. Currently, I  `devtools::use_data() ` to include the data, but the script would grab the data from online and shape it and save it into the same file. 

Do you know how this can be done?

**Comment by gaborcsardi** [comment]
All R code in the package runs at install time.

An alternative is to download the large file at run time, and then put it in an appropriate directory.
