### ISSUE TITLE
devtools::test() hangs with unit test involving parallel calculation

### ISSUE THREAD

**Issue by mjpnijmeijer** [hadley/devtools#1526]
Hello,
I experience that `devtools::check()` 'hangs' (it never returns, neither does it use any CPU) when there is a unit-test as follows:
```R 
test_that("hangs check", {
     expect_error( my_function(my_arguments), NA) 
  })
 ```
where `my_function(my_arguments)`  does a parallel calculation using the package 'parallel'. The unit test passes `devtools::test()`. 

Sorry if this is my mistake, but I thought it might be worthwhile to mention it.

**Comment by gaborcsardi** [comment]
Can you please provide a reproducible example?

**Comment by mjpnijmeijer** [comment]
I build the package (in which I kept the offending unit test as the only one). I am not sure if that allows you to reproduce the issue. If not, please let me know.

[lmvar_1.2.1.900.tar.gz](https://github.com/hadley/devtools/files/1081427/lmvar_1.2.1.900.tar.gz)

**Comment by gaborcsardi** [comment]
This is the infamous `R_TESTS` catch. Put this at the beginning of your test file:

```
Sys.unsetenv("R_TESTS")
```

**Comment by gaborcsardi** [comment]
Also, the `create_...` file should be a helper file, move it to `tests/testthat/helper.R` and then it is automatically loaded before the tests.

**Comment by mjpnijmeijer** [comment]
Thank you. Removing the `R_TESTS` variable indeed solves the issue. If there is some info available about this variable / issue, I'll go through it. I searched the internet but nothing much turned up.

I also did not know about the helper file. Nice!

**Comment by gaborcsardi** [comment]
See this thread: https://stat.ethz.ch/pipermail/r-package-devel/2017q1/001313.html

Can you please close this issue? Thanks.
