### ISSUE TITLE
Incorrect codecov badge generated by devtools::use_coverage()

### ISSUE THREAD

**Issue by MarkEdmondson1234** [hadley/devtools#1528]
It seems the syntax has changed for the badge, and when I tried to submit to CRAN with the old style I got a warning that the old badge URL was invalid. 

```r
> devtools::use_coverage()
* Adding covr to Suggests
Next:
Overwrite `codecov.yml`?
1: Uhhhh... Maybe?
2: Yes
3: I forget

Selection: 2
* Creating `codecov.yml` from template.
* Adding `codecov.yml` to `.Rbuildignore`.
* Add to `README.md`: 
[![Coverage Status](https://img.shields.io/codecov/c/github/MarkEdmondson1234/googleAnalyticsR/master.svg)](https://codecov.io/github/MarkEdmondson1234/googleAnalyticsR?branch=master)
* Add to `.travis.yml`:
after_success:
  - Rscript -e 'covr::codecov()'
```

...yet the badge settings when visiting https://codecov.io/gh/MarkEdmondson1234/googleAnalyticsR/settings/badge are:

```
[![codecov](https://codecov.io/gh/MarkEdmondson1234/googleAnalyticsR/branch/master/graph/badge.svg)](https://codecov.io/gh/MarkEdmondson1234/googleAnalyticsR)
```

**Comment by jimhester** [comment]
This is a bug in the pandoc version that CRAN is using, in particular the pandoc dependency `tls` https://github.com/vincenthz/hs-tls/issues/152. It is _not_ an error in shields.io, but a bug in validating the (actually valid) ssl certificate from shields.io.

You can work around the issue by using the badge from `codecov.io`, which uses a different encryption method that does not uncover this bug, as you mentioned.

**Comment by hadley** [comment]
Closed in favour of https://github.com/r-lib/usethis/issues/36
