### ISSUE TITLE
load_all fails with package including a DLL

### ISSUE THREAD

**Issue by stla** [hadley/devtools#1529]
Hello, 

 I have a package with a DLL in `inst/libs`. It works very well. I did some `testthat` tests which work when I run them in the console. But `devtools::test()` generates an error because of `load_all`:
```
> devtools:::load_all(".")
Loading hwriteXLSX
Error in library.dynam("json2xlsx", pkgname, libname) : 
  DLL ‘json2xlsx’ not found: maybe not installed for this architecture?
Called from: library.dynam("json2xlsx", pkgname, libname)
```

**Comment by hadley** [comment]
It's hard to know what the problem is without more context. devtools certainly works fine with dlls.

**Comment by stla** [comment]
My package is here: <https://github.com/stla/hwriteXLSX> but I don't upload the DLL"s on Github. Do you see any problem with the architecture? The package works fine. 
I can create a package with a small DLL if needed.

**Comment by stla** [comment]
Mmmh sorry, since I don't upload the DLL you cannot see the architecture.  I put the DLLs in `inst/libs` like this:
```
inst
||
+- libs
|  |
|  +- x64
|  |  |
|  |  `- json2xlsx.dll
|  |
|  +- json2xlsx.so
|  |
|  `- i386
|     |
|     `- json2xlsx.dll

```

**Comment by hadley** [comment]
Oh, you're just copying in DLLs from elsewhere. It's possible that devtools has never been tested for that use case.  

It looks like the error is coming from your call to `library.dynam()` which obviously can't find the DLL because the package isn't installed. I think you'll need to call `dyn.load()` instead.

**Comment by jimhester** [comment]
We _could_ add a shim for `library.dynam()`. We have one for `library.dynam.unload()` but not for `library.dynam()` https://github.com/r-lib/pkgload/blob/793c8245dac9c6b260470a160b53c87364a786f0/R/shims.r#L102
