### ISSUE TITLE
install_deps issue on R-devel OSX

### ISSUE THREAD

**Issue by colearendt** [hadley/devtools#1530]
Hello,

I am using Travis CI to test the `xlsx` package on OSX with R-devel.  The build has been successful on all combinations of OS / versions of R except (OSX, R-devel).  The failing step seems to be related to `devtools::install_deps`, which seems to somehow be missing and not installing the packages that are currently in `Depends`.  

Both packages are available from CRAN (`rJava` and `xlsxjars`) and again, the build is successful elsewhere (even R-devel on UNIX), which suggests to me that this is something perhaps to be addressed in the new version of R on OSX.

Not sure how to be of any assistance with this other than providing the [log](https://travis-ci.org/colearendt/xlsx/jobs/244847216):

and the failing step:
```
[0K$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'

missing: rJava, xlsxjars
```

**Comment by hadley** [comment]
@jimhester can you please have a look at this travis issue?

**Comment by jimhester** [comment]
The build log doesn't provide any clues unfortunately, but this may be due to you running `[R CMD javareconf](https://github.com/colearendt/xlsx/blob/master/.travis.yml#L25)` on MacOS, try removing that and see if the build passes.

**Comment by colearendt** [comment]
Same issue after removing `R CMD javareconf`.  

```
$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
missing: rJava, xlsxjars

The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
```

Is there any way to add additional verbosity to the log that would be helpful?  Or a way to test this out locally?  I am happy to contribute, but am ignorant of how to test these sorts of builds locally.  If this is an issue with `devtools`, I would love to figure it out before the next R release.

Config on [most recent build](https://travis-ci.org/colearendt/xlsx/jobs/260979266/config):
```
{
  "language": "r",
  "os": "osx",
  "sudo": true,
  "cache": "packages",
  "r": "devel",
  "before_script": [
    "java -version",
    "echo PATH=$PATH",
    "echo JAVA_HOME=$JAVA_HOME"
  ],
  "after_success": [
    "Rscript -e 'covr::codecov()'"
  ]
}

```

**Comment by jimhester** [comment]
Try just using a install block for those dependencies explicitly and remove devtools out of the equation entirely.

```yaml
install: 
  - R -e 'install.packages(c("rJava", "xlsxjars"))'
```

**Comment by colearendt** [comment]
The install block (required _all_ dependencies) was a successful workaround for the devtools issue.  I am out of ideas for what might be the root issue, as it does not look like devtools even tries to install the packages before failing.  I also tried moving the packages from `Depends` to `Imports`, unfortunately to no avail.  Not sure if there is something about these dependencies in particular that is a problem.  Perhaps it would be worth building a test package that allows more easily declaring various dependencies to see where the root cause is.  Is this concerning in any regard from a devtools perspective; enough to warrant re-opening?  Might it be something related to building from source or the version of R that packages are built with on CRAN?  (i.e. if it does not look like the packages are on CRAN because it is running on R 3.5?)

It is definitely less than ideal to have to maintain a list of all dependencies in DESCRIPTION, as well as in .travis.yml, when devtools works great on all other OS / version combinations.

**Comment by colearendt** [comment]
@jimhester I am fairly concerned this might be a devtools bug that is worth re-opening.  I created a [basic package](https://github.com/colearendt/testtravis) with RStudio, and the build on osx with R 3.5 is failing with the same problems.  I tested [`rJava`](https://travis-ci.org/colearendt/testtravis/builds/261580287) by itself, as well as [`dplyr`](https://travis-ci.org/colearendt/testtravis/builds/261586026) by itself.  Both failed with the same error message, suggesting that the packages are not the problem.

It seems that for some reason, devtools is not installing dependencies appropriately on osx / R 3.5.  The hope is that this would only be due to it being a "devel" release at present and perhaps something about how CRAN is built, but it might be worth doing some deeper digging to be sure.  I am unsure of the best way to do so or what next steps might be beneficial.

**Comment by colearendt** [comment]
Related to #1370, perhaps, although this problem is only on OSX and the devel version of R, so not sure whether there is any relationship.

**Comment by colearendt** [comment]
@hadley @jimhester I think this ought to be reopened and addressed, as it suggests a universal problem with `devtools` properly installing dependencies on devel / OSX.  I would think it is preferable to resolve the issue before R 3.5 is released.  (Again - build failure with a dependency only on [`dplyr`](https://travis-ci.org/colearendt/testtravis/builds/261586026))

**Comment by colearendt** [comment]
More OSX R-devel [build failures](https://travis-ci.org/colearendt/tidyjson/jobs/266404031) on otherwise good builds... not sure if this is related or not.  Maybe R-devel is having problems on OSX and `devtools` just did not handle it nicely... (or handled it too nicely to give a nice warning / error)

```
curl -fLo /tmp/R.pkg https://r.research.att.com/mavericks/R-devel/R-devel-mavericks-signed.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
The command "eval curl -fLo /tmp/R.pkg https://r.research.att.com/mavericks/R-devel/R-devel-mavericks-signed.pkg " failed. Retrying, 2 of 3.
```

Confirmed that the same failure occurred on my previous test (fail is on R install now, before `devtools` goes to work).  Here is to hoping that R-3.5 is the problem and not `devtools`!
