### ISSUE TITLE
Cannot initialize KerasR due to import failure

### ISSUE THREAD

**Issue by uevencodebro** [hadley/devtools#1533]
I am using Windows 7 64-bit and I've installed the various tensorflow, keras, numpy_mkl, and scipy packages on my machine and they work fine in Python, and now I've got a new situation I haven't seen in the forums: py_module available evaluates to TRUE for tensorflow, keras, numpy, and scipy, but I can't run library(kerasR). I see this: 
"Error: package or namespace load failed for ‘kerasR’:
 .onLoad failed in loadNamespace() for 'kerasR', details:
  call: py_module_import(module, convert = convert)
  error: ImportError: cannot import name '_ellipsoid"

And a few other callbacks after that. So, I've got everything now, but it just won't load. I tried the development version from github, but it doesn't install (says python isn't available even though I ran reticulate::use_python to set the right version).

**Comment by akumaraug** [comment]
The same issue i have find.

**Comment by hadley** [comment]
I'm not sure why you've filed this issue here. I think you want https://github.com/rstudio/reticulate
