### ISSUE TITLE
[security problem] You can't automatically download projects from github securetly without checking the cryptographic hash

### ISSUE THREAD

**Issue by yurivict** [hadley/devtools#1534]
Command like this:
```
devtools::install_github("hadley/devtools")
```
is vulnerable to a MITM attack. There is generally no guarantee that a particulate website isn't impersonated.

Instead, you need to download tarballs for particular package versions with mandatory hash that should be required by this command.

**Comment by gaborcsardi** [comment]
I believe `devtools::install_github` uses libcurl, which checks the certificate of github.com. github.com is HTTPS only AFAIK.
