### ISSUE TITLE
install_version quiet option doesn't do anything

### ISSUE THREAD

**Issue by deephoot** [hadley/devtools#1544]
The quiet option in install_version doesn't do anything because it isn't passed to any of the underlying install functions. 

Step to reproduce

```R
library(devtools)
devtools::install_version('glue', '1.1.1', quiet=TRUE)
# produces the same output as 
devtools::install_version('glue', '1.1.1', quiet=FALSE)
```

Have tested with change to `install-version.r` passing `quiet = quiet` to install functions and it suppresses output as expected.

**Comment by hadley** [comment]
This appears to be fixed in the remotes package, which devtools will soon switch to using.
