### ISSUE TITLE
update .gitignore in vignettes folder with `use_vignette()`?

### ISSUE THREAD

**Issue by kevinushey** [hadley/devtools#1547]
To ignore `.R` and `.html` files generated when knitting `.Rmd` documents.

(If this feels too aggressive, perhaps this would only be done if a `.gitignore` file in that directory did not already exist?)

**Comment by hadley** [comment]
What's the use case for this? knitting a vignette in order to preview it already happens in a temp dir.

(If you still think it's important, can you please refile with motivation at https://github.com/r-lib/usethis/issues/new)
