### ISSUE TITLE
cannot install package

### ISSUE THREAD

**Issue by TinkaMiau** [hadley/devtools#1548]
Hello everyone, I am quite new with R but want to install the package for my bachelor thesis. Unfortunately it always says:

```
install.packages("devtools")
Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES.rds': HTTP status was '404 Not Found'
Installing package into ‘C:/Users/t_kni/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘jsonlite’, ‘git2r’, ‘withr’

Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'

  There is a binary version available but the source version is later:
      binary source needs_compilation
git2r 0.18.0 0.19.0              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/jsonlite_1.5.zip'
Content type 'application/zip' length 1159835 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/git2r_0.18.0.zip'
Content type 'application/zip' length 3053025 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/withr_1.0.2.zip'
Content type 'application/zip' length 44348 bytes (43 KB)
downloaded 43 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/devtools_1.13.2.zip'
Content type 'application/zip' length 443150 bytes (432 KB)
downloaded 432 KB
```

What can I do?

Thank you

**Comment by jimhester** [comment]
Good news!

The warnings you show can be ignored, and devtools should have been installed, so there is nothing else you need to do, just start using devtools.

**Comment by TinkaMiau** [comment]
Unfortunately not. 
I also tried the german version to install it and it says after installing I should use "devtools::install_github("dcangst/batplotr",dependencies=TRUE)" but there the information "Error in loadNamespace(name) : es gibt kein Paket namens ‘devtools’" is given which means "there is no "devtools" package". I tried again to install it as following:

install.packages(c("devtools"),dependencies=TRUE)
Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES.rds': HTTP status was '404 Not Found'
Installing package into ‘C:/Users/t_kni/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependency ‘BiocInstaller’ is not available
also installing the dependencies ‘backports’, ‘lazyeval’, ‘irlba’, ‘pkgconfig’, ‘assertthat’, ‘BH’, ‘praise’, ‘magrittr’, ‘yaml’, ‘htmltools’, ‘caTools’, ‘base64enc’, ‘rprojroot’, ‘stringr’, ‘highr’, ‘markdown’, ‘rex’, ‘stringdist’, ‘igraph’, ‘stringi’, ‘brew’, ‘desc’, ‘commonmark’, ‘xml2’, ‘jsonlite’, ‘git2r’, ‘withr’, ‘crayon’, ‘testthat’, ‘Rcpp’, ‘rmarkdown’, ‘knitr’, ‘hunspell’, ‘lintr’, ‘bitops’, ‘roxygen2’, ‘evaluate’, ‘rversions’, ‘covr’, ‘gmailr’

Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/backports_1.1.0.zip'
Content type 'application/zip' length 32812 bytes (32 KB)
downloaded 32 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/lazyeval_0.2.0.zip'
Content type 'application/zip' length 140103 bytes (136 KB)
downloaded 136 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/irlba_2.2.1.zip'
Content type 'application/zip' length 263497 bytes (257 KB)
downloaded 257 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/pkgconfig_2.0.1.zip'
Content type 'application/zip' length 20030 bytes (19 KB)
downloaded 19 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/assertthat_0.2.0.zip'
Content type 'application/zip' length 43793 bytes (42 KB)
downloaded 42 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/BH_1.62.0-1.zip'
Content type 'application/zip' length 16150325 bytes (15.4 MB)
downloaded 15.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/praise_1.0.0.zip'
Content type 'application/zip' length 17957 bytes (17 KB)
downloaded 17 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/magrittr_1.5.zip'
Content type 'application/zip' length 155022 bytes (151 KB)
downloaded 151 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/yaml_2.1.14.zip'
Content type 'application/zip' length 179637 bytes (175 KB)
downloaded 175 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/htmltools_0.3.6.zip'
Content type 'application/zip' length 618631 bytes (604 KB)
downloaded 604 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/caTools_1.17.1.zip'
Content type 'application/zip' length 285771 bytes (279 KB)
downloaded 279 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/base64enc_0.1-3.zip'
Content type 'application/zip' length 39385 bytes (38 KB)
downloaded 38 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rprojroot_1.2.zip'
Content type 'application/zip' length 60673 bytes (59 KB)
downloaded 59 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringr_1.2.0.zip'
Content type 'application/zip' length 148102 bytes (144 KB)
downloaded 144 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/highr_0.6.zip'
Content type 'application/zip' length 36059 bytes (35 KB)
downloaded 35 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/markdown_0.8.zip'
Content type 'application/zip' length 168929 bytes (164 KB)
downloaded 164 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rex_1.1.1.zip'
Content type 'application/zip' length 88365 bytes (86 KB)
downloaded 86 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringdist_0.9.4.4.zip'
Content type 'application/zip' length 201966 bytes (197 KB)
downloaded 197 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/igraph_1.1.2.zip'
Content type 'application/zip' length 8250281 bytes (7.9 MB)
downloaded 7.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringi_1.1.5.zip'
Content type 'application/zip' length 14289534 bytes (13.6 MB)
downloaded 13.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/brew_1.0-6.zip'
Content type 'application/zip' length 104967 bytes (102 KB)
downloaded 102 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/desc_1.1.0.zip'
Content type 'application/zip' length 173196 bytes (169 KB)
downloaded 169 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/commonmark_1.2.zip'
Content type 'application/zip' length 251436 bytes (245 KB)
downloaded 245 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/xml2_1.1.1.zip'
Content type 'application/zip' length 3528889 bytes (3.4 MB)
downloaded 3.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/jsonlite_1.5.zip'
Content type 'application/zip' length 1159897 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/git2r_0.19.0.zip'
Content type 'application/zip' length 3027960 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/withr_1.0.2.zip'
Content type 'application/zip' length 44312 bytes (43 KB)
downloaded 43 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/crayon_1.3.2.zip'
Content type 'application/zip' length 705930 bytes (689 KB)
downloaded 689 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/testthat_1.0.2.zip'
Content type 'application/zip' length 1057262 bytes (1.0 MB)
downloaded 1.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rcpp_0.12.12.zip'
Content type 'application/zip' length 3319033 bytes (3.2 MB)
downloaded 3.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rmarkdown_1.6.zip'
Content type 'application/zip' length 2275638 bytes (2.2 MB)
downloaded 2.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/knitr_1.16.zip'
Content type 'application/zip' length 1026285 bytes (1002 KB)
downloaded 1002 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/hunspell_2.6.zip'
Content type 'application/zip' length 1808003 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/lintr_1.0.0.zip'
Content type 'application/zip' length 152090 bytes (148 KB)
downloaded 148 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/bitops_1.0-6.zip'
Content type 'application/zip' length 37218 bytes (36 KB)
downloaded 36 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/roxygen2_6.0.1.zip'
Content type 'application/zip' length 756939 bytes (739 KB)
downloaded 739 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/evaluate_0.10.1.zip'
Content type 'application/zip' length 48479 bytes (47 KB)
downloaded 47 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rversions_1.0.3.zip'
Content type 'application/zip' length 17110 bytes (16 KB)
downloaded 16 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/covr_3.0.0.zip'
Content type 'application/zip' length 118076 bytes (115 KB)
downloaded 115 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/gmailr_0.7.1.zip'
Content type 'application/zip' length 109971 bytes (107 KB)
downloaded 107 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/devtools_1.13.2.zip'
Content type 'application/zip' length 443150 bytes (432 KB)
downloaded 432 KB

package ‘backports’ successfully unpacked and MD5 sums checked
package ‘lazyeval’ successfully unpacked and MD5 sums checked
Error in install.packages : cannot open file 'C:/Users/t_kni/Documents/R/win-library/3.4/file38b0745a65/irlba/doc/irlba.pdf': Permission denied

I do not know what to do...

**Comment by samkart** [comment]
Hey, everything looks good with the download part. 
You can it again by starting it with admin privileges. The same thing happened to me. I found that the dll files were inaccessible due to improper permissions. 

I'm thinking it is relevant because `Error in install.packages : cannot open file 'C:/Users/t_kni/Documents/R/win-library/3.4/file38b0745a65/irlba/doc/irlba.pdf': Permission denied` has **Permission denied** in it.

**Comment by TinkaMiau** [comment]
thanks for your reply. I do have the admin privileges because I am the only user at that computer. :/
