### ISSUE TITLE
use_readme_rmd() not compatible with pkgdown::build_site()

### ISSUE THREAD

**Issue by mvuorre** [hadley/devtools#1549]
Say you've created a new package with R Studio (New Project -> R Package). If you then add a README.Rmd to it with `devtools::use_readme_rmd()`, `pkgdown::build_site()` fails with

```R
Updating README.md
Error in (function (variant = "markdown_strict", preserve_yaml = FALSE,  : 
  unused argument (html_preview = FALSE)
```

A [pkgdown issue](https://github.com/hadley/pkgdown/issues/286) was filed and closed with no fix except advising users to manually switch the README.Rmd YAML to

```R
output: rmarkdown::github_document
```

which fixes the problem and `pkgdown::build_site()` succeeds.

Although at core this is an issue with pkgdown requirements, there should be no reason to favor the incompatible devtools default YAML for README.Rmd. Could the default YAML be changed to the latter for automatic compatibility with pkgdown?

Thanks for the great software.

**Comment by hadley** [comment]
`use_readme_rmd()` now lives in usethis, which contains an up-to-date version: https://github.com/r-lib/usethis/blob/master/inst/templates/omni-README

We'll be updating devtools to use usethis v. shortly.
