### ISSUE TITLE
build_github_devtools() fails with 'Error: Command failed (127)'

### ISSUE THREAD

**Issue by alexilliamson** [hadley/devtools#1562]
Please see example below...

`
> library(devtools)
> build_github_devtools()
"//cityofno/cno-fs/UserData/Home2/abwilliamson/R/R-3.3.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD SHLIB foo.c 

Error: Command failed (127)
`

And when I try to update devtools, here is what happens:

`
> install.packages("devtools")
Installing package into ‘C:/Users/abwilliamson/Rpackages’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
         binary source needs_compilation
devtools 1.13.2 1.13.3             FALSE

installing the source package ‘devtools’

trying URL 'http://cran.rstudio.com/src/contrib/devtools_1.13.3.tar.gz'
Content type 'application/x-gzip' length 486402 bytes (475 KB)
downloaded 475 KB

Warning in install.packages :
  running command '"//cityofno/cno-fs/UserData/Home2/abwilliamson/R/R-3.3.3/bin/x64/R" CMD INSTALL -l "C:\Users\abwilliamson\Rpackages" C:\Users\ABWILL~1\AppData\Local\Temp\RtmpM3XUwz/downloaded_packages/devtools_1.13.3.tar.gz' had status 127
Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\abwilliamson\AppData\Local\Temp\RtmpM3XUwz\downloaded_packages’
`

Any ideas about how I can resolve?  Thanks immensely

**Comment by jimhester** [comment]
`build_github_devtools()` is no longer needed, if you want to update devtools to the latest CRAN release just use `update.packages("devtools")` or `install.packages("devtools")`.

It looks to me like having R installed on a NFS is causing problems, are you able to install other packages successfully?

**Comment by alexilliamson** [comment]
Yes installing other packages works fine.  Here is what happens when I try to install from CRAN:

`
install.packages("devtools")
Installing package into ‘C:/Users/abwilliamson/Rpackages’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
         binary source needs_compilation
devtools 1.13.2 1.13.3             FALSE

installing the source package ‘devtools’

trying URL 'http://cran.rstudio.com/src/contrib/devtools_1.13.3.tar.gz'
Content type 'application/x-gzip' length 486402 bytes (475 KB)
downloaded 475 KB

Warning in install.packages :
  running command '"//cityofno/cno-fs/UserData/Home2/abwilliamson/R/R-3.3.3/bin/x64/R" CMD INSTALL -l "C:\Users\abwilliamson\Rpackages" C:\Users\ABWILL~1\AppData\Local\Temp\RtmpsPnNQq/downloaded_packages/devtools_1.13.3.tar.gz' had status 127
Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status
`

**Comment by hadley** [comment]
Either install the binary version, or just wait a couple of days until the binary is updated on CRAN.
