### ISSUE TITLE
Rstudio crashes when running: devtools::check() or devtools::document() 

### ISSUE THREAD

**Issue by paternogbc** [hadley/devtools#1563]
Hi,

I am using Rstudio and devtools to build an R package for a long time now.
More recently when running these comands (`devtools::check()` and `devtools::document()`) in the console causes Rstudio to crash instantly. However, when running the same commands through Rstudio panel it works fine.

Any ideas of what could cause this issue? I cant provide any further information because there is no crash report from Rstudio or error message from R.

I am using LINUX (Deepin 15.3, debian based distribution)
Rstudio Version 1.1.319

sessionInfo()
``` r
sessionInfo()
#> R version 3.3.3 (2017-03-06)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Deepin 15
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] backports_1.1.0 magrittr_1.5    rprojroot_1.2   tools_3.3.3    
#>  [5] htmltools_0.3.6 yaml_2.1.14     Rcpp_0.12.12    stringi_1.1.5  
#>  [9] rmarkdown_1.6   knitr_1.16      stringr_1.2.0   digest_0.6.12  
#> [13] evaluate_0.10.1
```

**Comment by jimhester** [comment]
Try running the code in a R terminal outside of RStudio.

Also you can check the [RStudio error logs](https://support.rstudio.com/hc/en-us/articles/200554756-RStudio-Application-Logs) to see if there is a useful error message there. They are stored by default in `~/.rstudio-desktop/log` if you are using RStudio Desktop on linux.

**Comment by paternogbc** [comment]
Thanks @jimhester !

I will do that and give you a feedback!

**Comment by hadley** [comment]
I've closed this issue due to lack of reprex. If you manage to capture the logs, please file a new issue.
