### ISSUE TITLE
Error running find_rtools()

### ISSUE THREAD

**Issue by alexilliamson** [hadley/devtools#1565]
Hello,

When I run `find_rtools()`, I get the following message:

Error in system(full, intern = TRUE, ignore.stderr = quiet, ...) : 
  'CreateProcess' failed to run 'T --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC'

I just reinstalled 'devtools' from CRAN, and I tried uninstalling and reinstalling rtools, but I am getting the same error.  Any ideas what the issue might be?

**Comment by jimhester** [comment]
The `system()` call in question is trying to run `R CMD config CC`. I would imagine there is an issue with your `%PATH%` variable and R is not on it.

**Comment by alexilliamson** [comment]
I reinstalled R, Rtools, and then RStudio. Not ideal, but hey it works now!  Thanks for your help
