### ISSUE TITLE
use_data(internal = TRUE) doesn't check NAMESPACE

### ISSUE THREAD

**Issue by dmurdoch** [hadley/devtools#1570]
In my system, new packages in RStudio are created with the NAMESPACE exporting everything not starting with a dot.  If I create one and use

    devtools::use_data(foo, internal = TRUE)

the `foo` object is exported, even though the help page says about `internal`:  "If TRUE, stores all objects in a single R/sysdata.rda file. These objects are only available within the package."

Perhaps the help page should be changed to describe what really happens (i.e. the object is exported if the NAMESPACE says to export it), or perhaps the NAMESPACE file should be checked and a warning issued if a user chooses `internal` but the NAMESPACE exports the name.

**Comment by hadley** [comment]
I don't think this is perfect, but the docs should be better now. It's hard to succinctly describe all the details.

**Comment by dmurdoch** [comment]
On 09/08/2017 11:00 AM, Hadley Wickham wrote:
> I don't think this is perfect, but the docs should be better now. It's hard to succinctly describe all the details.


Thanks, it looks good to me.
