### ISSUE TITLE
Feature request: ref argument in other install_* functions other than install_github

### ISSUE THREAD

**Issue by paulobrecht** [hadley/devtools#1574]
Is there a reason that only install_github allows the ref argument? I have a use case in which I'm trying to use install_git() to install from a git repo on a network file system and need to be able to select particular commits for reproducibility. Thanks.

**Comment by hadley** [comment]
Probably because implementing it for `install_git` is more challenging. Can you please continue discussion over at [remotes](https://github.com/r-lib/remotes)? That's where devtools installation code is moving in the near future.
