### ISSUE TITLE
NEWS.md to inst/NEWS.rd with document()

### ISSUE THREAD

**Issue by Neil-Schneider** [hadley/devtools#1575]
This is a feature request.

I like the fact that inst/NEWS.rd get published in the package index, but I would like to maintain the NEWS using markdown in the root folder. Is it possible to use @gaborcsardi work for the markdown in the roxygen headers to also translate the NEWS.md into the inst/NEWS.rd?

Thanks,

**Comment by gaborcsardi** [comment]
What's the package index?

**Comment by Neil-Schneider** [comment]
The help index can be seen here: help(package="devtools"). It is populated by /library/devtools/html/00index.html.  

The inst/NEWS.Rd gets included in the help index during the install as seen here: help(package = "lme4"). You can see at the top of the index is a link to `Package NEWS`. (/library/lme4/NEWS.Rd)

**Comment by gaborcsardi** [comment]
I see. That would probably be a new roclet I think.

**Comment by hadley** [comment]
@Neil-Schneider this is something that we're unlikely to find the time to work on, but it's possible to create a roclet in any package, so there's nothing holding you back from working on it 😄
