### ISSUE TITLE
Review rstudioapis

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#1576]
* Save all open files before `test()`, `load_all()` etc
* Open project with `create()`

**Comment by jimhester** [comment]
Should the saving be configurable with an option? Or is there one set in the IDE we could query?

**Comment by hadley** [comment]
I don't think its necessary - generally saving is not a dangerous option, and it's more frustrating to forget to save and then wonder why loading the package didn't change anything. The keyboard shortcuts do already save, so it's mostly a matter of bringing the CLI up to spec.

**Comment by jimhester** [comment]
Closed by https://github.com/hadley/devtools/commit/5517fdb9f4b655eaeffdc7e371db42cddcc679e4, https://github.com/hadley/devtools/commit/ebe4cbfc65f8c2fe50a00c9cfe00571b78d29e90
