### ISSUE TITLE
install_deps() fails w/R 3.2 and pkgType = "both"

### ISSUE THREAD

**Issue by kevinushey** [hadley/devtools#1581]
`download.packages(type = "both")` is broken with R 3.2.1,  and `devtools` bumps into this with some of its own invocations of `download.packages()`. To reproduce, try running:

```R
download.packages("psych", destdir = tempdir(), type = "both")
```

you should see

```R
> download.packages("psych", tempdir(), type = "both")
Warning in download.file(url, destfile, method, mode = "wb", ...) :
  download had nonzero exit status
Warning in download.packages("psych", tempdir(), type = "both") :
  download of package 'psych' failed
     [,1] [,2]
```

`devtools` uses this API here:

https://github.com/hadley/devtools/blob/8628dc40e9432e0551eea6c22582ea1fa0c113ac/R/install-cran.r#L57-L59

Should `devtools` sanitize the `pkgType` argument here? (likely just replace it with `"source"` for older versions of R)

Note that `options(pkgType = "both")` is the default option here, so presumedly users running with this older version of R would bump into it. Also note that R 3.2.1 is still published as the last available binary for Snow Leopard (https://cran.r-project.org/bin/macosx/) so I expect some of these are still out in the wild.

**Comment by hadley** [comment]
This is likely to get completely replaced once we move to remotes

(BTW when did the cool inline previews of links to code start happening???)
