### ISSUE TITLE
`document` generates wrong S3 exports if NAMESPACE doesn’t exist yet

### ISSUE THREAD

**Issue by klmr** [hadley/devtools#1585]
My package ‹modules› has an [insidious bug](https://github.com/klmr/modules/issues/117) related to incorrect exports of S3 methods, generated via roxygen2. However, [the roxygen2 tags inside my package *are correct*](https://github.com/klmr/modules/blob/32e7404e9a4ed59e10a30e88e8b1970479d9edb8/R/export_roclet.r#L5-L7):

```r
#' @importFrom roxygen2 roclet_tags
#' @export
roclet_tags.roclet_export = function (x) {
```

The problem is that my deployment process (which generates the documentation) starts from a blank slate, i.e. no `NAMESPACE` file exists yet. As a consequence, even though the `Imports` are correctly listed in the `DESCRIPTION`, devtools fails to import the necessary S3 generic which my method extends. Subsequently roxygen2 fails to recognise that these methods are, indeed, S3 methods; and [it generates the following `NAMESPACE` entry](https://github.com/klmr/modules/blob/4dc6a9202b54a2ddd852ca9124854613d8815b7d/NAMESPACE#L19):

```r
export(roclet_tags.roclet_export)
```

---

### To reproduce this issue:

1. Generate an empty package using `Rscript -e 'dummy = 1; package.skeleton("foo", "dummy")'`
2. `cd foo`
3. Add imports: `echo 'Imports: roxygen2' >> DESCRIPTION`
4. `rm NAMESPACE`
5. Add a new file `R/test.r` with the contents

    ```r
    #' @importFrom roxygen2 roclet_tags
    #' @export
    roclet_tags.roclet_foobar = function (x) { list() }
    ```

6. Run `Rscript -e 'devtools::document()'`

### Expected output:

```r
# Generated by roxygen2: do not edit by hand

S3method(roclet_tags,roclet_foobar)
importFrom(roxygen2,roclet_tags)
```

### Actual output:

```r
# Generated by roxygen2: do not edit by hand

export(roclet_tags.roclet_foobar)
importFrom(roxygen2,roclet_tags)
```

Running `Rscript -e 'devtools::document()'` *a second time* yields a corrected `NAMESPACE` file.

---

I am reporting this bug here since using `roxygen2::roxygenize()` instead of `devtools::document()` actually *works*: `roxygen2::roxygenize` is “dumber” and performs less sophisticated loading. `devtools::load_all`, by contrast, is “too smart” and attempts to use the (non-existent) `NAMESPACE` as a hint for loading. This is fundamentally circular and, though a good heuristic, bound to produce false results on occasion.

Unfortunately devtools gives no indication of potential problems, and the result is very hard to debug failures (see linked bug report): I took several days of trial and error and going through roxygen2 and devtools internals to find the problem; if I hadn’t already known my way around both code bases this would have taken even longer.

At the very least `document` should produce a clear warning about potentially mis-classifying S3 methods; even better would be a way of controlling the behaviour so that a single pass of `document` produces the correct output.

**Comment by jimhester** [comment]
The easy solution is as you noted to just run `document()` twice.

Having to run `document()` twice ends up being fairly common when you make changes that affect the `NAMESPACE`.

**Comment by klmr** [comment]
Fair enough, that’s an acceptable solution if it’s clearly documented.

I’m wondering if it’s actually necessary to load the package so meticulously when generating the `NAMESPACE` file, rather than simply loading all imports — similar to what `roxygen2:::source_package` does (although it would probably be better not to use `require`, which attaches packages).

… But I’m probably overlooking some corner cases where *that* would yield wrong results, am I not?

**Comment by hadley** [comment]
The long term solution is here: https://github.com/klutometis/roxygen/issues/372

**Comment by klmr** [comment]
@jimhester `roxygen2:::load_pkg_dependencies` (which is called internally) should take care of that, shouldn’t it?
