### ISSUE TITLE
minor error in revdep_check() output

### ISSUE THREAD

**Issue by rpruim** [hadley/devtools#1591]
This came while doing checking reverse dependencies for `mosaicCore`.  The counting of packages being installed doesn't match the number of packages listed.

```
Installing dependencies ------------------------------------------------------------------
Installing 2 packages: ggformula, mosaic, mosaicCalc
```

**Comment by hadley** [comment]
`revdep_check()` has been deprecated in favour of [revdepcheck](http://github.com/r-lib/revdepcheck)
