### ISSUE TITLE
Unused argument error in `pkgbuild::build`

### ISSUE THREAD

**Issue by ShanSabri** [hadley/devtools#1592]
```
==> devtools::check()

Updating TestPkg documentation
Loading TestPkg
Setting env vars --------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building TestPkg ---------------------------------------------------------------
Error in pkgbuild::build(pkg$path, tempdir(), quiet = quiet, args = build_args,  : 
  unused argument (check_dir = "/Users/some/parent/directory/to/TestPkg")
Calls: <Anonymous> -> <Anonymous> -> force
Execution halted

Exited with status 1.
```

If I run `devtools::check()` from the RStudio console, then it returns `Error: Function documentSaveAll not found in RStudio`. 

Session info posted below. I've just upgraded my R to the latest version: 
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.3.9000 usethis_0.0.0.9000  

loaded via a namespace (and not attached):
[1] compiler_3.4.1        tools_3.4.1           withr_2.0.0           rstudioapi_0.6.0.9000 memoise_1.1.0         pkgload_0.0.0.9000   
[7] digest_0.6.12         pkgbuild_0.0.0.9000   rlang_0.1.2.9000     
```

**Comment by jimhester** [comment]
Make sure you are using fully upgraded versions of the packages.

```r
devtools::install_github("hadley/devtools")
```

Should upgrade all of them for you automatically.

The `documentSaveAll()` looks like it needs IDE version 1.1.287 or later to work. We will need to add code to devtools which checks that these functions are available.

**Comment by fishnerdsunite** [comment]
@jimhester Thank you for the suggestions and updating devtools. However, I'm running into a very similar issue as @ShanSabri. He was having issues both in the build tab and console. At this moment, I'm able to enter `devtools::check() ` in the console and devtools operates as normal and checks the package I'm building, but if I am to run the check in the build tab it produces the same error as described above. Thanks for any help.

**Comment by benjaminhlina** [comment]
@jimhester Thank you for the suggestions and updating devtools. However, I'm running into a very similar issue as @ShanSabri. He was having issues both in the build tab and console. At this moment, I'm able to enter `devtools::check()` in the console and devtools operates as normal and checks the package I'm building, but if I am to run the check in the build tab it produces the same error as described above. Thanks for any help.

**Comment by jimhester** [comment]
If you are seeing different behavior in the IDE and in the console the only possibilities are a stale version in your session (which restarting the entire IDE should fix) or different `.libPaths()` picking up an old version of devtools.

**Comment by benjaminhlina** [comment]
Thank you for your help. I have tried both possibilities, as well as removing previous versions of R and old packages. However, I have narrowed down the issue to, when using `devtools::check() `with `devtools` installed from CRAN, no errors occur regardless if it's in console or build tab. Once I install the newest version of `devtools` from github, the console checks the package without error but the build tab doesn't. 



```
sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1   
> .libPaths()
[1] "C:/Users/Ben Hlina/Documents/R/win-library/3.4"
[2] "C:/Program Files/R/R-3.4.1/library"            
> library(devtools)
Loading required package: usethis
> library(roxygen2)
> session_info()
─ Session info ────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2017-09-05                  

─ Packages ────────────────────────────────────────────────────────────────────────────
 package     * version     date       source                             
 clisymbols    1.2.0       2017-05-21 CRAN (R 3.4.1)                     
 commonmark    1.4         2017-09-01 CRAN (R 3.4.1)                     
 devtools    * 1.13.3.9000 2017-09-06 Github (hadley/devtools@a0c8d73)   
 digest        0.6.12      2017-01-27 CRAN (R 3.4.1)                     
 magrittr      1.5         2014-11-22 CRAN (R 3.4.1)                     
 memoise       1.1.0       2017-04-21 CRAN (R 3.4.1)                     
 pkgbuild      0.0.0.9000  2017-09-05 Github (r-lib/pkgbuild@6574561)    
 pkgload       0.0.0.9000  2017-09-05 Github (r-lib/pkgload@6d4a7b6)     
 R6            2.2.2       2017-06-17 CRAN (R 3.4.1)                     
 Rcpp          0.12.12     2017-07-15 CRAN (R 3.4.1)                     
 rlang         0.1.2.9000  2017-09-05 Github (tidyverse/rlang@fd64bce)   
 roxygen2    * 6.0.1.9000  2017-09-05 Github (klutometis/roxygen@52180f2)
 sessioninfo   1.0.1       2017-09-05 Github (r-lib/sessioninfo@e813de4) 
 stringi       1.1.5       2017-04-07 CRAN (R 3.4.1)                     
 stringr       1.2.0       2017-02-18 CRAN (R 3.4.1)                     
 usethis     * 0.0.0.9000  2017-09-05 Github (r-lib/usethis@12e6f95)     
 withr         2.0.0       2017-07-28 CRAN (R 3.4.1)                     
 xml2          1.1.1       2017-01-24 CRAN (R 3.4.1)
``` 

error in build tab 

```
Updating ecotox documentation
Loading ecotox
Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
Writing LC.Rd
Setting env vars --------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building ecotox ---------------------------------------------------------------
Error in pkgbuild::build(pkg$path, tempdir(), quiet = quiet, args = build_args,  : 
  unused argument (check_dir = "C:/Users/Ben Hlina/Documents")
Calls: <Anonymous> -> <Anonymous> -> force
Execution halted

Exited with status 1.
```

**Comment by qinghenyuanluo** [comment]
@benjaminhlina I encountered the exact same problem as yours. "I'm able to enter devtools::check() in the console, devtools operates as normal and checks the package, but if I am to run the check in the build tab it produces the same error as described above. " How do you fix it? Thank you!

**Comment by jimhester** [comment]
Was able to reproduce this. The IDE calls `devtools::check()` with a `check_dir` argument (https://github.com/rstudio/rstudio/blob/ff4ec56122a07058aafa04d6f80b2d1225e037c9/src/cpp/session/modules/build/SessionBuild.cpp#L937), but doesn't show that in it's output.

**Comment by jimhester** [comment]
We will need to keep `check_dir` for the time being, even if we just swallow the input. Or modify rcmdcheck to accept a `check_dir` argument.

**Comment by qingchenyuanluo** [comment]
@jimhester Thanks for your answers. But I'm really new to R, and I'm not sure what does "keep check_dir" mean and how to "modify the rcmdcheck to accept a check_dir argument". Sorry about this. If you could further explain it, I would be appreciated!

**Comment by hadley** [comment]
@qingchenyuanluo we've made this change, so you just need to reinstall devtools from github.
