### ISSUE TITLE
devtools::use_operator() for operator inclusion boilerplate.

### ISSUE THREAD

**Issue by MilesMcBain** [hadley/devtools#1593]
Lately it seems like part of my standard package boilerplate is to paste:
```
#' Pipe operator
#'
#' @name %>%
#' @rdname pipe
#' @keywords internal
#' @export
#' @importFrom magrittr %>%
#' @usage lhs \%>\% rhs
NULL
```
At the top of a suitable file and add `magrittr` to imports. I'm starting to really like `rlang::%||%` so I can see this becoming yet another bit of boilerplate. I'm suggesting a function gets added to devtools like:
`use_operator("magrittr::%>%")` that would take care of this for me. 

It would need to create a file, but I reckon a standard filename for this type of thing is probably good practice. It could be called '__imported_ops.R' or something else suitable.

edit: Sorry. maybe this should be filed under `usethis`?

**Comment by jimhester** [comment]
`usethis::use_pipe()` may make you happy :smile:, and yeah this should have been in **usethis**
