### ISSUE TITLE
Expand scope of argument branch in `install_git`

### ISSUE THREAD

**Issue by malwinare** [hadley/devtools#1594]
Would it be possible to add additional parameters - commit and call to github_pull -  to argument branch in `install_git`, so it would be possible to install from git references, other than branch names?

Likewise in the `install_github`, where argument ref takes commit, tag, or branch name, or a call to github_pull.

**Comment by jimhester** [comment]
In the `install_github()` case you can specify any treeish object e.g. `install_github("hadley/devtools@branchname")` or `install_github("hadley/devtools@sha123abc")`.

For `install_git()` you can install from branches or tags, this is unlikely to change in the near term.
