### ISSUE TITLE
Incompatible API 

### ISSUE THREAD

**Issue by Keaton1188** [hadley/devtools#1597]
Hey, can we get DevTools updated so it allows API 7 please. 

@kevinushey

**Comment by hadley** [comment]
What is API 7?

**Comment by Keaton1188** [comment]
My bad, meant API versions* Its currently on 3.0.0-ALPHA6  

Need it on ALPHA7 please.

**Comment by hadley** [comment]
I have no idea what you are talking about. I think you have a wrong repo
