### ISSUE TITLE
check function naming

### ISSUE THREAD

**Issue by jimhester** [hadley/devtools#1598]
Should we rename `build_win()` to `check_win()` and `rhub_check()` to `check_rhub()` to make the names more consistent and easier to discover?

**Comment by hadley** [comment]
Yes!

**Comment by hadley** [comment]
I think we should also have `check_win_devel()` and `check_win_release()` just because for the last year I thought `build_win()` defaulted to "R-devel" (and typically you only want to run one)

**Comment by jimhester** [comment]
I am not really sure why the code it written as it is, having 'R-release' first in the default argument does make it seem like it would default to 'R-release', but it does default to R-devel

https://github.com/hadley/devtools/blob/a0c8d7333be185f979a60823dcfad66c9f3ea35e/R/build-win.r#L23-L24

Anyway, I agree having separate functions makes sense to me.

**Comment by hadley** [comment]
Oh that is super confusing!

**Comment by tbates** [comment]
Getting an error from release check in code which used to work (in my package

    devtools::check_win()

    Missing or unexported object: ‘devtools::check_win’
    packageVersion("devtools")
    [1] ‘1.13.3’
