### ISSUE TITLE
Devtools ‘1.13.3.9000’ error: 'rcmd_safe_env' is not an exported object from 'namespace:callr'

### ISSUE THREAD

**Issue by tbates** [hadley/devtools#1602]
Trying to update to latest install_github("hadley/devtools") version of `devtools`, I got errors during the install, and, while the package installed, using `devtools::install("~/bin/umx")`

All seems to involve  'rcmd_safe_env' not being an exported object from 'namespace:callr'
e.g.
```
    Installing BH
    Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
    Installing whoami
    Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
```
I have `packageVersion("callr")`  ‘1.0.0’,  - the latest available on CRAN.

**Comment by jimhester** [comment]
You need to use the devel version of callr, which should have been installed when you ran `install_github("hadley/devtools")`, but perhaps there was an issue during the install. You can run the following to install devel callr without devtools, and then reinstall devel devtools.

```r
source("https://install-github.me/r-lib/callr")
source("https://install-github.me/hadley/devtools")
```

**Comment by tbates** [comment]
Manually grabbing callr succeeded. I see `callr` installed two new dependencies - perhaps that was the hiccup. So, people should be installing `callr` first before `devtools`

```
source("https://install-github.me/r-lib/callr")
Downloading GitHub repo r-lib/callr@master
Installing 2 packages: debugme, processx
* installing *source* package ‘callr’ ...
```

The devtools source line, however yielded the following Warning messages:
```
1: In utils::install.packages(...) :
  installation of package ‘/var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T//RtmpRROAWG/remotesb4585adbf006/hadley-testthat-c7e8330’ had non-zero exit status
2: In utils::install.packages(...) :
  installation of package ‘/var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T//RtmpRROAWG/remotesb4583aab6e58/tidyverse-rlang-53ebc71’ had non-zero exit status
```

I then quit R, reopened, and tried building a package.
This triggered some additional package downloading, and scales failed

```
Installing scales
Running command /Library/Frameworks/R.framework/Resources/bin/R 
Arguments:
CMD
INSTALL
/private/var/folders/nk/c_89sgqd3tv4gfwty7tzkmj80000gn/T/RtmpDgn8tU/devtoolsc99819a202ec/scales
--library=/Library/Frameworks/R.framework/Versions/3.4/Resources/library
--install-tests

Installation failed: run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),      stderr_line_callback = real_callback(stderr), stdout_callback = real_block_callback,      stderr_callback = real_block_callback, echo_cmd = echo, echo = show,      spinner = spinner, error_on_status = fail_on_status, timeout = timeout) : System command error
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : derr), stdout_callback = real_block_callback,      stderr_callback = real_block_callback, echo_cmd = echo, echo = show,      spinner = spinner, error_on_status = fail_on_status, timeout = timeout) : System command error
  namespace ‘scales’ 0.4.1 is being loaded, but >= 0.5.0 is required
```
This would not resolve with repeated attempts using devtools. The update of scales to .5 failed, leaving v 1.4.1 of scales installed.

.5.0 is  just the CRAN version, and a simple `install.packages("scales")` fixed it, so unclear what's going wrong when devtools tries too...

All's working now.

**Comment by jimhester** [comment]
This should be fixed by https://github.com/hadley/devtools/commit/c9ca63a21586e537a2fcb1ed44ba38159da55e7e. I am pretty sure it is caused by callr being moved to r-lib.

**Comment by tbates** [comment]
@jimhester  after some more manual installs got it all working.
FYI, though, just got this error running release

    Error: ‘rversions’ is not in Suggests: for pkgload!
