### ISSUE TITLE
check() fails at install step while install() succeeds with no issues

### ISSUE THREAD

**Issue by sushilashenoy** [hadley/devtools#1607]
Working on a package which had previously passed R CMD check (running within the Rstudio "Build" tab). The package still builds & installs successfully, but when I run check() it fails with this error:

```* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘blah’ can be installed ... ERROR
Installation failed.
See ‘/home/sushila/blah.Rcheck/00install.out’ for details.
* DONE
Status: 1 ERROR
```

By the time I see this message the blah.Rcheck directory has already been deleted. However I found that if I run `devtools::check()` from the console it will run in a temporary directory (e.g.  ‘/tmp/RtmpsD063J/blah.Rcheck/00check.log’) which is around long enough to inspect. In the `00install.out` file there is some additional information on the error:

```
* installing *source* package ‘blah’ ...
** R
** preparing package for lazy loading
Error: package or namespace load failed for ‘survival’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘Matrix’
Error : package ‘survival’ could not be loaded
ERROR: lazy loading failed for package ‘blah’
* removing ‘/tmp/RtmpsD063J/blah.Rcheck/blah’
```

Now this is really confusing because both "Matrix" and "survival" are installed. Reinstalling them did not make a difference, nor did adding "Matrix" as a "Depends" in `DESCRIPTION` (survival was already there). Based on the advice here http://r-pkgs.had.co.nz/check.html , I tried running devtools::install() to figure out what is going on, but it completes successfully:

```
Installing blah
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/home/sushila/blah'  \
  --library='/home/sushila/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 

* installing *source* package ‘blah’ ...
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (blah)
Reloading installed blah
```

So I'm not sure what the difference is that is causing installation to fail when run within check(). I don't believe the behavior I am seeing is as intended.

**Comment by jimhester** [comment]
Please try running `R CMD check` from the terminal / command line and see if the error is reproduced there. `devtools::check()` is just a thin wrapper around `R CMD check`. 

If you can provide an example package that exhibits this behavior we can try to help further. This is very likely an issue with your package or your local libraries rather than a devtools issue.

**Comment by sshenoy-mdsol** [comment]
Running R CMD check from the terminal does work. I have included the output below.

[R_CMD_check_output.txt](https://github.com/hadley/devtools/files/1285613/R_CMD_check_output.txt)
[R_check_install_output.txt](https://github.com/hadley/devtools/files/1285611/R_check_install_output.txt)
[00install.out.txt](https://github.com/hadley/devtools/files/1285615/00install.out.txt)

Unfortunately I am not allowed to share this package but I will try to create a minimal example package that exhibits the same behavior.

**Comment by sushilashenoy** [comment]
Okay, I was able to reproduce this issue with only two lines from the DESCRIPTION file. If I make a new package in Rstudio without changing any defaults, devtools::check() completes with 1 warning. If I add these lines to the end of the DESCRIPTION file:

```
Imports: caret
Depends: survival
```

Then this happens:

```
....
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘blah’ can be installed ... ERROR
Installation failed.
See ‘/tmp/RtmpxbD6lO/blah.Rcheck/00install.out’ for details.
* DONE

Status: 1 ERROR
See
  ‘/tmp/RtmpxbD6lO/blah.Rcheck/00check.log’
for details.

R CMD check results
1 error  | 0 warnings | 0 notes
checking whether package ‘blah’ can be installed ... ERROR
Installation failed.
See ‘/tmp/RtmpxbD6lO/blah.Rcheck/00install.out’ for details.
```

and the 00install.out file contains:
```
* installing *source* package ‘blah’ ...
** R
** preparing package for lazy loading
Error: package or namespace load failed for ‘survival’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘Matrix’
Error : package ‘survival’ could not be loaded
ERROR: lazy loading failed for package ‘blah’
* removing ‘/tmp/RtmpxbD6lO/blah.Rcheck/blah’
```

If I remove either the "Imports: caret" or "Depends: survival" lines from the DESCRIPTION file, devtools::check() no longer fails at installation.

**Comment by jimhester** [comment]
A simple package with those dependencies works fine on my machine. Please make sure you have updated all your packages to the latest versions, this seems like a library corruption issue to me.

```r
update.packages(ask = FALSE, checkBuilt = TRUE)
```
