### ISSUE TITLE
Should `devtools::use_package_doc()` use "_PACKAGE"?

### ISSUE THREAD

**Issue by DavisVaughan** [hadley/devtools#1608]
I like how `dplyr`'s package doc page contains the Authors and See Also headers generated from using `"_PACKAGE"` rather than `NULL`.

Should `devtools::use_package_doc()` do this? 

For motivation, `base::promptPackage()` creates an `Rd` file with the Author and See Also headers, so this might be more consistent with that.

This template would be changed:

https://github.com/hadley/devtools/blob/master/inst/templates/packagename-package.r

**Comment by jimhester** [comment]
Yes this is done in [usethis](https://github.com/r-lib/usethis/blob/07553f3a052f7fc30588bb0da317f4457e2fa0d2/inst/templates/packagename-package.R#L2), which is where the devtools use_ functions have gone and what devtools will be using in the future.
