### ISSUE TITLE
Failure to find devtools in R-devel

### ISSUE THREAD

**Issue by navdeep-G** [hadley/devtools#1613]
Getting this error with travis:

The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .

The travis file is here: https://github.com/h2oai/rsparkling/blob/master/.travis.yml
Travis run is here: https://travis-ci.org/h2oai/rsparkling/jobs/276645588

Any ideas would be greatly appreciated.

**Comment by navdeep-G** [comment]
Potential solution: https://github.com/h2oai/rsparkling/commit/d7163a8272efc304e38549b36ed2adedca54bcc3

**Comment by jimhester** [comment]
Why are you installing devel devtools in the first place? It is probably better to just rely on CRAN devtools which is installed by default with `language: r`.

**Comment by navdeep-G** [comment]
I believe I had a reason and now I do not remember. I remove those two lines and rely on the CRAN version of devtools. I have a test here: https://github.com/h2oai/rsparkling/pull/54

Thanks!
