### ISSUE TITLE
``install`` fails with a trailing "/"

### ISSUE THREAD

**Issue by kendonB** [hadley/devtools#1614]
This fails:
``` r
devtools::install("D:/pathtopackage/")
#> Error: Can't find 'D:\pathtopackage\'.
```

This works 
``` r
devtools::install("D:/pathtopackage")
```

I think this is worth dealing with since 1) install.packages works with the trailing "/" and RStudio puts the trailing slash when autocompleting paths.

Hope this helps!

**Comment by crew102** [comment]
Hi @kendonB, the reason why the trailing slash isn't working for you is b/c on Windows file names ending in / are actually invalid. I think I agree that it would be nice if trailing slashes were supported by devtools, given that RStudio adds the trailing slash when auto-completing (though perhaps this should be considered more of an issue with RStudio than with devtools). Here are two discussions of the issue:

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=14721
http://r.789695.n4.nabble.com/file-exists-does-not-like-path-names-ending-in-td4683717.html

@hadley , what are your thoughts on devtools stripping trailing /'s in file paths? If you think it should be done, I can issue PRs to devtools, pkgload, and desc to support this.

**Comment by jimhester** [comment]
This should already be fixed in the development version of devtools.
