### ISSUE TITLE
can we just take the full url of a repo as `install_github` parameter?

### ISSUE THREAD

**Issue by dracodoc** [hadley/devtools#1616]
Compare to

```r
devtools::install_github("tidyverse/ggplot2")
```

How about we also accept

```r
devtools::install_github("https://github.com/tidyverse/ggplot2")
```

So user can just copy the root url of a repo and install it. This only save one manual selection, but it's still a saving, and I think it's easy and simple enough to implement. 

I can submit a PR for review if you think this is a good idea.

**Comment by hadley** [comment]
@jennybc is already working on this

**Comment by jimhester** [comment]
More specifically https://github.com/r-lib/remotes/pull/112

**Comment by dracodoc** [comment]
Great, thanks!
