### ISSUE TITLE
New testthat environment affects Rcpp::sourceCpp

### ISSUE THREAD

**Issue by cdeterman** [hadley/devtools#1617]
This issue is in reference to a post I made on R-package-devel [here](https://stat.ethz.ch/pipermail/r-package-devel/2017q3/001951.html).  In essence, I want to test a `Rcpp::sourceCpp` call but it fails when `devtools::test()` is called because it is trying to look for the internal headers in the `include` directory when they are in the `inst/include` directory.  The test also works fine when call `testthat::test_file` directly (as it looks where the package is installed and has the `include` directory.  Any thoughts how to address this problem?

**Comment by jimhester** [comment]
It would be easier to recommend the best solution if you could link to the actual package directly.

But the short answer I think is to use `system.file(package = "foo", "include")`. Devtools modifies `system.file()` to look in `inst/` if the package is loaded by `devtools::load_all()`, which is what is done in `devtools::test()`.

**Comment by cdeterman** [comment]
@jimhester [here](https://github.com/cdeterman/gpuR/tree/develop) is the package I am developing.

**Comment by cdeterman** [comment]
@jimhester how would you suggest applying the `system.file` approach you are suggesting?  I'm not sure how anything I pass to `test` can alter where the process looks for the files.

**Comment by jimhester** [comment]
I think the simplest solution for your use case might be to just symlink `include` to `inst/include`. and put `include` in your .Rbuildignore file.
