### ISSUE TITLE
load_all() sources from old package directory

### ISSUE THREAD

**Issue by Bandytwin** [hadley/devtools#1618]
I recently copied a package I was working on (in Documents/packages-dev/) to another directory (Documents), and now when I run `devtools::load_all()` it seems to source files from the original package location--see below:

```
`devtools::load_all('~/Documents/pkgTest/R/refill_dt.R')`
Loading pkgTest
`str(refill_dt)`
function (dt, group_var = NULL, date_index, fill_cols = NULL, 
    interp_cols = NULL, ind_cols = NULL, other_fill_cols = NULL)  
 attr(*, "srcref")=Class 'srcref'  atomic [1:8] 34 14 151 1 14 1 34 151
  .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x11b9b45c0> 
`source('~/Documents/pkgTest/R/refill_dt.R')`
`str(refill_dt)`
function (dat, group_var = NULL, date_index, fill_cols = NULL, 
    interp_cols = NULL, interp_method = "stine", 
    ind_cols = NULL, other_fill_cols = NULL, num_cores = NULL)  
 attr(*, "srcref")=Class 'srcref'  atomic [1:8] 42 14 173 1 14 1 42 173
  .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x1aae4ff10> 
```

If I edit the refill_dt() function in Documents/packages-dev/pkgTest, and then run `devtools::load_all('~/Documents/pkgTest/R/refill_dt.R')` I see those changes reflected in the refill_dt() function that is returned. This behavior is consistent for all the functions/R files in the package. 

Oddly enough, if I do devtools::document() or devtools::install() then the appropriate R files are used (the problem only seems to be with load_all()).

devtools is awesome--I use it all the time--so thank you for all the work you do to maintain and develop it!

**Comment by hadley** [comment]
You're using `load_all()` in a bit of a weird way - you should be giving it a directory, not a file. 

It's also possible that you accidentally `source()`d a file (I do this all the time) and so you might also try restarting R with a clean session.

**Comment by Bandytwin** [comment]
Yes I had accidently sourced a file, thanks for the help!
