### ISSUE TITLE
print.spellcheck throws error if no errors found

### ISSUE THREAD

**Issue by mikemeredith** [hadley/devtools#1620]
I ran `spell_check` on my package, corrected all the genuine misspellings and put the false alarms into a `spellcheckIgnore` vector. I then re-ran `spell_check`:

```R
tmp <- spell_check("HDInterval", ignore=c(hunspell::en_stats, spellcheckIgnore), "en_GB")
tmp
# Error in sprintf(fmt, "  WORD") : 
#  invalid format '%--Inf'; use format %s for character objects
# In addition: Warning message:
# In max(nchar(words)) : no non-missing arguments to max; returning -Inf

traceback()
# 4: sprintf(fmt, "  WORD")
# 3: cat(sprintf(fmt, "  WORD"), "  FOUND IN\n", sep = "")
# 2: print.spellcheck(x)
# 1: function (x, ...) 
#   UseMethod("print")(x)

length(tmp)
# [1] 0
```
It would be nice if `spell_check` gave more encouraging output when all is well!

Sorry, can't do a reproducible example without including all the package documentation, but I have tried it with several packages.

**Comment by hhoeflin** [comment]
Seconded. Found the same issue. After removing all the words the spell-checker complains about (or ignoring them), it throws an error - same as above.

**Comment by hadley** [comment]
We're just calling `spelling::spell_check_package()`, so @jeroen will need to fix this in the spelling package. Would you mind filing an issue over there?

**Comment by jeroen** [comment]
Yes please open an issue on https://github.com/ropensci/spelling. Also note that the default file to wordlist words is `inst/WORDLIST` in your pkg.
