### ISSUE TITLE
Option to prevent files opening with `use_vignette()` etc.

### ISSUE THREAD

**Issue by mixtrak** [hadley/devtools#1621]
Some functions to add useful infrastructure to a package also then open the files created. For example, `use_news_md()` will create and then open the news.md file, and similar behaviour is found in `use_readme_rmd()`, `use_package_docs()`, `use_vignette()` and possibly others.

I have written a wrapper function which initialises a new package with infrastructure and then switches to the new RStudio project in a new RStudio session. However, as a side-effect, all the files mentioned above get opened in my old RStudio session.

It would be nice to be able to pass an `open = FALSE` argument to the underlying code. For example, here is the code for `use_package_doc`:

```
function (pkg = ".") 
{
    pkg <- as.package(pkg)
    use_template("packagename-package.r", file.path("R", paste(pkg$package, 
        "-package.r", sep = "")), data = list(name = pkg$package), 
        open = TRUE, pkg = pkg)
}
<environment: namespace:devtools>
```

Note the `open = TRUE` on the fourth line of function body code, which seems to be an argument of the internal `{devtools}` function `devtools:::use_template`. Perhaps this argument could be exposed to users of the higher-level functions.

**Comment by jimhester** [comment]
the `use_*` functions in future versions of devtools will be part of https://github.com/r-lib/usethis. If you could please open this issue there instead, as `usethis::use_package_doc()` still seems to have no `open` argument.
