### ISSUE TITLE
"Install and restart" devtools::install()

### ISSUE THREAD

**Issue by goranbrostrom** [hadley/devtools#1625]
I'm building a package in RStudio with devtools. When I click on "Install and Restart", 
R CMD INSTALL --no-multiarch --with-keep.source eha
is run and ends with 
Warning in file(con, "w") :
  cannot open file '/usr/local/lib/R/site-library/eha/doc/index.html': No such file or directory
Error in file(con, "w") : cannot open the connection
ERROR: installing vignettes failed

Running devtools::install(build_vignettes = TRUE) works ok, because it eventually runs
...CMD INSTALL .../eha_2.5.0.9000.tar.gz

The same events occur at the command line (unix prompt).

R CMD INSTALL should be applied to the tarball, not to a directory, right?

**Comment by hadley** [comment]
That's an RStudio function so you might want to file an issue at https://github.com/rstudio/rstudio, but from the error message I suspect it's a problem with one of your vignettes.
