### ISSUE TITLE
Expose rhub::check_for_cran

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#1630]

**Comment by hadley** [comment]
Requires https://github.com/r-hub/rhub/issues/98

**Comment by gaborcsardi** [comment]
If we just want to start running the checks, why do we need `default_cran_check_platforms`? Can't we just call `check_for_cran` ?

**Comment by hadley** [comment]
Maybe that's a better approach - it'll change the signature, but it's only in the dev version.

**Comment by gaborcsardi** [comment]
Oh, I see, the current function just takes the platform, of course. Yeah, that makes sense as well, I don't mind updating the package.

**Comment by gaborcsardi** [comment]
Actually, my CRAN submission just failed with:
```
Package has help file(s) containing install/render-stage \Sexpr{} 
expressions but no prebuilt PDF manual. 
```

It happens to me EVERY TIME when I have code in the manual...

Anyway, this is good now, so I can resubmit it with the changes we need. :)
