### ISSUE TITLE
Install fails with non-ASCII characters in Windows user path (install_github)

### ISSUE THREAD

**Issue by jogrue** [hadley/devtools#1637]
`install_github` fails for me because my Windows user name contains an umlaut ("ü"). I would not setup my Windows account that way anymore, but still, this could probably be fixed. I found a similar (supposedly fixed) issue from 2015: #676 

The error happens here, where my user path `C:/Users/Johann Gründl/` becomes `C:/Users/Johann Gr|ndl`:
```
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/Johann Gr|ndl/Documents/R/win-library/3.4/httr/DESCRIPTION': Invalid argument
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package 'httr'
* removing 'C:/Users/Johann Gründl/Documents/R/win-library/3.4/httr'
```
R version 3.4.2
devtools version 1.13.3

I uploaded the full output of `install_github `and `sessionInfo()` here:
https://gist.github.com/jogrue/c55a95fe9890f83d56acf96b353c9631

**Comment by jogrue** [comment]
Sorry, I just saw that this functionality has now been moved to https://github.com/r-lib/remotes. I have got the same problem when using `remotes 1.1.0`. Should I close this and move the issue there?

**Comment by hadley** [comment]
Yes please.

**Comment by jogrue** [comment]
Thank you and sorry for opening the issue here. It is now at https://github.com/r-lib/remotes/issues/114.
