### ISSUE TITLE
devtools::install() hanging

### ISSUE THREAD

**Issue by renkun-ken** [hadley/devtools#1639]
In a package directory, calling `devtools::install()` should install the package from source. Sometimes, however, I run `Rscript -e 'devtools::install()'` from terminal and it hangs for quite a long time at `Installing <package>`. 

```sh
$ Rscript -e 'devtools::install()'
Installing <package>
```

**Comment by hadley** [comment]
Sometimes compiling a package from scratch does take a long time. Does it eventually finish?

**Comment by jimhester** [comment]
It also could be an internet connectivity issue if the package is using Remotes.

**Comment by renkun-ken** [comment]
@hadley, the problem is that for the same package, sometimes it takes only a few seconds to go through `Installing <package>` but it may sometimes takes several minutes as well hanging at `Installing <package>`. Mostly it finishes unless I cannot wait any longer and kill it. If it hangs, then I kill it. After several times, it may eventually step to compiling and so on without hanging at `Installing <package>`.

@jimhester The package does not depends on or imports any remotes (no declared Remotes in `DESCRIPTION`).

I'm not sure what's happening at `Installing <package>`?

**Comment by gaborcsardi** [comment]
Also, if you don't touch the dependencies, you still get this:
```
❯ install(upgrade_dependencies=FALSE)
Installing devtools
Error in curl::curl_fetch_disk(url, x$path, handle = handle) :
  Could not resolve host: raw.githubusercontent.com
```
(I was offline to show the error message.)

**Comment by renkun-ken** [comment]
No hanging is observed so far.
