### ISSUE TITLE
Call for feature: Use faster downloading tools instead of curl

### ISSUE THREAD

**Issue by bioinformatist** [hadley/devtools#1641]
Curl downloads slowly and usually raise error when the network is blocked. 
Can you add a parameter for `devtools::install()` and `devtools::install_github()` to allow user-defined executable downloading tools like `aria2c` or `axel`?

**Comment by hadley** [comment]
No, but we're working on other faster ways of downloading by default.

**Comment by bioinformatist** [comment]
Glad to hear that. Thanks.
