### ISSUE TITLE
Need to import + re-export inst from pkgload

### ISSUE THREAD

**Issue by jimhester** [hadley/devtools#1643]
A bunch of packages depending on devtools use `devtools::inst()`, and it is currently removed. Examples (https://github.com/search?utf8=%E2%9C%93&q=user%3Acran+%22devtools%3A%3Ainst%22&type=Code)

**Comment by jimhester** [comment]
Or have these packages update to using `pkgload::inst()` instead.

**Comment by hadley** [comment]
We should probably re-export to reduce the time needed for release.
