### ISSUE TITLE
devtools::check() fails with Pandoc 2.0.1

### ISSUE THREAD

**Issue by magic-lantern** [hadley/devtools#1651]
Just upgraded my local install of pandoc and now devtools::check fails due to change in pandoc options. 

I have the latest version of all installed R packages (just updated all outdated packages to see if that fixed the issue).

Here's part of the output from running devtools::check() and the error about pandoc.

```
devtools::check()
...
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
* creating vignettes ... ERROR

--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
Error: processing vignette 'pccc-example.Rmd' failed with diagnostics:
pandoc document conversion failed with error 2
Execution halted
Error: Command failed (1)
```

If this issue should be filed elsewhere or has already been addressed in a development version (or version not yet on CRAN) please let me know!

**Comment by jimhester** [comment]
This is not a devtools issue, likely it is due to the CRAN rmarkdown using `--smart`, which seems to have been fixed https://github.com/rstudio/rmarkdown/commit/fa23a72208ceeab8f3d81a9cea19273b54bf2cdf in the devel version.

I would suggest installing devel rmarkdown if you want to use pandoc 2.0.

```r
devtools::install_packages("rstudio/rmarkdown")
```

**Comment by Melkiades** [comment]
*
`devtools::install_github("rstudio/rmarkdown")`

**Comment by magic-lantern** [comment]
Thanks for the guidance @Melkiades and @jimhester
