### ISSUE TITLE
Error in fetch(key) : lazy-load database 

### ISSUE THREAD

**Issue by vishnu1994** [hadley/devtools#1660]
Hi,

I understand that this issue (Error in fetch(key) : lazy-load database, corrupt .rdb file) has been around for some time and it has been fixed(?) since package 1.10 from what I learnt while browsing through github.

Well I still have the problem and am using devtools version 1.13.3. I believe this happens when the package is rebuild and redocumented while it is attached in my rsession. Clearing my environment and restarting the session fixes this, but is there a way to prevent it from coming up entirely during the package building process? I have a few S4 classes in my package and I suspect that the error is generated through devtools::document().

**Comment by hadley** [comment]
It's not sorry, it's a limitation of base R
