### ISSUE TITLE
Error with devtools::check() in Docker container

### ISSUE THREAD

**Issue by darsoo** [hadley/devtools#1661]
When I'm trying run devtools::check() on the sources of developed R
package (in Docker container) I get following error:
"
From devtools::check()
Error: package or namespace load failed for ‘rtracklayer’ in
loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck =
vI[[j]]):
there is no package called ‘lattice’
Error : package ‘rtracklayer’ could not be loaded
ERROR: lazy loading failed for package ‘myPackage’
"

But R CMD check works correctly.
Reinstall of the lattice package doesn't help.

Thanks in advance for any help,
Darek

PS. Below some potentially useful details

sessionInfo:"
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)
Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so"

**Comment by jimhester** [comment]
I am not sure, but this looks like an issue with the `.libPaths()`, and is likely fixed by using devel devtools, which uses the [rcmdcheck](https://github.com/r-lib/rcmdcheck). If it is not fixed I would encourage you to open this issue at https://github.com/r-lib/rcmdcheck/issues.
