### ISSUE TITLE
 install_github(build_vignettes=TRUE) rebuilds installed dependencies recursively

### ISSUE THREAD

**Issue by unDocUMeantIt** [hadley/devtools#1662]
i just ran
```r
install_github(repo="crsh/papaja", build_vignettes = TRUE, force=TRUE)
```
which failed with an error because a dependency (`afex`) was not installed. i installed the missing package system wide and ran the command again.
after a while i was wondering what takes so long. turns out `install_github()` first successfully installed `papaja` with vignette, but after that began to install all dependencies recursively to my user R library. is this intended? it does not happen if i omit the `build_vignettes = TRUE` option.

**Comment by jimhester** [comment]
If you are building vignettes you need all `Suggested` dependencies for the package as well, which is the difference. Otherwise you only need hard dependencies (`Imports`, `Depends`, `LinkinTo`). So I think this is working as intended.

**Comment by unDocUMeantIt** [comment]
i think i didn't explain myself too well. the one missing package was already installed, system wide, but `install_github()` decided to install it _again_, but in my user's R library and from scratch. what's more, the installation happened _after_ the package i actually wanted to install has also already successfully been installed, so installing all dependencies _after_ that doesn't seem to make too much sense to me.
