### ISSUE TITLE
build_vignettes returns null

### ISSUE THREAD

**Issue by kmcconeghy** [hadley/devtools#1664]
Hello, 

I am making an attempt at writing my first major package. https://github.com/kmcconeghy/flumodelr

I am developing vignettes, but I can't get them to show up in the installed package. They knit fine in preview. 

build_vignettes() returns a null value

If I do build() or install(build_vignettes=T), the package is compiled and installs fine, but no vignette is listed by browseVignettes(). 

I do notice in the build() output, it says : 'Removed empty directory 'flumodelr/vignettes'', despite their being three .Rmd files in that folder. 

Any suggestions?

**Comment by kmcconeghy** [comment]
I discovered issue, I had a line in .Rbuildignore "md".

**Comment by randy3k** [comment]
Also, if you are building Rmarkdown files, make sure you have put
```
VignetteBuilder: knitr
```
in the `DESCRIPTION`.
