### ISSUE TITLE
devtools::check() does not respect --no-build-vignettes 

### ISSUE THREAD

**Issue by mkhezr** [hadley/devtools#1667]
As suggested in [R Packages - Automated Checking](http://r-pkgs.had.co.nz/check.html), I added `--no-build-vignettes `  to the commands list in “Build Source Packages” field in the project options. And restarted Rstudio too. Still when I run devtools::check() the vignettes get built.

I'm running RStudio Version 1.0.153. and here is the output of `R.version`:

`platform       x86_64-apple-darwin15.6.0 `  
`arch           x86_64`
`os             darwin15.6.0`
`system         x86_64, darwin15.6.0`
`status`
`major          3`
`minor          4.1`
`year           2017`
`month          06`
`day            30`
`svn rev        72865 `
`language       R`
`version.string R version 3.4.1 (2017-06-30)`
`nickname       Single Candle`

**Comment by jimhester** [comment]
The `--no-build-vignettes` needs to go in the `Check Package` dialog to be added when running `R CMD check()` and the check needs to be run with `build->Check` from within RStudio to pick up the option.
![screenshot 2018-02-13 15 35 20](https://user-images.githubusercontent.com/205275/36172396-bd6d0b56-10d3-11e8-93ab-19bd1321e55a.png)

**Comment by FMKerckhof** [comment]
I am having a very similar issue, but I do have addedd --no-build--vignettes to the configure build tools:
![image](https://user-images.githubusercontent.com/2431458/38247836-d9ab2070-3746-11e8-9e3a-764e65fc3a5c.png)
Nevertheless, running build>Check keeps building vignettes ...

**Comment by FMKerckhof** [comment]
Thanks Jim, that indeed was the case.
