### ISSUE TITLE
devtools fails with any package on windows

### ISSUE THREAD

**Issue by Bustami** [hadley/devtools#1674]
When i try to install any packages with `devtools::install_github("...")` it fails.

Error messages:
> Error in file(file, if (append) "a" else "w") : 
  no se puede abrir la conexión
ERROR: installing package DESCRIPTION failed for package '...'

I looked on other issues here, but i can't find the solution for windows

Any idea?

**Comment by jimhester** [comment]
Please include the results of `traceback()` after the error, to help us pinpoint the issue on your machine.

**Comment by Bustami** [comment]
> 9: stop(e)
8: value[[3L]](cond)
7: tryCatchOne(expr, names, parentenv, handlers[[1L]])
6: tryCatchList(expr, classes, parentenv, handlers)
5: tryCatch(loadNamespace(name), error = function(e) stop(e))
4: getNamespace(ns)
3: asNamespace(ns)
2: getExportedValue(pkg, name)
1: devtools::install_github

It seems be related to my user name in path "Ismael Gómez" not match:

> * installing *source* package 'icon' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/Ismael Gsmez/Documents/R/win-library/3.4/icon/DESCRIPTION': No such file or directory

**Comment by Bustami** [comment]
I solved it this way:
1) Changed my dir for install packages, adding  the new path to my Rpprofile.site:
`R_LIBS_USER="new_path"`.  
(It's important the new path have only ASCII characters!! )
2) I copied the already installed packages to the new path
3) Then i restarted R and execute `.libPaths()` in order to probe the solution and it has been OK: now i can install hadley/devtools and other packages with `devtools::install_github()`
