### ISSUE TITLE
devtools::test() and testthat::test_dir("tests/") give different results

### ISSUE THREAD

**Issue by twolodzko** [hadley/devtools#1675]
Recently I started seeing errors when using devtools + testthat with [my package](https://github.com/twolodzko/kernelboot). 

In one case I see:

```
> testthat::test_dir("tests/")
✔ | OK F W S | Context
══ testthat results  ═════════════════════════════════════════════════════════════════════════════
OK: 345 SKIPPED: 3 FAILED: 0

══ Results ═══════════════════════════════════════════════════════════════════════════════════════
Duration: 5.2 s

OK:       0
Failed:   0
Warnings: 0
Skipped:  0
```
and in another:

```

> devtools::test()
Loading kernelboot
Testing kernelboot
✔ | OK F W S | Context
⠼ | 235       | 0Error in x[[method]](...) : attempt to apply non-function

══ Results ═══════════════════════════════════════════════════════════════════════════════════════
Duration: 2.7 s

OK:       235
Failed:   4
Warnings: 0
Skipped:  1
```

and devtoos::check() give:

```
Status: OK

R CMD check results
0 errors | 0 warnings | 0 notes
```

Please notice that this started happening after tettthat update. I didn't make any changes in the code that may brake anything. I have also no reasons to believe that there are bugs in my code that were not detected before the testthat update since I checked everything by hand.

**Comment by ELToulemonde** [comment]
Hi,

I encounter the same problem. (By the way thanks for the idea of ` testthat::test_dir`)


I have managed to build a reproducible example:

foo.R: a R file in /R/

```
foo <- function(obj){
  return(as.numeric(obj))
}
```

test_foo.R: a uniit test file in /tests/testthat

```
test_that("Test my foo function: ",
          {
            expect_true(is.na(foo("1,5")))
            })

```

testhat.R: to run my units tests in /tests/
```
library(testthat)
library(foo)
test_check("foo")
```


<h1> Two scenarios </h1>

**Running: devtools::test()**

```
> devtools::test()
Loading foo
Loading required package: testthat
Testing foo
√ | OK F W S | Context
Error in x[[method]](...) : attempt to apply non-function

== Results =====================================================================
Duration: 0.1 s

OK:       0
Failed:   4
Warnings: 1
Skipped:  0
```

**Running testtjat::test_dir("tests/")**

```

> testthat::test_dir("tests/")
√ | OK F W S | Context
== testthat results  ===========================================================
OK: 2 SKIPPED: 0 FAILED: 0

== Results =====================================================================
Duration: 0.1 s

OK:       0
Failed:   0
Warnings: 0
Skipped:  0
```


<h1>Environement</h1>

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] foo_0.0.0.9000 testthat_2.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     roxygen2_6.0.1   rprojroot_1.3-2  crayon_1.3.4     assertthat_0.2.0 digest_0.6.14    withr_2.1.1      commonmark_1.4  
 [9] R6_2.2.2         backports_1.1.2  magrittr_1.5     cli_1.0.0        rlang_0.1.6      stringi_1.1.6    rstudioapi_0.7   xml2_1.1.1      
[17] desc_1.1.1       devtools_1.13.4  tools_3.4.3      stringr_1.2.0    yaml_2.1.16      compiler_3.4.3   memoise_1.1.0   
```

**Comment by ELToulemonde** [comment]
I got back to testthat v1.0.2 and it is working well.

I guess this issue appeared when testthat was updated to v2.0.0

**Comment by jimhester** [comment]
This seem to be https://github.com/r-lib/testthat/issues/700, and to be related to where and how many `context()` calls are in your test file.

In any case it is not a devtools issue, so I will close this.

**Comment by twolodzko** [comment]
@jimhester are you sure? The bug you link mentions usage of `context()`. I haven't set *any* `context()` in the tests that fail. The example given by @ELToulemonde also does not mention using it. Moreover, difference is between calling tests from `devtools::test()` and `testthat::test_dir()` etc., so testthat alone seems to be OK.

**Comment by jimhester** [comment]
Yes, I am sure. The progress reporter assumes a context, those examples don't have one.
