### ISSUE TITLE
Cannot install devtools in R 3.4.3, withr unavailable?

### ISSUE THREAD

**Issue by MarcHiggins** [hadley/devtools#1677]
Hello,

I am trying to install devtools in the most recent version of R (3.4.3). I am unable to load devtools, and I get the error "error: there is no package called withr". I then tried installing the package withr from the url, which also does not work and returns the error "package 'https://cran.studio.com/bin/windows/contrib/3.4/withr_2.1.1.zip’ is not available (for R version 3.4.3)". Would you be able to offer any advice please? I am new to R so excuse me if I am overlooking something simple. Sample code is pasted below.

Thanks,
Marc.

> install.packages("devtools")
Installing package into ‘/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘git2r’, ‘withr’

  There is a binary version available but the source
  version is later:
      binary source needs_compilation
git2r 0.19.0 0.20.0              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/git2r_0.19.0.zip'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/git2r_0.19.0.zip': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/git2r_0.19.0.zip'
Warning in install.packages :
  download of package ‘git2r’ failed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/withr_2.1.0.zip'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/withr_2.1.0.zip': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/withr_2.1.0.zip'
Warning in install.packages :
  download of package ‘withr’ failed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/devtools_1.13.4.zip'
Content type 'application/zip' length 443915 bytes (433 KB)
downloaded 433 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	\AppData\Local\Temp\RtmpcPK2uo\downloaded_packages
> install.packages("https://cran.studio.com/bin/windows/contrib/3.4/withr_2.1.1.zip")
Installing package into ‘/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘https://cran.studio.com/bin/windows/contrib/3.4/withr_2.1.1.zip’ is not available (for R version 3.4.3)
> library(devtools)
Error: package or namespace load failed for ‘devtools’:
 .onLoad failed in loadNamespace() for 'devtools', details:
  call: loadNamespace(name)
  error: there is no package called ‘withr’

**Comment by krlmlr** [comment]
I suspect this is a temporary problem that will resolve itself in a few hours or days.

**Comment by jimhester** [comment]
Both git2r and withr have had new releases in the past couple of days, it looks like your package database is stale. I would try restarting your R session and trying to install devtools again.

**Comment by MarcHiggins** [comment]
Thanks Jim, that worked.
