### ISSUE TITLE
build_vignettes failing to build PDF document 

### ISSUE THREAD

**Issue by gilbertocamara** [hadley/devtools#1679]
Dear Hadley and RStudio team:

I am trying to build a PDF documentation for my package using build_vignettes(), but the output is always an HTML file. Here is a minimum working example:

** start of MWE **
---
title: "Build_test2"
author: "Gilberto Camara"
date: "22/12/2017"
vignette: >
    %\VignetteEngine{knitr::knitr}
    %\VignetteIndexEntry{Build_test2}
    %\VignetteEncoding{UTF-8}
output: pdf_document
---

## R Markdown to PDF

I am trying to build a PDF document,but devtools::clean_vignettes() always creates an HTML document instead.
*** end of MWE ***

When using knitr directly in the RStudio interface, I get a different error. The PDF document is built, but the execution is halted before the intermediate files are cleaned.

*** output of knitr for file above **
Error in tools::file_path_as_absolute(output_file) : 
  file '/private/var/folders/hw/mb8c4xls23ncyndxj_7mhvrc0000gn/T/Rtmpi5Wk3E/preview-2a3c7a3238ca.dir/build_devtools.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
In addition: Warning message:
In file.rename(file_with_ext(texfile, "pdf"), output_file) :
  cannot rename file '/private/var/folders/hw/mb8c4xls23ncyndxj_7mhvrc0000gn/T/Rtmpi5Wk3E/preview-2a3c7a3238ca.dir/build_devtools.pdf' to '/private/var/folders/hw/mb8c4xls23ncyndxj_7mhvrc0000gn/T/Rtmpi5Wk3E/preview-2a3c7a3238ca.dir/build_devtools.pdf', reason 'No such file or directory'
Execution halted
**** 

My session info follows:

--- Session Info ----
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  backports_1.1.1 magrittr_1.5    rprojroot_1.2   htmltools_0.3.6 tools_3.4.3     yaml_2.1.16    
 [8] Rcpp_0.12.14    stringi_1.1.6   rmarkdown_1.8.5 knitr_1.18.2    stringr_1.2.0   digest_0.6.13   evaluate_0.10.1

----- end of SessionInfo ---

Any help would be much appreciated. 

Merry Xmas for you and all RStudio foljs,
Keep the great work!!

Best
Gilberto

**Comment by gilbertocamara** [comment]
Dear Hadley and RStudio team:

I found what the problem was. Instead of 
%\VignetteEngine{knitr::knitr}
it should have been written 
%\VignetteEngine{knitr::rmarkdown}

Sorry for disturbing you. In any case, the RStudio documentation could be a bit improved on this matter.

**Comment by jennybc** [comment]
For the future, `usethis::use_vignette()` is a handy function to initiate a new vignette and it gets all this fiddly stuff set up for you.
