### ISSUE TITLE
Installation failed: An unknown option was passed in to libcurl

### ISSUE THREAD

**Issue by nmattia** [hadley/devtools#1682]
I'm getting errors when trying to install specific package versions with `install_version`:
`Installation failed: An unknown option was passed in to libcurl`

This is run on a pristine Ubuntu 14.04 Trusty. Here's how R was installed:

``` bash
#!/usr/bin/env bash

set -xe

codename=$(lsb_release -c -s)
echo "deb http://cloud.r-project.org/bin/linux/ubuntu $codename/" | sudo tee -a /etc/apt/sources.list > /dev/null
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
sudo apt-get update
sudo apt-get install r-base r-base-dev
R --version
```

Here's the code that was run (nothing else was run prior to that):

``` r
pkgs <- list(
            list(pname="httr", pver="1.2.1"),
            list(pname="DBI",pver= "0.6"),
            list(pname="dplyr",pver= "0.7.2"),
            list(pname="dbplyr",pver= "1.0.0"),
            list(pname="jsonlite",pver= "1.2")
        )

# Use devtool for specifying the package version
install.packages("devtools", repos='http://cran.us.r-project.org')
require(devtools)

# Install all packages with the correct version
lapply(pkgs, function(p) install_version(p$pname, version=p$pver, repos = 'http://cran.us.r-project.org'))
```

```
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/httr/httr_1.2.1.tar.gz
Installation failed: An unknown option was passed in to libcurl
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/DBI/DBI_0.6.tar.gz
Installation failed: An unknown option was passed in to libcurl
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/dplyr/dplyr_0.7.2.tar.gz
Installation failed: An unknown option was passed in to libcurl
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/dbplyr/dbplyr_1.0.0.tar.gz
Installation failed: An unknown option was passed in to libcurl
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/jsonlite/jsonlite_1.2.tar.gz
Installation failed: An unknown option was passed in to libcurl
```

The program `curl` is installed. I've tried installing `libcurl4` (`libcurl4-gnutls-dev` and `libcurl4-openssl-dev`) but nothing helps.

I'm able to curl the addresses (for instance `$ curl http://cran.us.r-project.org/src/contrib/Archive/dbplyr/dbplyr_1.0.0.tar.gz`). What can I do to debug this? is there a _more_ verbose mode for `install_version` than `quiet=FALSE`?

Thanks in advance.

**Comment by bheavner** [comment]
I'm having the same issue with `install_github`, also unsure how to troubleshoot:
```
> devtools::install_github("UW-GAC/wgsaparsr")
Installation failed: An unknown option was passed in to libcurl

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/local/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] httr_1.3.1      compiler_3.4.3  R6_2.2.2        withr_2.1.1    
[5] curl_3.1        memoise_1.1.0   git2r_0.21.0    digest_0.6.14  
[9] devtools_1.13.4
```

**Comment by jimhester** [comment]
I think this is an issue with a mismatch between libcurl versions, see https://github.com/jeroen/curl/issues/129#issuecomment-339730996, and potentially open an issue in the curl repository if you are not able to debug it further.

In any case this is not an issue in the devtools package, so I will close this issue here.

**Comment by htso** [comment]
Any update on this issue. Have exactly the same error. 

> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] PBO_0.1.0       gtools_3.8.1    **devtools_1.13.6**

loaded via a namespace (and not attached):
 [1] httr_1.3.1     compiler_3.4.4 R6_2.2.2       tools_3.4.4   
 [5] withr_2.1.2    **curl_3.2**       yaml_2.2.0     memoise_1.1.0 
 [9] git2r_0.23.0   digest_0.6.16
