### ISSUE TITLE
cran_comments() warning 

### ISSUE THREAD

**Issue by SymbolixAU** [hadley/devtools#1684]
The function `devtools:::cran_comments()` issues this warning if it can't find the `cran-comments.md` file:

> Can't find cran-comments.md. This file gives CRAN volunteers comments about the submission and it must exist

Given that "it must exist", should this actually be an error, rather than a warning? With it being a warning you are still able to submit the package without the `cran-comments.md` file?

**Comment by jimhester** [comment]
It originally was a warning and was changed in https://github.com/hadley/devtools/commit/f541a131bfd41079c1c19bd6f684aafa886eaeac

I tweaked the wording in b85dacd

**Comment by SymbolixAU** [comment]
Thanks. I think that's clearer now.
