### ISSUE TITLE
Installation failed: 404: Not Found

### ISSUE THREAD

**Issue by dtelad11** [hadley/devtools#1685]
Not sure whether this is a `devtools` issue or a problem with the package. Apologies if the latter.

I'm trying to install https://github.com/RGLab/flowCore, getting the following error:

```
> devtools::install_github('RGLab/flowCore')
Downloading GitHub repo RGLab/flowCore@master
from URL https://api.github.com/repos/RGLab/flowCore/zipball/master
Installation failed: 404: Not Found
 (404)
```

I also tried forking and mirroring the repo, getting the same error.

**Comment by dtelad11** [comment]
My bad, the solution was to pull from trunk branch, not master. Sorry for false alarm!

**Comment by SamGG** [comment]
For those who may come here, the solution is
```
library(devtools)
install_github("RGLab/flowCore",ref='trunk')
```
