### ISSUE TITLE
Error when using install_github()

### ISSUE THREAD

**Issue by DocOfi** [hadley/devtools#1692]
Hi,
I just finished crating a mock package for the course Building R Packages. The package passed travis and appveyor.  But when i tried to download it I get the following errors:

> install_github("DocOfi/FARSread-Package", build_vignettes = TRUE)
Downloading GitHub repo DocOfi/FARSread-Package@master
from URL https://api.github.com/repos/DocOfi/FARSread-Package/zipball/master
Installing FARSread
Installation failed: formal argument "repos" matched by multiple actual arguments
Downloading GitHub repo tidyverse/rlang@master
from URL https://api.github.com/repos/tidyverse/rlang/zipball/master
Installation failed: not a namespace
Installation failed: formal argument "repos" matched by multiple actual arguments
Installation failed: formal argument "repos" matched by multiple actual arguments
Running command C:/PROGRA~1/R/R-34~1.1/bin/x64/Rcmd.exe 
Arguments:
build
C:\Users\user\AppData\Local\Temp\RtmpY5QwG7\devtools1c9879915e51\DocOfi-FARSread-Package-2982c44
--no-resave-data
--no-manual
* checking for file 'C:\Users\user\AppData\Local\Temp\RtmpY5QwG7\devtools1c9879915e51\DocOfi-FARSread-Package-2982c44/DESCRIPTION' ... OK
* preparing 'FARSread':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warning: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR
Quitting from lines 162-163 (functions-readfars.Rmd) 
Error: processing vignette 'functions-readfars.Rmd' failed with diagnostics:
object 'rlang_quo_get_expr' not found
Execution halted
Installation failed: System command error
Warning message:
In if (!is_loaded(package)) return(NULL) :
  the condition has length > 1 and only the first element will be used

BUT when I omit the argument  build_vignettes = TRUE I get the following errors but actually have the package installed.  I checked it and it's working.

> install_github("DocOfi/FARSread-Package")
Downloading GitHub repo DocOfi/FARSread-Package@master
from URL https://api.github.com/repos/DocOfi/FARSread-Package/zipball/master
Installing FARSread
Installation failed: formal argument "repos" matched by multiple actual arguments
Downloading GitHub repo tidyverse/rlang@master
from URL https://api.github.com/repos/tidyverse/rlang/zipball/master
Installation failed: not a namespace
Installation failed: formal argument "repos" matched by multiple actual arguments
Installation failed: formal argument "repos" matched by multiple actual arguments
Running command C:/PROGRA~1/R/R-34~1.1/bin/x64/Rcmd.exe 
Arguments:
INSTALL
"C:/Users/user/AppData/Local/Temp/RtmpqeE79i/devtools1eb836ce3a3d/DocOfi-FARSread-Package-02e8ae8"

* installing to library 'C:/Users/user/Documents/R/win-library/3.4'
* installing *source* package 'FARSread' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (FARSread)
Warning messages:
1: In if (!is_loaded(package)) return(NULL) :
  the condition has length > 1 and only the first element will be used
2: In if (!is_attached(package)) return(NULL) :
  the condition has length > 1 and only the first element will be used

I thought it might be happening only to my package but when i tried it on another package in GitHub, i get the same error

> library(devtools)
> install_github('ramnathv/slidify')
Downloading GitHub repo ramnathv/slidify@master
from URL https://api.github.com/repos/ramnathv/slidify/zipball/master
Installing slidify
Installation failed: formal argument "repos" matched by multiple actual arguments
Installation failed: formal argument "repos" matched by multiple actual arguments
Running command C:/PROGRA~1/R/R-34~1.1/bin/x64/Rcmd.exe 
Arguments:
INSTALL
"C:/Users/user/AppData/Local/Temp/RtmpQpKlqM/devtools13045f2a26ec/ramnathv-slidify-1dd41a3"

* installing to library 'C:/Users/user/Documents/R/win-library/3.4'
* installing *source* package 'slidify' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (slidify)
Warning message:
In if (!is_attached(package)) return(NULL) :
  the condition has length > 1 and only the first element will be used

I'm on windows 7 64 bit operating system
R version 3.4.1 (2017-06-30) -- "Single Candle"
Platform: x86_64-w64-mingw32/x64 (64-bit)

I was able to install RTools and only now got a TRUE output from has_devel()
> library(devtools)
> find_Rtools()
Error in find_Rtools() : could not find function "find_Rtools"
> library(pkgbuild)
> find_rtools()
[1] TRUE
> has_devel()
[1] TRUE

But when i try to click on Build and reload tab in RStudio I get:
==> devtools::document(roclets=c('rd', 'collate', 'namespace', 'vignette'))

Updating FARSread documentation
Error in path.expand(path) : invalid 'path' argument
Calls: suppressPackageStartupMessages ... <Anonymous> -> get_start_path -> normalizePath -> path.expand
Execution halted

Exited with status 1

I'm sorry if this is too long but i tried to search for answers and I 'm facing a brick wall. I cloned the repo in another directory and i'll try to see if i can make that work.  Thanks A lot.

**Comment by DocOfi** [comment]
Hi,

I'm still getting the same error.  Is there anything you can advise me to do?

**Comment by jimhester** [comment]
What version of devtools do you have installed?

**Comment by DocOfi** [comment]
Thank you for your kind reply.  from the package help page: Documentation for package ‘devtools’ version 1.13.3.9000

**Comment by jimhester** [comment]
I would suggest re-installing devtools from CRAN in a fresh R session.

```r
install.packages("devtools")
```

**Comment by DocOfi** [comment]
Thanks!
 I also tried installing ggplot2 from github and got this error.  Just in case you can make something of it.

> devtools::install_github('hadley/ggplot2')
Downloading GitHub repo hadley/ggplot2@master
from URL https://api.github.com/repos/hadley/ggplot2/zipball/master
Installing ggplot2
Downloading GitHub repo r-lib/cli@master
from URL https://api.github.com/repos/r-lib/cli/zipball/master
Installing cli
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Downloading GitHub repo r-lib/ansistrings@master
from URL https://api.github.com/repos/r-lib/ansistrings/zipball/master
Installing ansistrings
Downloading GitHub repo r-lib/cli@master
from URL https://api.github.com/repos/r-lib/cli/zipball/master
Skipping cli, it is already being installed.
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Downloading GitHub repo MangoTheCat/rematch2@master
from URL https://api.github.com/repos/MangoTheCat/rematch2/zipball/master
Installing rematch2
Downloading GitHub repo r-lib/cli@master
from URL https://api.github.com/repos/r-lib/cli/zipball/master
Skipping cli, it is already being installed.
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Running command C:/PROGRA~1/R/R-34~1.1/bin/x64/Rcmd.exe 
Arguments:
INSTALL
C:/Users/user/AppData/Local/Temp/RtmpMPTQpC/devtools9e832831acd/MangoTheCat-rematch2-180fb61
--library=C:/Users/user/Documents/R/win-library/3.4
--install-tests

* installing *source* package 'rematch2' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (rematch2)
Running command C:/PROGRA~1/R/R-34~1.1/bin/x64/Rcmd.exe 
Arguments:
INSTALL
C:/Users/user/AppData/Local/Temp/RtmpMPTQpC/devtools9e839db49a1/r-lib-ansistrings-f27619b
--library=C:/Users/user/Documents/R/win-library/3.4
--install-tests

* installing *source* package 'ansistrings' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c map.c -o map.o
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o ansistrings.dll tmp.def map.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.1/bin/i386 -lR
installing to C:/Users/user/Documents/R/win-library/3.4/ansistrings/libs/i386

*** arch - x64
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c map.c -o map.o
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o ansistrings.dll tmp.def map.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.1/bin/x64 -lR
installing to C:/Users/user/Documents/R/win-library/3.4/ansistrings/libs/x64
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (ansistrings)
Downloading GitHub repo r-lib/progress@master
from URL https://api.github.com/repos/r-lib/progress/zipball/master
Installing progress
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Running command C:/PROGRA~1/R/R-34~1.1/bin/x64/Rcmd.exe 
Arguments:
INSTALL
C:/Users/user/AppData/Local/Temp/RtmpMPTQpC/devtools9e8452658d4/r-lib-progress-97f2c4e
--library=C:/Users/user/Documents/R/win-library/3.4
--install-tests

* installing *source* package 'progress' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (progress)
Running command C:/PROGRA~1/R/R-34~1.1/bin/x64/Rcmd.exe 
Arguments:
INSTALL
C:/Users/user/AppData/Local/Temp/RtmpMPTQpC/devtools9e848105baa/r-lib-cli-1b58269
--library=C:/Users/user/Documents/R/win-library/3.4
--install-tests

* installing *source* package 'cli' ...
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (cli)
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Downloading GitHub repo tidyverse/rlang@master
from URL https://api.github.com/repos/tidyverse/rlang/zipball/master
Installing rlang
Running command C:/PROGRA~1/R/R-34~1.1/bin/x64/Rcmd.exe 
Arguments:
INSTALL
C:/Users/user/AppData/Local/Temp/RtmpMPTQpC/devtools9e86fe93697/r-lib-rlang-c6747f9
--library=C:/Users/user/Documents/R/win-library/3.4
--install-tests

* installing *source* package 'rlang' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I./lib/    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c capture.c -o capture.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I./lib/    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c export.c -o export.o
In file included from export/init.c:242:0,
                 from export.c:3:
export/../internal/expr-interp.h:11:20: warning: 'uq_names' defined but not used [-Wunused-variable]
 static const char* uq_names[UQ_N] = { "UQ", "!!" };
                    ^
export/../internal/expr-interp.h:12:20: warning: 'uqe_names' defined but not used [-Wunused-variable]
 static const char* uqe_names[UQE_N] = { "UQE" };
                    ^
export/../internal/expr-interp.h:19:20: warning: 'fixup_ops_names' defined but not used [-Wunused-variable]
 static const char* fixup_ops_names[FIXUP_OPS_N] = {
                    ^
export/../internal/expr-interp.h:22:20: warning: 'fixup_unary_ops_names' defined but not used [-Wunused-variable]
 static const char* fixup_unary_ops_names[FIXUP_UNARY_OPS_N] = {
                    ^
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I./lib/    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c internal.c -o internal.o
In file included from internal/arg.c:2:0,
                 from internal.c:1:
internal/expr-interp.h:11:20: warning: 'uq_names' defined but not used [-Wunused-variable]
 static const char* uq_names[UQ_N] = { "UQ", "!!" };
                    ^
internal/expr-interp.h:19:20: warning: 'fixup_ops_names' defined but not used [-Wunused-variable]
 static const char* fixup_ops_names[FIXUP_OPS_N] = {
                    ^
internal/expr-interp.h:22:20: warning: 'fixup_unary_ops_names' defined but not used [-Wunused-variable]
 static const char* fixup_unary_ops_names[FIXUP_UNARY_OPS_N] = {
                    ^
In file included from internal.c:4:0:
internal/expr-interp.c: In function 'call_interp_impl':
internal/expr-interp.c:318:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I./lib/    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c lib.c -o lib.o
In file included from lib.c:16:0:
lib/parse.c: In function 'r_op_as_c_string':
lib/parse.c:386:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
C:\Rtools\mingw_32\bin\nm.exe: lib.c: File format not recognized
C:\Rtools\mingw_32\bin\nm.exe: internal.c: File format not recognized
C:\Rtools\mingw_32\bin\nm.exe: export.c: File format not recognized
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o rlang.dll tmp.def capture.o export.o internal.o lib.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.1/bin/i386 -lR
installing to C:/Users/user/Documents/R/win-library/3.4/rlang/libs/i386

*** arch - x64
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I./lib/    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c capture.c -o capture.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I./lib/    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c export.c -o export.o
In file included from export/init.c:242:0,
                 from export.c:3:
export/../internal/expr-interp.h:11:20: warning: 'uq_names' defined but not used [-Wunused-variable]
 static const char* uq_names[UQ_N] = { "UQ", "!!" };
                    ^
export/../internal/expr-interp.h:12:20: warning: 'uqe_names' defined but not used [-Wunused-variable]
 static const char* uqe_names[UQE_N] = { "UQE" };
                    ^
export/../internal/expr-interp.h:19:20: warning: 'fixup_ops_names' defined but not used [-Wunused-variable]
 static const char* fixup_ops_names[FIXUP_OPS_N] = {
                    ^
export/../internal/expr-interp.h:22:20: warning: 'fixup_unary_ops_names' defined but not used [-Wunused-variable]
 static const char* fixup_unary_ops_names[FIXUP_UNARY_OPS_N] = {
                    ^
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I./lib/    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c internal.c -o internal.o
In file included from internal/arg.c:2:0,
                 from internal.c:1:
internal/expr-interp.h:11:20: warning: 'uq_names' defined but not used [-Wunused-variable]
 static const char* uq_names[UQ_N] = { "UQ", "!!" };
                    ^
internal/expr-interp.h:19:20: warning: 'fixup_ops_names' defined but not used [-Wunused-variable]
 static const char* fixup_ops_names[FIXUP_OPS_N] = {
                    ^
internal/expr-interp.h:22:20: warning: 'fixup_unary_ops_names' defined but not used [-Wunused-variable]
 static const char* fixup_unary_ops_names[FIXUP_UNARY_OPS_N] = {
                    ^
In file included from internal.c:4:0:
internal/expr-interp.c: In function 'call_interp_impl':
internal/expr-interp.c:318:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I./lib/    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c lib.c -o lib.o
In file included from lib.c:16:0:
lib/parse.c: In function 'r_op_as_c_string':
lib/parse.c:386:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
C:\Rtools\mingw_64\bin\nm.exe: lib.c: File format not recognized
C:\Rtools\mingw_64\bin\nm.exe: internal.c: File format not recognized
C:\Rtools\mingw_64\bin\nm.exe: export.c: File format not recognized
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o rlang.dll tmp.def capture.o export.o internal.o lib.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.1/bin/x64 -lR
installing to C:/Users/user/Documents/R/win-library/3.4/rlang/libs/x64
Warning in file.copy(files, dest, overwrite = TRUE) :
  problem copying .\rlang.dll to C:\Users\user\Documents\R\win-library\3.4\rlang\libs\x64\rlang.dll: Permission denied
** R
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
Error: package or namespace load failed for 'rlang':
 .onLoad failed in loadNamespace() for 'rlang', details:
  call: dots_list(...)
  error: object 'rlang_dots_list' not found
Error: loading failed
Execution halted
ERROR: loading failed for 'x64'
* removing 'C:/Users/user/Documents/R/win-library/3.4/rlang'
* restoring previous 'C:/Users/user/Documents/R/win-library/3.4/rlang'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\user\Documents\R\win-library\3.4\00LOCK-r-lib-rlang-c6747f9\rlang\libs\x64\rlang.dll to C:\Users\user\Documents\R\win-library\3.4\rlang\libs\x64\rlang.dll: Permission denied
Installation failed: run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),      stderr_line_callback = real_callback(stderr), stdout_callback = real_block_callback,      stderr_callback = real_block_callback, echo_cmd = echo, echo = show,      spinner = spinner, error_on_status = fail_on_status, timeout = timeout) : System command error
Running command C:/PROGRA~1/R/R-34~1.1/bin/x64/Rcmd.exe 
Arguments:
INSTALL
C:/Users/user/AppData/Local/Temp/RtmpMPTQpC/devtools9e84d9b5f82/tidyverse-ggplot2-a2dc248
--library=C:/Users/user/Documents/R/win-library/3.4
--install-tests

* installing *source* package 'ggplot2' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error : 'enexprs' is not an exported object from 'namespace:rlang'
Error : unable to load R code in package 'ggplot2'
ERROR: lazy loading failed for package 'ggplot2'
* removing 'C:/Users/user/Documents/R/win-library/3.4/ggplot2'
* restoring previous 'C:/Users/user/Documents/R/win-library/3.4/ggplot2'
Installation failed: run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),      stderr_line_callback = real_callback(stderr), stdout_callback = real_block_callback,      stderr_callback = real_block_callback, echo_cmd = echo, echo = show,      spinner = spinner, error_on_status = fail_on_status, timeout = timeout) : System command error

**Comment by DocOfi** [comment]
Hi,
I did as you suggested and was able to successfully install devtools and was able to use install_github.

Thanks for your help.
