### ISSUE TITLE
build() fails if getOption("repos") is too long

### ISSUE THREAD

**Issue by ijlyttle** [hadley/devtools#1695]
I am finding a strange error when I use `build()` from the command line. It appears when I add "too many" repositories to `options(repos = ...)` in my .Rprofile.

I chased the error down to this line:

https://github.com/hadley/devtools/blob/2e3c4b692e3aecd7a4fd746e3000db1f4aa706bd/R/R.r#L41

Here are my repos:

```R
options(
  repos = c(
    CRAN = "https://cran.rstudio.com/",
    SERAN = "https://pages.github.schneider-electric.com/SE-AAP-R/SERAN/",
    EMRAN = "https://pages.github.schneider-electric.com/SE-AAP-R/SERAN2/"
  ),
  ...
)
```

When I run `dput(getOption("repos"))` I get:
```
structure(c("https://cran.rstudio.com/", "https://pages.github.schneider-electric.com/SE-AAP-R/SERAN/", 
"https://pages.github.schneider-electric.com/SE-AAP-R/SERAN2/"
  ...
```

As you can see, the output is truncated. This is consistent with the error I get from `build()`.

I googled for "dput truncation" and found that @mdsumner (who I hope will not mind me tagging him) has already produced these:

https://github.com/mdsumner/dputtruncat/blob/master/README.md

https://gist.github.com/mdsumner/129f7290f90ec424275222897bf0d3bd

I'm afraid I don't have any suggestions - none of the `dput()` control options look applicable (but I could be wrong).

**Comment by jimhester** [comment]
This should not be an issue if you use `pkgbuild::build()`, which is what devel devtools uses.

**Comment by ijlyttle** [comment]
@jimhester Thanks! The best sort of bugs are the ones that are already fixed!
