### ISSUE TITLE
Problem when using RcppArmadillo

### ISSUE THREAD

**Issue by DiogoFerrari** [hadley/devtools#1699]
I am using RcppArmadillo, with  arma namespace. When I use 

    devtools::document()

It does not recognize the arma namespace and produces the error

error: ‘arma’ has not been declared

I am using in my .cpp files the arma::... to use its objects as usual, and also 

using namespace arma;

Using sourceCpp() it compiles and runs ok.

Would you know what is going on?

**Comment by shrektan** [comment]
you should declare the linking in the DESCRIPTION file

**Comment by DiogoFerrari** [comment]
Yes, of course. That works. Thanks

**Comment by DiogoFerrari** [comment]
Ok, I had to generate the folders using RcppArmadillo.package.skeleton(). If I copy the Makevars file generated by that function to the src folder generated by devtools::use_rcpp(), it works. Then, `devtools::document()` works in the folder generated by devtools. The Makevars contains:

    CXX_STD = CXX11

    PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS) 
    PKG_LIBS = $(SHLIB_OPENMP_CFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
 
I think it give a clue for the solution.

**Comment by jimhester** [comment]
Sounds like this is fixed then
