### ISSUE TITLE
Include incorrect roxygen2 tag in devtools::check()?

### ISSUE THREAD

**Issue by jrosen48** [hadley/devtools#1701]
I have a question about whether something could / ought to be included in the tests / checks run by `devtools::check()`.

I made a mistake when using the **roxygen2** tag `importFrom`. In particular, in an R file, I included the tag:

`importFrom tibble`

Instead of `importFrom tibble tibble`

According, when I used `devtools::document()`, the following line was added to the `NAMESPACE` file:

`importFrom(tibble,)`

I think this caused problems with installing the package for some users with devtools::install_github()`.

What do you think of adding a check for this - either in terms of the **roxygen2** tag or the `NAMESPACE` file? If this is not sensible for any reason, please feel welcome to close this. Thanks.

**Comment by jimhester** [comment]
This feels like a roxygen2 issue rather than a devtools issue, Ideally roxygen2 would fail if the tag is defined incorrectly in this case. I encourage you to open an issue at https://github.com/klutometis/roxygen
