### ISSUE TITLE
devtools::test() throws strange error

### ISSUE THREAD

**Issue by paul-buerkner** [hadley/devtools#1704]
When running `devtools::test()` on the brms package (https://github.com/paul-buerkner/brms), I get the following error at the end even if all tests are passing:

```R
error in x[[method]](...) : try to apply a non-function
```

Moreover, it constantly reports 4 failing tests, even if none are really failing when running them manually or with R CMD Check. I think, the problem began after updating to the latest version of testthat so I am not sure really, where the error comes from.

**Comment by jimhester** [comment]
There is an issue with the new default reporter when you do not have a `context()` block, which none of your test files seems to have.

https://github.com/r-lib/testthat/issues/700

**Comment by paul-buerkner** [comment]
Thanks!
