### ISSUE TITLE
Update packages directly from github/bitbucket etc

### ISSUE THREAD

**Issue by imanuelcostigan** [hadley/devtools#387]
Rather than going through CRAN, it would be nice to be able to update packages that are available on public / private repos (with the usual authentication). 

Functionally this could mean writing a new function (say `update_packages()`) that is a wrapper for `update.packages()` plus another function that checks whether there are any newer commits on master branches of repos from which packages have previously been installed. 

It might be necessary to be able to maintain a record of such packages. And it might be necessary to run `check()` before installing.

Is this sort of talk verboten (i.e. will this be unpalatable to some influential members of the R dev community) or could it be accommodated?

Is there a reason why this isn't already happening more officially? (cf. to  homebrew on OSX)

**Comment by hadley** [comment]
This is out of scope of devtools, but I agree that it's an important. I think there are some other initiatives in progress where this will happen naturally - it's a common use case, and we won't forget about it.

**Comment by leeper** [comment]
This function has been implemented in [dtupdate](https://github.com/hrbrmstr/dtupdate).
