### ISSUE TITLE
Optionally roxygenize (or execute custom R code) before build

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#397]
As requested in https://github.com/hadley/devtools/issues/43#issuecomment-30662304.

In order to avoid having to manage `.Rd` files at GitHub, at lest the `install_github()` routine (probably also `build()`) should support roxygenization before build. Execution of custom R code is a plus, but not necessary for this feature.

To start, I'd suggest supporting a field `Devtools: list(document = TRUE)` in `DESCRIPTION`. During `build` this field is examined, and `devtools::document('.')` is executed after unpacking but before the call to `R CMD build`. As `devtools` already suggests `roxygen2`, no immediate action in terms of dependency management is needed.

Build-time dependencies could be supported by a new field `BuildDepends:` in `DESCRIPTION`, with the same syntax as `Depends:`. For the given use case this is probably overkill, but it could be useful for specifying generic pre-build code by e.g. `Devtools: list(pre_build = Rd2roxygen::rab('.'))`.

The `document` parameter to `check` could be made obsolete.

**Comment by hadley** [comment]
I think this is best handled elsewhere. Currently `install_github()` is a very common way to install packages and having to run additional code before installation is going to add a lot of complexity.

**Comment by krlmlr** [comment]
Would you support an argument `document = TRUE` for `build()`?
