### ISSUE TITLE
Automated bumping of version numbers

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#594]
- [ ] Run `document()`
- [ ] Update `DESCRIPTION`
- ~~Update `<package>-index.R`~~
- [ ] Add prefix to `NEWS.md`
- [ ] Run `document()` once more
- [ ] Run package-specific actions
- ~~Auto-commit (subject to #593)~~
- ~~Create tag (subject to #593)~~

**Comment by hadley** [comment]
I'm generally not super excited about this, because I don't think it's hard to do by hand, and updating the NEWS (and all the variations) is going to be hard.  I'll still review a PR though

**Comment by krlmlr** [comment]
It's not hard to do by hand, but if it's automated you can assign new version identifiers more often, and it's less error-prone.

Updating `NEWS.d` works for me by means of a [`NEWS.md.tmpl`](https://github.com/krlmlr/kimisc/blob/5537fa864ce06c344eef8d057f0d3e3315e3dc8f/NEWS.md.tmpl) file with placeholders for version and date. The file (with placeholders expanded) is prepended to `NEWS.md`. I'd add also a function that creates this `.tmpl` file and adds it to `.Rbuildignore`. How do you like this approach?

**Comment by hadley** [comment]
It just feels too complicated and fragile to me :/

**Comment by hadley** [comment]
But maybe I'm being needlessly negative, because `use_package()` is fragile in a similar way
