### ISSUE TITLE
"Cyclic dependency check skipped" in release()

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#602]
When I call `devtools::release()`, at some point during the check process the following message appears:

```
Package has help file(s) containing install/render-stage \Sexpr{} expresssons but no prebuilt PDF manual.
* checking package namespace information ... OK
* checking package dependencies ... NOTE
  No repository set, so cyclic dependency check skipped
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
```

I'm not sure if the `NOTE` about package dependencies is related to the note about the `\Sexpr`-s. With `check(cran = TRUE)` these notes are not shown.

**Comment by hadley** [comment]
How does this work on travis? You can set a CRAN env var there.

**Comment by hadley** [comment]
Related to #678

**Comment by krlmlr** [comment]
We seem to need all of the three above -- our own `.Rprofile`, setting the env var *and* changing command-line arguments. The `.Rprofile` would look like this:

```
options(repos=c(CRAN="http://cran.rstudio.com"))
```

**Comment by hadley** [comment]
Seems like we should modify `R()` and `RCMD()` to do that?

It might be possible to just do it via env vars, by setting `R_ENVIRON`, `R_ENVIRON_USER`, `R_PROFILE`, `R_PROFILE_USER` etc. I think it requires a close reading of `?Startup` to figure out what the best process is.  

Maybe we can drop `--vanilla` in favour of ignoring user files, and overriding the location of `R_PROFILE` to something we create?
