### ISSUE TITLE
devtools::load_all() may fail when S4 class definitions are in different files

### ISSUE THREAD

**Issue by Geoff99** [hadley/devtools#623]
Hi
This is similar to something I tried to raise in #550, but in the previous issue I confused two different aspects of my problem when I try to use the devtools package development sequence, so I am trying again, just concentrating on explaining the aspect that causes devtools to fail for me.

If I create a simple example project and add two files in the R directory as follows
a.r is 

```r
#' @include b.r
Class2 <- setClass('Class2',contains='Class1')
```

and b.r is 

```
Class1 <- setClass('Class1')
```

then when I try to run load_all() on this package I get the following error messages

```
> library(devtools)
> load_all()
Loading loadallExample
Error in reconcilePropertiesAndPrototype(name, slots, prototype, superClasses,  (from a.r#2) : 
  no definition was found for superclass “Class1” in the specification of class “Class2”
> 
```

The problem arises because although I have the @include directive in my file a.r, it has not yet been processed, so load_all() attempts to read the code from the files in alphabetical order.

I still get an error if I try and run devtools::document('.'), as seen here

```
> document('.')
Updating loadallExample documentation
Loading loadallExample
Error in reconcilePropertiesAndPrototype(name, slots, prototype, superClasses,  (from a.r#2) : 
  no definition was found for superclass “Class1” in the specification of class “Class2”
> 
```

And because of the error while loading, the document('.') does not finish, and does not update the collate entry in the package DESCRIPTION file.

A solution is to run roxygen2::update_collate() before trying to load_all() or document() my package

```
> roxygen2::update_collate('.')
Updating collate directive in  ./DESCRIPTION 
> load_all()
Loading loadallExample
> 
```

The updated collate entry in the DESCRIPTION file created by roxygen2::update_collate tells load_all() (and all the other devtools machinery) the correct order to process the files in.

I can avoid this problem myself now I know what causes it, but as an absolute novice package creator it really confused me for ages. In my real life example the alphabetic order of the file names was not so obvious, and when I tried to pin the error down by commenting out bits of code, it enabled devtools::document to run successfully.  Then when I removed the commenting out, the original code would behave nicely, making the problem appear only intermittently and very frustratingly.  It would be nice if some fix of the type I have illustrated could be included in the official devtools.

Thanks

Geoff

 PS I'm still pretty much a novice package creator (waiting keenly for the book to be finished and published), just a little more informed about this particular problem.

PPS Because roxygen2::update_collate emits a message when it runs, I think simply adding a call to roxygen2::update_collate into the code for load_all may cause some of the testthat tests on devtools to fail (because they are not expecting that particular message to be there)

PPPS I have tried to write a testhat for devtools to check that the collate order is *correct* and up to date.  The testthat code is

```
test_that("Collate sequence is uptodate, and @includes have been recognised", {
  # Make a temporary clean copy of the test package, in order to
  #   avoid (unwanted here but usually beneficial) side_effects
  #   namely that devtools::load_all may update the collate order in the
  #   DESCRIPTION file
  clean_testCollateOrder <- file.path(tempdir(),'testCollateOrder')
  dir.create(clean_testCollateOrder)
  test_pkg_files <- c('testCollateOrder/DESCRIPTION',
                      'testCollateOrder/NAMESPACE',
                      'testCollateOrder/R')
  file.copy(test_pkg_files,clean_testCollateOrder,recursive=TRUE)

  expect_message(load_all(clean_testCollateOrder), "Loading testCollateOrder")

  expect_equal(a, 1) #even though b.r set it to 2

  unload(clean_testCollateOrder)
  unlink(clean_testCollateOrder,recursive=TRUE)
})  
```

It requires a template project (which I have called testCollateOrder) with a plain vanilla DESCRIPTION file
```
Package: testCollateOrder
Title: Confirm that the collate order is uptodate
Version: 0.1
Authors@R: "Geoff Lee<geoff.lee99@bigpond.com> [aut, cre]"
Description: load_all fails with an error when S4 classes with inheritance
  are read in the wrong order.  This package checks that all @includes
  have been recognised and processed by roxygen2,
  so that the collate order in the DESCRIPTION file is uptodate
Depends: R (>= 3.1.1)
License: What license is it under?
LazyData: true
```
The key feature is that there is no collate entry in the file yet.

The two files in the R directory are 
a.r
```
#' @include b.r
a <- 1
```

and b.r

```
a <- 2
```

The test will succeed if the @include directive has been recognised so that a.r is read after b.r

**Comment by Geoff99** [comment]
Hi @hadley 

Not sure if it is the correct protocol to comment on a closed issue but I'd like to reopen the issue / suggest an additional change.  

The `test_that` (from pull request #649) `load_all()` recognises and processes the `@include` generated collate order is still failing, even though load_all now includes a call to `roxygen2::update_collate`.

It appears that as well as calling `update_collate` to create / refresh the Collate field in the DESCRIPTION file, `devtools` also needs to refresh the `pkg$collate` entry in the `pkg` list / structure so that the remainder of the `load_all()` code is aware that the collate order has been generated / refreshed and is (possibly) non-alphabetical.

The following extra line (after the commented explanation) does this

`roxygen2::update_collate(pkg$path)`
`#Refresh the pkg structure with any updates to the Collate entry`
`#in the DESCRIPTION file`
`pkg <- as.package(pkg$path)`

**Comment by hadley** [comment]
Can you please refile a pull request with that change and the tests?

**Comment by Geoff99** [comment]
Sure, I’ll be happy to.

 

Will be later today (my time) before I get chance to make sure I’ve got everything neat and tidy

 

Geoff

**Comment by Geoff99** [comment]
Please see pull request #649 

Happy to make any adjustments you want

Geoff
