### ISSUE TITLE
Adding repository name to package description

### ISSUE THREAD

**Issue by Mullefa** [hadley/devtools#626]
It would be convenient to have an argument in `devtools::build()` which can be used to append a `Repository` field to the `DESCRIPTION` file; or more generally, a named list specifying field-value pairs to append to the `DESCRIPTION` file. Here is some example code:

```R
build <- function(path, ..., repos) {
  if (is.null(repos)) {
    return(devtools::build(path, ...))
  }
  desc_path <- file.path(path, "DESCRIPTION")
  desc <- add_repos_to_desc(desc_path, repos)
  on.exit(write_dcf(desc_path, desc))
  devtools::build(path, ...)
}

add_repos_to_desc <- function(path, repos) {
  desc <- read_dcf(path)
  if (!("Repository" %in% names(desc))) {
    write.dcf(data.frame(Repository = repos), path, append = TRUE)
  }
  desc
}
```

The use case is to facilitate deployment to CRAN-like repositories. If this isn't the right way to achieve this, I'd be keen to hear alternatives.

Cheers.

**Comment by hadley** [comment]
I think that's a reasonable approach, but I'd prefer to hold off on including this in devtools. I need more time to think about the problem in general
