### ISSUE TITLE
Return useful information from check()

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#639]
- [ ] Errors
- [ ] Warnings
- [ ] Notes
- [ ] Path to `R CMD check` results (if `cleanup` is `FALSE`)

Could return an S3 class with a `print` method (and perhaps an `as.logical` method for backward compatibility).

Use case: Better support for CI services.

@hadley: Would you review a pull request?

**Comment by krlmlr** [comment]
Would you consider exporting `check_failures()`?

**Comment by hadley** [comment]
Sure, PR?
