### ISSUE TITLE
Should install_github() et al. use call install() with local = FALSE?

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#655]
Is there an advantage of calling `install()` with `local = TRUE` (the default) for a package that has been downloaded e.g. from GitHub and extracted to a temporary directory? If not, I think it would be good to have `local = FALSE` by default in this case, in order to be closer to the standard installation procedure (e.g., building vignettes; cf. #344).

Any opinions?

**Comment by hadley** [comment]
I'm probably going to change my vignette policy - I think it makes more sense to treat them like documentation, and store a rendered copy in the package.

**Comment by krlmlr** [comment]
Storing a `.md` file is helpful, but do you really want to store binary PDF or virtually binary HTML files?

**Comment by hadley** [comment]
It's your choice, with your .gitignore, but I think there are good reasons to store html files
