### ISSUE TITLE
Error with setClassUnions in load_all()

### ISSUE THREAD

**Issue by jayweiler** [hadley/devtools#657]
Similarly to #168 , I am encountering an issue with `setClassUnion` when running `devtools::load_all(".") `

To reproduce, I create an empty project in rstudio, and in an R file have:

```
setClassUnion("DataFrameOrLogical", c("data.frame","logical"))
setClassUnion("DateOrLogical", c("Date", "logical"))

setClass("A",representation(slotA= "DataFrameOrLogical"))
setClass("B",representation(slotB="DateOrLogical"))
```

Running `devtools::load_all(".")` appears to work fine initially.

Then I build with command+shift+B and get no errors.

Following that, all calls to devtools::load_all(".") error out with:

```
Error in .walkClassGraph(ClassDef, "contains", where, attr(ext, "conflicts")) : 
  the 'superClass' list for class “logical”, includes an undefined class “DateOrLogical”
Error in setClassUnion("DataFrameOrLogical", c("data.frame", "logical")) (from testError.R#1) : 
  unable to create union class:  could not set members "logical"
```

As you can see, it would appear that the "DateOrLogical" definition is somehow being preserved in the super class of the "logical". 

Any help would be wonderful. Thanks so much.

**Comment by prise6** [comment]
Hi, i don't know if this bug was fixed in later versions but it's still there for R 3.2.0.
FYI, same issue with: 
```
> devtools::session_info()
Session info ----------------------
 setting  value                       
 version  R version 3.2.0 (2015-04-16)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.902)          
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris  
```
