### ISSUE TITLE
run_examples does not like sub-folders

### ISSUE THREAD

**Issue by kwstat** [hadley/devtools#665]
My package man folder has a sub-folder called "figures".

When I try to use run_examples on the package, I get this:

```
R> devtools::run_examples("c:/x/rpack/agridat")
Updating agridat documentation
Loading agridat
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'c:\x\rpack\agridat/man/figures': Permission denied
```

The problem here is likely not properly in run_examples, but somewhere down the calling stack where the list of files to check is created.  I started to follow down the called sub-functions and found this (edited):
```
8: FUN(c("c:\\x\\rpack\\agridat/man/#burgueno.alpha.Rd#", "c:\\x\\rpack\\agridat/man/#yates.oats.Rd#", 

   "c:\\x\\rpack\\agridat/man/archbold.apple.Rd", "c:\\x\\rpack\\agridat/man/archbold.apple.Rd~", 

   "c:\\x\\rpack\\agridat/man/fan.stability.Rd", "c:\\x\\rpack\\agridat/man/federer.diagcheck.Rd", 

   "c:\\x\\rpack\\agridat/man/federer.tobacco.Rd", "c:\\x\\rpack\\agridat/man/figures", 
```

My suggestion is to limit this list to only files matching ".Rd$" and ".rd$" (any others???) so that the following file types are ignored:
1. subdirectories
2. emacs backup files that end in a tilde
3. emacs auto-save files that start/end with hash
4. .git files? 
5. etc.

**Comment by hadley** [comment]
It already does:

```R
rd_files <- function(pkg) {
  path_man <- file.path(pkg$path, "man")
  files <- dir(path_man, pattern = "\\.[Rr]d$", full.names = TRUE)
  names(files) <- basename(files)
  with_collate("C", sort(files))
}
```
