### ISSUE TITLE
would like something like with_package

### ISSUE THREAD

**Issue by colablikje** [hadley/devtools#671]
sometimes I need to use commands that rely heavily on an external function. E.g.:
httr::GET(apiURL, httr::add_headers(Authorization = sessiontoken, Accept = "application/json"))

although I can write it like this, I a, wondering if a "with_package" function could be developed that would allow me to write this call as
with_package("httr", GET(apiURL, add_headers(Authorization = sessietoken, Accept = "application/json"))

would that be possible, or is there a better solution?

**Comment by hadley** [comment]
You could do something like this:

```R
with(as.environment("package:httr"), GET("http://google.com"))
```

but that requires that you attach the package first

**Comment by wch** [comment]
I think `with(as.environment("package:httr"), GET(url))` won't work as expected, since it won't be able to find the `url` variable in the httr package environment.

**Comment by hadley** [comment]
Here's a better approach:

```R
with_package <- function(pkg, code) {
  env <- getNamespaceInfo(pkg, "exports")
  eval(substitute(code), envir = env)
}
with_package(httr, GET("http://google.com"))
```

but it still suffers from the problem that @wch identified. I don't think there's a general way of avoiding the problem, expect maybe attaching then detaching the package. Either way, I don't think this function is suitable for devtools.

**Comment by wch** [comment]
Here's an example that illustrates the problem. It needs to be in a function to more closely simulate code running in a package; if you run it at the console, the behavior will be different because the global environment is in the search path of the httr namespace.

```R
foo <- function() {
  x <- 10
  with(asNamespace("httr"), print(x))
}

foo()
#  Error in print(x) : object 'x' not found 


# If you use as.environment('package:httr'), you get a different error when httr isn't
# already attached
foo2 <- function() {
  x <- 10
  with(as.environment("package:httr"), print(x))
}
foo2()
# Error in as.environment("package:httr") : 
#   no item called "package:httr" on the search list
```

I can't think of a good way in general to accomplish what's being asked for -- as far as I can tell, this requires manipulating the search path.
