### ISSUE TITLE
Encoding issue with devtools on Windows

### ISSUE THREAD

**Issue by VUarrota** [hadley/devtools#676]
Greetings from VUarrota

I'm getting a problem when installing a hyperChemoBridge in R (windows machine)
Looking at the error message, It seems that it tries to install in a folder with ‘Virgilio’ (accent on the i).
But the error occurs when it tries to access a folder called “Virgmlio” where the accented i has become an m.

some one can help me

```R
> install_github(repo = "Chathurga/HyperChemoBridge",ref = "devel")
Downloading github repo Chathurga/HyperChemoBridge@devel
Installing hyperChemoBridge
"C:/PROGRA~1/R/R-31~1.2/bin/i386/R" --vanilla CMD INSTALL  \
  "C:\Users\Virgílio\AppData\Local\Temp\RtmpclBFBe\devtools1a107863463d\Chathurga-HyperChemoBridge-5e993b4"  \
  --library="C:/Users/Virgílio/Documents/R/win-library/3.1" --install-tests 

* installing *source* package 'hyperChemoBridge' ...
Warning in file(file, ifelse(append, "a", "w")) :
  cannot open file 'C:/Users/Virgmlio/Documents/R/win-library/3.1/hyperChemoBridge/DESCRIPTION': No such file or directory
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package 'hyperChemoBridge'
* removing 'C:/Users/Virgílio/Documents/R/win-library/3.1/hyperChemoBridge'
Error: Command failed (1)
```

**Comment by wch** [comment]
@hadley I suspect this doesn't fix the root problem. I experimented a bit with the problem, and I think even if you try this on Windows, it fails when the path contains a non-ASCII character:

```R
system('R --vanilla CMD INSTALL /path/to/package')
```

(Note that this is from memory; I haven't looked at it in a few weeks.) If this is right, then I don't think there's a good way to solve the issue.

**Comment by hadley** [comment]
@wch yes, but `normalizePath` should convert any weird path to the 8.3 short form, avoiding the problem.

**Comment by wch** [comment]
Oh, maybe you're right. It's hard to believe that resorting to 8.3 filenames is still the solution to filename troubles in Windows!
