### ISSUE TITLE
Why does devtools:::R use --vanilla?

### ISSUE THREAD

**Issue by kenahoo-windlogics** [hadley/devtools#678]
In another ticket I just opened (https://github.com/hadley/testthat/issues/199), I poked around in `devtools:::R()` version 1.6.1 and noticed that it calls R with the `--vanilla` flag.  This means it's not loading the site-wide Renviron, which is where we set our local `R_LIBS_USER` variable:

```
% cat /opt/R-3.1.1/lib64/R/etc/Renviron.site
R_LIBS_USER=/opt/R3.1-lib:~/R/x86_64-unknown-linux-gnu-library/3.1
```

Perhaps it would be more appropriate to use `--no-save --no-restore --quiet` instead?  The effect, for me, is that the build finds its prereqs and succeeds:

```
[spstat01:/tmp/Rtmp7u2sT0] % '/opt/R-3.1.1/lib64/R/bin/R' --vanilla CMD INSTALL '/home/kwilliams/git/AMGUtils' --library='/tmp/Rtmp7u2sT0' --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec --no-multiarch --no-test-load
ERROR: dependencies ‘FNN’, ‘ggplot2’, ‘lubridate’, ‘Rcpp’, ‘stringr’, ‘testthat’, ‘zoo’ are not available for package ‘AMGUtils’
* removing ‘/tmp/Rtmp7u2sT0/AMGUtils’

[spstat01:/tmp/Rtmp7u2sT0] % '/opt/R-3.1.1/lib64/R/bin/R' --no-save --no-restore --quiet CMD INSTALL '/home/kwilliams/git/AMGUtils' --library='/tmp/Rtmp7u2sT0' --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec --no-multiarch --no-test-load
* installing *source* package ‘AMGUtils’ ...
** libs
g++ -I/opt/R-3.1.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/opt/R3.1-lib/Rcpp/include"   -fpic  -g -O2  -c window.cpp -o window.o
/opt/R3.1-lib/Rcpp/include/Rcpp/Date.h: In member function ‘void Rcpp::Date::update_tm()’:
/opt/R3.1-lib/Rcpp/include/Rcpp/Date.h:108: warning: converting to ‘time_t’ from ‘double’
/opt/R3.1-lib/Rcpp/include/Rcpp/Date.h: In function ‘Rcpp::Date Rcpp::operator+(const Rcpp::Date&, int)’:
/opt/R3.1-lib/Rcpp/include/Rcpp/Date.h:139: warning: converting to ‘time_t’ from ‘double’
g++ -shared -L/usr/local/lib64 -o AMGUtils.so RcppExports.o window.o -L/opt/R-3.1.1/lib64/R/lib -lR
installing to /tmp/Rtmp7u2sT0/AMGUtils/libs
* DONE (AMGUtils)
```

(FYI - this was previously filed as https://github.com/hadley/testthat/issues/200 and then moved here).

**Comment by hadley** [comment]
The choice of `--vanilla` was deliberate because we want to ignore the user files. But maybe ` --no-init-file --no-environ` would be adequate

**Comment by kenahoo-windlogics** [comment]
I think you'd still want `--no-save --no-restore` too, or else you could really mess up the user's workspace.

What's the reason for wanting to ignore the user files though?

**Comment by hadley** [comment]
Because people often load packages in their `.Rprofile`, and set up other stuff that's not the same as on CRAN.

**Comment by kenahoo-windlogics** [comment]
People also use config files to set basic facts about their environment though, e.g. if they don't have administrative rights on the box, they may need to point R to their library locations.

If `~/.Rprofile` isn't read, then it seems prudent to give the non-admin user *some* way to set options for R startup - the only other thing I can think of would be to set the `R_PROFILE` environment variable to some userspace file and use that to set things up.  Similarly with `R_ENVIRON`.  That seems like a misuse of those mechanisms though, and encouraging people to change their `~/.Rprofile` to something less invasive might be a good idea.

The `Startup` help page in R has this to say about the matter:

> If you want ‘~/.Renviron’ or ‘~/.Rprofile’ to be ignored by child R processes (such as those run by R CMD check and R CMD build), set the appropriate environment variable R_ENVIRON_USER or R_PROFILE_USER to (if possible, which it is not on Windows) "" or to the name of a non-existent file.

This seems to imply that people should expect those files to be read during building & testing unless explicitly turned off.

**Comment by hadley** [comment]
Setting `R_PROFILE` might be a reasonable thing to do. But the reality is that most people developing packages have not read ?Startup, and have lots of junk in that file. So this mostly reduces problems rather than causing them. But I take your point that some users need extra control.

**Comment by hadley** [comment]
It doesn't anymore!  

However, there's no command line option to say skip user files and not site files, so I don't think this will solve your problem.  But devtools is usually pretty good about parsing on your R library, so maybe you could provide a bit more context about where this problem crops up?

**Comment by hadley** [comment]
Feel free to re-open with more details.
