### ISSUE TITLE
Mysterious "Error: Command failed (1)"

### ISSUE THREAD

**Issue by kenahoo-windlogics** [hadley/devtools#679]
UPDATE, TL/DR: it would be nice to let the caller of `test()` choose between `load_all(pkg, quiet = TRUE))` or `load_all(pkg, quiet = FALSE))`.  Currently it's hard-coded to `quiet=TRUE`, which can make it hard to see what the problem is.

(Migrated from https://github.com/hadley/testthat/issues/199.)

Sometimes when I try to test a package in RStudio, I get the following response:
```
> test()
Testing AMGUtils
Error: Command failed (1)
```

I can get a stack trace like so:

```
> traceback()
10: stop("Command failed (", status, ")", call. = FALSE)
9: system_check(r_path, options, c(r_env_vars(), env_vars), ...)
8: force(code)
7: in_dir(path, system_check(r_path, options, c(r_env_vars(), env_vars), 
       ...))
6: R(paste("CMD", cmd, options), path = path, env_vars = env_vars, 
       ...)
5: RCMD("INSTALL", c(shQuote(pkg$path), paste("--library=", shQuote(dest), 
       sep = ""), no_args, "--no-multiarch", "--no-test-load", args), 
       quiet = quiet)
4: install_min(pkg, tempdir(), components = "libs", args = if (needs_clean(pkg)) "--preclean", 
       quiet = quiet)
3: compile_dll(pkg, quiet = quiet)
2: load_all(pkg, quiet = TRUE)
1: test()
```

I stepped through using the debugger, and in the `system_check()` call I see this:

```
Browse[2]> full
[1] "'/opt/R-3.1.1/lib64/R/bin/R' --vanilla CMD INSTALL '/home/kwilliams/git/AMGUtils' --library='/tmp/RtmpZdCcCw' --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec --no-multiarch --no-test-load"
Browse[2]> 
debug: if (quiet) {
    status <- attr(result, "status") %||% 0
} else {
    status <- result
}
Browse[2]> 
debug: status <- attr(result, "status") %||% 0
Browse[2]> result
[1] "g++ -I/opt/R-3.1.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I\"/opt/R3.1-lib/Rcpp/include\"  -UNDEBUG -Wall -pedantic -g -O0 -fpic  -g -O2  -c window.cpp -o window.o"
attr(,"status")
[1] 1
```

If I go look in the temp directory `/tmp/RtmpZdCcCw`, I only see a couple of `.rds` files, none of the package files.  If I try the INSTALL command manually in that directory, I get some errors about Rcpp:

```
[spstat01:/tmp/RtmpZdCcCw] % '/opt/R-3.1.1/lib64/R/bin/R' --vanilla CMD INSTALL '/home/kwilliams/git/AMGUtils' --library='/tmp/RtmpZdCcCw' --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec --no-multiarch --no-test-load
* installing *source* package ‘AMGUtils’ ...
** libs
g++ -I/opt/R-3.1.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/home/kwilliams/R/library/Rcpp/include"   -fpic  -g -O2  -c window.cpp -o window.o
Error: package ‘Rcpp’ was built before R 3.0.0: please re-install it
Execution halted
g++ -shared -L/usr/local/lib64 -o AMGUtils.so RcppExports.o window.o -L/opt/R-3.1.1/lib64/R/lib -lR
Error: package ‘Rcpp’ was built before R 3.0.0: please re-install it
Execution halted
installing to /tmp/RtmpZdCcCw/AMGUtils/libs
* DONE (AMGUtils)
```

Looks like it's picking up stuff in an old `~/R/library` directory.  So I moved that out of the way, tried again, and got this error again:

```
> test()
Testing AMGUtils
Error: Command failed (1)
```

Back in the shell, I see this:

```
[spstat01:/tmp/Rtmp7u2sT0] % '/opt/R-3.1.1/lib64/R/bin/R' --vanilla CMD INSTALL '/home/kwilliams/git/AMGUtils' --library='/tmp/Rtmp7u2sT0' --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec --no-multiarch --no-test-load
ERROR: dependencies ‘FNN’, ‘ggplot2’, ‘lubridate’, ‘Rcpp’, ‘stringr’, ‘testthat’, ‘zoo’ are not available for package ‘AMGUtils’
* removing ‘/tmp/Rtmp7u2sT0/AMGUtils’
```

So these are understandable errors, but it would be great if they were exposed in the R console rather than having to dig through with the debugger to find out what's going on.

Perhaps the easiest way would be to let the caller of `test()` choose between `load_all(pkg, quiet = TRUE))` or `load_all(pkg, quiet = FALSE))`?  Currently it's hard-coded to `quiet=TRUE`.

**Comment by hadley** [comment]
I don't understand why this is a problem. Why not just do `load_all()` to diagnose the problem?

**Comment by kenahoo-windlogics** [comment]
Well, it's just not an obvious step to take (at least it wasn't to me!) since `test()` doesn't document that it calls `load_all()`, so I didn't even understand until I started poking around in the debugger (and truthfully, not even then, until you mentioned it) that manually calling `load_all()` would be helpful.

Why the reluctance to pass the errors through to the user, at least when explicitly requested, though?  In general, if some piece of software spits out an error saying "some mysterious error happened, go try to figure it out, but you're on your own" that's a pretty good sign that it could probably find something more helpful to say.  It seems like an easy way to throw the user a helpful bone.  But perhaps a mention in the help page for `test()` would be just as good if you prefer that.
