### ISSUE TITLE
Show size of uploaded archive before submission in release()

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#683]
This just hit me -- some test artifacts were ignored in `.gitignore` but not in `.Rbuildignore` and unnecessarily increased the file size by a large factor.

Perhaps a listing of the directories, too?

(On the other hand, you can always rerun `release()` without clicking on the confirmation link, that arrives by e-mail, so this is probably of minor importance.)

**Comment by gaborcsardi** [comment]
Don't you get warnings/notes for these from `check()`?

**Comment by krlmlr** [comment]
I do get warnings if the vignette is too large and can be compressed. I didn't notice any warnings about a substantially larger size of the archive.

**Comment by hadley** [comment]
I would have thought existing warnings would have picked this up too. But displaying the archive size prior to the upload question would work well

**Comment by hadley** [comment]
It'd be useful if could give me the output of `git clean -n` in order to help me understand when this problem occurs

**Comment by krlmlr** [comment]
In this case, `git clean -nx` would have shown lots of stuff in the `tests` directory -- ignored via `.gitignore` but forgot to ignore via `.Rbuildignore`. (`git clean -n` would have been empty.)

**Comment by wch** [comment]
I think you also need `-d`, as in `git clean -nxd` so that if there are any subdirs, they'll be listed as well.

**Comment by hadley** [comment]
I'd be happy to review a PR that printed the file size before uploading
