### ISSUE TITLE
install_github(): default argument for auth_token

### ISSUE THREAD

**Issue by Mullefa** [hadley/devtools#687]
As recommended, I have set the environment variable `GITHUB_PAT`. This allows me to install packages from my company github without having to pass my `auth_token` explicitly. However, if I try and install a package from public github I get an error:

```R
devtools::install_github("hadley/devtools")

# Using github PAT from envvar GITHUB_PAT
# Downloading github repo hadley/devtools@master
# Error in download(dest, src, auth) : client error: (401) Unauthorized
```

This can of course be mitigated by setting `auth_token = NULL`, however, this seems like a bit of a hassle. Could instead the default for the `auth_token` argument be something like:

```R
auth_token = if (host == "api.github.com") NULL else github_pat()
```

**Comment by hadley** [comment]
Oh hmmm, that is a problem. Your fix won't work for me, since I use a PAT for public git to increase the standard API limits. We probably need two distinct env vars

**Comment by hadley** [comment]
I'd be happy to review a PR if you want to add an alternative env var

**Comment by Mullefa** [comment]
Sure thing. Have you got any preference for their names? GITHUB_PAT and GITHUB_PAT_ENT?

**Comment by hadley** [comment]
Sounds reasonable to me
