### ISSUE TITLE
source_gist() function not working

### ISSUE THREAD

**Issue by timothyslau** [hadley/devtools#689]
When I try to run `source_gist("https://gist.github.com/jmcastagnetto/2253d846af1c60f5c0da")`
similar to the package example `source_gist("https://gist.github.com/hadley/6872663")`, R gives an error:
> Error in function (type, msg, asError = TRUE)  : 
> SSL certificate problem, verify that the CA cert is OK. Details:
> error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by hadley** [comment]
What OS are you using?

**Comment by timothyslau** [comment]
Windows 7 Enterprise SP1 & if I run it on Mac OSX 10.10 I get:
>Error in structure(as.daxmlToList(xmlParse(response, asText = TRUE)),  :
> could not find function "as.daxmlToList"

**Comment by hadley** [comment]
Make sure you have the latest versions of RCurl and httr.  The OS X problem doesn't sound like it's coming from devtools.

**Comment by timothyslau** [comment]
Updated packages tried:
source_gist("https://gist.github.com/jmcastagnetto/2253d846af1c60f5c0da")

Got:
Sourcing https://gist.githubusercontent.com/jmcastagnetto/2253d846af1c60f5c0da/raw/2869a425de08ed70b743e424023ae17fe79268cd/nist-beacon-response.R
SHA-1 hash of file is eeb9a91d9e3c46d96e0da51c22b6f81aaf9e9c1c
 Show Traceback
 
 Rerun with Debug
 Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem: unable to get local issuer certificate

Clicked "Show Traceback" got:
11 fun(structure(list(message = msg, call = sys.call()), class = c(typeName, 
    "GenericCurlError", "error", "condition"))) 
10 function (type, msg, asError = TRUE) 
{
    if (!is.character(type)) {
        i = match(type, CURLcodeValues) ... 
9 curlPerform(curl = curl, .opts = opts, .encoding = .encoding) 
8 getURL(url, headerfunction = headers$update) at C:\Users\t0lau001\AppData\Local\Temp\RtmpeyFTvT\file17d811f1783f#15
7 NISTBeaconResponse(ts) at C:\Users\t0lau001\AppData\Local\Temp\RtmpeyFTvT\file17d811f1783f#49
6 eval(expr, envir, enclos) 
5 eval(ei, envir) 
4 withVisible(eval(ei, envir)) 
3 source(temp_file, ...) 
2 source_url(url, ..., sha1 = sha1) 
1 source_gist("https://gist.github.com/jmcastagnetto/2253d846af1c60f5c0da")

**Comment by timothyslau** [comment]
This might be an issue with the Gist code rather than **source_gist** I'm not sure how to tell.

**Comment by timothyslau** [comment]
Scratch that, It is an issue with the gist, not source_gist. Sorry to bother you.

**Comment by timothyslau** [comment]
Linux vs Windows issue apparently ;(
https://gist.github.com/jmcastagnetto/2253d846af1c60f5c0da
