### ISSUE TITLE
Check local repo is up-to-date in release()

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#691]
@wch do you know how to do this? (i.e. I want to make sure there aren't commits on remote that I need to pull)

**Comment by wch** [comment]
Maybe a `git fetch` and then compare SHAs for HEAD and the tracking branch?

Or maybe parse the output of `git branch -vv`, as suggested at http://stackoverflow.com/a/12538667/412655

```
$ git branch -vv
* master cd0a739 [origin/master: ahead 1] Update license information
```

**Comment by hadley** [comment]
Done (mostly) in 14cca3f5
