### ISSUE TITLE
Would it be possible to drop Rcurl dependency?

### ISSUE THREAD

**Issue by vspinu** [hadley/devtools#701]
Rcurl has non-standard dependencies as it relies on dev libraries (`libcurl-gnutls-dev` or `libcurl-openssl-dev`) which are not part of default installation on linux servers.  I am currently stuck without devtools on a linux server for which I don't have sudo rights and so far IT (for unclear reason to me) was not able to install those libraries.

**Comment by Ironholds** [comment]
What alternative would you propose?

**Comment by vspinu** [comment]
```
download.file("https://github.com/hadley/devtools/archive/master.zip", "devtools.zip", "curl")
```

**Comment by gaborcsardi** [comment]
`"curl"` is not portable I guess. And the rest do not support https. But FIXME.

**Comment by wch** [comment]
The [downloader](http://cran.r-project.org/web/packages/downloader/index.html) package is meant to make it possible to download via https on the various platforms. But this isn't enough to remove the httr dependency from devtools. In devtools, httr is used for more than just downloading files. For example:
https://github.com/hadley/devtools/blob/b064918e42548cdf478a89aee69f6d05960b33d0/R/release.r#L260-L266

**Comment by hadley** [comment]
It might be possible to drop in 3.2 since curl is now bundled, but devtools is always going to need httr (which needs curl) for github API stuff.
