### ISSUE TITLE
Delete generated files?

### ISSUE THREAD

**Issue by noamross** [hadley/devtools#703]
I occasionally have problems that are resolved by deleting files generated in package building, which include

- Rcpp attribute-generated files: RcppExports.R/.cpp, inst/includes (Most issues are these)
- Roxygen man files, NAMESPACE (sometimes issues originate here)
- Vingettes, etc.

It would be nice to have one function (+ button in RStudio) to delete these files, as they are spread around the package directory.  Most have a comment indicating their origin so it should be easy to detect which should be removed.

**Comment by hadley** [comment]
I've never had a problem with Rcpp generated files. I think you'd be best to report any problems with that directly to Rcpp.

Otherwise, roxygen automatically deletes man files when you re-document, and you can't delete the NAMESPACE because that often yields an un-loadable package.
