### ISSUE TITLE
index.html for vignettes

### ISSUE THREAD

**Issue by schloerke** [hadley/devtools#705]
Currently in [ggobi/ggally@vignette](https://github.com/ggobi/ggally/pull/56), I can not pass ``check()`` as it fails to find an ``index.html`` file.

```
...
* installing *source* package ‘GGally’ ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
Warning in file(con, "w") :
  cannot open file '/Users/barret/Copy/git/R/ggobi_org/ggally/GGally.Rcheck/GGally/doc/index.html': No such file or directory
Error in file(con, "w") : cannot open the connection
ERROR: installing vignettes failed
```

Am I missing a step?  I thought R would auto compile the ``index.html`` file for me.

I have a single ``.Rmd`` file in the ``ggally/vignettes`` folder that builds.  This file is successfully compiled, then ``check()`` fails to find the index file.

Thank you,
Barret

**Comment by hadley** [comment]
https://github.com/ggobi/ggally/blob/master/.Rbuildignore#L2 ;)

**Comment by schloerke** [comment]
ha!.... Thank you

**Comment by schloerke** [comment]
@llhh000 Add `..Rcheck` to your .Rbuildignore file.
