### ISSUE TITLE
Issue behind Proxy

### ISSUE THREAD

**Issue by saptarshiguha** [hadley/devtools#706]
Hello,
Does install_github use git or curl? i ask because I get a 404 not found despite the repo being present.
I am behind a proxy with HTTP_PROXY, HTTPS_PROXY and git proxies set (in .gitconfig)

> library(devtools)
> install_github("tesseradata/datadr")
Installing github repo(s) tesseradata/datadr/master from hadley
Downloading tesseradata/datadr.zip from https://github.com/hadley/tesseradata/datadr/archive/master.zip
Error: client error: (404) Not Found

Regards
Saptarshi

**Comment by hadley** [comment]
It uses curl, via httr. Are you sure you have the latest devtools, because that url looks wrong (i.e. there shouldn't be a hadley in it)

**Comment by saptarshiguha** [comment]
You are correct. Updated and it works now.
Thanks much.
