### ISSUE TITLE
install_version issues with DCF/continuation lines

### ISSUE THREAD

**Issue by andrewblim** [hadley/devtools#709]
Running R 3.1.2 on OS X 10.10.1. 

I've observed that on some packages, but not all, `install_version` gives me an error about continuation lines. An example that I ran into: 

- `install_version('RcppEigen', '0.3.2.1.2')` gives me an error `Error: Found continuation line starting '   The RcppEigen pac ...' at begin of record.`
- `install_version('BH', '1.54.0-2')` is no problem

It seems like an issue with `read.dcf` and continuation lines in DESCRIPTION that contain only a period, to indicate a blank line. The above version of RcppEigen happens to have two of these lines in DESCRIPTION, but BH does not. 

I debugged `read.dcf`. It's called 3 times during `install_version`, twice to an identical file in `/var/folders/...` that looks like a temp directory, and once to a nearly identical path but in `/private/var/folders/...` Weirdly, the version in `/private/var/folders/...` seems to have had the period lines replaced with total blank lines, and `.Internal(readDCF(...))` fails, presumably because it reads the next line as a start-of-record line. 

I can download and install the old version of RcppEigen with `R CMD INSTALL` just fine.

**Comment by drknexus** [comment]
bump.  also see https://github.com/eddelbuettel/drat/issues/1.  Issue also bites with install_github on https://github.com/lianos/buckshot

**Comment by hadley** [comment]
Closed in ed3475f117b768cd5f14b8fca1b72cdc0717a32f

**Comment by andrewblim** [comment]
Thank you!
