### ISSUE TITLE
Implement "install_gitlab"

### ISSUE THREAD

**Issue by barryrowlingson** [hadley/devtools#716]
[GitLab](about.gitlab.com) hosts unlimited private and public repositories, and looks like a good alternative to github. Can we have, in the spirit of `install_github`, an `install_gitlab` function?

Currently the following seem to work:

```
install_git("git@gitlab.com:b-rowlingson/rgitlab.git")
install_git("https://gitlab.com/b-rowlingson/rgitlab.git")
```

so I guess it would be just wrapping those. GitLab's code is open source and it is possible to set up a local GitLab server. 

Maybe there are enough `install_{online service}` functions already?

**Comment by hadley** [comment]
I'd be happy to review a pull request.

**Comment by bheavner** [comment]
https://twitter.com/jimhester_/status/1003727023385333761
