### ISSUE TITLE
Possible bug in install_local under RStudio on Windows

### ISSUE THREAD

**Issue by tom-n-pdx** [hadley/devtools#718]
My build script for our research teams is failing on only one user's windows system with an error on the install_local() command.

The script successfully uses devtools build to build the source package and then when it tries to load it - it gets the error message:

cygwin warning:
  MS-DOS style path detected: C:\Users\Sam\AppData\Local\Temp\RtmpSE6FO8\file8e014a26e8b/TFDEA_0.9.9.tar.gz
  Preferred POSIX equivalent is: /cygdrive/c/Users/Sam/AppData/Local/Temp/RtmpSE6FO8/file8e014a26e8b/TFDEA_0.9.9.tar.gz
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
Error: Does not appear to be an R package (no DESCRIPTION)

The path produced by build after it's normalized is: C:\Users\Sam\Desktop\TFDEA\tfdea\TFDEA_0.9.9.tar.gz. THis is what I pass to install_local().

He can manually load that package and it is a valid source package. He's running under the most recent RStudio & R on windows.

I'm testing on Linux & Mac - it works fine. Other windows users have used the build script and it works fine.

I suspect it's a interaction between his system configuration and how the local_install() copies things to temp - but I am not sure what to check.

**Comment by hadley** [comment]
Any chance there's an `&` in the path?

**Comment by tom-n-pdx** [comment]
Humm.. no - there wasn't a & in the path

I'll check the latest version and see if problem is still there.

tom


On Tue, Apr 21, 2015 at 7:29 AM, Hadley Wickham <notifications@github.com>
wrote:

> Any chance there's an & in the path?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/devtools/issues/718#issuecomment-94814480>.
>



-- 
tom shott <tshott@pdx.edu>, Portland State University

*http://www.pdx.edu/extreme-technology-analytics/
<http://www.pdx.edu/extreme-technology-analytics/>*mobile
503-970-7341
*google cal *  tshott@pdx.edu

**Comment by hadley** [comment]
The fact that it shows the warning mentioning nodosfilewarning is suspicious - in regular operation, devtools sets the env var to suppress that message.

**Comment by wleepang** [comment]
FYI:
I'm on a windows machine with R 3.1.2 for development and I had this issue occur today with devtools 1.7.1.

To resolve, I:

* removed MingGW from my PATH.
* (re)installed Rtools3.2
* upgraded devtools to 1.9.1
