### ISSUE TITLE
Check DESCRIPTION title formatting

### ISSUE THREAD

**Issue by jemus42** [hadley/devtools#722]
This is a very minor issue, but while I tried to submit my package to CRAN, they noted that the `Title:` should be in title case, and embarrassingly enough it took me two tries to get it right.

Since I now feel very bad for wasting volunteer time on formalities, I wonder whether a simple check for that could be added to avoid future mishaps.

**Comment by hadley** [comment]
The problem is that it's really hard to test if something has been correctly title-cased. The rules are complicated

**Comment by jemus42** [comment]
I understand.

If it's not feasible/worth the effort, I'd agree to closing the issue.

**Comment by wch** [comment]
The development version of R has this check built in. If you run `check()` on R-devel, you'll see this warning. Also, if you run `build_win()` on your package before submitting it to CRAN, it will automatically run `R CMD check` on R-devel and send you the results.

**Comment by briatte** [comment]
> The problem is that it's really hard to test if something has been correctly title-cased. The rules are complicated

How about comparing the title to the results of `tools::toTitleCase(title)` and sending a warning if they differ?
