### ISSUE TITLE
install_git hanging on Windows RStudio

### ISSUE THREAD

**Issue by lucacerone** [hadley/devtools#725]
Hi, I am trying to setup my Windows environment to use devtools, but I am having
a hard time in having install_git to work.

I installed R, Rtools and then I installed RStudio. After that I installed git (from here http://git-scm.com/download/win, which also include ssh and ssh-keygen etc...). In Rstudio ssh seems to work, if I clone a repository with an R project, and create a project in Rstudio I can commit, push and pull from within Rstudio.

Next I installed devtools:
install.packages(devtools, dependencies = TRUE)
build_github_devtools()
restart R
install.packages("devtools.zip", repos = NULL)

and everything goes fine, I receive the message:

package ‘devtools’ successfully unpacked and MD5 sums checked

but next when I do:

install_git("ssh_path_here")

devtools hangs after displaying the message

"Downloading git repo ....."

Is this normal? I have no idea how to debug the issue and check whether is a configuration issue on my side (probable), an Rstudio bug or a devtools bug.

**Comment by lucacerone** [comment]
I also tried to use install_git("https:/address.git") but the effect is the same.

**Comment by scheuchzer** [comment]
What was your solution? I'm having the same issue here when installing from a private Git repository.
