### ISSUE TITLE
Feature request: include location information in error message of `load_all()`

### ISSUE THREAD

**Issue by rappster** [hadley/devtools#733]
Would it be possible to have the errors thrown upon a failed `load_all()` include the name of the file containing the code that led to the error? 

After a bit of refactorin, I had a repeated formal argument somewhere in my code:

> Loading rapi
Error in parse(text = lines, n = -1, srcfile = srcfile) : 
  repeated formal argument 'api' on line 30

But solely from the information given in the error message, it was pretty hard finding the actual lines of code.

So I had to step through my files and manually source them, and eventually this came up:

> Error in source("~/code/public/rapp2/rapi/R/createClassInstances_ref.R") : 
  repeated formal argument 'api' on line 30
> devtools::load_all(".")

It'd be great if you could include similar "location information" in the error message of `load_all()`.

Thanks in case you should consider this.

**Comment by hadley** [comment]
They should already do that. I tried creating a parse error in devtools and got:

```R
> devtools::load_all(".")
 Error in parse(text = lines, n = -1, srcfile = srcfile) (from source.r#24) : 
  /Users/hadley/Documents/devtools/devtools/R/source.r:35:0: unexpected end of input
33:   invisible()
34: }
   ^ 
```
