### ISSUE TITLE
install_git not working with ssh addresses copied from Github on Windows.

### ISSUE THREAD

**Issue by lucacerone** [hadley/devtools#735]
I finally figured out why install_git hangs on Windows machines.

If I use

```
library(devtools)
install_github("hadley/memoise")
```
it works fine both on Windows and  Unix.

If I use

```
install_git("git@github.com:hadley/memoise.git")
```
it works fine on my Linux installations (Debian, Ubuntu and Arch), but it doesn't work on
Windows.

However if I modify slightly the address to be:

```
install_git("git://github.com/hadley/memoise.git")
```
it works just fine on both platforms.

For sharing code with people that are not used to git, I think this add an extra layer of difficulty,
and I guess it would be great to have a consistent behaviour on both platforms.

Cheers,
Luca

**Comment by wch** [comment]
`install_github` and `install_git` work in different ways: `install_github` downloads a zip file from github, while `install_git` does a `git clone --depth=1`.

As for the difference between the `git://` and the `git@github.com` repo addresses, the latter uses ssh, so my guess is that you have some sort of ssh issue on Windows. Have you tried doing a git clone of the ssh address from the command line in Windows? Something like:

```
git clone git@github.com:hadley/memoise.git
```

**Comment by lucacerone** [comment]
Hi @wch I think one of the possible causes of errors is becuase in Windows you have both a
USERPROFILE variable and a HOME variable; on my computer HOME was set to the same path
where the .ssh folder with the public and private keys are, but USERPROFILE was not.

I got confused, because if I asked RStudio to see the public key, it was shown just fine, 
but then running `system("git clone gitrepo .") didn't work, while git works just fine in both
git-bash and cmd.exe.

Changing HOME and USERPROFILE to be the same and where .ssh is, fixed the issue for me.

Anyway, in the event install_git doesn't find the proper key, I think it should return an Error rather
thank hanging and blocking R (possibly suggesting to fix the environment variable); does that make sense?

**Comment by wch** [comment]
That does make sense. Although if it's `git` that's hanging, there's not much that devtools can do about it.
