### ISSUE TITLE
build_vignette fails quietly if no knitr available

### ISSUE THREAD

**Issue by barryrowlingson** [hadley/devtools#736]
I have a package with a knitr-built .Rnw vignette, pulled it to a new machine with the latest R and devtools. Build the vignette:

     > build_vignettes("./colloc/")
     NULL

Nothing happens. Hmm. Try command line:

     Error in loadVignetteBuilder(pkgdir, TRUE) : 
       vignette builder 'knitr' not found

Installing knitr fixes the build_vignettes call.

Could `build_vignettes` produce an informative message as R CMD build does?

**Comment by hadley** [comment]
I just call `tools::buildVignettes()` so I'm a bit mystified as to why it doesn't complain. 

What do you think about automatically installing the vignette builder package if needed?
