### ISSUE TITLE
Pass git arguments to `install_github`?

### ISSUE THREAD

**Issue by richfitz** [hadley/devtools#737]
The `args` argument to `devtools::install_git` is useful for installing from repositories that include submodules (as discussed in #306), but I don't see that it's possible to pass this along to `devtools::install_github`.  Is this just feature bloat?  Or worth having a `git_args` argument?

**Comment by ashander** [comment]
This would be helpful, and avoid issues for some folks (e.g., https://github.com/armstrtw/rzmq/issues/15 ). But, the implementation of `install_github` relies on github zipballs -- which don't include submodules.

So, a change in implementation would be needed. The first of the options below seems simplest: 

* `git clone --recursive` to a temp dir and use `install_git`
* Use approach mentioned in [this SO thread on the topic](http://stackoverflow.com/questions/12936014/include-a-github-submodule-automatically-in-download) to parse `.gitmodules`, download several zipballs and build a single one.

**Comment by hadley** [comment]
Unfortunately I don't think `install_github()` can rely on having git installed locally.
