### ISSUE TITLE
Update Rtools detection for Rtools 3.3

### ISSUE THREAD

**Issue by jjallaire** [hadley/devtools#738]
Need to do two things:

- Add Rtools\bin to the PATH (you don't add the gcc directories like you used to)
- Set an RTOOLS environment variable to the location of Rtools (e.g. C:/Rtools33/). Note that forward slashes and the trailing slash are required.

Similar work was done for:

- Rcpp: https://github.com/RcppCore/Rcpp/pull/274
- RStudio: https://github.com/rstudio/rstudio/blob/45df6cbb483cc03471d8094b323984d7576b7640/src/cpp/core/r_util/RToolsInfo.cpp#L109-L120

**Comment by dtenenba** [comment]
I guess you don't want to do this anymore (at least not yet); sounds like Rtools33 is going to roll back to using gcc 4.6.3.
