### ISSUE TITLE
Feature Request: allow install_deps to accept multiple src directories

### ISSUE THREAD

**Issue by skyebend** [hadley/devtools#741]
I have build/testing scripts that need to  install dependencies of a bunch of packages in local src files. (so I can CRAN checks on all of the reverse-depending packages of my about-to-be-submitted packages). The install_deps function is awesome, but I'd love to be able to pass it a vector of package src directories and have it loop over them to determine the set of (often largely overlapping) Dependencies for all of them together before moving on to the install stage.  (This is especially important when trying to use ncpus args to speed up the process).  Or maybe there is a better way to do this? Thanks for all the great work on devtools!

**Comment by hadley** [comment]
How about `lapply(c(path1, path2), install_deps)` ?

**Comment by skyebend** [comment]
if package C is a Dependency of packages A and B, won't lapply(c(A, B), install_deps)  calculate the set of dependencies for A and B independently in parallel, and so install C twice?

**Comment by hadley** [comment]
Nope, the installs happen in series.
