### ISSUE TITLE
Issue + found the place for "error in running command" in install_github()

### ISSUE THREAD

**Issue by laurikoobas** [hadley/devtools#742]
install_github() just fails, with every package.
````
> devtools::install_github("RcppCore/Rcpp")
Downloading github repo RcppCore/Rcpp@master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) :
  error in running command
````

After some digging around it seems that I had not installed unzip package to my Cygwin.
The command that failed was `system_check()` in R/system.R [link](https://github.com/hadley/devtools/blob/32ee83341a9fe7b414c255b6004d20e16083dbaf/R/system.r#L21).

The error message, if quite mode is turned off, is:
````
sh: /usr/bin/unzip: No such file or directory
Error: Does not appear to be an R package (no DESCRIPTION)
````

It would be useful to check for the presence of unzip and give a better error message, but I don't know exactly how to do that (or I would make a pull request instead).

**Comment by hadley** [comment]
Did you have Rtools installed? You shouldn't need any cygwin config.

**Comment by laurikoobas** [comment]
Nope. I started to use R in cygwin just today and didn't know to install Rtools first.
Besides: package ‘Rtools’ is not available (for R version 3.1.2). I guess I could go and download 3.1.3 and install that from source or something.

**Comment by wch** [comment]
Rtools isn't an R package - it's a a set of tools for Windows.
http://cran.r-project.org/bin/windows/Rtools/

**Comment by laurikoobas** [comment]
Right. Thanks. I'll try it on a different machine later as I already got everything working without RTools.
I guess feel free to close the comment?

**Comment by hadley** [comment]
I'd strongly recommend you use RTools, or you a likely to face random crashes later because your package will be using a different compiler toolchain to what R uses.
