### ISSUE TITLE
A create_function() function with documentation best practices?

### ISSUE THREAD

**Issue by stephlocke** [hadley/devtools#743]
I'm building functions and each time I do, I usually start c&ping from earlier functions I've written to grab all the roxygen comment stuff at the top.

Is there benefit in adding into devtools a function that creates a .R file with all the roxygen bits at the top and a skeleton function call?
e.g. `create_function("foo")` produces files pkg/R/foo.R which could look like
```{r}
#' Short description
#'
#' Here's where you put a long description
#'
#' @param input1   Input1 description
#' 
#' @return output  Output description
#'
#' @keywords foo bar
#'
#' @seealso \code{\link{bar}}
#'
#' @family dummyfuncs
#' 
#' @examples
#' # describe example purpose
#' foo( "a" )
#' 
#' # describe example purpose
#' foo( c( "a" , "b" ) )
#' 
#'
#' @export

foo <- function(input1){
           output<- input1
           return(output)
}
```

**Comment by hadley** [comment]
See here ;)
https://github.com/rstudio/rstudio/pull/359
