### ISSUE TITLE
Support specifying repos for install_url when dependencies=TRUE

### ISSUE THREAD

**Issue by jread-usgs** [hadley/devtools#745]
Currently, repos is not used, e.g.,:

```R
library(devtools)
install_url("https://github.com/hadley/plyr/archive/plyr-1.8.zip", dependencies=TRUE, repos="http://cran.r-project.org")
```
This yields
```Downloading package from url: https://github.com/hadley/plyr/archive/plyr-1.8.zip
Error in install(source, ..., quiet = quiet) : 
  unused argument (repos = "http://cran.r-project.org")```

use case is needing to install packages from tagged versions on GH `as Rserve` and trickle down for dependencies from specified repo(s)

**Comment by hadley** [comment]
My feeling is that it's easier to set the global repos function - maybe it would be useful to have `with_repos()` analogous to  `with_libpaths()` ?

**Comment by jread-usgs** [comment]
Yes, that would be a good fit for our needs. Any others running into a similar use case? We can find a way around it, but it would be handy to be cooked into `devtools`

**Comment by hadley** [comment]
Hmm, I'm flip-flopping on this a bit - might be best to add `repos` and `type` arguments to `install()`, which will get passed along to `install_deps()` which is going to get overhauled shortly.

**Comment by hadley** [comment]
I think I've plumbed it all together so that `...` now (through a chain of like 6 functions) gets passed to `install.packages()`, can you please give it a go and re-open if it doesn't work?

**Comment by jread-usgs** [comment]
Thank you. Will try this out and if you don't hear back from me, it works for our pattern.
