### ISSUE TITLE
code segfaults when run after load_all()

### ISSUE THREAD

**Issue by thk686** [hadley/devtools#748]
I am developing a package with Rcpp and CXX11 mode enabled. I have test code that fails (segfaults) when calling devtools::test(), but runs perfectly fine in a normal R session. I have isolated this to a dll issue with load_all(). If I start an R session and call load_all() to load the package and then run the test code, it will segfault. If I use library(pkg) and then run the same code, no problem. This code links to a number of other dll's and the segfault occurs in an external dll. I suspect this is nothing but a dynamic linking issue. It is rather complicated to provide an example. I will provide the package on request.

**Comment by thk686** [comment]
Here's output from a test case. First without "load_all" and then with "load_all":

==8076== Memcheck, a memory error detector
==8076== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==8076== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==8076== Command: /usr/lib/R/bin/exec/R --vanilla -f test.R
==8076== 

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(geospatial)
> library(testthat)
> x = georaster(100, 100, driver = "GTiff", nosave = TRUE)
> expect_is(x, "GeoRaster")
> SRS(x) = "EPSG:4326"
> expect_equal(as(SRS(x), "character"), "+proj=longlat +datum=WGS84 +no_defs ")
> SRS(x) = SRS("+proj=longlat")
> expect_equal(as(SRS(x), "character"), "+proj=longlat +ellps=WGS84 +no_defs ")
> SRS(x) = sp::CRS("+proj=longlat")
> expect_equal(as(SRS(x), "character"), "+proj=longlat +ellps=WGS84 +no_defs ")
> 
==8076== 
==8076== HEAP SUMMARY:
==8076==     in use at exit: 75,808,747 bytes in 39,381 blocks
==8076==   total heap usage: 140,968 allocs, 101,587 frees, 190,212,374 bytes allocated
==8076== 
==8076== LEAK SUMMARY:
==8076==    definitely lost: 240 bytes in 5 blocks
==8076==    indirectly lost: 4,755 bytes in 235 blocks
==8076==      possibly lost: 0 bytes in 0 blocks
==8076==    still reachable: 75,803,752 bytes in 39,141 blocks
==8076==         suppressed: 0 bytes in 0 blocks
==8076== Rerun with --leak-check=full to see details of leaked memory
==8076== 
==8076== For counts of detected and suppressed errors, rerun with: -v
==8076== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

Using "load_all":

==8127== Memcheck, a memory error detector
==8127== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==8127== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==8127== Command: /usr/lib/R/bin/exec/R --vanilla -f test2.R
==8127== 

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(testthat)
> devtools::load_all("~/Desktop/tkeitt/Dropbox/Software/R-Project/geospatial/")
Loading geospatial
> x = georaster(100, 100, driver = "GTiff", nosave = TRUE)
> expect_is(x, "GeoRaster")
> SRS(x) = "EPSG:4326"
==8127== Invalid read of size 1
==8127==    at 0x12A87FC5: ??? (in /usr/lib/libgdal.so.1.18.1)
==8127==    by 0x11EED375: Rcpp::S4_Impl<Rcpp::PreserveStorage> Rcpp::internal::as<Rcpp::S4_Impl<Rcpp::PreserveStorage> >(SEXPREC*, Rcpp::traits::r_type_generic_tag) [clone .isra.36] (RcppCommon.h:97)
==8127==    by 0x11EEE636: geospatial_set_georaster_srs (RcppExports.cpp:191)
==8127==    by 0x4EC83E1: ??? (in /usr/lib/R/lib/libR.so)
==8127==    by 0x4F07F25: Rf_eval (in /usr/lib/R/lib/libR.so)
==8127==    by 0x4F0B501: ??? (in /usr/lib/R/lib/libR.so)
==8127==    by 0x4F07E00: Rf_eval (in /usr/lib/R/lib/libR.so)
==8127==    by 0x4F0A062: ??? (in /usr/lib/R/lib/libR.so)
==8127==    by 0x4F07D3E: Rf_eval (in /usr/lib/R/lib/libR.so)
==8127==    by 0x4F09014: Rf_applyClosure (in /usr/lib/R/lib/libR.so)
==8127==    by 0x4F07ADD: Rf_eval (in /usr/lib/R/lib/libR.so)
==8127==    by 0x4F0A062: ??? (in /usr/lib/R/lib/libR.so)
==8127==  Address 0x4e is not stack'd, malloc'd or (recently) free'd
==8127== 

 *** caught segfault ***
address 0x4e, cause 'memory not mapped'

Traceback:
 1: .Call("geospatial_set_georaster_srs", PACKAGE = "geospatial",     georas, srs)
 2: set_georaster_srs(object, srs)
 3: `SRS<-`(`*tmp*`, value = "EPSG:4326")
 4: `SRS<-`(`*tmp*`, value = "EPSG:4326")
aborting ...
==8127== 
==8127== HEAP SUMMARY:
==8127==     in use at exit: 88,218,425 bytes in 45,971 blocks
==8127==   total heap usage: 134,855 allocs, 88,884 frees, 213,945,830 bytes allocated
==8127== 
==8127== LEAK SUMMARY:
==8127==    definitely lost: 0 bytes in 0 blocks
==8127==    indirectly lost: 0 bytes in 0 blocks
==8127==      possibly lost: 5,427 bytes in 155 blocks
==8127==    still reachable: 88,212,998 bytes in 45,816 blocks
==8127==         suppressed: 0 bytes in 0 blocks
==8127== Rerun with --leak-check=full to see details of leaked memory
==8127== 
==8127== For counts of detected and suppressed errors, rerun with: -v
==8127== ERROR SUMMARY: 2 errors from 1 contexts (suppressed: 0 from 0)

**Comment by hadley** [comment]
Strange. Unfortunately I have no idea how to fix this :/

**Comment by thk686** [comment]
Yes, its weird. I've found that 99% of the time segfaults are user errors.
I just cannot find it in this case.

T.

On Tue, Apr 21, 2015 at 9:36 AM, Hadley Wickham <notifications@github.com>
wrote:

> Strange. Unfortunately I have no idea how to fix this :/
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/devtools/issues/748#issuecomment-94816859>.
>



-- 
Timothy H. Keitt
http://www.keittlab.org/
