### ISSUE TITLE
Update .travis.yml with sudo: required

### ISSUE THREAD

**Issue by davidski** [hadley/devtools#749]
Travis CI is moving to container based build environments. Both the community and the integrated R support currently require sudo permissions. Adding in `sudo: required` to the `.travis.yml` allows both methods to continue to function.

**Comment by hadley** [comment]
Do we need `sudo: required` always, or only if we use the apt-get install mechanism? (The only bit that currently requires sudo at the user end)

**Comment by hadley** [comment]
Should be fixed now.
