### ISSUE TITLE
A suggestion for documentation somewhere... devtools::check() versus R CMD check

### ISSUE THREAD

**Issue by jmarca** [hadley/devtools#754]
This is not really an issue, but rather a documentation request, so feel free to close it right away.

I have been using R for a long time, but am really new to packages.  devtools helps a lot, but just now (when preparing this issue, in fact) I just figured something out that was not obvious and would like to suggest that it be added to the docs somewhere (or in the excellent developing with R book?)

Okay, I created my package using devtools.

When I run devtools::check(), everything passes okay.

But, because I wanted to make sure that the generic R install approach would work, I ran  ` R CMD check .`   My understanding was that it would test the package in the current directory, but it fails right away:

```
* using log directory ‘/home/james/repos/jem/R_libs/configr/..Rcheck’
* using R version 3.1.2 (2014-10-31)
* using platform: x86_64-slackware-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘./DESCRIPTION’ ... ERROR
Required fields missing or empty:
  ‘Author’ ‘Maintainer’
```

Staring at the echo from devtools::check() I see in an interactive R session I saw:

```
> devtools::check()
Updating configr documentation
Loading configr
'/usr/lib64/R/bin/R' --vanilla CMD build  \
  '/home/james/repos/jem/R_libs/configr' --no-resave-data --no-manual 

...
```

So I did *that* first, then ran  `R CMD check configr_1.0.0.tar.gz` and everything checked out fine.

My misunderstanding was that I assumed the argument of  "."  when in the toplevel package directory was the same as the argument of "configr_1.0.0.tar.gz"

**Comment by hadley** [comment]
Best practice for checking the package is to first build it, and then check the built file - that's what devtools does. There are some more notes on the process at http://r-pkgs.had.co.nz/check.html

**Comment by jmarca** [comment]
Ah yes.  The notes in check.html are *exactly* what I was missing.  

I guess I expected that passage in "Testing", I didn't think to look in "Best Practices".
