### ISSUE TITLE
github_install assumes SSL?

### ISSUE THREAD

**Issue by schnee** [hadley/devtools#755]
Have a private github enterprise, not under SSL. Try to do this:

```
devtools::install_github("bschneeman/geminiUtil", host="github.host/api/v3", auth_token="my_token")
Downloading github repo bschneeman/geminiUtil@master
Error in function (type, msg, asError = TRUE)  : 
  Failed connect to github.host:443; Connection refused
```

Same result if host="github.host"

Is there a mechanism to turn off SSL? I looked at the install_github.R code and it appears "https" is hardcoded, but maybe there's a mechanism that I missed.

**Comment by hadley** [comment]
Hmmmm, it seems weird that you're not using SSL (even though it's internal). I guess this needs an extra option :/

**Comment by schnee** [comment]
Oh, it is definitely weird, and I've pointed that out to the keepers of our internal github.
