### ISSUE TITLE
Sometimes I have to add files manually to Collate in description

### ISSUE THREAD

**Issue by lucacerone** [hadley/devtools#770]
As for subject, I couldn't exactly understand why,
but sometimes I have to add the name of files manually to the Collate field in the DESCRIPTION.

Sometimes it seemed relationed to some issues with roxygen2 (e.g. more than one space between
#' and the roclet, fails to fill correct some fields like name, title , describeIn),
but other times I can't understand why.

I read it could depend on the encoding, but my files "source" fine (i.e. doing source("file.R") works flawlessly).
All the files end with .R to avoid confusion caused by different extensions (as I read in some thread in R-help).

I have no idea how I can inspect more in depth the issue to figure out if there is any mistake on my part, or it is really a bug and help with fixing it.

Thanks a lot in advance!

**Comment by hadley** [comment]
I've never seen this problem. Do you have an example package?

**Comment by lucacerone** [comment]
unfortunately none that I can share... and I am not able to find the logic behind the bug....
(if I have time I'll try to create a mock package reproducing the bug).

Sometimes when I load_all() there is a message saying that some functions are being added to the Collate field, but then they are not added (though the functions work just fine in the R shell) in the DESCRIPTION.

When this happens if I document() and then install() I get an error saying that the same functions are not in the Collate field. If I add them manually then everything works fine.

I have found that document() sometimes fail to create correct documentation if there is an extraspace between #' and the roclet, for example

    #' @describeIn fun1

produces good documentation, 

but
 
    #'    @describeIn fun1 

doesn't (the file fun1 is produced, but the \title are messed up and sometimes empty (like \title{})
which makes impossible to install.

I have found that this was the case for the functions that were not added. Removing the extra spaces produced good documentation, but still they were not added to DESCRIPTION.

I am sorry I can't help you more with this, I hope I can make a reproducible example soon!

**Comment by hadley** [comment]
Ok, please re-open if you manage to create a reprex.
