### ISSUE TITLE
ccache support

### ISSUE THREAD

**Issue by eMPee584** [hadley/devtools#771]
Hi
it would be nice to have ccache supported.. just had to rebuild packages that couldn't get installed because of insufficient folder permissions.. fixed that, now everything recompiling :smirk:

**Comment by hadley** [comment]
You can do it yourself with a `~/.R/Makevars` I have:

```
CC=ccache clang -Qunused-arguments # -Wsign-compare
CXX=ccache clang++ -Qunused-arguments # -Wsign-compare
CCACHE_CPP2=yes
```
