### ISSUE TITLE
install_deps fails with hanging comma in DESCRIPTION file

### ISSUE THREAD

**Issue by jread-usgs** [hadley/devtools#774]
Probably a `wontfix`, but worth pointing out. The following snippet of a DESCRIPTION file errors for `install_deps` as 
```
Error in isNamespaceLoaded(pkg) : attempt to use zero-length variable name
```
DESCRIPTION snippet:
```YAML
Depends:
    R (>= 3.0),
Imports:
    dplyr
```
This fails because the `parse_deps(paste(deps, collapse = ","))` creates an empty package as a row in the deps data.frame. The odd thing is, this fails on mac, but seems to silently pass through on windows, even though the empty package row is created on both platforms.

**Comment by hadley** [comment]
Yeah, I think this is wontfix, unless you want to do a PR that drops empty package names (or warns about invalid specification)
