### ISSUE TITLE
install_git from tfs

### ISSUE THREAD

**Issue by jangorecki** [hadley/devtools#775]
A FR for new method.
TFS supports git repositories so it could be nice to be able `install_git` directly from tfs, kind of `remote_download.tfs_remote` method.
Some examples how to interact with tfs from R made by @stephlocke in [tfsR](https://github.com/stephlocke/tfsR) package.

**Comment by stephlocke** [comment]
This might be made more generic by enabling the passing of a `httr::authenticate()` token or similar to the `install_git` function as an optional parameter. That way bitbucket, github private repos, and other sources of private repositories could be utilised.

**Comment by hadley** [comment]
I'd be happy to accept a PR for this, but since I don't have TFS, I have no way to write the code.

@stephlocke the install functions are designed around a fairly flexible S3 class, so it shouldn't be too hard to implement.
