### ISSUE TITLE
"path to R isn't quoted" bug

### ISSUE THREAD

**Issue by Frikster** [hadley/devtools#779]
The following post still doesn't have an answer: http://stackoverflow.com/questions/25898039/error-installing-shinyapps . Yihui (I believe he was the principle developer of knitr) seems convinced it's a devtools bug.

I tried reinstalling R in a file with no spaces as suggested by one of the answers. It didn't work. Same issue.

Though, admittedly, my error message is somewhat different from the post. See below.

```
Error message
----------
Downloading github repo rstudio/shinyapps@master
Installing shinyapps
"C:/R/R-3.2.0/bin/x64/R" --vanilla CMD INSTALL "C:/Users/dirkh_000/AppData/Local/Temp/Rtmp8oSGFw/devtools12c073c72c69/rstudio-shinyapps-5bc3814" --library="C:/R/R-3.2.0/library"  \
  --install-tests 

Error: Command failed (65535)


library(devtools); sessionInfo()
-------
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.7.0

loaded via a namespace (and not attached):
[1] httr_0.6.1     tools_3.2.0    RCurl_1.95-4.6 stringr_0.6.2  bitops_1.0-6  
```

**Comment by hadley** [comment]
By looking at that command, you can see all the paths are quoted, so it's clearly a different problem.

Googling a bit suggests that it's a generic windows file system error message, so you might want to try running some disk checker tool.
