### ISSUE TITLE
confusing default for 'devtools.desc.author'

### ISSUE THREAD

**Issue by kevinushey** [hadley/devtools#789]
```
> getOption("devtools.desc.author")
[1] "person(\"First\", \"Last\", , \"first.last@example.com\", role = c(\"aut\", \"cre\"))"
```

Should set `email = "first.last@example.com"` explicitly; skipping `middle` with a missing argument is confusing. See https://support.rstudio.com/hc/communities/public/questions/203982267-Malformed-DESCRIPTION-file-template for related confusion.

**Comment by hadley** [comment]
It's only confusing if you're not familiar with R's function call semantics - I prefer this form because then you can get an author per line.

**Comment by kevinushey** [comment]
But that's only if you know that the extra comma was intentional and not a typo. and you can't know that without knowing the function's signature. I definitely don't think it's an idiom worth encouraging.

**Comment by hadley** [comment]
Oh maybe I'll just keep using it in my packages, but change the default to be a bit more explanatory. Want to do a quick PR?
