### ISSUE TITLE
devtools sometimes screw the DESCRIPTION file

### ISSUE THREAD

**Issue by kforner** [hadley/devtools#791]
I do not have a reproducible example, but it happened two times: I could not load a package, and I realized that the DESCRIPTION file was a mess. Here's an excerpt of the git diff:

```
+Maintainer: <karl.forner@quartzbio.com>Version: 0.1
+Description: NA
 Depends:
-    R (>= 3.0),
-    methods,
-    devtools
-License: file LICENSE
-Encoding: UTF-8
+    NA
+Package: NA
+License: NA
+Copyright: NA
+Encoding: NA
```

I suspect that it might be related to encoding issues, since I recall seeing an **iconv**-related error message...

Anyway, I'm not a big fan of devtools/roxygen modifying my DESCRIPTION files (I do not use a Collate:). 
Would it be possible to have an option in load_all() to control this behavior ? 

Thanks,
 
P.S:
 devtools     1.7.0      2015-05-06 Github (hadley/devtools@f154070)

**Comment by hadley** [comment]
Devtools should never touch `DESCRIPTION` unless you explicitly ask for it (e.g. with a `use_*` function), and roxygen2 shouldn't touch it unless you're using `@include`. If you can figure out what's triggering it, I'm happy to fix it

**Comment by kforner** [comment]
the **roxygen2::update_collate()** call in **load_all()**, and  **write.description()** in roxygen2::update_collate() 
also from the NEWS.md about 1.7.0:
`
load_all() runs roxygen2::update_collate() before loading code. This ensures that files are sourced in the way you expect, as defined by roxygen @include tags. If you don't have any @include tags, the collate will be not be touched (#623). 
`

**Comment by hadley** [comment]
You have an old version of roxygen2. The current release has:

```R
update_collate <- function(base_path) {
  collate <- generate_collate(file.path(base_path, "R"))
  if (is.null(collate)) return()
  ...
}
```

**Comment by kforner** [comment]
indeed, thanks. 
Question: I installed the devtools 1.7 version using devtools::install_github. It does not enforce the deps versions specified in the DESCRIPTION file ?

**Comment by hadley** [comment]
That's fixed in the dev version of devtools - it might be overly aggressive now, but it currently ensures that all dependencies are also up to date.

**Comment by kforner** [comment]
Thanks.
