### ISSUE TITLE
install_gitlab instead of install_gitorious

### ISSUE THREAD

**Issue by iembry-USGS** [hadley/devtools#792]
Hi, can you change install_gitorious to install_gitlab?

See the note below about the acquiring of Gitorious by GitLab:

https://gitorious.org/
System notice: Gitorious is being acquired by GitLab and gitorious.org will shut down end of May. Please import your repositories to GitLab.com

Thank you.

**Comment by hadley** [comment]
I'm happy to review a PR for this change.

**Comment by iembry-USGS** [comment]
Hi Hadley, check out http://blog.gitorious.org/2015/04/15/gitorious-org-is-dead-long-live-gitorious-org/ (Gitorious.org is dead, long live gitorious.org) & https://about.gitlab.com/2015/03/03/gitlab-acquires-gitorious/ (GitLab acquires Gitorious to bolster its on premises code collaboration platform). Thank you.
