### ISSUE TITLE
install_git no longer recognizes ssh addresses

### ISSUE THREAD

**Issue by lucacerone** [hadley/devtools#796]
Hi Hadley, prior to version 1.8.0 I was able to install packages hosted on machines to which I have
ssh access using:

install_git("git@gitrepopath.git")

From version 1.8.0 this has changed and I have an error from git2r saying that the protocol is an unsupported URL.

Is this going to be some stable change? or is it just a bug? Is there any workaround for this other than setting up https access to my remote machines?

Thanks a lot in advance for the help,

Cheers!

**Comment by hadley** [comment]
It should work. It's likely to be a problem with git2r config

**Comment by lucacerone** [comment]
Thanks Hadley!
Is git2r a new introduction to devtools or has always been there?

The problem you mention with git2r config is something that I should fix on my side? can you point me to some guide for this?

**Comment by hadley** [comment]
It's new in 1.8.0.  I'd recommend taking a look at the code in `install_git` to see if you can create a minimal reprex using git2r code (it should be pretty simple). Then you can follow up with the git2r folks.

**Comment by lucacerone** [comment]
The issue is not present with R 3.1.3 (that I have at home), so I can't reproduce the issue.
I'll try again with my laptop at work (where I have R 3.2.0) and try to figure out why it happens.
I have seen there are several git2r repos in github, which is the official one? I guess it is the cran/git2r, but would like to be sure.

Thanks a lot again for your help with this!

**Comment by hadley** [comment]
https://github.com/ropensci/git2r

On Mon, May 11, 2015 at 1:14 PM, Luca Cerone <notifications@github.com>
wrote:

> The issue is not present with R 3.1.3 (that I have at home), so I can't
> reproduce the issue.
> I'll try again with my laptop at work (where I have R 3.2.0) and try to
> figure out why it happens.
> I have seen there are several git2r repos in github, which is the official
> one? I guess it is the cran/git2r, but would like to be sure.
>
> Thanks a lot again for your help with this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/devtools/issues/796#issuecomment-101003207>.
>



-- 
http://had.co.nz/

**Comment by lucacerone** [comment]
Thanks! It turns out is is an issue with a missing C library, libssh2.  Installing that fixes the issue.

**Comment by daliati** [comment]
I'm getting the same error now, `R version 3.5.0 (2018-04-23) -- "Joy in Playing"`, newest devtools. libssh2 is installed. But mostly I just got sentimental coming across this issue :)
