### ISSUE TITLE
r 3.2 required

### ISSUE THREAD

**Issue by aaronbenz** [hadley/devtools#799]
I believe some of these new functions require or depend on packages that only support 3.2 right? Like dr_devtools did not work on 3.1

**Comment by hadley** [comment]
Could you please file a reprex? It should work with 3.1, but I may have missed something.

**Comment by bamcdougall** [comment]
Hi Hadley,

I'm glad you are thinking about this issue.

With library("devtools"), RStudio (Version 0.98.1102) returns:
*WARNING: Rtools 3.2 found on the path at d:/Rtools is not compatible with R 3.1.2.*

*Please download and install Rtools 3.1 from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH, then run find_rtools().
warning: Rtools 3.2 found on the path at d:/Rtools is not compatible with R 3.1.2.Please download and install Rtools 3.1 from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH, then run find_rtools().*

From sessionInfo():  R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by bamcdougall** [comment]
<sigh> a simple package update resolved my issue <sigh>
