### ISSUE TITLE
Error: a character vector argument expected

### ISSUE THREAD

**Issue by englianhu** [hadley/devtools#801]
> install_github("ropensci/lawn")
Downloading github repo ropensci/lawn@master
Installing lawn
Error: a character vector argument expected
> install_github('christophergandrud/DataCombine')
Downloading github repo christophergandrud/DataCombine@master
Installing DataCombine
Error: a character vector argument expected
> install_github("choroplethr", "trulia")
Downloading github repo trulia/choroplethr@master
Installing choroplethr
Error: a character vector argument expected
In addition: Warning message:
Username parameter is deprecated. Please use trulia/choroplethr 
> install_github('nathanvan/rstanmulticore')
Downloading github repo nathanvan/rstanmulticore@master
Installing rstanmulticore
Error: a character vector argument expected
> install_github("trulia/choroplethr")
Downloading github repo trulia/choroplethr@master
Installing choroplethr
Error: a character vector argument expected

**Comment by hadley** [comment]
Works for me. Please supply `traceback()` and `devtools::package_deps("devtools")`

**Comment by englianhu** [comment]
> traceback()
15: tolower(names(x))
14: insensitive(setNames(values, names))
13: FUN(X[[i]], ...)
12: lapply(unname(split(lines, grps)), parse_single_header)
11: parse_headers(headers)
10: perform(handle, writer, method, opts, body)
9: make_request("head", hu$handle, hu$url, config)
8: httr::HEAD(src_submodules, , auth)
7: github_has_remotes(x, auth)
6: remote_download.github_remote(remote, quiet = quiet)
5: remote_download(remote, quiet = quiet)
4: FUN(X[[i]], ...)
3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
2: install_remotes(remotes, ...)
1: devtools::install_github("ropensci/plotly")
> 1
[1] 1
> devtools::package_deps("devtools")
> devtools::install_github("ropensci/plotly")
Downloading github repo ropensci/plotly@master
Installing plotly
Error in basename(fnames) : a character vector argument expected
> traceback()
9: basename(fnames)
8: payload(filenames = files, description)
7: update(pkg, Ncpus = threads, ...)
6: install_deps(pkg, dependencies = dependencies, threads = threads,
       ...)
5: install(source, ..., quiet = quiet)
4: FUN(X[[i]], ...)
3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
2: install_remotes(remotes, ...)
1: devtools::install_github("ropensci/plotly")
> devtools::install_github("ropensci/plotly")
Downloading github repo ropensci/plotly@master
Installing plotly
Error in basename(fnames) : a character vector argument expected

Kindly assist.


2015-05-15 21:10 GMT+09:00 Hadley Wickham <notifications@github.com>:

> Works for me. Please supply traceback() and
> devtools::package_deps("devtools")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/devtools/issues/801#issuecomment-102382698>.
>



-- 
®

**Comment by englianhu** [comment]
Dear,

Any idea?
[image: 埋め込み画像 1]

Thanks lot.
®

2015-05-16 0:31 GMT+09:00 Ryo Eng <englianhu@gmail.com>:

> > traceback()
> 15: tolower(names(x))
> 14: insensitive(setNames(values, names))
> 13: FUN(X[[i]], ...)
> 12: lapply(unname(split(lines, grps)), parse_single_header)
> 11: parse_headers(headers)
> 10: perform(handle, writer, method, opts, body)
> 9: make_request("head", hu$handle, hu$url, config)
> 8: httr::HEAD(src_submodules, , auth)
> 7: github_has_remotes(x, auth)
> 6: remote_download.github_remote(remote, quiet = quiet)
> 5: remote_download(remote, quiet = quiet)
> 4: FUN(X[[i]], ...)
> 3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
> 2: install_remotes(remotes, ...)
> 1: devtools::install_github("ropensci/plotly")
> > 1
> [1] 1
> > devtools::package_deps("devtools")
> > devtools::install_github("ropensci/plotly")
> Downloading github repo ropensci/plotly@master
> Installing plotly
> Error in basename(fnames) : a character vector argument expected
> > traceback()
> 9: basename(fnames)
> 8: payload(filenames = files, description)
> 7: update(pkg, Ncpus = threads, ...)
> 6: install_deps(pkg, dependencies = dependencies, threads = threads,
>        ...)
> 5: install(source, ..., quiet = quiet)
> 4: FUN(X[[i]], ...)
> 3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
> 2: install_remotes(remotes, ...)
> 1: devtools::install_github("ropensci/plotly")
> > devtools::install_github("ropensci/plotly")
> Downloading github repo ropensci/plotly@master
> Installing plotly
> Error in basename(fnames) : a character vector argument expected
>
> Kindly assist.
>
>
> 2015-05-15 21:10 GMT+09:00 Hadley Wickham <notifications@github.com>:
>
>> Works for me. Please supply traceback() and
>> devtools::package_deps("devtools")
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hadley/devtools/issues/801#issuecomment-102382698>.
>>
>
>
>
> --
> ®
>



-- 
®

**Comment by LiNk-NY** [comment]
I got the same error. I was able to work around it by running the same code with R --vanilla. 
> traceback()
9: basename(fnames)
8: payload(filenames = files, description)
7: update(pkg, Ncpus = threads, ...)
6: install_deps(pkg, dependencies = dependencies, threads = threads, 
       ...)
5: install(source, ..., quiet = quiet)
4: FUN(X[[i]], ...)
3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
2: install_remotes(remotes, ...)
1: install_github("hadley/haven")

My session info: 

> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.04

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.8.0       FirebrowseR_0.2.10   BiocInstaller_1.18.3 gistr_0.2.0          vimcom_1.2-6         setwidth_1.0-3      
[7] colorout_1.1-1      

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6     knitr_1.10.5    xml2_0.1.1      magrittr_1.5    R6_2.0.1        stringr_1.0.0   httr_0.6.1      dplyr_0.4.2    
 [9] tcltk_3.2.0     tools_3.2.0     parallel_3.2.0  DBI_0.3.1       git2r_0.10.1    htmltools_0.2.6 rversions_1.0.1 assertthat_0.1 
[17] digest_0.6.8    bitops_1.0-6    RCurl_1.95-4.6  curl_0.8        memoise_0.2.1   rmarkdown_0.7   stringi_0.4-1   jsonlite_0.9.16

**Comment by hadley** [comment]
You must have something else on the search path that's interfering with devtools.

**Comment by englianhu** [comment]
May I know what path will normally crash with devtools? There is a Python
path error if I run with R3.1.3...

**Comment by englianhu** [comment]
Ryo  Eng® would like to share papers and updates with you.

Accept Ryo  Eng®'s invitation:
http://academia.edu/t/a-Kf5XyNk-sf2dC/Yes-reply%2B006e48be20c568605b7cef35179c2e69fd2e1bc4de818a5992cf00000001116da42c92a169ce048ff2d3-at-reply.github.com-is-an-academic-or-graduate-student

Ryo  Eng® has invited you to Academia.edu, a global network of over 23,662,800 researchers. After you sign up, you'll be able to share your papers, see analytics on your profile and papers, follow other people in your field, and more.

Thanks,
The Academia.edu Team

For more information visit https://www.academia.edu/t/a-Kf5XyNk-sf2dC/press or contact us: feedback@academia.edu

-----
You can opt out of receiving these kinds of emails from Academia.edu with the link below:
https://www.academia.edu/t/a-Kf5XyNk-sf2dC/optout/88844f8004a25ebb44af1bd5343ea34c

Academia.edu, 251 Kearny St., Suite 520, San Francisco, CA, 94108

**Comment by englianhu** [comment]
Ryo  Eng® would like to share papers and updates with you.

Accept Ryo  Eng®'s invitation:
http://academia.edu/t/a-Kf5XyQk-EedSw/Yes-reply%2B006e48be6a296864379d85dc77050bca8041f3dcaf1f4dbb92cf00000001119bc24792a169ce048ff2d3-at-reply.github.com-is-an-academic-or-graduate-student

Ryo  Eng® has invited you to Academia.edu, a global network of over 23,662,800 researchers. After you sign up, you'll be able to share your papers, see analytics on your profile and papers, follow other people in your field, and more.

Thanks,
The Academia.edu Team

For more information visit https://www.academia.edu/t/a-Kf5XyQk-EedSw/press or contact us: feedback@academia.edu

-----
You can opt out of receiving these kinds of emails from Academia.edu with the link below:
https://www.academia.edu/t/a-Kf5XyQk-EedSw/optout/3b8b2b6a5ee8a3a16f49ce4172d715b0

Academia.edu, 251 Kearny St., Suite 520, San Francisco, CA, 94108

**Comment by englianhu** [comment]
I tried to setup *RStudio* and *Shiny Server* but there is an error with installation of `devtools` packages. Any idea? or alternative method?

According to below link, **devtools does indeed require** `libssl-dev` **to be installed**
<http://deanattali.com/2015/05/09/setup-rstudio-shiny-server-digital-ocean/#comment-2021216940>
![](https://a.disquscdn.com/uploads/mediaupload/tmp/c5913ed44d209460c3e3c32fe0f20813d2149199f7db57bd6efac93c/original.jpg)

**Comment by englianhu** [comment]
Subject Line (for proofing, doesn't show in actual email)
<https://www.digitalocean.com>                         == Deploy a Server
For Free! ==

  Your friend Eng Lian Hu has been using DigitalOcean – a cloud hosting
service designed just for developers – and thought you might want to give
it a shot. You can deploy a server in 55 seconds from our control panel or
use our simple API. 

 Because you’ve been invited by a friend, we’d like to give you a $10
credit to try it out. Just use this link to create an account and you’ll
be credited automatically.

 Redeem Your Credit
<https://cloud.digitalocean.com/accept?code=9169936f1fc332&amp;utm_campaign=Referral_Invite&amp;utm_medium=Referral_Program&amp;utm_source=Mandrill>

  Happy Coding,
 DigitalOcean 

            © DigitalOcean <http://do.co/email_twitter>
<http://do.co/email_gplus> <http://do.co/email_facebook>

**Comment by englianhu** [comment]
Subject Line (for proofing, doesn't show in actual email)
<https://www.digitalocean.com>                         == Deploy a Server
For Free! ==

  Your friend Eng Lian Hu has been using DigitalOcean – a cloud hosting
service designed just for developers – and thought you might want to give
it a shot. You can deploy a server in 55 seconds from our control panel or
use our simple API. 

 Because you’ve been invited by a friend, we’d like to give you a $10
credit to try it out. Just use this link to create an account and you’ll
be credited automatically.

 Redeem Your Credit
<https://cloud.digitalocean.com/accept?code=bec4df50a36014&amp;utm_campaign=Referral_Invite&amp;utm_medium=Referral_Program&amp;utm_source=Mandrill>

  Happy Coding,
 DigitalOcean 

            © DigitalOcean <http://do.co/email_twitter>
<http://do.co/email_gplus> <http://do.co/email_facebook>

**Comment by englianhu** [comment]
hadley/devtoolsさん

LinkedInでつながってください。よろしくお願いします。

®γσ

®γσさんのリクエストを承認する: https://www.linkedin.com/e/v2?e=0-ik840954-rq&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=_ARYYjBp&invitationId=6100955036555235332








本メールはLinkedInのつながりリクエストをご案内するものです。LinkedInは、あなたのメールアドレスを知り合いの紹介機能に使用します。メール購読を停止するには次のリンクをクリックしてください: https://www.linkedin.com/e/v2?e=0-ik840954-rq&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEoFj1_Gl0DEgAAAVKryZ5NaKlGV1mUi8KZfObT8WBZuwhuSO-EF8xHGHepx7BtC4yuLSSiUPLMRQgUw0eEyM90imxoCIpprhDV2A_-Va42qSit7jcIBRUgQ7K8QicJVT87ajHRWFdonaQo1dDDmaj1EFwcXU60bqnLziNlDwwBCaxH940BIw3PUt2yLJs5il7o&eid=0-ik840954-rq


本メールはreply@reply.github.comに送信されています。

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ik840954-rq&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043.LinkedInおよびLinkedInのロゴは、LinkedInの登録商標です。

**Comment by englianhu** [comment]
hadley/devtoolsさん

LinkedInでつながってください。よろしくお願いします。

®γσ

®γσさんのリクエストを承認する: https://www.linkedin.com/e/v2?e=0-ik8409fz-hy&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=56Te5LWF&invitationId=6100955036764958721








本メールはLinkedInのつながりリクエストをご案内するものです。LinkedInは、あなたのメールアドレスを知り合いの紹介機能に使用します。メール購読を停止するには次のリンクをクリックしてください: https://www.linkedin.com/e/v2?e=0-ik8409fz-hy&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFxyKeyjMC5ZAAAAVKry5VoevMP9zUW3rI9l6Fk5M6fJH5myveU0gX_F4axfJ_yrODjyHvilPCIs5VgH9dkU0pAOYpSAyRA5fSi38JKndy9fPFG7OWrbE9rqt1296JCe9ffnO-pdCAXDGxCYSKdfckpdHykgKeWDNP42y9WmRAU6ft70SwLPzVE8Lsv-zqX-V4U&eid=0-ik8409fz-hy


本メールはreply@reply.github.comに送信されています。

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ik8409fz-hy&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043.LinkedInおよびLinkedInのロゴは、LinkedInの登録商標です。

**Comment by englianhu** [comment]
®γσ Eng would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-s1wy7h-ikge626s-f9&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=56Te5LWF&invitationID=6100955036764958721

View ®γσ Eng&#39;s profile: https://www.linkedin.com/e/v2?e=-s1wy7h-ikge626s-f9&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=56Te5LWF&invitationID=6100955036764958721





本メールはLinkedInのつながりリクエストをご案内するものです。LinkedInは、あなたのメールアドレスを知り合いの紹介機能に使用します。購読停止: https://www.linkedin.com/e/v2?e=-s1wy7h-ikge626s-f9&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-s1wy7h-ikge626s-f9&loid=AQEgSPaA3VQeoQAAAVLKbJsPVDyHgvBxKQ_8ILCJ9sDtU1KssXfxhr6DofSHpakMW8OjeR4SuLQlRglQX3RHETqwtuv5xTGVuiZMIa6dJ1JWQTGZIwHBAnM8BBT3aCq5h1BdnDhmyoRm1M-v9L_6Dua2wmSWAI4i7eE5rkrOUAe19_tiHKWYLzoSUlavOOAumozX

本メールはreply@reply.github.comに送信されています。

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-s1wy7h-ikge626s-f9&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043.LinkedInおよびLinkedInのロゴは、LinkedInの登録商標です。

**Comment by englianhu** [comment]
®γσ Eng would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=usu9ap-ikge3t8n-x6&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=_ARYYjBp&invitationID=6100955036555235332

View ®γσ Eng&#39;s profile: https://www.linkedin.com/e/v2?e=usu9ap-ikge3t8n-x6&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=_ARYYjBp&invitationID=6100955036555235332





本メールはLinkedInのつながりリクエストをご案内するものです。LinkedInは、あなたのメールアドレスを知り合いの紹介機能に使用します。購読停止: https://www.linkedin.com/e/v2?e=usu9ap-ikge3t8n-x6&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=usu9ap-ikge3t8n-x6&loid=AQGt9FlDzztmkgAAAVLKb6GdOhMjJAZzV7XncSnsqiAQIvpwTjcXRhplU1UPk8yLS3f8-m655MLeEy0ERzXpvsrAQtCD1GzbuuI96tYBp8O5I2EpNBaiXUBsJF_g133T9fp62I9YC1Ad2U3oXEo6qe3jcf8NwCH4oL-maTM7GrOTuhcJmeRfp9jND0lbshuuU6hK

本メールはreply@reply.github.comに送信されています。

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=usu9ap-ikge3t8n-x6&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043.LinkedInおよびLinkedInのロゴは、LinkedInの登録商標です。
