### ISSUE TITLE
Can't install from devtools::install_github('rstudio/shinyapps')

### ISSUE THREAD

**Issue by Rewarp** [hadley/devtools#804]
I am trying to push apps with shinyapps.io, and this is the command to do in the next step:

    devtools::install_github('rstudio/shiny')

This was the output generated in R (ver 3.1.1).

    Downloading github repo rstudio/shiny@master
    Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
      error in running command

I originally filed this issue in shiny, and after failing to make sense of the issue I am filing it here instead.
https://github.com/rstudio/shiny/issues/835

**Comment by BrainyGuy** [comment]
I am seeing the same error for any GitHub install:

```
> devtools::install_github("hadley/devtools")
Using github PAT from envvar GITHUB_PAT
Downloading github repo hadley/devtools@master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
  error in running command
```

**Comment by hadley** [comment]
Can you please provide the output of `devtools::session_info()`

**Comment by Rewarp** [comment]
Sorry for the delay. I ran the devtools command from a new RStudio installation.

> devtools::session_info()
Session info ---------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.1 (2014-07-10)
 system   x86_64, linux-gnu           
 ui       RStudio (0.98.1103)         
 language en_US                       
 collate  en_US.UTF-8                 
 tz       America/Chicago             

Packages -------------------------------------------------------------------------
 package   * version  date       source        
 bitops      1.0-6    2013-08-17 CRAN (R 3.1.1)
 devtools    1.8.0    2015-05-09 CRAN (R 3.1.1)
 digest      0.6.8    2014-12-31 CRAN (R 3.1.1)
 git2r       0.10.1   2015-05-07 CRAN (R 3.1.1)
 httr        0.6.1    2015-01-01 CRAN (R 3.1.1)
 magrittr    1.5      2014-11-22 CRAN (R 3.1.1)
 memoise     0.2.1    2014-04-22 CRAN (R 3.1.1)
 RCurl       1.95-4.6 2015-04-24 CRAN (R 3.1.1)
 rversions   1.0.0    2015-04-22 CRAN (R 3.1.1)
 stringi     0.4-1    2014-12-14 CRAN (R 3.1.1)
 stringr     1.0.0    2015-04-30 CRAN (R 3.1.1)
 XML         3.98-1.1 2013-06-20 CRAN (R 3.1.1)

**Comment by thepetestop** [comment]
Call options(unzip = 'internal') before calling install_github

**Comment by Rewarp** [comment]
What's the full syntax? I am, very new to devtools. My apologies.

**Comment by thepetestop** [comment]
Enter R on the terminal using sudo

$ sudo R

On R,

options(unzip = 'internal')
devtools::install_github('rstudio/shinyapps')

It worked for me. I changed your shiny to shinyapps. You do have the shiny package installed already, I assume.

**Comment by Rewarp** [comment]
Oh I see. options is the base package. Yes it works now. Thanks!
