### ISSUE TITLE
How to use authenticated request to get pass rate limiting?

### ISSUE THREAD

**Issue by jeffwong** [hadley/devtools#805]
I hit a rate limit using install_github today.  In the response I see

{
  "message": "API rate limit exceeded for ********** (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}

I don't see any options in install_github though to use the authenticated request, is this feature enabled in devtools?

**Comment by hadley** [comment]
Set the envar GITHUB_PAT to your personal access token
