### ISSUE TITLE
devtools::check() incorrectly passes tests using lintr::lint_package()

### ISSUE THREAD

**Issue by nsh87** [hadley/devtools#811]
**Update: see next comment.**
I've added a test function that lints a package and prints any linter errors as if running `lint_package()` directly. The idea is that when someone submits a pull request any linter errors will be contained in the Travis CI log for easy viewing. And if I `devtools::check()` the package locally I can simply see the lint errors there without having to run an extra `lint_package()` beforehand.

**Comment by nsh87** [comment]
I just installed the latest version of `lintr` from GitHub (I was using CRAN's version before), and now I don't get the error, but `devtools::check()` incorrectly passes:

```R
> devtools::test()
Loading receptormarker
Testing receptormarker
Lint package to verify code style : 
......
[[1]]
R/receptormarker.R:57:1: style: lines should not be more than 80 characters.
                                     "on your system. In order to achieve the slajsld",
^~

1
Run a basic test to verify tests are working : .
System checks for getting Python and Biopython version numbers : .......


1. Failure(@test_lint_package.R#39): code conforms to the style guide -------------------------------------------------
length(lint_errs) not equal to 0
Mean absolute difference: 1

> devtools::check()
Updating receptormarker documentation
Loading receptormarker
Skipping invalid path:  .onLoad.Rd 
Skipping invalid path:  .onAttach.Rd 
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD build  \
  '/Users/me/dev/receptormarker/receptormarker' --no-resave-data --no-manual 

* checking for file ‘/Users/me/dev/receptormarker/receptormarker/DESCRIPTION’ ... OK
* preparing ‘receptormarker’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘receptormarker_0.0.0.9000.tar.gz’

'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD check  \
  '/var/folders/ps/4zmxslc50ls5cxjpng935wpm0000gn/T//Rtmp9vQKu4/receptormarker_0.0.0.9000.tar.gz' --timings 

* using log directory ‘/private/var/folders/ps/4zmxslc50ls5cxjpng935wpm0000gn/T/Rtmp9vQKu4/receptormarker.Rcheck’
* using R version 3.2.0 (2015-04-16)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* checking for file ‘receptormarker/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘receptormarker’ version ‘0.0.0.9000’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘receptormarker’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘fpc’
  All declared Imports should be used.
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking PDF version of manual ... OK
* DONE

Status: 1 NOTE
See
  ‘/private/var/folders/ps/4zmxslc50ls5cxjpng935wpm0000gn/T/Rtmp9vQKu4/receptormarker.Rcheck/00check.log’
for details.
```

This is using the same test function as in my original comment. Here's [a commit with the code](https://github.com/nsh87/receptormarker/commit/5b198487beb1912e31992ab7b90dac4e568716cb). I'm going to update the title of the issue.

**Comment by hadley** [comment]
@jimhester any thoughts?

**Comment by jimhester** [comment]
There is a lint expectation built into lintr, I would recommend @nsh87 use that, from the lintr README

```r
if (requireNamespace("lintr", quietly = TRUE)) {
  context("lints")
  test_that("Package Style", {
    lintr::expect_lint_free()
  })
}
```

**Comment by nsh87** [comment]
Ok, I'll try that. It seems like the behavior of devtools should be to fail still, since I'm just check list sizes and it failed in `test`, but what do I know! It is quite possible to use lintr's CRAN version still, which doesn't have the option pointed out by @jimhester. @jimhester, given the strange behaviors I saw with lintr and the commonly used devtools package it might be worth it to give a hard suggestion not to install via CRAN, or if possible update CRAN's version. The README or somewhere says to add lintr to Suggests... It becomes a bit confusing since it would seem acceptable to install lintr from CRAN at that point since Suggests would be checked against CRAN's version. Just my 2 cents. In any case, coming from the Python world the R community seems wonderful thus far; thanks for the support. It seems like the community needs a new solution to package management, though, with issues like this cropping up because there are two common ways to install and each repo has a different version. Perhaps there are restrictions by CRAN that prevent newer versions of lintr or devtools from going there... If so maybe those restrictions need to be rethought..?

**Comment by nsh87** [comment]
After implementing the suggestion to use the lint expectation this issue still isn't solved. `devtools::check()` still passes even though `devtools::test()` fails.

**Comment by jimhester** [comment]
This is not a bug in devtools (but maybe in lintr).  `devtools::check()` runs the check in a temporary directory, but `lint_package()` assumes it is being run in a package directory, therefore there are no source files to be linted.  @nsh87 you can confirm this with `devtools::check(check_dir = ".")`, which should produce linting failures if `devtools::test()` does.

Maybe `lintr:::expect_lint_free` should use `system.file()` to find the source files (but this would then break `test()` unless we revisit #744 to properly shim `system.file()` globally.
