### ISSUE TITLE
unable to install dev tools

### ISSUE THREAD

**Issue by vinodh-ranga** [hadley/devtools#812]
Installing package into ‘C:/Users/Wel Come/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.1
Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.1
Warning message:
package ‘devtools’ is not available (for R version 3.1.1)

**Comment by hadley** [comment]
This looks like a mirror problem - I'd recommending us the 0-cloud mirror.
