### ISSUE TITLE
Error installing FredR

### ISSUE THREAD

**Issue by ernstfitschen** [hadley/devtools#814]
Trying to install FredR, I get the following error:

> devtools::install_github("jcizel/FredR")
Downloading github repo jcizel/FredR@master
Installing FredR
"C:/Program Files/R/R-3.1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/Ernst/AppData/Local/Temp/RtmpgPTx0Y/devtools3d705d9d6f2b/jcizel-FredR-cef0c9c" --library="C:/Program Files/R/R-3.1.3/library"  \
  --install-tests 

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)

**Comment by hadley** [comment]
Can you please give me `devtools::session_info()`?
