### ISSUE TITLE
can devtools pull from private Atlassian Stash repo?

### ISSUE THREAD

**Issue by jeffwong** [hadley/devtools#827]
Seems like the functions for install_github can only interface with github specifically, is it possible to interface with other remote git repos, for example ones that are hosted on 

https://www.atlassian.com/software/stash

**Comment by BrianDiggs** [comment]
Is there a reason you can't do it with appropriate arguments to `install_git`?

**Comment by jeffwong** [comment]
Yes discovered it is possible through install_git
