### ISSUE TITLE
load_all and Modules

### ISSUE THREAD

**Issue by baptiste** [hadley/devtools#828]
I'm unable to use Rstudio package building tools for my Rcpp packages planar and cda. The problem occurs with load_all, which seems to dislike Modules,

```
Loading cda
Error in loadRcppModules(direct = FALSE) : 
  loadRcppModules can only be used within a .onLoad function
Calls: suppressPackageStartupMessages ... load_all -> run_pkg_hook -> <Anonymous> -> loadRcppModules
Execution halted
```

**Comment by hadley** [comment]
Could you link to a minimal reproducible example?

**Comment by hadley** [comment]
Closing for now. If you add a MRE, I'll reopen.

**Comment by baptiste** [comment]
Here's a minimal package failing to build with devtools (but fine with R CMD) because of this load_all issue,

https://github.com/baptiste/mini

Note that Rcpp's internal unit tests seem to have moved away from this loadRcppModules strategy, but I prefer it to expose just the module names and not the module contents in the Namespace (cf direct argument).

**Comment by hadley** [comment]
`loadRcppModules()` contains:

```R
    calls <- sys.calls()
    w <- which(sapply(calls, function(call) {
        identical(call[[1L]], as.name("runHook"))
    }))
    if (!length(w)) 
        stop("loadRcppModules can only be used within a .onLoad function")
    w <- w[length(w)]
    call <- calls[[w]]
    if (!identical(call[[2L]], ".onLoad")) 
        stop("loadRcppModules can only be used within a .onLoad function")
```

So they really don't you to run it some other way (and devtools calls `.onLoad()` directly, not through the usual `runHook()` mechanism). `runHook()` isn't an exported function, so I can't use that, so I think that makes this an Rcpp issue.

Maybe @romainfrancois has some thoughts.

**Comment by romainfrancois** [comment]
That's definitely an Rcpp issue, please log it on theire repo. 

I currently don't have time to offer a fix

**Comment by dmenne** [comment]
@hadley: I don't think of devtools as an "build obfuscation^Hhelper tool" as mentioned in the above reference; thanks for putting your effort into it. 
However, it might be helpful to reconsider some environment-fiddling workaround; Ben Goodrich has confirmed at current they have not yet found a solution for packages with precompiled C++.
