### ISSUE TITLE
check using cran version of packages

### ISSUE THREAD

**Issue by matthieugomez** [hadley/devtools#837]
Could devtools run `check` with the CRAN version of the packages rather than the ones installed on my computer (potentially development/github version)? I missed errors when sending a version to CRAN.

**Comment by hadley** [comment]
See the revdep check functions. I also recommend checking with `build_win()`

**Comment by briencj** [comment]
I was under the misapprehension that using devtools::check with CRAN=TRUE is the same as running R CMD check with --as-cran. This is not the case and so I missed some errors when I submitted a package. I now use args = "--as-cran" with devtools::check and so far so good. However, it would be better if it was clearer what CRAN=TRUE does - I am still not sure.

**Comment by matthieugomez** [comment]
@briencj does --as-cran use the cran version of packages that a package imports and not the local version? Or are you talking about something else.

**Comment by briencj** [comment]
My comment was more about the general problem of getting the same checking as CRAN does. To quote from the R CMD check --help: --as-cran selects customizations similar to those used for incoming cran checking. I do not know the technicalities of what is done, but I have found that I get error messages when using it that do not show when just CRAN=TRUE is used. One of my problems revolved around having the namespace for stats loaded by default when I run R and this namespace is not available when --as-cran is used. I do not know which version of the package (local or cran) is used to import the namespace of a package.

**Comment by hadley** [comment]
It's as similar as we can make it without running CRAN checks that we don't want (e.g. checking the incoming version check which is lengthy and not usually important). `release()` runs `check()` with `--as-cran` as a final check. You should also be checking on other platforms like with `build_win()`
