### ISSUE TITLE
UBUNTU 14.04,  why can't install?  install.packages("devtools", dependencies = TRUE) 

### ISSUE THREAD

**Issue by StevenLOL** [hadley/devtools#838]
> install.packages("devtools", dependencies = TRUE)
Installing package into ‘/home/steven/R/x86_64-pc-linux-gnu-library/3.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependencies ‘BiocInstaller’, ‘lintr’, ‘xml2’ are not available
also installing the dependency ‘rversions’

trying URL 'http://cran.rstudio.com/src/contrib/rversions_1.0.1.tar.gz'
Content type 'application/x-gzip' length 4624 bytes
opened URL
==================================================
downloaded 4624 bytes

trying URL 'http://cran.rstudio.com/src/contrib/devtools_1.8.0.tar.gz'
Content type 'application/x-gzip' length 141487 bytes (138 Kb)
opened URL
==================================================
downloaded 138 Kb

ERROR: dependency ‘xml2’ is not available for package ‘rversions’
* removing ‘/home/steven/R/x86_64-pc-linux-gnu-library/3.0/rversions’
Warning in install.packages :
  installation of package ‘rversions’ had non-zero exit status
ERROR: dependency ‘rversions’ is not available for package ‘devtools’
* removing ‘/home/steven/R/x86_64-pc-linux-gnu-library/3.0/devtools’
Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmphn1AwS/downloaded_packages’

**Comment by StevenLOL** [comment]
[Error when installing “devtools” package for R in Ubuntu] (http://stackoverflow.com/questions/26445815/error-when-installing-devtools-package-for-r-in-ubuntu)

**Comment by hadley** [comment]
It
