### ISSUE TITLE
Accidentally added a package to Suggest in Description. Keep's being added automatically to description when re-loading the package

### ISSUE THREAD

**Issue by leerichardson** [hadley/devtools#853]
Hello,

I accidentally added the wrong dependency using the code:
devtools::use_package("dplyr", "Suggests")

So then I removed it from the Description file. However, now every time I re-load the file, dplyr appears automatically as in the Suggests: portion. I can get around this by using (reset = FALSE), but I'm wondering if there is an easy way to permanently remove this file. 

Thanks! And sorry if this is an obvious question.

**Comment by hadley** [comment]
Restart R?

**Comment by leerichardson** [comment]
This didn't quite fix it. 

But I ended up adding a vignette to the package, and then this ended up fixing the issue, no longer does dplyr in Suggests when building. 

Thanks!!! The dev tools package incredibly useful.
