### ISSUE TITLE
update use_travis

### ISSUE THREAD

**Issue by pearsonca** [hadley/devtools#854]
Per [r-travis README](https://github.com/craigcitro/r-travis), r is now a "first class citizen" @ Travis CI, so the template should change from the current version to approximately:

```
language: r

r_binary_packages:
 - testthat
```

Also, if possible, would be nice to have the warning message about the shield link mention the appropriate (current?) branch.  I don't normally do package development in master.

**Comment by hadley** [comment]
Already fixed in dev version
