### ISSUE TITLE
infrastructure creation tool to generate a CITATION file 

### ISSUE THREAD

**Issue by cboettig** [hadley/devtools#862]
As far as I can tell, the generation of CITATION files is reasonably manual: fields have to be copied individually into the `citEntry` function.  

In the devtools spirit, I think there should be something like `add_citation()` which could take a path to a bibentry R object, a path to a bibtex file (or even just a DOI using RefManageR or a simple httr call to http://www.crosscite.org/cn/ rather than adding dependencies) and generate the appropriate CITATION file.  yesnomaybe? (I can work up a PR if you like but thought it would be better to get your feedback first before I sink some time in what may be a silly approach)

**Comment by hadley** [comment]
Seems reasonable to me (although I'd call it `use_citation()` to be consistent with the other functions)

**Comment by hadley** [comment]
I'd be happy to review a pull request
