### ISSUE TITLE
Skipping package dependencies because of type mismatch.

### ISSUE THREAD

**Issue by vladpetyuk** [hadley/devtools#864]
The problem is described and demonstrated [here](https://github.com/vladpetyuk/toypack)
It turned out that `devtools::package_deps` is forcing type to be "binary".
```r
    if (identical(type, "both")) {
        type <- "binary"
    }
```
However, some of the packages (e.g. `GO.db`) are not maintained as binary on Bioconductor.
Thus, the installation skips them.

**Comment by vladpetyuk** [comment]
A workaround is just set the type to "source" by default.  However, this will make all the packages to be installed as "source".
```r
options(pkgType="source")
```

**Comment by hadley** [comment]
I think `type = "both"` is still a bit buggy, but I will revert to it eventually. See #907 for progress.
