### ISSUE TITLE
Support for language string translation

### ISSUE THREAD

**Issue by barryrowlingson** [hadley/devtools#865]
Internationalisation (I18n) is often left as an afterthought to software, added on once the "real code" is working, and only if there's some demand for it. If the mechanisms for I18n are included at the start, then it is easier to include translation string code as the package is developed.

I would propose a `use_translations(pkg)` function (or similar) that sets up the directories for string translation, and adds an example or two. It could also set up a string translation function for the domain of the package, perhaps `T`(because `_` - the conventional name in other languages -  needs quoting), although there's still T for TRUE lurking (but shouldn't ever get confused with a T function). T would not need to be exported.

I'm not sure what packages currently use I18n apart from Rcmdr if you need to find examplars of current practice.

**Comment by hadley** [comment]
I think that would be reasonable as its own package :)

**Comment by richierocks** [comment]
Try Thomas Leeper's [msgtools](https://github.com/leeper/msgtools), though it's a work-in-progress.
