### ISSUE TITLE
cran = TRUE

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#866]
Should use `--as-cran` and set the env vars we need to turn off.

**Comment by hadley** [comment]
@wch would have a little time to look into this? It causes some hassles for CRAN.

**Comment by wch** [comment]
Can you clarify a bit? I'm not sure exactly what you mean.

**Comment by hadley** [comment]
Currently we set a whole lot of envvars to mimic what as cran does  instead we should probably use regular as cran and override only the envvars for things we want to turn off.

**Comment by eibanez** [comment]
Will this catch the new requirement that functions from all packages other than base (e.g., utils) need to be explicitly imported?

**Comment by hadley** [comment]
@elbanez yes, if you're using R-devel

**Comment by eibanez** [comment]
Excellent. Thanks, Hadley.
