### ISSUE TITLE
Error when using `install_local` w/in a cloned github repo (v1.8.0)

### ISSUE THREAD

**Issue by carljv** [hadley/devtools#868]
In version 1.7 I was able to clone a github repo w/ a source package and install it from that directory.  For example, see the README here: https://github.com/polynumeral/academia-citations/tree/461d21222f200497d63724b08c99d5178217ec2e

As of version 1.8, this no longer works, because of something failing around the call to `git2r::repository`:

```
> devtools::install_local('acadcites_0.2.tar.gz')
Error in .local(path, ...) : 'path' is not a directory
> traceback()
14: stop("'path' is not a directory")
13: .local(path, ...)
12: git2r::repository(path)
11: git2r::repository(path)
10: git_sha1(path = x$path)
9: remote_metadata.local_remote(remote, bundle, source)
8: remote_metadata(remote, bundle, source)
7: stopifnot(is.list(x), is.list(val))
6: modifyList(desc, meta)
5: add_metadata(source, remote_metadata(remote, bundle, source))
4: FUN(X[[i]], ...)
3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
2: install_remotes(remotes, ...)
1: devtools::install_local("acadcites_0.2.tar.gz")
```
which doesn't work when the path (here the `tar.gz` file) is not a directory. I'm not sure if this is a devtools bug or a git2r bug. The git2r source is rather dense and so I've been unable to make much progress debugging there.

For now, copying the source package out of the cloned folder seems to fix the issue. (Because the `uses_git` call no longer returns TRUE, and `git2r::repository` is never called).

**Comment by carljv** [comment]
As a workaround, I've just put the raw/unbuilt source in the repo, so we can use `install_github` (which doesn't seem to work for built packages).

**Comment by hadley** [comment]
Do you have the dev version of devtools?

**Comment by carljv** [comment]
No --
` devtools  * 1.8.0   2015-05-09 CRAN (R 3.2.0)`

**Comment by hadley** [comment]
Please try installing the development version, and if that fails, post a minimal repfrex.
