### ISSUE TITLE
install_github() fails to install non-CRAN deps

### ISSUE THREAD

**Issue by dtenenba** [hadley/devtools#869]
I have a package in Github that has a Bioconductor package (BiocCheck) in its Suggests field. I thought if I passed the bioconductor repos as the `repos` argument that I could install my package and the Bioconductor dependency in one go, but it doesn't work:

```{r}
# in R-3.2.1
library(devtools)
install_github("dtenenba/anRpackage", build_vignettes=TRUE, 
  repos="http://bioconductor.org/packages/3.2/bioc", 
  dependencies=TRUE, type="source")
```

The output says `Skipping 1 packages not available: BiocCheck`. The package fails to build (and install) because its vignette requires that BiocCheck be present and is set to fail on error. The repos argument is supposed to be passed to `install.packages()` which is never called (I know this because I set `debug(install.packages)`). So something else is deciding that BiocCheck is not available, and that something else is not using the repos argument that I passed in.

**Comment by hadley** [comment]
Fixed by #895? cc @jimhester

**Comment by jimhester** [comment]
This is actually a different issue that I have just tracked down, I will send a pr fixing it in the next couple of minutes.

**Comment by jimhester** [comment]
@hadley your fix at https://github.com/hadley/devtools/commit/884d6e2bdd8eb515bc012bca91bb51b12e44b332 will fix this as well, it was the same issue at heart in both.

**Comment by hadley** [comment]
It's still not quite right:

```
> install_github("dtenenba/anRpackage", build_vignettes=TRUE, 
+     repos="http://bioconductor.org/packages/3.2/bioc", 
+     dependencies=TRUE, type="source")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo dtenenba/anRpackage@master
Installing anRpackage
Skipping 8 packages not available: devtools, httr, knitr, optparse, RCurl, rmarkdown, RUnit, XML
Installing 1 packages: BiocCheck
Installing package into ‘/Users/hadley/R’
(as ‘lib’ is unspecified)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 20 4025k   20  814k    0     0  1954k      0  0:00:02 --:--:--  0:00:02 1952k100 4025k  100 4025k    0     0  3623k      0  0:00:01  0:00:01 --:--:-- 3626k
ERROR: dependency ‘optparse’ is not available for package ‘BiocCheck’
* removing ‘/Users/hadley/R/BiocCheck’
```

So I'm not getting quiet downloading for some reason, and optparse doesn't get installed (probably because it's on CRAN and that repo is clobbered)

**Comment by jimhester** [comment]
Try
```r
install_github("dtenenba/anRpackage", build_vignettes=TRUE, 
  repos=BiocInstaller::biocinstallRepos(),
  dependencies=TRUE, type="source")
```
That sets a CRAN repo properly, so should work.  This is also what https://github.com/hadley/devtools/pull/895 is doing.

**Comment by hadley** [comment]
Oh, the file doesn't download quietly because `type = "source"`

**Comment by hadley** [comment]
Thanks!
