### ISSUE TITLE
Use system2 instead of system in system_check

### ISSUE THREAD

**Issue by leeper** [hadley/devtools#872]
So, it looks `devtools::system_check()` originally used `system()` then switched to `system2()`, then switched back (here: https://github.com/hadley/devtools/commit/e11e949b1d92a9f097aaaf4318330d477b978708). Is there logic to this?

The reason I ask is [a StackOverflow question](http://stackoverflow.com/questions/31251544/how-can-i-send-the-output-of-r-cmd-check-to-a-file-or-variable) that came up today about redirecting the output of `check()` to a file. It doesn't seem like this is possible for two reasons:

 1. `check_r_cmd()` has a `...` that is passed to `system()` via `R()`, but that `...` is not accessible from `check()`. The `...` in `check()` goes to provide access to the `manual`, `vignette`, and `binary` arguments to `build()`, while there is no `check_args` (or similar) argument to pass arguments to `check_r_cmd`.
 2. The use of `system` means there's no way to redirect output, whereas there would be under `system2` (see my answer on SO).

That's two issues, but they're related. I would propose switching `system()` back to `system2()` and then either (1) adding an generic list-like argument to `check()` to pass arguments to `system()` or (2) explicitly exposing an output redirection option through the whole stack of check-related functions.

**Comment by hadley** [comment]
`system2()` is a just wrapper for `system()`, so I'd prefer to use `system()` directly.  Plus this code is sensitive and not well tested, so I'd need a very strong argument to change it.

Why not just use the log generated by R CMD check?

**Comment by leeper** [comment]
Well, `system2()` is not a wrapper for `system()`; they're both wrappers for the same Internal but `system()` does not expose all of the arguments of that internal to the user. It seems like you want to be using `system2()` because that's the recommendation (according to the R docs) due to it providing finer control. And the code for `system_check()` is doing things like setting environment variables and concatenating a system command, which could be handled directly by `system2()`. (I assume that's why you were using `system2()` previously?)

That said, in terms of the specific problem motivating all of this, I think pointing to the .Rcheck file makes sense.

**Comment by hadley** [comment]
The recommendation to use `system2()` in the docs is not good - I've been burned before.  The way it sets env var is extremely suboptimal - it just lumps then together before the command `A=1 B=1 ls`.

**Comment by leeper** [comment]
Interesting...that seems like a strange recommendation, then.
