### ISSUE TITLE
imports in startup

### ISSUE THREAD

**Issue by brry** [hadley/devtools#874]
**Key issue:**
devtools::install depends on utils and stats, so it doesn't run in the startup, where these two are not loaded/attached yet.

**Details:**
From Rprofile.site, I can't install my package with 
```R
devtools::install("path/to/my/package")
```
--> could not find function "available.packages"
--> could not find function "update"
If I first 'library' the corresponding two packages utils and stats, it works fine.

Is this an import issue?
Or is it expected not to work without first loading the packages in the startup routine?

Here's the reverse traceback:
devtools::install
-> install_deps
-> dev_package_deps
-> package_deps
-> available_packages
-> f 
-> suppressWarnings(available.packages(contrib.url(repos, type),  type = type))
-> withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))

**Comment by hadley** [comment]
This will be fixed in the next release (because the dev version of R now will pick up these missing issues), but installing a package in your Rprofile is a rather unusual thing to do.

**Comment by brry** [comment]
Awesome. (I use it in Rprofile to install the package I'm developing if there is a more recent version on my harddrive than currently installed. I tend to forget to RCMD INSTALL at the end of the day and later wonder where my fixes went.)
