### ISSUE TITLE
with_something fns should be split into their own package

### ISSUE THREAD

**Issue by richierocks** [hadley/devtools#876]
The `with_*` functions are useful outside of a package development context, so they should be split into their own small package.

One particular benefit is that if you have a package with `testthat` tests and translated messages, you want to run the tests with language fixed to (probably) US English.  So the `testthat.R` file now contains:

```{r}
library(testthat)
library(devtools)
library(yourpackage)

with_envvar(
  c(LANG = "en_US"),
  test_check("yourpackage")
)
```

It feels a little cumbersome to have `devtools` as a suggested package just for this, but a smaller `withr` (?) package would be fine.

**Comment by jimhester** [comment]
See https://github.com/jimhester/robustr for a start to this

**Comment by hadley** [comment]
Once this robustr on CRAN, I'd be happy to review a PR

(ps. I think wither would be a cooler name ;)

**Comment by jimhester** [comment]
I changed the name to withr, but maybe I should stick the 'e' on as well...

I want to make a withering vine logo for it, but my photoshop / artistic talents are lackluster at best. :frowning:
