### ISSUE TITLE
Feature Request: clean() to remove all generated files

### ISSUE THREAD

**Issue by johann-petrak** [hadley/devtools#882]
A function devtools::clean() that removes all files which are automatically generated by devtools would help to e.g. check a project into some version control system.

**Comment by gaborcsardi** [comment]
Hmmm, what files specifically? I can't recall having to remove any files. Maybe you just need a `.gitignore` file?

**Comment by johann-petrak** [comment]
I think the cleaner solution would be for the tool to know which files get generated. Having a method that removes everything that gets generated would be helpful independently of the used VCS and for other tasks too. But a .gitignore file would also be helpful if devtools generates it and pre-fills it with the list of files/patterns of what gets generated. But the basic point is that the authors of the tools usually know better which files these are than the end-user. 
TBH I have submitted this because I am a noob and I feel that others know better which files to not check in.
So, from my noob perspective, I think ideally the clean() method would remove all the *.Rd files that got generated, the NAMESPACE file, other files generated by roxygen2, any compiled files, and probably others I do not even know about yet. 
Again, experienced users or the tool authors probably know much better the detailed list.

**Comment by hadley** [comment]
devtools generally already protects you against any problems by adding appropriate files to `.gitignore` and `.Rbuildignore`. If you have a concrete problem, I'm happy to fix it, but I don't think there's any need to for a clean function. In particular, it's best practice to check in the NAMESPACE and Rd files.

**Comment by gaborcsardi** [comment]
> I think the cleaner solution would be for the tool to know which files get generated. Having a method that removes everything that gets generated would be helpful independently of the used VCS and for other tasks too. 

`git clean -fdx` removes everything that is not in the VCS.

> But a .gitignore file would also be helpful if devtools generates it and pre-fills it with the list of files/patterns of what gets generated.

`devtools` already does that AFAIR.

> So, from my noob perspective, I think ideally the clean() method would remove all the *.Rd files that got generated, the NAMESPACE file, other files generated by roxygen2, any compiled files, and probably others I do not even know about yet.

You are supposed to put the .Rd files and NAMESPACE in the VCS. Otherwise tools like `install_github` do not work correctly. 

Compiled files are ignored by default in `devtools`'s `.gitignore` AFAIR. Again, you can remove them with `git clean -fdx`.

I hope this helps.
