### ISSUE TITLE
release() failing under new version of git2r

### ISSUE THREAD

**Issue by tmcd82070** [hadley/devtools#883]
I updated to R 3.2.1 today, and updated all packages (devtools, git2r).  The following error occurs when release is called, 

`
> release()
Warning: DR_DEVTOOLS FOUND PROBLEMS
* Devtools or dependencies out of date: BH
Error in git2r::status(r, verbose = FALSE) : 
  unused argument (verbose = FALSE)
`

git2r::status(r) works without verbose=FALSE.  My guess is that git2r removed the verbose parameter.

**Comment by hadley** [comment]
Pretty sure this is fixed now
