### ISSUE TITLE
Why does devtools 1.8 import so many namespaces, but doesn't in 1.7?

### ISSUE THREAD

**Issue by jeffwong** [hadley/devtools#886]
On my macbook I am running devtools 1.8 which loads Rcpp through a namespace. On another ubuntu machine using devtools 1.7 nothing else is loaded. I noticed this when I was trying to update Rcpp through an install.packages(...), but RStudio complained that because Rcpp was already loaded it would need to restart. I didn't recognize that devtools uses Rcpp so upon restart I loaded devtools again (so that I can get install_github for a different package) and then saw the same error that I couldn't update Rcpp because it was loaded.  The simple answer I think is to install.packages(Rcpp), then load devtools and call install_github for my other package, but this seems cumbersome to keep track of what devtools imported.  What are some other workarounds for this?

> require(devtools)
Loading required package: devtools
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] devtools_1.8.0

loaded via a namespace (and not attached):
[1] rversions_1.0.1 curl_0.9.1      Rcpp_0.11.6     memoise_0.2.1
[5] xml2_0.1.1      git2r_0.10.1    digest_0.6.8

> require(devtools)
Loading required package: devtools
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] devtools_1.7.0

**Comment by jeffwong** [comment]
A strange consequence to this is Rcpp cannot be required after devtools

> require(Rcpp)
Loading required package: Rcpp
Error in unloadNamespace(package) :
  namespace ‘Rcpp’ is imported by ‘xml2’ so cannot be unloaded
Failed with error:  ‘Package ‘Rcpp’ version 0.11.6 cannot be unloaded’

**Comment by wch** [comment]
That's strange - why would Rcpp be trying to unload itself?

**Comment by jeffwong** [comment]
Sorry I was the culprit on the first issue of not being able to update Rcpp because it's already loaded - this was because I had a require(Rcpp) tucked away in my script. However the second issue is pretty strange

    require(devtools)
    require(Rcpp)

in a clean R session will show an error. If you require them in the opposite order it will go succeed though

**Comment by gaborcsardi** [comment]
I have the same platform as you and cannot replicate this with any devtools/Rcpp versions, CRAN or GitHub.

**Comment by wch** [comment]
I can't reproduce it either. `require()` shouldn't ever try to unload a package. Do you have something in your `~/.Rprofile` that might be modifying the behavior?

If you type `require` and hit enter, it should show a function that looks like this:
 https://github.com/wch/r-source/blob/826de7c2/src/library/base/R/library.R#L586-L616
