### ISSUE TITLE
interface `make` [feature-request]

### ISSUE THREAD

**Issue by cbeleites** [hadley/devtools#887]
Would a tiny interface function to call `make` be welcomed?

I mostly use devtools by now, but  I have `make` targets for some tasks such as 

- preparing vignettes where the source is too large and/or calculations are too time consuming to be allowed on CRAN. These are prepared offline; pdfs go with the package but the real source & data is distributed via the project web site.
- the same applies to some tests
- `jekyll` for updating the project web site

**Comment by famuvie** [comment]
I would certainly appreciate it.

**Comment by hadley** [comment]
As I mentioned in the pull request, devtools is already too big, so I think this belongs elsewhere.
