### ISSUE TITLE
absence of hooks directory is not definitive test for git repo

### ISSUE THREAD

**Issue by jennybc** [hadley/devtools#888]
I confess: I created a git repo using [sourcetree](https://www.sourcetreeapp.com) instead of `git init` or RStudio. Apparently this can lead to a repo in which the `.git` directory does not contains a `hooks` subdirectory. Even after you've made a commit. So when I attempt to use `devtools::use_readme_rmd()`, I hit [this code](https://github.com/hadley/devtools/blob/0b122b24cead594b86d237eb6965205c8fd27c64/R/infrastructure-git.R#L81-L84) in `use_git_hook()` and get `Error: This project doesn't use git`. Apparently there are [other](https://gitlab.com/gitlab-org/gitlab-ce/issues/1327) [ways](https://github.com/sprintly/Sprintly-GitHub/issues/17) to have a valid git repo and yet NOT have a `hooks` subdirectory.

I admit this maybe a rare phenomenon. Not sure if a different error message is the way to go or just outright creation of `hooks`.

**Comment by jennybc** [comment]
FWIW, from reading Git docs and my own experience, it seems perfectly OK to create the `.git/hooks` subdirectory *de novo* and carry on.

**Comment by hadley** [comment]
Agreed. Want to do a PR or want me to do it?

**Comment by jennybc** [comment]
I am happy either way. Was planning to PR this after the one other played itself out. This is much smaller thing.
