### ISSUE TITLE
install_github and LFS

### ISSUE THREAD

**Issue by mdlincoln** [hadley/devtools#889]
With GitHub now gradually rolling out LFS, is it possible to support downloading files tracked with LFS through `install_github`? Currently, it seems only to clone the pointers to LFS-tracked files, not the files themselves.

**Comment by hadley** [comment]
If you can tell me what to do, I can do it. But I don't have access to LFS (even though I applied to the beta months ago)

**Comment by jennybc** [comment]
Hey! Git Large File Storage (Git LFS) has reached a 1.0 milestone and is now available to all repositories on GitHub.com

https://github.com/blog/2069-git-large-file-storage-v1-0

**Comment by zji90** [comment]
It would be very helpful if install_github can download the data file tracked by LFS. I have a package now on github using LFS but install_github cannot get the LFS tracked file. I have to ask users to manually download and install the package, which is tedious.

**Comment by rBatt** [comment]
I just ran into this too with 

```{r}
*** moving datasets to lazyload DB
Warning: file ‘ETOPO.RData’ has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error : bad restore file magic number (file may be corrupted) -- no data loaded
```

**Comment by rBatt** [comment]
Also, like @jennybc mentions, I'm pretty sure you don't need a special invite anymore, @hadley 

Right now I tell people to clone the repo, and to just use `devtools::install()`.

**Comment by hadley** [comment]
There doesn't seem to be a github API for this, and the github docs on LFS are terrible, so I'm not optimistic about this.

**Comment by jennybc** [comment]
In addition to no API, I think for public repositories you have to choose between using LFS and using forks + pull requests? This was written in October 2015 -- I'm not sure if anything has changed for the better.

[GitHub’s Large File Storage is no panacea for Open Source — quite the opposite](https://medium.com/@megastep/github-s-large-file-storage-is-no-panacea-for-open-source-quite-the-opposite-12c0e16a9a91#.coe0d5f4q)

@mdlincoln I'm not sure what your large file problem is, but you might want to look at [`datastorr`](https://github.com/richfitz/datastorr) by @richfitz or the ideas there. From him I learned you can attach inconveniently large files to GitHub releases (and yet they don't live in your repo) and a lot of the normal GH limits don't apply. It seems too good to be true and I'm sure he can explain it better.

**Comment by mdlincoln** [comment]
agreed re: all of this

On Wed, Jan 20, 2016 at 3:30 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> In addition to no API, I think for public repositories you have to choose
> between using LFS and using forks + pull requests? This was written in
> October 2015 -- I'm not sure if anything has changed for the better.
>
> GitHub’s Large File Storage is no panacea for Open Source — quite the
> opposite
> <https://medium.com/@megastep/github-s-large-file-storage-is-no-panacea-for-open-source-quite-the-opposite-12c0e16a9a91#.coe0d5f4q>
>
> @mdlincoln <https://github.com/mdlincoln> I'm not sure what your large
> file problem is, but you might want to look at datastorr
> <https://github.com/richfitz/datastorr> by @richfitz
> <https://github.com/richfitz> or the ideas there. From him I learned you
> can attach inconveniently large files to GitHub releases (and yet they
> don't live in your repo) and a lot of the normal GH limits don't apply. It
> seems too good to be true and I'm sure he can explain it better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/devtools/issues/889#issuecomment-173350404>.
>



-- 
Matthew D. Lincoln
Ph.D Candidate
Department of Art History & Archaeology <http://arthistory.umd.edu>
University of Maryland
College Park, MD 20742

mlincol1@umd.edu
matthewlincoln.net

**Comment by rBatt** [comment]
It looks like GitHub changed the way LFS files are displayed --- clicking to download a .RData file, for example, no longer downloads the 3 lines of text, but instead downloads the actual binary. However, I run into the same issue with `devtools::install_github()`.

If someone is able and motivated, it might be taking another look at tackling this problem to see if recent changes might have made facilitated the use of `install_github()` with Git LFS>
