### ISSUE TITLE
Command 'library' with devtools or git2r returns error

### ISSUE THREAD

**Issue by Gofer51** [hadley/devtools#890]
OS: Windows XP 3
R: 3.2.1
RStudio: 0.99.467
devtools: 1.8.0
git2r: 0.10.1

![image](https://cloud.githubusercontent.com/assets/13706748/9150337/cb2a156a-3dd4-11e5-9c08-dec809328477.png)

> library("devtools", lib.loc="C:/Programmi/R/R-3.2.1/library")
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Programmi/R/R-3.2.1/library/git2r/libs/i386/git2r.dll':
  LoadLibrary failure:  Impossibile trovare la procedura specificata.(*)

Error: package or namespace load failed for ‘devtools’

(*)Translate: It's not possible find specified procedure.

**Comment by hadley** [comment]
Probably need to reinstall git2r

**Comment by Gofer51** [comment]
I reinstalled git2r but there is the same error message. Again: the problem
is present only with git2r and then consequently with devtools.
I will report issue to github/git2r.
Thanks

Goffredo Iannetti

2015-08-08 14:52 GMT+02:00 Hadley Wickham <notifications@github.com>:
