### ISSUE TITLE
Rtools absent registry information

### ISSUE THREAD

**Issue by spadehed** [hadley/devtools#904]
Installed R and Rtools on a machine without admin rights, so unable to set registry version information in HKLM tree.  Have created the relevant information manually under HKLU instead, but the devtools scan_registry_for_rtools function doesn't check this tree.

Consistently getting the warning message about rtools not being installed, even though it is available.

**Comment by hadley** [comment]
It currently checks HCU and HLM. Should it also try HKLU (and HKLM?) instead? And in what order? (and a little explanation would be helpful since I no nothing about the registry)

**Comment by hadley** [comment]
@jjallaire any thoughts on this? I don't know which registry "hives" I should be looking in.

**Comment by spadehed** [comment]
HKLU would be a good option in addition to the others, as it is the Users own registry tree that is searched.  It's main use would be for those stuck on windows machines without admin rights who have installed Rtools, but are unable to set the registry values in the main HKLM hive, they could then set their own user values themselves.

Admittedly it is likely a small pool of users who would be affected by this.

**Comment by hadley** [comment]
So I should try (in order) HCU, HLM, HKLU and HKLM?

**Comment by jjallaire** [comment]
I don't have any thoughts beyond what devtools and rstudio already do (I
actually thought that HCU was an alias to user-writeable storage so could
still work with non-admin installs).

**Comment by hadley** [comment]
Reading around about registry hives, I think the current behaviour is correct. @spadehed I suspect your problem will be fixed if you just try the dev version.
