### ISSUE TITLE
Shared library is not reloaded instead of a compile error

### ISSUE THREAD

**Issue by mikeyupol** [hadley/devtools#934]
Hi Everyone,

Stumbled upon a weird issue that took a couple of hours of restarting R and loading packages to pinpoint. I've finally found what's causing this, but I'm confounded as to why, on two fronts. Not sure if this belongs in Rcpp forum, please let me know if I should repost there.

First a brief description of the problem: assigning an integer to an element of Rcpp::CharacterVector doesn't produce a compile time error. This is an issue number one. It's an issue with Rcpp, not devtools, and I can study the code and understand how it's allowed, although probably not why. The second issue is that doing so makes R not reload the shared library of my package when I re-install it using load_all(). This is the real puzzle to me.

Now to reproduce the problem. I'm running 64bit Ubuntu Linux Trusty 14.04 with 3.13.0-61-generic kernel. Start a new R session and do:

```R
> library(devtools)
> library(Rcpp)
> session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2015-09-18                  

Packages -----------------------------------------------------------------------
 package    * version date       source        
 devtools   * 1.9.1   2015-09-11 CRAN (R 3.2.2)
 digest       0.6.8   2014-12-31 CRAN (R 3.2.2)
 memoise      0.2.1   2014-04-22 CRAN (R 3.2.2)
 Rcpp       * 0.12.1  2015-09-10 CRAN (R 3.2.2)
 rstudioapi   0.3.1   2015-04-07 CRAN (R 3.2.2)

> create("testpkg",rstudio=F)
```
This is my DESCRIPTION file:
```
Package: testpkg
Title: What the Package Does (one line, title case)
Version: 0.0.0.9000
Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
Description: What the package does (one paragraph).
Depends: R (>= 3.2.2)
License: What license is it under?
LazyData: true
Imports: Rcpp
LinkingTo: Rcpp
```
This is my NAMESPACE file:
```
exportPattern("^[^\\.]")
useDynLib(testpkg)
importFrom(Rcpp, sourceCpp)
```

And this is my C++ code in testpkg/src/test.cpp:
```C++
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
CharacterVector tptest() {
  return wrap("foo");
}

RObject some_test() {
  CharacterVector c(1);
  c[0] = 1;
  return c;
}
```

After this setup in R session load the package the first time:
```R
> load_all("testpkg", quiet=T)
> tptest()
[1] "foo"
```
I then modify the function tptest() in test.cpp to return string "bar" and reload in R:
```R
> load_all("testpkg", quiet=T)
> tptest()
[1] "foo"
```

The string didn't change, it's still "foo". It looks like the shared library is not reloaded. Any changes in test.cpp after this point will not be visible after the package is reloaded with load_all(). I've tried adding functions, removing them (after which I can still use .Call to call them), changing arguments... nothing works. R session now needs to be restarted and the package loaded anew for the changes to take effect.

If however the code `c[0] = 1;`, which is incorrect and should not even have compiled, is replaced with `c[0] = "aaa";` everything works. I can reload the package with load_all() and see my changes reflected right away. (Notice that the R session has to be restarted for the correct code to take effect.)

So my question is:
1. This is for Rcpp forum: how come the C++ code `c[0] = 1;` above compiles? If someone happens to know here for a reason, please point me in the right direction.
2. How come after inclusion of this incorrect code the shared library of a package is not reloaded with load_all()? I think this question belongs in this forum, but please tell me if I should post this to Rcpp.

Thanks.

**Comment by hadley** [comment]
That's very weird - I've never seen that problem before and I do a lot of re-loading of C++ code. Unfortunately it's likely to be something idiosyncratic with your setup/environment.
