### ISSUE TITLE
install_version fails because of CRANextra

### ISSUE THREAD

**Issue by oseiskar** [hadley/devtools#943]
`devtools::install_version` apparently tries to download already installed packages from the "CRANextra" repo, which can cause the installation to fail for no good reason.

My `getOption('repos')` is

                                CRAN                            CRANextra 
         "https://cran.rstudio.com/" "http://www.stats.ox.ac.uk/pub/RWin" 

and when I try `devtools::install_version('data.table', '1.9.4')`, the very end of the 
installation fails with

    ...
    ** testing if installed package can be loaded
    *** arch - i386
    *** arch - x64
    * DONE (data.table)
    Downloading package from url: http://www.stats.ox.ac.uk/pub/RWin/src/contrib/Archive/data.table/data.table_1.9.4.tar.gz
    Error in download(bundle, x$url, x$config) : 
      client error: (404) Not Found

__even though the package was installed succesfully__ (`library(data.table)` succeeds).

If I remove "CRANextra" from repos, with, e.g., 

    devtools::install_version('data.table', '1.9.4', repos='https://cran.rstudio.com/')
    
the installation succeeds.

**Comment by karl-forner-quartz-bio** [comment]
same kind of problems here. install_version fails with length(repos) > 1.
My current work-around is to set the repos params, e.g. repos= getOption("repos")[1]

**Comment by hadley** [comment]
@jimhester could you take a look at this one too please?

**Comment by jimhester** [comment]
@hadley might be easier for me (and you) to keep track of if you just assign these issues to me. It doesn't look like I can assign them to myself. :frown:
