### ISSUE TITLE
I don't understand how to use Remotes with travis

### ISSUE THREAD

**Issue by jennybc** [hadley/devtools#944]
I'm trying to understand how to express that a package depends on the development/github version of another package. Such the right things happen for a user who does `devtools::install_github("jennybc/whatever")` and that it build successfully on travis for me.

I hoped I could specify a non-CRAN version for the dependency in DESCRIPTION and add the new `Remotes` field. But that leads to a failure on travis. Here's the possibly most informative part of the log:

```
[0K$ Rscript -e 'options(repos = "http://cran.rstudio.com"); tryCatch({   deps <- devtools::install_deps(dependencies = TRUE) }, error = function(e) {   message(e);   q(status=1) }); if (!all(deps %in% installed.packages())) {  message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", "));  q(status = 1, save = "no") }'
Malformed remote specification 'hadley/readr'travis_time:end:03ddefb0:start=1443816228668380316,finish=1443816228819430449,duration=151050133
[0K
[31;1mThe command "Rscript -e 'options(repos = "http://cran.rstudio.com"); tryCatch({   deps <- devtools::install_deps(dependencies = TRUE) }, error = function(e) {   message(e);   q(status=1) }); if (!all(deps %in% installed.packages())) {  message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", "));  q(status = 1, save = "no") }'" failed and exited with 1 during .[0m

Your build has been stopped.
```

Note this: `Malformed remote specification 'hadley/readr'`.

I get a successful build when I remove `Remotes` from DESCRIPTION and instead put this in `.travis.yml`:

```
r_github_packages:
- hadley/readr
```

Am I just missing how the various moving parts in DESCRIPTION and `.travis.yml` interact?

Here's a little test package [jennybc/jane](https://github.com/jennybc/jane) and my exploration of failure on travis [jennybc/jane](https://travis-ci.org/jennybc/jane/builds).

cc @jimhester

**Comment by jimhester** [comment]
This is unfortunately currently broken until https://github.com/hadley/devtools/pull/936 is merged.

If you do
```yaml
r_github_packages:
  - hadley/devtools#936
```
It should work without without having to specify `hadley/readr` in `.travis.yml`.

**Comment by jennybc** [comment]
OK so when that's merged the depedency on a dev/github version could be fully captured in DESCRIPTION? You won't have to change `.travis.yml` and you won't have to put something in a `README.md` that says, e.g., `devtools::install_github("hadley/readr"); devtools::install_github("jennybc/jane")`?

**Comment by jimhester** [comment]
Yeah exactly that is the idea, it just has the bug currently that prevents
it from working on travis because devtools is not attached to the search
path in the travis-r script (so it can't find the proper `install_*`
function).

**Comment by jennybc** [comment]
[Yay](https://github.com/jennybc/jane/commit/d40987207e80f0226f31a3d10cd8ab247c681d6f) [it works!](https://travis-ci.org/jennybc/jane/builds/83376850) Thanks.

**Comment by jennybc** [comment]
One last thing: the bit about the user getting the proper result with a simple `devtools::install_github("jennybc/jane")` ... that will require that *they* have the post-merge dev version of devtools ... yes?

**Comment by jimhester** [comment]
Yes, so it is still a ways away before it can be used widely, I wish I had caught this bug before the last release :frowning:

**Comment by maxheld83** [comment]
Is it possible this problem still exists and/or that there has been a recursion @jimhester @jennybc?

I am running `devtools` `1.12.0`, and so, presumably, is Travis CI.

I've added a reproducible example on this [repo branch](https://github.com/maxheld83/travis-cache-test/tree/remotes-test). Also see this [failing](https://travis-ci.org/maxheld83/travis-cache-test/builds/199207562) and this [successful](https://travis-ci.org/maxheld83/travis-cache-test/builds/199210574) build.

It appears that again, setting `r_github_packages` in the `.travis.yml` works, but the equivalent settings just in `DESCRIPTION` do not.

----

## Successful Build

**`.travis.yml`**

```
language: r

sudo: false

r_github_packages:
  - maxheld83/qmethod

warnings_are_errors: false

cache:
  packages: true

script:
  - Rscript test-script.R

notifications:
  email: false
```

**DESCRIPTION**:

```
Package: travis-cache-test
Title: placeholder
Version: 0.0.0.9000
Authors@R: c(
    person("Maximilian", "Held", email = "info@maxheld.de", role = "cre")
Depends:
    R (>= 3.2.3)
License: None
Encoding: UTF-8
LazyData: true
Imports: 
  ggplot2,
  devtools
```

-----

## Failing Build

`.travis.yml`:

```
language: r

sudo: false

warnings_are_errors: false

cache:
  packages: true

script:
  - Rscript test-script.R

notifications:
  email: false
```


`DESCRIPTION`

```
Package: travis-cache-test
Title: placeholder
Version: 0.0.0.9000
Authors@R: c(
    person("Maximilian", "Held", email = "info@maxheld.de", role = "cre")
Depends:
    R (>= 3.2.3)
License: None
Encoding: UTF-8
LazyData: true
Imports: 
  ggplot2,
  devtools
Remotes: github::maxheld83/qmethod
```

**Comment by jimhester** [comment]
You need to have the Remotes in one of the other fields as well, e.g. `Imports:` `Suggests:` `Depends:` `LinkingTo:`.

Also it isn't necessary to specify `github::`, that is the implicit default.

**Comment by maxheld83** [comment]
thanks @jimhester. 
I added some PRs to make sure other people as dense as myself don't stumble upon this. 

- [x] [Travis-CI Docs](https://github.com/travis-ci/docs-travis-ci-com/pull/957)
- [ ] Remotes vignette
- [ ] rpkgs book (maybe?)
