### ISSUE TITLE
Using unlockBinding produces check NOTE for unsafe calls

### ISSUE THREAD

**Issue by renkun-ken** [hadley/devtools#949]
I'm writing a package in which I create an environment and want to protect it against user modification by `lockEnvironment(x, bindings = TRUE)`. While a symbol in the environment can be updated by a package function. The function first checks if the newly supplied value is valid and unlocks the binding, assign, and re-lock the binding.

However, I notices that when I use `unlockBinding`, it will produce a NOTE in package check:

```
* checking R code for possible problems ... NOTE
Found the following possibly unsafe calls:
File 'reflite/R/ref.R':
  unlockBinding("object", object)
```

Will this prevent the package from accepting by CRAN due to this NOTE?

**Comment by hadley** [comment]
You should avoid all NOTEs if possible. Just don't expose the environment to the user rather than locking it.
