### ISSUE TITLE
load_all always reloads data

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#953]
It would be great to have implement lazy-loading here, too. The main problem seems to be that the names are not known until the `.rda` files are read. Some kind of index seems to be necessary, invalidated when updating the data files. The index should perhaps be persistent.

**Comment by krlmlr** [comment]
Can be worked around by placing data into `inst/extdata` instead.

**Comment by vsbuffalo** [comment]
Sorry to reopen this issue, but is `inst/extdata` the preferred method here? I think there's a case to be made that data should be in `data/` (as recommended in the book *R Packages*) and `load_all()` should listen to `LazyData: true` in `DESCRIPTION`.

**Comment by krlmlr** [comment]
Comments in closed issues tend to be overlooked. I have no idea how to implement such a feature efficiently, given the data is stored in `.rda` files, and it may not be worth the effort (hasn't been for me, at least).

**Comment by gaborcsardi** [comment]
@krlmlr hash the data file(s) and only reload if they change? This assumes that hashing is much quicker than loading, which is probably true, but we would need to measure it.

**Comment by krlmlr** [comment]
Hash + timestamp would be faster, yes. Anyway, this discussion belongs in *pkgload* now.?

**Comment by gaborcsardi** [comment]
> Hash + timestamp would be faster, yes.

Some file systems do not have proper mtimes, so timestamps can be messy. Hashing is simpler imo.

> Anyway, this discussion belongs in pkgload now.?

Indeed.
