### ISSUE TITLE
Check for vignettes titled "Vignette Title"

### ISSUE THREAD

**Issue by jennybc** [hadley/devtools#960]
I keep coming across vignettes entitled "Vignette Title". Here are some of the ones currently on CRAN:

https://github.com/search?l=rmarkdown&q=%22Vignette+Title%22+user%3Acran&ref=searchresults&type=Code&utf8=✓

This might be nice to catch in a doctor function or `release()`?

**Comment by hadley** [comment]
Yes!

**Comment by hadley** [comment]
Any interest in doing a PR for this?  I think you could just do a regexp on the first (say) ~20 lines.  It would be another function called from `release_checks()`

**Comment by jennybc** [comment]
OK yes.
