### ISSUE TITLE
Deprecated openssl on osx preventing from git2r install

### ISSUE THREAD

**Issue by iros** [hadley/devtools#961]
I believe this applies to 10.11 (although I am seeing it on 10.10 as well.)
When running `install.packages("devtools")` I am running into an issue installing `git2r` as a result of the deprecation of openssl on osx.  See this issue:

https://github.com/ropensci/git2r/issues/162

My temporary fix has been to set the path to my openssl (brew installed) like so:

https://github.com/ropensci/git2r/issues/162#issuecomment-151938467

Thanks!

**Comment by hadley** [comment]
This seems like a downstream problem, not a devtools problem?
