### ISSUE TITLE
load_all("PackageName") fails

### ISSUE THREAD

**Issue by kenahoo** [hadley/devtools#963]
This fails:

```
> load_all("PackageName")
Error: Can't find directory PackageName
```

The `load_all` function says it can accept a "package description, can be path or package name. See `as.package` for more information."

`as.package` says it can accept a "path" or "package object", but doesn't say how to create a package object.  It seems to be literally looking for something of class `"package"`, but blessing a name into that package doesn't help:

```
> load_all(structure("PackageName", class="package"))
Error in pkg$package : $ operator is invalid for atomic vectors
```

What's the proper way to do this?

I'm using devtools 1.9.1 on R 3.2.2.

**Comment by hadley** [comment]
It should be path. Where is your package relative to the working directory?

**Comment by kenahoo** [comment]
I can get it to work fine if I give it a path, but the docs say it can take a package name, and I was really hoping to use it that way.  Has that ever worked?

**Comment by hadley** [comment]
No. How could it know where your package is? (I admit the documentation is confusing)

**Comment by kenahoo** [comment]
It could easily know by just calling the `find.package()` function, which is what I'll use as a workaround I guess.

This does seem like a common use case - install a newer version of a package (perhaps one under active development locally) and then in a long-running session, load the new package.  It would be nice to support that flow.

**Comment by wch** [comment]
That wouldn't work, because an installed package (which is what `find.package()` gives you) has a very different structure from package source (which is what devtools wants for `load_all()`).

**Comment by wch** [comment]
Oh, unless you mean to call `find.package()` on a package that was loaded with `load_all()`. But then you'd still need a way to tell when a string represents the name of a package vs. the directory containing a package.

**Comment by kenahoo** [comment]
Given all that, I think there's still a bug here - `load_all` says it can take a package name, so that's a doc bug;  and if it really can only take a path string, then the code that's looking for a `package` object is also a code bug that should be removed.
