### ISSUE TITLE
Improve default warning behaviour

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#965]
``` R
options(
  warn = 1,
  warnPartialMatchDollar = TRUE,
  warnPartialMatchArgs = TRUE,
  warnPartialMatchAttr = TRUE
)
```

**Comment by hadley** [comment]
And check? Maybe it should be a argument to check()? (That's probably the best place for it)

**Comment by hadley** [comment]
I'm going to put this in my user profile and leave it to stew for a bit.  Can probably drop `warnPartialMatchArgs` since R CMD check already gets that.

**Comment by hadley** [comment]
From Kurt:

What the check code already does is

```R
    ## Allow specifying a codetools "profile" for checking via the
    ## environment variable _R_CHECK_CODETOOLS_PROFILE_, used as e.g.
    ##   _R_CHECK_CODETOOLS_PROFILE_="suppressLocalUnused=FALSE"
    ## (where the values get converted to logicals "the usual way").
    args <- list(skipWith = TRUE,
                 suppressPartialMatchArgs = FALSE,
                 suppressLocalUnused = TRUE)
    opts <- unlist(strsplit(Sys.getenv("_R_CHECK_CODETOOLS_PROFILE_"),
                            "[[:space:]]*,[[:space:]]*"))
```

so we should always see the partial match args notes in the code
analysis.

**Comment by helix123** [comment]
I would very much welcome such checks in devtools. While partial argument matching is checked for already by the above, having an complementary test especiallyfor  partial dollar matching (extraction by `$`) would be great!

**Comment by hadley** [comment]
Move to rcmdcheck
