### ISSUE TITLE
make 'devtools::create()', 'devtools::setup()' more flexible

### ISSUE THREAD

**Issue by kevinushey** [hadley/devtools#966]
I find myself doing something like this often:

1. Create a new project in RStudio (but forget to create it as an R package),
2. Wish that I could call `devtools::create()` or `devtools::setup()` to turn it into an R package.

Two things to 'wish' for:

1. `devtools::create()` shouldn't fail for empty directories (or directories only a .Rproj file),
2. `devtools::setup()` shouldn't fail if a `.Rproj` file already exists.

**Comment by hadley** [comment]
Any interest in implementing this?

**Comment by kevinushey** [comment]
Sure, I can take a shot at this.
