### ISSUE TITLE
Should devtools add DevtoolsNote field?

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#969]
Like RoxygenNote, this would make it easier to track usage, and in form users when a new version comes out.

**Comment by gaborcsardi** [comment]
IMO `DevtoolsNote` will not pass `R CMD check`. `RoxygenNote` does, because `Roxygen` is a valid key. So for devtools you would need another valid key, and append `Note` to if, which is not ideal.

**Comment by jimhester** [comment]
I believe the relevant source lines are https://github.com/wch/r-source/blob/c2eacc98080d425319d44708fc06435522315737/src/library/tools/R/QC.R#L6605-L6611, which gives us the following fields to choose from

``` r
paste0(tools:::.get_standard_DESCRIPTION_fields(),"Note")
#>  [1] "PackageNote"                 "VersionNote"                
#>  [3] "PriorityNote"                "DependsNote"                
#>  [5] "ImportsNote"                 "LinkingToNote"              
#>  [7] "SuggestsNote"                "EnhancesNote"               
#>  [9] "LicenseNote"                 "License_is_FOSSNote"        
#> [11] "License_restricts_useNote"   "OS_typeNote"                
#> [13] "ArchsNote"                   "MD5sumNote"                 
#> [15] "NeedsCompilationNote"        "Additional_repositoriesNote"
#> [17] "AuthorNote"                  "Authors@RNote"              
#> [19] "BiarchNote"                  "BugReportsNote"             
#> [21] "BuildKeepEmptyNote"          "BuildManualNote"            
#> [23] "BuildResaveDataNote"         "BuildVignettesNote"         
#> [25] "BuiltNote"                   "ByteCompileNote"            
#> [27] "Classification/ACMNote"      "Classification/ACM-2012Note"
#> [29] "Classification/JELNote"      "Classification/MSCNote"     
#> [31] "Classification/MSC-2010Note" "CollateNote"                
#> [33] "Collate.unixNote"            "Collate.windowsNote"        
#> [35] "ContactNote"                 "CopyrightNote"              
#> [37] "DateNote"                    "DescriptionNote"            
#> [39] "EncodingNote"                "KeepSourceNote"             
#> [41] "LanguageNote"                "LazyDataNote"               
#> [43] "LazyDataCompressionNote"     "LazyLoadNote"               
#> [45] "MailingListNote"             "MaintainerNote"             
#> [47] "NoteNote"                    "PackagedNote"               
#> [49] "SysDataCompressionNote"      "SystemRequirementsNote"     
#> [51] "TitleNote"                   "TypeNote"                   
#> [53] "URLNote"                     "VignetteBuilderNote"        
#> [55] "ZipDataNote"                 "RepositoryNote"             
#> [57] "PathNote"                    "Date/PublicationNote"       
#> [59] "LastChangedDateNote"         "LastChangedRevisionNote"    
#> [61] "RevisionNote"                "RcmdrModelsNote"            
#> [63] "RcppModulesNote"             "RoxygenNote"                
#> [65] "AcknowledgementsNote"        "AcknowledgmentsNote"        
#> [67] "biocViewsNote"
```

We could probably co-opt PackageNote, Package*d*Note, MaintainerNote or one of the other ones if they seem more suitable.

**Comment by hadley** [comment]
I like the idea of using `MaintainerNote`. 

When should this be recorded? On package creation? Every time you run `load_all()`? Every time `as.package()` is run?

**Comment by gaborcsardi** [comment]
@hadley Personally, I am not sure if this is a good idea.

If you do it at package creation, then it will get outdated, and useless.

If you do it in `load_all` or in `as.package`, then there will be spurious changes in `DESCRIPTION`. OK, not too frequently, but still. 

Maybe more importantly, I think the state of the package should be independent of the `devtools` version.

(Roxygen is a different thing IMO, because that creates package files on purpose, and these might change depending on roxygen version.)

I think if you want to inform people about new versions, `devtools` could just check occasionally whether there is a new version available, and if `isTRUE(interactive())`, inform the users. I have long wanted to write a micropackage for this. With metacran, it is trivial, anyway, just get http://crandb.r-pkg.org/devtools and check `Version`. If `devtools` sends an extra header with the current version, then we can even track usage.

**Comment by hadley** [comment]
@gaborcsardi I was thinking may be it would be a simple flag - i.e. that the package uses devtools, not that it uses a specific version.

I really would like a way to proactively reach out to devtools uses so I can ask a wide range of uses to test pre-release versions.

**Comment by gaborcsardi** [comment]
@hadley I see. Without version numbers it is definitely better.

Although I bet that it'll still be annoying at times. E.g. if I fork a package that does not have it, I'll have to remove it from my commits and the PRs I submit. And if `as.package()` keeps adding it back, I'll have to remove it over and over again....

How about reporting usage to google analytics, anonymously? Is that off limits? Probably, as even as much as a package name can be sensitive information. It could be opt-on, though.

**Comment by jimhester** [comment]
If the idea is to communicate back to devtools users the GA idea won't help (it is an interesting idea though).

Could we add a registration prompt to devtools that would ask devtools users to send their email addresses to us? They could be entered in a drawing to win devtools stickers as incentive to register?

**Comment by gaborcsardi** [comment]
On 20 Jan 2016 18:22, "Jim Hester" <notifications@github.com> wrote:
>
> If the idea is to communicate back to devtools users the GA idea won't
help (it is an interesting idea though).

Devtools can send the package name to GA. The email address as well, but
that might be too much....

> Could we add a registration prompt to devtools that would ask devtools
users to send their email addresses to us? They could be entered in a
drawing to win devtools stickers as incentive to register?

**Comment by hadley** [comment]
I'm going to close this for now. I think GA and requesting emails are interesting ideas, but too challenging right now.
