### ISSUE TITLE
Review travis install process

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#974]
3rd gen travis install process (https://github.com/hadley/xml2/blob/master/.travis.yml) seems to be considerable faster than 2nd gen (i.e. `language:R`) and without too much extra overhead.

Could devtools make the process even simpler? Would a devtools apt package help streamline the install process? Do we need `devtools::update_package()` to install a package only if it's out of date?

cc @craigcitro @jimhester

**Comment by hadley** [comment]
Maybe we could make devtools respect a `CRAN_MIRROR` env var?

**Comment by jimhester** [comment]
A agree, it seems like all the CIs scripts have to jump through hoops to set the CRAN mirror.

It might be worth using a format that allows one to set any repository (so you could use alternate bioconductor, omegahat or other repositories as well).

Maybe a format like

```bash
R_REPOS=cran=http://cran.rstudio.com:BiocSoft=https://bioconductor.org/packages/3.3/bioc:CRANxtras=http://www.stats.ox.ac.uk/pub/RWin
```
Simple implementation to parse could be something like

```r
parse_repos <- function(x) {
  # perl = TRUE is needed for the negative lookahead assertion
  splt <- strsplit(strsplit(x, ":(?!//)", perl = TRUE)[[1]], "=")
  if (length(splt[[1]]) == 1) {
    return(splt[[1]])
  }

  nms <- vapply(splt, `[[`, character(1), 1)
  urls <- vapply(splt, `[[`, character(1), 2)

  setNames(urls, nms)
}
Sys.setenv(R_REPOS="cran=http://cran.rstudio.com:BiocSoft=https://bioconductor.org/packages/3.3/bioc:CRANxtras=http://www.stats.ox.ac.uk/pub/RWin")
parse_repos(Sys.getenv("R_REPOS"))
#>                                         cran 
#>                    "http://cran.rstudio.com" 
#>                                     BiocSoft 
#> "https://bioconductor.org/packages/3.3/bioc" 
#>                                    CRANxtras 
#>         "http://www.stats.ox.ac.uk/pub/RWin"
Sys.setenv(R_REPOS="http://cran.rstudio.com")
parse_repos(Sys.getenv("R_REPOS"))
#> [1] "http://cran.rstudio.com"
```
The above also handles simple case of specifying only the CRAN repository, i.e. `R_REPOS=http://cran.rstudio.com`

I feel like this should really be supported in base R, but that is probably too steep a hill to climb.

**Comment by hadley** [comment]
I'm not sure if it's important to generalise - I think `CRAN_REPOS` + `BIOC_REPOS` would solve 90% of issues.

**Comment by jimhester** [comment]
I guess if drat repos get more popular that would be another use case, but you are probably right most people aren't going to use them.

**Comment by hadley** [comment]
Maybe we could have `devtools::set_repos()` - that would take care of modifying the correct file on disk.

Would also be useful to have a `devtools::install_pandoc()` which would download and install the RStudio binary

**Comment by craigcitro** [comment]
FWIW, the only reason I haven't already switched to supporting multiple CRAN repos is a silly one -- `${CRAN}` gets used in two contexts for both travis variants:

 * as an env var which is inlined to a URL ([example](https://github.com/craigcitro/r-travis/blob/master/scripts/travis-tool.sh#L63))
 * as an R string ([example](https://github.com/craigcitro/r-travis/blob/master/scripts/travis-tool.sh#L185))

A list syntax that works in both of those cases doesn't exist, right? :wink:

**Comment by jimhester** [comment]
You could reduce the list to only the CRAN part pretty simply though. Tweaking the proposed scheme to be just a quoted R character vector.

```bash
CRAN="http://cran.rstudio.com"
CRAN_INLINE=$(echo $CRAN | perl -pe 's/.*cran="([^"]+)".*/$1/')
echo $CRAN_INLINE
# http://cran.rstudio.com
CRAN='c(cran="http://cran.rstudio.com", BiocSoft="https://bioconductor.org/packages/3.3/bioc", CRANxtras="http://www.stats.ox.ac.uk/pub/RWin")'
CRAN_INLINE=$(echo $CRAN | perl -pe 's/.*cran\s*=\s*"([^"]+)".*/$1/')
echo $CRAN_INLINE
# http://cran.rstudio.com
```
I used perl to do the substitution, but you could use an equivalent sed expression if you prefer, I just don't remember the proper regex syntax off-hand.

**Comment by craigcitro** [comment]
yeah, we definitely can do rewriting (though the error messages are going to be *totally* inscrutable if someone typos their `CRAN` variable).

honestly, though, maybe it's OK to just have two vars?

    CRAN="http://cran.rstudio.com"
    if [[ -z ${CRAN_REPOS} ]]; then
      CRAN_REPOS="c(cran=\"${CRAN}\")"
    fi

and people can override `CRAN_REPOS` as they'd like?

**Comment by hadley** [comment]
Closing since @jimhester is on this. @jimhester can you break this up into smaller issues?
