### ISSUE TITLE
`revdep_check` fails, can't create directory

### ISSUE THREAD

**Issue by sjPlot** [hadley/devtools#984]
I used `use_revdep` to create a template and tried to run the `check.R` file. However, when `revdep_check` is executed, following error occurs:

    Error in normalizePath(path.expand(path), winslash, mustWork) : 
      path[1]="C:\Users\Luedeke\AppData\Local\Temp\RtmpaQYr3B/R-lib": Das System kann den angegebenen Pfad nicht finden

(_Cannot find specified path_)

I use RStudio 0.99.782, devtools 1.9.1, R 3.2.2 on Windows 10 prof.

**Comment by hadley** [comment]
Can you supply a `traceback()` please?
