### ISSUE TITLE
load_code and load_all doesn't seem to load code for debugging

### ISSUE THREAD

**Issue by steventsimpson** [hadley/devtools#986]
@hadley 
I'm trying to use `devtools::load_code` or `devtools::load_all` during package debugging. I was thinking they would behave like the following custom function, which just sources the files into GlobalEnv : 
```r
source_R_folder <- function(path){
    invisible(lapply(dir(pattern=".R", path), function(x) source(file.path(path, x))))
} 
```

I can see that `load_all()` loads the package, but the functions don't show up in the Global Environment. 

I don't doubt that these choices were made for the correct reasons, but I'm wondering if there wouldn't be a place for the kind of use `source_R_folder()` serves. If this is the case, I'd be happy to a pull request. And if I've missed something helpful, please don't hesitate to let me know.

```r
setwd("~/Documents/repos/github_packages/brokenCSV")
devtools::load_code()
    Error: is.environment(envir) is not TRUE
    Error in dev_meta(pkg$package) : 
    Namespace not found for brokenCSV. Is it loaded?
devtools::load_code("./R")
    Error: is.environment(envir) is not TRUE
    Error in dev_meta(pkg$package) : 
    Namespace not found for brokenCSV. Is it loaded?
devtools::load_code("brokenCSV")
    Error: Can't find directory brokenCSV
devtools::load_code("~/Documents/repos/github_packages/brokenCSV")
    Error: is.environment(envir) is not TRUE
    Error in dev_meta(pkg$package) : 
    Namespace not found for brokenCSV. Is it loaded?
```

**Comment by hadley** [comment]
Is there a reason that `load_all()` doesn't do what you want? I think it's much better to put the functions in an environment.
