### ISSUE TITLE
vignettes are not found if installed with install_github

### ISSUE THREAD

**Issue by vzemlys** [hadley/devtools#987]
My R package resides in https://github.com/mpiktas/retacoro. I've added the vignette with `use_vignette()`. The `check` runs cleanly, and it seems that `DESCRIPTION` file is correct. But when installing the package with `install_github(mpiktas/retacoro)` package vignette is not installed. Although I see in the `install_github` output that vignettes are being installed, `vignette(package = "retacoro")
` says `no vignettes found`

If I build the package with `build()` and install the tarball  with `R CMD INSTALL` the vignette is installed. Here is my `sessionInfo()` output.

```
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] retacoro_0.0.5 Matrix_1.2-2   nleqslv_2.9    devtools_1.9.1

loaded via a namespace (and not attached):
 [1] httr_1.0.0      R6_2.1.1        magrittr_1.5    tools_3.2.1    
 [5] curl_0.9.3      memoise_0.2.1   stringi_1.0-1   grid_3.2.1     
 [9] knitr_1.11      stringr_1.0.0   digest_0.6.8    lattice_0.20-33
```

**Comment by krlmlr** [comment]
This seems to be by design, try

```
devtools::install_github(..., build_vignettes = TRUE)
```

The "build_vignettes" argument to install() (which is ultimately called) is set to FALSE by default.

**Comment by vzemlys** [comment]
I looked at the `install_github` man page for that option. Stupid me.
