### ISSUE TITLE
use_data won't receive a named object from as.name()

### ISSUE THREAD

**Issue by jgdt** [hadley/devtools#988]
If I understand correctly,, use_data should be able to take the output of the 'as.name' function as input argument: 'is.name' is used to check the input:
ll. 7-9 of use_data:
```R
if (any(!is_name)) { 
    stop("Can only save existing named objects", call. = FALSE) 
}
```
However it doesn't works, cf below.

Minimal working example (devtools v. 1.8.0 with R v. 3.2.2 on debian stretch)
```R
library(devtools)
a <- "b"
b <- 3
use_data(as.name(a))
```
=> `Error : Can only save existing named objects`

**Comment by hadley** [comment]
You call it like `use_data(a)`.

**Comment by jgdt** [comment]
Thanks for your reply. I will try to be clearer:

If I call `use_data(a)`, 'b' will be written in 'a.rda'. I want '3' to be written in 'b.rda'.
Actually I would like to call use_data in a loop:
```R
library(devtools)
dataToMake <- c("a.csv", "b.csv", "c.csv", "d.csv")
for (File in dataToMake)
{
        Data <- read.csv(File)
        DataName <- sub(".csv", "", File)
        assign(DataName, Data)
        use_data(as.name(DataName))
}
```

And anyway it seems strange that an output of 'as.name' function won't be accepted by the 'is.symbol' check. Maybe due to the 'dots' function (which I don't know):
`use_data()` ll. 5-6
```R
    to_save <- dots(...)
    is_name <- vapply(to_save, is.symbol, logical(1))
```

Thanks for replying.

**Comment by hadley** [comment]
That's not what `use_data()` is designed for. You're probably best off using `save()` directly.
