### ISSUE TITLE
store source in a destdir similar to install.packages when using install_github

### ISSUE THREAD

**Issue by nverno** [hadley/devtools#990]
This is a feature request I suppose.  Would be it dumb to be able to specify a destination folder to store source files similar to the `destdir` with the `type=source` option in `install.packages`?  Personally, I would like this since it saves a step of cloning the repository to where I store source, and seems like it would be a pretty simple addition since the repo is downloaded to a temporary location anyway?  Or maybe I just missed an option with `install_github`...

**Comment by hadley** [comment]
I don't really follow why this would be useful, and I've never felt the need for it myself. But I'd be happy to review a PR that implemented it :)

**Comment by jpmorris** [comment]
use case: organization uses changing codebase of libraries that are constantly evolving.  Some analysts might use particular versions of the library that is pulled by a particular hash from github using install_github (using ref=).  If the analyst needs to use legacy code installed locally to support an older version AND a different project using the more up-to-date library then install.packages would allow two separate locations and library (with lib.loc=) would allow loading two versions of the same library in two different projects without having to reinstall the diferent versions each time.  install_github does not allow for this possibility.  Though I may be missing a workaround that I'm not aware of.

**Comment by gaborcsardi** [comment]
@jpmorris Looks like you want to change the library directory. I think you can do that easily using:
`withr::with_libpaths(new_lib, install_github(...))`.
