### ISSUE TITLE
Improve CRAN / Github flexibility

### ISSUE THREAD

**Issue by drknexus** [hadley/devtools#993]
Sometimes you run into an issue with a version of a package and the package maintainer updates it in github, but you have to wait a while for it to get onto CRAN.  If you are launching a script on another machine that needs to download that package what do you do?  Do you install_github knowing that it is possible that in the future the maintainer will make some breaking change to the branch you specify?  I propose that ideal behavior in this instance is to check the version number on CRAN.  If it meets your threshold, you should use the (ostensibly stable) version from CRAN.  If it doesn't then you should fetch the bleeding (stable) edge from github.  This seems like a functionality that could exist in or extend something like install_version.  

I've provided a draft example of what a stand alone version, lacking the 'install from CRAN' functionality, of it might look like.  I can modify it into a pull request with a more full feature set if desired.  If it is wrong headed, please let me know.  If it just doesn't belong in devtools, please let me know so I can consider it for inclusion elsewhere.

```
requirePackageVersion_github <- function(packageName, githubLoc, requiredVersion) {
  library(devtools)
  installedVersion <- tryCatch(packageVersion(packageName),error = function(e) {NULL})
  if (length(installedVersion)==0) {
    requireInstall <- TRUE
  } else if (is.null(installedVersion) | is.na(installedVersion) | is.error(installedVersion)) {
    requireInstall <- TRUE
  } else {
    requireInstall <- compareVersion( as.character(installedVersion),requiredVersion) == -1 
  }

  if (requireInstall) {
    tryCatch(install_github(githubLoc), error=function(e) {warning(paste0("Unable to download from ", githubLoc)); return(FALSE)})
    installedVersion <- tryCatch(packageVersion(packageName),error = function(e) {warning(paste0("Unable to load ", packageName));return(FALSE)})
    #make sure the version we got from github meets our requirements
    if (compareVersion( as.character(installedVersion),requiredVersion) == -1) {
      stop("Version of ",packageName," on github doesn't meet the ",requiredVersion," requirement or the install failed")
    }
  } 
  packageLoaded <- require(packageName, character.only=TRUE)
  return(packageLoaded)
}

```

**Comment by jimhester** [comment]
You can specify a sha1 hash or tag to install with `install_github()` to pin it to a particular version. This is actually more stable than using CRAN, which always will install the most current version. See the examples at `?install_github`, e.g.

```r
install_github(c("hadley/httr@v0.4", "klutometis/roxygen#142",
       "mfrasca/r-logging/pkg"))
```

If you want to do this same thing with CRAN releases you can use the mirrors at https://github.com/cran/, which have tagged versions for each release.
