### ISSUE TITLE
flagging links

### ISSUE THREAD

**Issue by soodoku** [hadley/devtools#994]
Dear All,

One of the things that CRAN does is check whether all the links can be followed. And as far as I can tell from the documentation and from using devtools, devtools doesn't currently check that. There are two aspects to the problem:
1. https links always raise errors, afaik
2. CRAN also catches stuff where header request is not honored.

For instance, Kurt Hornik noted: 
"curl http://www.freebase.com/ works fine"
but curl -I -L http://www.freebase.com/ doesn't

And the latter is what is used by CRAN.

**Comment by hadley** [comment]
You need to run `check(as_cran = TRUE)` to run these additional (expensive) tests

**Comment by hadley** [comment]
If you're following the standard devtools release process, `release()` does that for you.

**Comment by soodoku** [comment]
Dear Hadley,

I went via release(). It may be that it doesn't check links in vignettes?

**Comment by hadley** [comment]
It runs exactly the same code that CRAN does, although CRAN runs it with R-devel.

**Comment by soodoku** [comment]
Dear Hadley,

I was able to fix the issue so let me describe the issue in detail.

I build vignettes using knitr. In the header, I had:
%\VignetteEngine{knitr::rmarkdown} 

This leads knitr to process Rmd so that when it sees a word starting with http://, it automatically creates a link. So in: 
https://github.com/soodoku/clarifai/blob/master/vignettes/poligrams.Rmd
http://localhost:1410/ became a link in the html. And of course that is not going to be accessible.

Using %\VignetteEngine{knitr::knitr} doesn't do that.
