### ISSUE TITLE
Add 'use_mit_license' helper function

### ISSUE THREAD

**Issue by kevinushey** [hadley/devtools#995]
Would just:

- Amend the DESCRIPTION to have License: MIT + file LICENSE
- Write a LICENSE file with the contents COPYRIGHT HOLDER: xxx YEAR: 2016
- (Optionally) open that file for editing so the user can enter their name / the true copyright holder

**Comment by hadley** [comment]
I like it!

**Comment by peterhurford** [comment]
:+1:
