### ISSUE TITLE
unloading package 'tcltk' causes segfault

### ISSUE THREAD

**Issue by esander91** [hadley/devtools#998]
Using R 3.2.3 on Ubuntu 14.04, unloading package `tcltk` (version 3.2.3) causes a segfault.

    > require(devtools)
    Loading required package: devtools
    > require(tcltk)
    Loading required package: tcltk
    > unload(inst('tcltk'))
    > 
     *** caught segfault ***
    address 0x7f7f8d19d4b0, cause 'memory not mapped'

**Comment by hadley** [comment]
Yeah, unfortunately you can't reliably unload packages with C code

**Comment by wch** [comment]
In many cases it's possible to reliably unload a package with compiled code, and devtools does that automatically. However, tcltk in particular is known to have problems with being unloaded.

**Comment by wch** [comment]
In many cases it's possible to reliably unload a package with compiled code, and devtools does that automatically. However, tcltk in particular is known to have problems with being unloaded.
