### ISSUE TITLE
Can't install() or install_github() package I wrote

### ISSUE THREAD

**Issue by TomNash** [hadley/devtools#999]
I wrote an R package that passes the check() function and can only be loaded using the document() command or by running check(). If I try to install it through install() or install_github() it gives output like it succeeded but is in fact not part of my session. It mysteriously installs a different package I was able to install through install_github() instead - in bold.

\> library(devtools)
\> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.10.5 (Yosemite)
>
>locale:
>[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
>
>attached base packages:
>[1] stats     graphics  grDevices utils     datasets  methods   base     
>
>other attached packages:
>[1] devtools_1.9.1
>
>loaded via a namespace (and not attached):
>[1] tools_3.2.2   memoise_0.2.1 digest_0.6.8 

\> install_github("TomNash/deseq.heatmap")
>Downloading GitHub repo TomNash/deseq.heatmap@master
>Installing deseq.heatmap
>'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore >CMD INSTALL  \

>'/private/var/folders/wk/jk80xx7573sctfzfzj3v1s680000gp/T/RtmpYoDx4B/devtoolsb374542d473/Tom>Nash-deseq.heatmap-f8fad39'  \
>  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

>\* installing *source* package ‘deseq.heatmap’ ...
>\* R
>\** preparing package for lazy loading
>\** help
>No man pages found in package  ‘deseq.heatmap’ 
>*** installing help indices
>** building package indices
>** testing if installed package can be loaded
>\* DONE (deseq.heatmap)

\> sessionInfo()
>R version 3.2.2 (2015-08-14)
>Platform: x86_64-apple-darwin13.4.0 (64-bit)
>Running under: OS X 10.10.5 (Yosemite)
>
>locale:
>[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
>
>attached base packages:
>[1] stats     graphics  grDevices utils     datasets  methods   base     
>
>other attached packages:
>[1] devtools_1.9.1
>
>loaded via a namespace (and not attached):
>[1] **httr_1.0.0.9000 R6_2.1.1**        tools_3.2.2     **curl_0.9.4**      memoise_0.2.1   digest_0.6.8

**Comment by gaborcsardi** [comment]
Installing a package does not load or attach it. `library()` does both.

**Comment by TomNash** [comment]
library(<package name>) wasn't working either after trying the install.

Renamed to remove the period from the package name and changed the repo name, now it seems to work.

**Comment by gaborcsardi** [comment]
Periods are totally fine in package and repo names. A lot of packages and repos have them. You must have made another mistake.
